#!/bin/bash

# Slackware build script for papirus-icon-theme

# Copyright 2018 Azure Zanculmarktum <zanculmarktum@gmail.com>
# Updates/Maintenance 2023-2025 Jay Lanagan (j@lngn.net), Detroit, MI.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=papirus-icon-theme
VERSION=${VERSION:-20250501}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz $PRGNAM-$VERSION/install.sh
cd $PRGNAM-$VERSION
sed -i -e 's,Papirus-Light,Papirus Papirus-Light,g' install.sh
THEMES=$(grep \{EXTRA_THEMES install.sh | cut -d= -f2 | cut -d} -f1)

mkdir -p $PKG/usr/share/icons
(
  cd $PKG/usr/share/icons
  for theme in $THEMES; do
    tar xvf $CWD/$PRGNAM-$VERSION.tar.gz --xform "s/$PRGNAM-$VERSION//" \
      $PRGNAM-$VERSION/$theme
  done
)

chown -R root:root .
find . -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + \
 -o \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +

# Papirus team recommends to remove ePapirus & ePapirus-Dark if the distro
# does not ship the Pantheon Desktop, so we're going to do that.
# These themes were removed in 20250501, keeping this for now so users
# become aware they have been removed.
# rm -r $PKG/usr/share/icons/{ePapirus,ePapirus-Dark}

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cd $PKG/usr/doc
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz $PRGNAM-$VERSION/{AUTHORS,LICENSE,README.md}
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
#sed -e "s/@THEMES@/$THEMES/" $CWD/doinst.sh > $PKG/install/doinst.sh
# Premade and gzipped doinst.sh
zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh

cd $PKG

# To create a new doinst.sh, comment the next line, uncomment the lines below
# it and @THEMES@ above, grab the new one from the package and gzip it.
find . -type l -delete

# 20200407 bkw: makepkg's symlink search and doinst.sh creation doesn't
# scale well. This makes the build complete much faster, and create an
# identical doinst.sh.
#find . -type l \
#  -printf '( cd %h ; rm -rf %f )\n( cd %h ; ln -sf %l %f )\n' -delete | \
#  sed 's,cd \./,cd ,' >> $PKG/install/doinst.sh

/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
