#!/bin/sh

# Slackware build script for OpenCASCADE
# With some inspiration from the Arch PKGBUILD script

# Copyright 2010-2011 Niels Horn, Rio de Janeiro, RJ, Brazil
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# revision date: 2011/08/10

PRGNAM=OpenCASCADE
VERSION=${VERSION:-6.5.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

SRCVERSION=$( echo $VERSION | sed "s/\.//g" )

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
# Source untars in current directory...
mkdir $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
tar xvf $CWD/${PRGNAM}${SRCVERSION}.tar.gz
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Patch source for newer gcc versions
#  (avoids "not declared in this scope" errors)
patch -p1 < $CWD/newgcc.patch

# Fix for newer fgtl versions
#  (thanks to the guys from openSUSE)
patch -p1 < $CWD/fix-ftgl-includes.patch

# Change to the directory where we'll build from
cd ros

autoreconf -f -i

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --with-tcl=/usr/lib${LIBDIRSUFFIX} \
  --with-tk=/usr/lib${LIBDIRSUFFIX} \
  --disable-debug \
  --enable-production \
  --build=$ARCH-slackware-linux

# Change the resulting Makefile so that we can use DESTDIR
sed -e "s|\$(prefix)|\$(DESTDIR)\$(prefix)|g" -i Makefile

make
make install DESTDIR=$PKG

cd ..

# Correct path of include files
mkdir -p $PKG/usr/include
mv $PKG/usr/inc $PKG/usr/include/$PRGNAM

# Correct path of source files
mkdir -p $PKG/usr/src/$PRGNAM
( set -e
  cd $PKG/usr
  mv config.h src/$PRGNAM/
  cd src
  for d in *; do
    if [ "$d" != "$PRGNAM" ]; then
      mv $d $PRGNAM/
    fi
  done
) || exit 1

# Remove unnecessary (and confusing) files
rm -r $PKG/usr/{lin,Linux,env_DRAW.sh}

mkdir -p $PKG/usr/share/$PRGNAM
cp -a data samples $PKG/usr/share/$PRGNAM

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  README LICENSE ros/README.txt \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# If you want *all* documentation in the package, use INSTALL_FULL_DOCS=yes
#   but be warned: we're talking about ~ 600MB of documentation...
if [ "${INSTALL_FULL_DOCS:-no}" = "yes" ]; then
  cp -a \
    doc/* \
    $PKG/usr/doc/$PRGNAM-$VERSION
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
