.\" This man page was written by Markus Koschany in August 2013. It is provided
.\" under the GNU General Public License 2 or (at your option) any later version.
.TH ufoded 6 "October 2021" "ufoai-2.5" "SlackBuilds.org"
.SH NAME
ufoded \- UFO: Alien Invasion dedicated server
.SH SYNOPSIS
.PP
\fBufoded\fR [\fB+<internal command> \fIoption\fR \fIvalue\fP] ...
.SH DESCRIPTION
\fBufoded\fP is the dedicated server for the strategy game UFO: Alien Invasion.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display this help
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable console output
.TP
\fB+<internal command>\fR
Options passed by "+<internal command>" are the same as the in-game console understands. For the in-game console press SHIFT+ESC.
Use the in-game \fBcvarlist\fR to get a list of all available options for the game.
.SH "FILES"
All these files are part of a pk3 file in \fI/usr/share/games/ufoai/base/\fR. You can extract them (pk3 files are just zip files)
and place them in the home directory of the user running the dedicated server. Use the path \fI~/.ufoai/<VERSION>/base/\fR to place
these files. The files that are not located in the pk3 files have a higher priority than the files that are stored in the pk3
files. So you are able to replace any file you want like this. You can also add new maps and other game content to the \fIbase/\fR
directory in your users home directory to be able to use new content in the game.
.TP
\fBdedicated.cfg\fR
Dedicated server config\&.
.TP
\fBautoexec.cfg\fR
Commands that are executed when starting the dedicated server\&.
.TP
\fBmapcycle.txt\fR
This defines the map cycle that the dedicated server will use\&.
.SH SEE ALSO
.PP
\fBufo\fR(6)
\fBufo2map\fR(6)
\fBufomodel\fR(6)
\fBufoslicer\fR(6)
