.\" This man page was written by Markus Koschany in July 2013. It is provided
.\" under the GNU General Public License 2 or (at your option) any later version.
.TH ufomodel "6" "October 2021" "ufoai-2.5" "SlackBuilds.org"
.SH NAME
ufomodel \- optimizer for model files
.SH DESCRIPTION
UFO: Alien invasion developer tool to modify and optimize model files.
.SH OPTIONS
.TP
\fB\-mdx\fR
generate mdx files
.TP
\fB\-skinfix\fR
fix skins for md2 models
.TP
\fB\-glcmds\fR
remove the unused glcmds from md2 models
.TP
\fB\-check\fR
perform general checks for all the models
.TP
\fB\-skinedit\fR <filename>
edit skin of a model
.TP
\fB\-skinnum\fR <filename>
edit the skin numbers of a model
.TP
\fB\-info\fR <filename>
show model information
.TP
\fB\-overwrite\fR
overwrite existing mdx files
.TP
\fB\-s\fR <float>
sets the smoothness value for normal\-smoothing (in the range \fB\-1\fR.0 to 1.0)
.TP
\fB\-f\fR <filename>
build tangentspace for the specified model file
.TP
\fB\-v\fR \fB\-\-verbose\fR
print debug messages
.TP
\fB\-h\fR \fB\-\-help\fR
show this help screen
.SH "SEE ALSO"
.PP
\fBufo\fR(6)
\fBufoded\fR(6)
\fBufo2map\fR(6)
\fBufoslicer\fR(6)
