.TH UFORADIANT 6 "October 2021" "ufoai-2.5" "SlackBuilds.org"
.SH NAME
uforadiant \- UFO: Alien Invasion Mapeditor

.SH SYNOPSIS
.PP
\fBuforadiant\fR

.SH DESCRIPTION
This manual page documents briefly the
.B uforadiant
command.
.PP
\fBuforadiant\fP is the map editor for the strategy game UFO: Alien Invasion.

.SH OPTIONS
.PP
Options are passed to the gtk init function.

.SH "FILES"
.TP
\fB~/.ufoai/radiant/settings.xml\fR
Editor configuration\&.
.TP
\fB~/.ufoai/radiant/shortcuts.ini\fR
Key bindings\&.
.TP
\fBbase/ufos/entities.ufo\fR
This file is included in the 0ufos.pk3 in your system wide UFO:AI installation directory and defines the entities the editor can add to maps\&.

.SH "SEE ALSO"
.PP
\fBufo\fR(6)

.SH AUTHOR
\fBuforadiant\fP was written by the UFO: Alien Invasion team and based on the GPLed release of GtkRadiant 1.5 by id Software.
.PP
This manual page was written by Florian Ludwig <dino@phidev.org>,
for the Debian project (but may be used by others). It was
modified slightly by B. Watson <yalhcru@gmail.com> for the SlackBuilds.org
project.

.SH "SEE ALSO"
.PP
\fBufo\fR(6)
\fBufoded\fR(6)
\fBufo2map\fR(6)
\fBufomodel\fR(6)
\fBufoslicer\fR(6)
