.\" This man page was written by Markus Koschany in July 2013. It is provided
.\" under the GNU General Public License 2 or (at your option) any later version.
.TH ufoslicer "6" "October 2021" "ufoai-2.5" "SlackBuilds.org"
.SH NAME
ufoslicer \- an UFO:AI map slicer
.SH SYNOPSIS
.B ufoslicer
\fI\-t N \-s N \-c \-m bspfile\fR
.SH DESCRIPTION
.TP
UFO Alien Invasion developer tool to slice map files.
.SH OPTIONS
.TP
\fB\-t\fR N
= use slice thickness of N units.
.TP
\fB\-s\fR N
= use scale factor of N.
.TP
\fB\-c\fR
= create a single contour map.
.TP
\fB\-m\fR
= create multiple contour maps.
.HP
\fB\-h\fR|\-\-help = show this help screen.
.PP
.SH EXAMPLES
ufoslicer \fB\-t\fR 64 \fB\-s\fR 8 maps/farm
.PP
The above command would slice the map "farm.bsp", moving by 64 units between slices and
would create a 1/8th scale bitmap file.
.PP
The default for \fB\-t\fR is 64 units.
.SH "SEE ALSO"
.PP
\fBufo\fR(6)
\fBufoded\fR(6)
\fBufo2map\fR(6)
\fBufomodel\fR(6)
