#!/bin/sh

# Slackware build script for rxvt-unicode

# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Currently maintained by Glenn Becker (glenn.becker@gmail.com)
# Updates by Kevin Paulus, aka "goarilla" (goarilla@gmail.com)
# Previously maintained by LEVAI Daniel, 2010-2014
# Initial SlackBuild written by Dugan Chen (dugan_c@fastmail.fm)

PRGNAM=rxvt-unicode
VERSION=${VERSION:-9.21}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Option to enable/disable the embedded perl interpreter
CONFIG_PERL=${CONFIG_PERL:-YES}

if [ "${CONFIG_PERL}" == 'YES' ];then
	_PERL_OPT='--enable-perl'
else
	_PERL_OPT='--disable-perl'
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --enable-everything \
  --enable-unicode3 \
  --enable-combining \
  --enable-xft \
  --enable-font-styles \
  --enable-transparency \
  --enable-fading \
  --enable-frills \
  --enable-pixbuf \
  --enable-rxvt-scroll \
  --enable-next-scroll \
  --enable-xterm-scroll \
  ${_PERL_OPT} \
  --enable-xim \
  --enable-iso14755 \
  --enable-keepscrolling \
  --enable-selectionscrolling \
  --enable-mousewheel \
  --enable-slipwheeling \
  --enable-smart-resize \
  --enable-text-blink \
  --enable-pointer-blank \
  --enable-utmp \
  --enable-wtmp \
  --enable-lastlog \
  --enable-256-color \
  --build=$ARCH-slackware-linux

make

mkdir -p $PKG/usr/share/terminfo
TERMINFO=$PKG/usr/share/terminfo make install DESTDIR=$PKG

find $PKG | xargs file | grep -e "executable" -e "shared object"  | grep ELF | \
  cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING Changes INSTALL README.FAQ $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG

# Fix usr/bin/urxvt permissions to enable writing to utmp and wtmp files
#
version="$(echo "$VERSION" |sed -e 's/[^0-9]//g')"
if [ "$version" -le 921 ]; then
  # standalone
  chgrp utmp usr/bin/urxvt
  chmod 2755 usr/bin/urxvt
  # client
  chgrp utmp usr/bin/urxvtc
  chmod 2755 usr/bin/urxvtc
  # server
  chgrp utmp usr/bin/urxvtd
  chmod 2755 usr/bin/urxvtd
fi

/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
