#!/bin/sh

# Slackware build script for AfterStep WM
# Written by NetrixTardis (netrixtardis@stealth3.com)

PRGNAM=afterstep
VERSION=${VERSION:-2.2.9}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

SRCNAM=AfterStep	# leave this alone

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
rm -rf $TMP/$SRCNAM-$VERSION
cd $TMP
tar xvf $CWD/$SRCNAM-$VERSION.tar.bz2
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R a-s,u+w,go+r-w .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --enable-i18n \
  --enable-alsa \
  --with-helpcommand="rxvt -e man" \
  --with-imageloader="" \
  --build=$ARCH-slackware-linux

make
make install DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null
)

# Take care of default xinitrc
install -D -m 0755 $CWD/xinitrc.afterstep $PKG/etc/X11/xinit/xinitrc.afterstep

mkdir -p $PKG/usr/doc
mv $PKG/usr/share/afterstep/doc/ $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYRIGHT ChangeLog INSTALL NEW README TEAM UPGRADE doc/menu.txt \
  doc/licences doc/languages doc/code  $PKG/usr/doc/$PRGNAM-$VERSION
( cd $PKG/usr/share/afterstep ; ln -s ../../doc/$PRGNAM-$VERSION doc )

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
