.\" man page for xcowthink
.TH "xcowthink" 6
.SH NAME
xcowthink \- Display a cute cow and speech bubble.
.SH SYNOPSIS
.B xcowthink
.RB [ "-h" ]
.RB [ "-t"
.RI \| time \|]
.RB [ "-r"
.RI \| speed \|]
.RB [ "-d" ]
.RB [ "-f"
.RI \| font \|]
.RI [\| text \|]...

.SH DESCRIPTION
\fBxcowthink\fP is a convenient shortcut for \fBxcowsay \-\-think\fP.
.P 
Please see \fBxcowsay (6)\fP for details.

.SH OPTIONS
Same as \fBxcowsay (6)\fP.

.SH "SEE ALSO"
.BR xcowsay (6)

.SH BUGS
There are no bugs.
