.\" man page for xcowfortune
.TH "xcowfortune" 6
.SH NAME
xcowfortune \- Display a cute cow and a fortune quote in a speech bubble.
.SH SYNOPSIS
.B xcowfortune
.RB [ "-h" ]
.RB [ "-t"
.RI \| time \|]
.RB [ "-r"
.RI \| speed \|]
.RB [ "-d" ]
.RB [ "-f"
.RI \| font \|]
.RI [\| text \|]...

.SH DESCRIPTION
\fBxcowfortune\fP is a convenient shortcut for piping the output of \fBfortune
(6)\fP to \fBxcowsay (6)\fP.
.P 
Please see \fBxcowsay (6)\fP for details.

.SH OPTIONS
Same as \fBxcowsay (6)\fP.

.SH "SEE ALSO"
.BR xcowsay (6)

.SH BUGS
There are no bugs.
