.\" man page for xcowdream
.TH "xcowdream" 6
.SH NAME
xcowdream \- Display a cute cow and speech bubble.
.SH SYNOPSIS
.B xcowdream
.RI [\| image\-file \|]
.RB [ "-h" ]
.RB [ "-t"
.RI \| time \|]
.RI [ "other \fBxcowsay(6)\fP options ..." ]

.SH DESCRIPTION
\fBxcowdream\fP is a convenient shortcut for \fBxcowsay \-\-dream\fP.
.P 
Please see \fBxcowsay (6)\fP for details.

.SH OPTIONS
Same as \fBxcowsay (6)\fP.

.SH "SEE ALSO"
.BR xcowsay (6)

.SH BUGS
There are no bugs.
