#!/bin/sh

# Slackware build script for "advancemame"

# Written by seb (sebastien.serre33@laposte.net)

PRGNAM=advancemame
VERSION=0.106.0
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

DOC="BUILD COPYING HISTORY RELEASE README $CWD/$PRGNAM.SlackBuild"

set -e

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --bindir=/usr/games \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

make

/usr/bin/ginstall -d -m 755 $PKG/usr/games
/usr/bin/ginstall -d -m 755 $PKG/usr/share/advance
/usr/bin/ginstall -d -m 755 $PKG/usr/doc/$PRGNAM-$VERSION
/usr/bin/ginstall -d -m 755 $PKG/usr/man/man1
/usr/bin/ginstall -d -m 755 $PKG/usr/share/advance/{rom,sample,artwork,image,crc}
/usr/bin/ginstall -m 755 obj/mame/linux/blend/advmame $PKG/usr/games
/usr/bin/ginstall -m 755 obj/cfg/linux/blend/advcfg $PKG/usr/games
/usr/bin/ginstall -m 755 obj/v/linux/blend/advv $PKG/usr/games
/usr/bin/ginstall -m 755 obj/s/linux/blend/advs $PKG/usr/games
/usr/bin/ginstall -m 755 obj/k/linux/blend/advk $PKG/usr/games
/usr/bin/ginstall -m 755 obj/j/linux/blend/advj $PKG/usr/games
/usr/bin/ginstall -m 755 obj/m/linux/blend/advm $PKG/usr/games
/usr/bin/ginstall -m 644 ./support/*.dat $PKG/usr/share/advance
/usr/bin/ginstall -m 644 ./doc/{*.html,*.txt} $PKG/usr/doc/$PRGNAM-$VERSION
/usr/bin/ginstall -m 644 $DOC $PKG/usr/doc/$PRGNAM-$VERSION
/usr/bin/ginstall -m 644 ./doc/*.1 $PKG/usr/man/man1

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
