#!/bin/sh

# Slackware build script for "advancemame"

# Originally written by seb (email removed)

# Now maintained by B. Watson <yalhcru@gmail.com>. Original version
# had no license, modified version released under the WTFPL. See
# http://www.wtfpl.net/txt/copying/ for details.

# 20171211 bkw:
# - Update for v3.6

# 20170610 bkw:
# - Update for v3.5

# 20170307 bkw:
# - Update for v3.4

# 20170211 bkw:
# - Take over maintenance
# - Update for v3.2
# - i486 => i586
# - install man pages to section 6, since this is a game
# - major script cleanup/simplification (use 'make install')
# - add .desktop, icon, doinst
# - document optional SDL2 dep, add SDL2 env var to control it

PRGNAM=advancemame
VERSION=${VERSION:-3.6}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

if [ "${SDL2:-yes}" != "yes" ]; then
   SDL2OPT="--enable-sdl --disable-sdl2"
fi

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  $SDL2OPT \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --bindir=/usr/games \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

make

# Please don't remove the -j1 from the make install command. Without it,
# the directories don't always get created before files are installed
# into them, resulting in a mess.
make -j1 install prefix=$PKG/usr bindir=$PKG/usr/games docdir=$PKGDOC

# Binaries are installed stripped. Man pages are in the wrong section!
mv $PKG/usr/man/man1 $PKG/usr/man/man6
sed -i '/^\.TH.* 1$/s,1$,6,' $PKG/usr/man/man6/*.1
rename .1 .6 $PKG/usr/man/man6/*.1
gzip -9 $PKG/usr/man/man6/*.6

# This one works better as a symlink:
rm -f $PKG/usr/man/man6/advmess.6.gz
ln -s advmame.6.gz $PKG/usr/man/man6/advmess.6.gz

# Easier to fix this after the fact than hack it to work right:
mv $PKGDOC/advance/* $PKGDOC
rmdir $PKGDOC/advance

# HISTORY, README, RELEASE are identical to history.txt, readme.txt,
# release.txt which are already installed, but the license doesn't have
# a lowercase.txt equivalent:
cp -a COPYING $PKGDOC

# Icon is a resized version of contrib/logo/megaman.png, which is the
# same as the Windows icon.
mkdir -p $PKG/usr/share/pixmaps
cat $CWD/$PRGNAM.png > $PKG/usr/share/pixmaps/$PRGNAM.png

# .desktop file written by SlackBuild author.
mkdir -p $PKG/usr/share/applications
cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop

# see if we were built with SDL2.
if ldd $PKG/usr/games/advmame | grep -q SDL2; then
  SDLVER="2.0"
else
  SDLVER="1.2"
fi

mkdir -p $PKG/install
sed "s,@SDLVER@,$SDLVER,g" $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
