# pod source for syobonaction man page
# pod2man -s6 -r0.2 --stderr -cSlackBuilds.org syobonaction.pod > syobonaction.6

=pod

=head1 NAME

B<syobonaction> - I<very> difficult side-scrolling platform game

=head1 SYNOPSIS

B<syobonaction> [I<-nosound>] [I<-fullscreen>]

=head1 DESCRIPTION

Syobon Action is a Japanese parody of Super Mario Brothers.

This man page documents OpenSyobon-M, the modified SDL port of OpenSyobon,
which is itself an unofficial SDL port of the original game.

=head1 OPTIONS

=over

=item B<-nosound>

Disables sound

=item B<-fullscreen>

Enables full-screen mode

=back

=head1 CONTROLS

=over

=item B<Jump>

Up arrow, Z, semicolon, joystick button 1

=item B<Movement>

Left/right arrows, joystick left/right

=item B<Enter Warp Pipe>

Down arrow, joystick down

=back

On the main menu, 0 through 9 select the starting level.

=head1 AUTHORS

OpenSyobon-M was written by Wei Mingzhi <whistler_wmz at users.sf.net>.
This version contains additional levels made by Kazuki Okawa.

OpenSyobon-M is based on Open Syobon Action RC 2 by Mathew Velasquez, which
is based on the original Syobon Action by Chiku.

This man page was written by B. Watson for the SlackBuild.org project.
