.TH "FreeFileSync" "1" "10 Dec 2011" "" ""
.SH "NAME"
FreeFileSync \(em a folder comparison and synchronization tool (GUI)
.SH "SYNOPSIS"

.PP 
.nf 
FreeFileSync CONFIG_FILE
.fi 
.PP 
.SH "DESCRIPTION"

.PP 
This is a folder comparison and synchronization tool. It is optimized 
for highest performance and usability without restricted or overloaded 
UI interfaces. 
.PP
It's key features: Multiple folder pairs, Batch capability, Binary 
comparison, Handle conflicts and propagate deletions, Optimized 
performance, Transactional file copy, ...
.PP 
.SH "AUTHOR"

.PP 
FreeFileSync was originally written by ZenJu. It is currently maintained
by Damien Lecan.
.PP
