'\" t
.\"     Title: jack-record
.\"    Author: Rohan Drape <rd@slavepianos.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "JACK\-RECORD" "1" "06/16/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jack-record \- JACK Capture Client
.SH "SYNOPSIS"
.sp
jack\-record [options] sound\-file
.SH "OPTIONS"
.sp
\fB\-b\fR : Set the disk buffer size in frames (default=4096)\&. This value must be a power of two\&. If the JACK period size at any time exceeds this value the recorder will halt\&.
.sp
\fB\-f\fR : Set the file format (default=0x10006)\&. The number is a bitwise\-or of two values, the first describes the file type, the second the data type\&. The default value of 0x10000 | 0x00006 describes a thirty\-two bit floating point WAV file\&. 0x2 is 16\-bit and 0x3 24\-bit\&.
.sp
\fB\-m\fR : Set the minimal disk transfer size in frames (default=32)\&. This is an optimization switch\&.
.sp
\fB\-n\fR : Set the number of input channels to create (default=2)\&.
.sp
\fB\-o\fR : Integer offset for port connection pattern (default=0)\&.
.sp
\fB\-p\fR : A pattern describing the JACK ports to connect to, ie\&. SuperCollider:out_%d (default=nil)\&.
.sp
\fB\-s\fR : Capture to a set of single channel sound files\&. The sound file name must be a valid template\&.
.sp
\fB\-t\fR : Set a timer to stop the recording after the specified number of seconds (default=\-1)\&.
.SH "DESCRIPTION"
.sp
jack\-record is a light\-weight JACK capture client to write an arbitrary number of channels to disk\&. It implements no connection logic, use jack\-plumbing(1) instead\&.
.sp
If the default mode a single multiple channel sound file is written\&. If the \fB\-s\fR option is given a set of single channel sound files are written\&. In this case the sound file name must be a valid template, the substring %d is replaced with the channel number counting from zero\&.
.sp
jack\-record will write files in any format supported by libsndfile\&. The table below shows the most common file format masks\&. For other values see the file \fIsndfile\&.h\fR\&.
.sp
Format Code Description
.br
SF_FORMAT_WAV 0x10000 Microsoft WAV format
.br
SF_FORMAT_AIFF 0x20000 Apple/SGI AIFF format
.br
SF_FORMAT_PCM_16 0x00002 Signed 16 bit data
.br
SF_FORMAT_PCM_24 0x00003 Signed 24 bit data
.br
SF_FORMAT_PCM_32 0x00004 Signed 32 bit data
.br
SF_FORMAT_FLOAT 0x00006 32 bit float data
.SH "AUTHOR"
.sp
Rohan Drape http://rd\&.slavepianos\&.org/
.SH "SEE ALSO"
.sp
jackd(1), libsndfile(3) http://mega\-nerd\&.com/libsndfile/
.SH "AUTHOR"
.PP
\fBRohan Drape\fR <\&rd@slavepianos\&.org\&>
.RS 4
Author.
.RE
