'\" t
.\"     Title: jack-udp
.\"    Author: Rohan Drape <rd@slavepianos.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "JACK\-UDP" "1" "06/16/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jack-udp \- JACK UDP Transport Client
.SH "SYNOPSIS"
.sp
jack\-udp [options] send|recv
.SH "OPTIONS"
.TP
\fB\-b\fR
Set the ring buffer size in frames (default=4096)\&. 
.TP
\fB\-c\fR
Set the client name (default=jack\-udp\-PID)\&. 
.TP
\fB\-n\fR
Set the number of channels, and therefore the number of JACK ports (default=2)\&. 
.TP
\fB\-p\fR
Set the port number (default=57160)\&. 
.TP
\fB\-r\fR
The remote host name, for use in send mode (default="127\&.0\&.0\&.1")\&.
.SH "DESCRIPTION"
.sp
jack\-udp is a UDP audio transport mechansim for JACK\&. The send mode reads signals from a set of JACK input ports and sends UDP packets to the indicated port at the indicated host at a rate determined by the local JACK daemon\&. The recv mode reads incoming packets at the indi\- cated port and writes the incoming data to a set of JACK output ports at a rate that is determined by the local JACK daemon\&.
.sp
This transport mechanism is unreliable\&. Both send and recv clients will report buffer overflow and underflow occurences, and recv clients will report dropped and out\-of\-order packets, and shutdown on channel mismatch packets\&. In practice this mechanism can be made highly reli\- able over local networks\&.
.sp
jack\-udp implements no connection logic, use jack\-plumbing(1) instead\&.
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
192\&.0\&.0\&.1:~$ jack\-udp \-r 192\&.0\&.0\&.2 send
192\&.0\&.0\&.2:~$ jack\-udp recv
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
Rohan Drape http://rd\&.slavepianos\&.org/
.SH "SEE ALSO"
.sp
jackd(1)
.SH "AUTHOR"
.PP
\fBRohan Drape\fR <\&rd@slavepianos\&.org\&>
.RS 4
Author.
.RE
