'\" t
.\"     Title: jack-dl
.\"    Author: Rohan Drape <rd@slavepianos.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "JACK\-DL" "1" "06/16/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jack-dl \- JACK shared library dsp loader
.SH "SYNOPSIS"
.sp
jack\-dl [options]
.SH "OPTIONS"
.TP
\fB\-b\fR
Set the number of buffers (default=8)\&.
.TP
\fB\-c\fR
Set the number of input and output channels (default=8)\&.
.TP
\fB\-k\fR
Set the number of control buses (default=64)\&.
.TP
\fB\-p\fR
Set the udp port number (default=57190)\&.
.SH "DESCRIPTION"
.sp
jack\-dl loads dsp algorithms from shared libraries and allows user interaction with the executing graph\&. Commands are sent as OSC packets over a UDP connection\&.
.sp
The dsp graph code must provide three functions:
.sp
.if n \{\
.RS 4
.\}
.nf
size_t (*dsp_memreq)();
void (*dsp_init)(void *);
void (*dsp_step)(void *,int);
.fi
.if n \{\
.RE
.\}
.sp
jack\-dl accepts the OSC commands:
.sp
Command - Arguments (Description)
.br
/b_alloc - id::int frames::int channels::int (buffer allocate)
.br
/c_set - index::int value::float (control set)
.br
/g_load - object\-file::file\-path (graph load)
.sp
jack\-dl consults the JACK_DL_CONNECT_TO and JACK_DL_CONNECT_FROM environment variables\&.
.sp
jack\-dl implements only a subset of the OSC protocol\&. In particular it does not implement the patten matching rules and does not implement a scheduler for incoming messages\&.
.sp
jack\-dl drops all unrecognized incoming packets\&.
.SH "AUTHOR"
.sp
Rohan Drape http://rd\&.slavepianos\&.org/
.SH "SEE ALSO"
.sp
jackd(1), OSC(7) http://opensoundcontrol\&.org/
.SH "AUTHOR"
.PP
\fBRohan Drape\fR <\&rd@slavepianos\&.org\&>
.RS 4
Author.
.RE
