'\" t
.\"     Title: jack-transport
.\"    Author: Rohan Drape <rd@slavepianos.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "JACK\-TRANSPORT" "1" "06/16/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jack-transport \- Minimalist Jack Transport Interface
.SH "SYNOPSIS"
.sp
jack\-transport
.SH "DESCRIPTION"
.sp
jack\-transport is a minimalist Jack transport control interface using ncurses\&. It displays the transport state and current time, and provides standard operating keys\&.
.SH "COMMANDS"
.TP
\fBs\fR
Start and stop transport\&. Aliased to [space]\&. 
.TP
\fBl\fR
Locate to entered time\&. Starting to type a number will also enter locate mode\&. 
.TP
\fBi\fR
Set forward & backward increment to entered interval (default = 5 seconds)\&. 
.TP
\fBz\fR
Locate to start (zero)\&. 
.TP
\fBr\fR
Erase and refresh screen\&. 
.TP
\fBf\fR
Move forwards by increment\&. Aliased to [>] and [right\-arrow]\&. 
.TP
\fBb\fR
Move backwards by increment\&. Aliased to [<] and [left\-arrow]\&. 
.TP
\fBF\fR
Move forwards one minute\&. Aliased to [\&.] and [up\-arrow]\&. 
.TP
\fBB\fR
Skip backwards one minute\&. Aliased to [,] and [down\-arrow]\&.
.SH "AUTHOR"
.sp
Rohan Drape http://rd\&.slavepianos\&.org/
.SH "SEE ALSO"
.sp
jackd(1), jack\-play(1)
.SH "AUTHOR"
.PP
\fBRohan Drape\fR <\&rd@slavepianos\&.org\&>
.RS 4
Author.
.RE
