'\" t
.\"     Title: jack-scope
.\"    Author: Rohan Drape <rd@slavepianos.org>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 06/16/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "JACK\-SCOPE" "1" "06/16/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jack-scope \- JACK Oscilloscope
.SH "SYNOPSIS"
.sp
jack\-scope [options]
.SH "OPTIONS"
.sp
\fB\-b\fR : Set the frame size of the data displayed by the scope (default=512)\&.
.sp
\fB\-d\fR : Set the delay interval in milli\-seconds between scope updates (default=100\&.0)\&.
.sp
\fB\-f\fR : Request that a still image file of each frame be stored to the indicated directory\&.
.sp
\fB\-m\fR : Set the scope operating mode (default=signal)\&. The operating modes are: signal and embed\&.
.sp
\fB\-n\fR : Set the number of channels, and therefore the number of JACK input ports (default=1)\&. Multiple channels are superimposed, each channel is drawn in a distinct color\&. There is a compile time channel limit\&.
.sp
\fB\-p\fR : A pattern describing the JACK ports to connect to, ie\&. SuperCollider:out_%d (default=nil)\&. If this is not set consults the environment variable JACK_SCOPE_CONNECT_TO\&.
.sp
\fB\-s\fR : Set the drawing style for signal mode (default=dot)\&.
.sp
\fB\-u\fR : Set the UDP port number to listen for OSC packets on (default=57140)\&.
.sp
\fB\-w\fR : Set the scope size in pixels (default=512)\&. The scope window is square\&.
.SH "DESCRIPTION"
.sp
jack\-scope is an oscilloscope for JACK under X11\&. jack\-scope draws either a time domain signal trace or a self correlation trace\&. Multiple input channels are superimposed, each channel is drawn in a different color\&. jack\-scope accepts OSC packets for interactive control of drawing parameters\&.
.sp
The operating mode of jack\-scope is set using \fB\-m\fR\&. In signal mode jack\-scope draws a time domain signal trace, in embed mode jack\-scope draws a self correlation trace\&.
.sp
The size of the jack\-scope window is set using \fB\-w\fR, the scope window is square\&. The window is of fixed size and has centered gravity\&. The time interval that is displayed is determined by the frame size, set using \fB\-b\fR\&. The image refresh rate is determined by the delay interval, set using \fB\-d\fR\&. Note that the interval is truncated to the nearest frame boundary and that the time taken to compose the image and blit to the screen is indeterminate\&.
.sp
The number of JACK input ports that jack\-scope creates and monitors is set using \fB\-n\fR\&. Multiple channels are drawn in superimposition, each channel is drawn in a distinct color\&.
.sp
In signal mode the trace is drawn in a style set using /style\&. In dot mode only the sample pixel in each column is drawn\&. In fill mode all pixels between the sample pixel and the zero pixel of each column are drawn\&. In line mode all pixels between the adjacent sample pixels of each column are drawn\&.
.sp
In embed mode the trace is a self correlation signal with a sample delay set using /embed\&. The delayed sample is on the x\-axis\&. The interpolation increment is set using /incr, increment values less than one result in increasingly continuous trace paths\&.
.sp
jack\-scope can store the animation as a sequence of uncompressed ppm(5) image files\&. To request this use the \fB\-f\fR option with the directory files should be written to as the argument\&.
.sp
The OSC messages understood by jack\-scope are given in the table below\&. Each command requires one argument of the indicated type\&. The last column gives the option that sets the same parameter\&.
.sp
Command (Description) Argument, Option
.br
/mode (drawing\-mode) string, \-m
.br
/style (style) string, N/A
.br
/frames (frame\-size) integer, \-b
.br
/delay (refresh\-interval) float, \-d
.br
/embed (embedding) integer, N/A
.br
/incr (increment) float, N/A
.sp
jack\-scope implements no connection logic, use jack\-plumbing(1) instead\&.
.SH "REFERENCES"
.sp
Monro, G\&. and Pressing, J\&. \(oq\(oqSound Visualization Using Embedding: The Art and Science of Auditory Autocorrelation\(cq\(cq CMJ, 22/2, 1998\&.
.SH "AUTHOR"
.sp
Rohan Drape http://rd\&.slavepianos\&.org/
.SH "SEE ALSO"
.sp
jackd(1), X(7x), OSC(7) http://opensoundcontrol\&.org/
.SH "AUTHOR"
.PP
\fBRohan Drape\fR <\&rd@slavepianos\&.org\&>
.RS 4
Author.
.RE
