.\" -*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH RUN-PARTS 8 "14 Apr 2002" "Slackware Version 8.1.0
.SH NAME
run-parts \- run scripts found in a directory
.SH SYNOPSIS
.B run-parts <directory>
.LP
.SH DESCRIPTION
.B run-parts
is a utility that will run scripts that are found in a directory.  For example,
it might be useful to create an /etc/cron.daily directory and put scripts in
there for daily cron jobs.  Then
.B run-parts
can be called once a day from root's crontab to run all the scripts found in
/etc/cron.daily:

40 4 * * * run-parts /etc/cron.daily

.B run-parts
automatically skips files with certain suffixes that are generally associated
with backup or extra files.  Any file that ends in one of these will be silently
ignored:  ~ ^ , .bak .new .rpmsave .rpmorig .rpmnew .swp
.SH AUTHOR
Patrick J. Volkerding <volkerdi@slackware.com>, with ideas borrowed from the
Red Hat and Debian versions of this utility.
.SH "SEE ALSO"
.BR crond(8),
.BR crontab(8).
