#!/bin/sh

# Slackware build script for qemu-kvm

# Written by Stu Miller <slackbuilds@go4it2day.com>
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=qemu-kvm
VERSION=${VERSION:-1.0}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

KVMGROUP=${KVMGROUP:-users}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

# Needed to build man pages if build with plain "su"
export PATH=$PATH:/usr/share/texmf/bin

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fixup udev rules file to remove NAME="%k" and allow use of a different group
patch -p1 < $CWD/patches/fixup_udev_rules.patch

# Fix build on recent kernels
patch -p1 < $CWD/patches/deprecate-time-drift-fix.patch

# Fix CVE-2012-029
patch -p1 < $CWD/patches/qemu-kvm-1.0-CVE-2012-029.patch

# Disable debug (hardcoded) and remove double CFLAGS
sed -i "s|^CFLAGS=\"-g\ |CFLAGS=\"|" configure
sed -i "s|^LDFLAGS=\"-g\ |LDFLAGS=\"|" configure
sed -i "s|^\ \ CFLAGS=\"-O2\ |  CFLAGS=\"|" configure

# check if spice support is enabled
if pkg-config --exists spice-server ; then
  with_spice="--enable-spice"
else
  with_spice="--disable-spice"
fi

# The script builds only the 32/64 bit x86 compatible Linux Target CPU emulator.
# If you need to emulate other available architectures you should install the
# "qemu" package, not the "qemu-kvm" package.  This package will only be useful
# for x86 architectures that can make use of KVM-KMOD kernel modules which are
# the kvm-intel, kvm-amd, and kvm modules.

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --enable-mixemu \
  --audio-drv-list=alsa,oss,sdl,esd \
  --enable-system \
  --target-list="x86_64-softmmu" \
  $with_spice

make V=1 \
  OS_CFLAGS="$SLKCFLAGS" \
  mandir=/usr/man \
  docdir=/usr/doc/$PRGNAM-$VERSION
make install \
  mandir=/usr/man \
  docdir=/usr/doc/$PRGNAM-$VERSION \
  DESTDIR=$PKG

# Rename the primary binary from "qemu-system-x86_64" to "qemu-kvm" so that the
# regular "qemu" package won't overwrite it.
mv $PKG/usr/bin/qemu-system-x86_64 $PKG/usr/bin/qemu-kvm

# Copy a missed binary
cp -a kvm/kvm_stat $PKG/usr/bin/

mkdir -p $PKG/lib/udev/rules.d/
sed "s/@GROUP@/$KVMGROUP/" kvm/scripts/65-kvm.rules \
  > $PKG/lib/udev/rules.d/65-kvm.rules

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
find $PKG/usr/man -type f -exec chmod 0644 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a kvm/scripts $PKG/usr/doc/$PRGNAM-$VERSION/
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
