# Build queue for clamtk
perl-Sub-Uplevel
perl-Test-Exception
perl-Carp-Clan
perl-Bit-Vector
perl-Date-Calc
perl-html-tagset
perl-html-parser
perl-encode-locale
perl-uri-escape
perl-http-date
perl-lwp-mediatypes
perl-file-listing
perl-net-http
perl-www-robotrules
perl-http-message
perl-http-negotiate
perl-http-cookies
perl-http-daemon
libwww-perl
locale-gettext
perl-Text-Glob
perl-Number-Compare
perl-File-Find-Rule
perl-net-ip
perl-digest-sha1
perl-digest-hmac
perl-net-dns
perl-extutils-pkgconfig
perl-extutils-depends
perl-glib
perl-test-number-delta
perl-cairo
perl-pango
perl-gtk2
clamav
clamtk
