#!/bin/bash
#
# SlackBuild for rpy2
#
# Copyright 2020-2026 Rob van Nues (sborg63@disroot.org)
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=rpy2
VERSION=${VERSION:-3.6.7}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}
SRCREF=RELEASE
SRCDELIM="_"
SRCNAM=${SRCNAM:-3_6_7}
SRCVERSION=$SRCREF$SRCDELIM$SRCNAM
MODULE1=${MODULE1:-rinterface}
MODULE2=${MODULE2:-robjects}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
else
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
#tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
tar xvf $CWD/$PRGNAM-$SRCVERSION.tar.gz
#cd $PRGNAM-$VERSION
cd $PRGNAM-$SRCVERSION

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

## make sure there is R
if ! [ -x "$(command -v R)" ]; then
  echo 'Error: R is not installed.' >&2
  exit 1
fi

## make sure that R has been compiled with
## --enable-R-shlib
## --enable-BLAS-shlib
RHOMLIB=$(R RHOME)
echo Found R libs:
echo $RHOMLIB/lib/*

if ! [ "$(readelf -h $RHOMLIB/lib/libR*.so | grep DYN)" ]; then
  echo "Error: R is not compiled with shared libraries." >&2
  exit 1
fi


# check where we build, on Slackware stable or on current (stable+)
OSVERSION="$(cat /etc/os-release | grep "VERSION_CODENAME" | cut -c 18-)"
PYVER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')

if [[ $OSVERSION == "current" ]]; then
  echo "Installing on current, into python$PYVER/site-packages/ "
elif [[ $OSVERSION == "stable" ]]; then
  echo "Installing on stable, into python$PYVER/site-packages/ "
  export PYTHONPATH=/opt/python$PYVER/site-packages/
else 
  echo "Stopping; $OSVERSION is not 'stable' nor 'current, sorry." 
  exit 1
fi

## this removes an error message from setup.py
## https://github.com/rpy2/rpy2/issues/675
export LD_LIBRARY_PATH="${RHOMLIB}/lib:${LD_LIBRARY_PATH}"
echo "LD_LIBRARY_PATH set to ${LD_LIBRARY_PATH}"

cd $PRGNAM-$MODULE1
# replace deprecated `python3 setup.py build install --root=$PKG`
# thanks to fourtysixandtwo
python3 -m build --no-isolation
python3 -m installer -d "$PKG" dist/*.whl

cd ../$PRGNAM-$MODULE2
python3 -m build --no-isolation
python3 -m installer -d "$PKG" dist/*.whl

cd ..

# Remove rpaths:
for file in $(find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : 2> /dev/null) ; do
  if [ ! "$(patchelf --print-rpath $file 2> /dev/null)" = "" ]; then
    patchelf --remove-rpath $file
    echo "\nremoved rpath-file: $file\n"
  fi
done

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM-$MODULE1
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM-$MODULE2
mkdir -p $PKG/usr/share/$PRGNAM-$VERSION/scripts
cp -a AUTHORS gpl-2.0.txt NEWS README* $PKG/usr/doc/$PRGNAM-$VERSION
cp  $PRGNAM-$MODULE1/README* $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM-$MODULE1
cp  $PRGNAM-$MODULE2/README* $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM-$MODULE2
cp -a scripts/* $PKG/usr/share/$PRGNAM-$VERSION/scripts
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
## to facilitate dynamic linking with R,
## libR.so and libRblas.so still need to be found
## https://github.com/rpy2/rpy2/issues/675
## for this, create "/etc/ld.so.conf.d/Rlibs.conf" with the line
## "/usr/lib${LIBDIRSUFFIX}/R/lib"
## via doinst.sh
# thanks to cwilling
## directly cat to package in case no w-permission on $CWD
#cat > $CWD/doinst.sh <<EOF
cat > $PKG/install/doinst.sh  <<EOF
echo "/usr/lib${LIBDIRSUFFIX}/R/lib" > etc/ld.so.conf.d/Rlibs.conf
sbin/ldconfig
EOF
#cat > $CWD/douninst.sh <<EOF
cat > $PKG/install/douninst.sh <<EOF
rm etc/ld.so.conf.d/Rlibs.conf
sbin/ldconfig
EOF
#cat $CWD/doinst.sh > $PKG/install/doinst.sh
#cat douninst.sh > $PKG/install/douninst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
