#!/bin/sh
#
# Written by Jockey S. Kyd (jockey dot kyd at gmail dot com)
# Public domain
#

PRGNAM=alloy
VERSION=4.1.10
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$(uname -m)" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$(uname -m) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
DIST=$PRGNAM${VERSION%%.*}

case "$ARCH" in
  x86_64) LIBDIRSUFFIX="64" ;;
       *) LIBDIRSUFFIX="" ;;
esac

set -e
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP

mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/$PRGNAM
install -Dm 644 $CWD/$DIST.jar $PKG/usr/lib$LIBDIRSUFFIX/$PRGNAM/$DIST.jar

mkdir -p $PKG/usr/bin
( cd $PKG/usr/bin
  cat > $DIST <<__END__
#!/bin/sh
java -jar /usr/lib$LIBDIRSUFFIX/$PRGNAM/$DIST.jar "\$@"
__END__
  chmod 755 $DIST
  ln -sf $DIST $PRGNAM
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
