.TH COLEM "1" "January 2011" "SlackBuilds.org" "User Commands"
.SH NAME
colem \- Emulator for ColecoVision and Coleco Adam consoles
.SH SYNOPSIS
.B colem
[\fI-option1 \fR[\fI-option2\fR...]] [\fIfilename\fR]
.SH DESCRIPTION
ColEm is a portable emulator of the old ColecoVision videogame console. It should run most ColecoVision games and supports Coleco's SuperAction controllers with spin wheels.
.PP
You can always get the latest ColEm binaries, source code, and support files from
.B http://fms.komkon.org/ColEm/ 
.SH OPTIONS
.TP
\fB[filename]\fR
Name of the file to load as a cartridge [default: CART.ROM]
.PP
This program will transparently uncompress singular GZIPped
and PKZIPped files.
.TP
\fB\-verbose\fR <level>
Select debugging messages [bitmask, default: 5]
.br
0 \- Silent
.br
1 \- Startup messages
.br
2 \- VDP
.br
4 \- Illegal Z80 ops
.br
16 \- Sound
.TP
\fB\-pal\fR, \fB\-ntsc\fR
Video system to use [default: \-ntsc]
.TP
\fB\-skip\fR <percent>
Percentage of frames to skip [default: 25]
.TP
\fB\-help\fR
Print this help page
.TP
\fB\-home\fR <dirname>
Set directory with system ROM files [default: see FILES, below]
.TP
\fB\-adam\fR, \fB\-cv\fR
Run in Adam/ColecoVision mode [default: \-cv]
.TP
\fB\-allspr\fR
Show all sprites [off]
.TP
\fB\-autoa\fR, \fB\-noautoa\fR
Autofire/No autofire for FIRE\-R button [default: \-noautoa]
.TP
\fB\-autob\fR, \fB\-noautob\fR
Autofire/No autofire for FIRE\-L button [default: \-noautob]
.TP
\fB\-spin1x\fR, \fB\-spin1y\fR
Mouse X/Y position as SuperAction spinner 1 [default: off]
.TP
\fB\-spin2x\fR, \fB\-spin2y\fR
Mouse X/Y position as SuperAction spinner 2 [default: off]
.TP
\fB\-drums\fR, \fB\-nodrums\fR
Hit/Don't hit MIDI drums on noise [default: \-nodrums]
.TP
\fB\-logsnd\fR <filename>
Write soundtrack to a MIDI file [default: LOG.MID]
.TP
\fB\-palette\fR <number>
Use given color palette [default: 0]
.br
0 \- Scaled VDP colors
.br
1 \- Original VDP colors
.br
2 \- Faded NTSC colors
.TP
\fB\-sound\fR [<quality>]
Sound emulation quality [default: 22050]
.TP
\fB\-nosound\fR
Don't emulate sound [default: emulate sound]
.TP
\fB\-trap\fR <address>
Trap execution when PC reaches address [default: FFFFh]
.TP
\fB\-sync\fR <frequency>
Sync screen updates to <frequency> [default: 60]
.TP
\fB\-nosync\fR
Do not sync screen updates [default: \-nosync]
.TP
\fB\-tv\fR, \fB\-notv\fR
Simulate/Don't simulate scanlines [default: \-notv]
.TP
\fB\-soft\fR, \fB\-nosoft\fR
Scale screen up with softening [default: \-nosoft]
.TP
\fB\-saver\fR, \fB\-nosaver\fR
Save/don't save CPU when inactive [default: \-saver]
.TP
\fB\-shm\fR, \fB\-noshm\fR
Use/don't use MIT SHM extensions for X [default: \-shm]
.TP
\fB\-scale\fR <factor>
Scale window by <factor> [default: 2]
.SH "KEYBOARD BINDINGS"
.TP
\fB[ALT]\fR
Hold to switch to the second controller
.TP
\fB[SPACE]\fR
FIRE\-R button (also: [SHIFT],A,S,D,F,G,H,J,K,L)
.TP
\fB[CONTROL]\fR
FIRE\-L button (also: Z,X,C,V,B,N,M)
.TP
\fB[Q]\fR
SuperAction PURPLE button (also: E,T,U,O)
.TP
\fB[W]\fR
SuperAction BLUE button (also: R,Y,I,P)
.TP
\fB[0]\-[9]\fR
Digit buttons
.TP
\fB[\-]\fR
[*] button
.TP
\fB[=]\fR
[#] button
.TP
\fB[PGUP]\fR
Fast\-forward emulation (also: [F9])
.TP
\fB[ESC]\fR
Quit emulation (also: [F12])
.TP
\fB[F1]\fR
Go into the built\-in debugger
.TP
\fB[F2]\fR
Turn soundtrack log on/off
.TP
\fB[F3]\fR
Toggle FIRE\-R autofire on/off
.TP
\fB[F4]\fR
Toggle FIRE\-L autofire on/off
.TP
\fB[F5]\fR
Invoke configuration menu
.TP
\fB[F6]\fR
Load emulation state
.TP
\fB[F7]\fR
Save emulation state
.TP
\fB[F8]\fR
Turn scanline simulation on/off
.TP
\fB[ALT]+[F8]\fR
Toggle screen softening on/off
.TP
\fB[F9]\fR
Fast\-forward emulation (also: [PGUP])
.TP
\fB[F11]\fR
Reset hardware
.TP
\fB[F12]\fR
Quit emulation (also: [ESC])
.TP
\fB[ALT]+[PGUP]\fR
Increase audio volume
.TP
\fB[ALT]+[PGDOWN]\fR
Decrease audio volume
.SH FILES
.TP
\fBcoleco.rom\fR
ColecoVision BIOS ROM image (8192 bytes). This is the only ROM required
for playing ColecoVision games.
.TP
\fBwriter.rom\fR
SmartWriter ROM (32768 bytes), only required for emulating the Coleco ADAM system.
.TP
\fBeos.rom\fR
Extended OS ROM (8192 bytes), only required for emulating the Coleco ADAM system.
.PP
The above ROM images may be named in all\-lowercase or all\-uppercase,
and are searched for in:
.PP
1. The directory specified by \fB\-home\fR, or the current directory if \fB\-home\fR not given.
.br
2. \fI/usr/share/colem\fR
.br
3. \fI~/.colem\fR
.PP
The coleco.rom file will occasionally be found on websites with the names "os7.rom"
or "ColecoVision\ BIOS\ (1982).col". Its md5sum is one of:
.PP
2c66f5911e5b42b8ebe113403548eee7 (original version)
.br
00fd13b66d39c69706aa48eb84a78411 (hacked version, different font)
.br
47f7180592a00b9631c97a12ff0fdd3c (hacked version, no title screen delay)
.PP
ColEm works with any of the above ROM images.
.SH AUTHOR
ColEm is by Marat Fayzullin, (C)FMS 1994\-2010
.PP
This man page is by B. Watson, for the SlackBuilds.org project (but may
be used by anyone for any purpose).
