# pod source for colem man page. convert with:
# pod2man --stderr -s6 -r3.3 -cSlackBuilds.org colem.pod > colem.6

=pod

=head1 NAME

colem - Emulator for ColecoVision and Coleco Adam consoles

=head1 SYNOPSIS

colem [-option1 [-option2...]] [filename]

=head1 DESCRIPTION

ColEm is a portable emulator of the old ColecoVision videogame console. It should run most ColecoVision games and supports Coleco's SuperAction controllers with spin wheels.

You can always get the latest ColEm binaries, source code, and support files from
http://fms.komkon.org/ColEm/

=head1 OPTIONS

[filename]
Name of the file to load as a cartridge [default: CART.ROM]

This program will transparently uncompress singular GZIPped files.

=over 4

=item -verbose <level>

Select debugging messages [bitmask, default: 5]

=over 4

=item Z<>0

Silent

=item Z<>1

Startup messages

=item Z<>2

VDP

=item Z<>4

Illegal Z80 ops

=item Z<>16

Sound

=back

=item -pal, -ntsc

Video system to use [default: -ntsc]

=item -skip <percent>

Percentage of frames to skip [default: 25]

=item -help 

Print this help page

=item -home <dirname>

Set directory with system ROM files [default: see FILES, below]

=item -adam, -cv

Run in Adam/ColecoVision mode [default: -cv]

=item -allspr

Show all sprites [off]

=item -autoa, -noautoa

Autofire/No autofire for FIRE-R button [default: -noautoa]

=item -autob, -noautob

Autofire/No autofire for FIRE-L button [default: -noautob]

=item -spin1x, -spin1y

Mouse X/Y position as SuperAction spinner 1 [default: off]

=item -spin2x, -spin2y

Mouse X/Y position as SuperAction spinner 2 [default: off]

=item -drums, -nodrums

Hit/Don't hit MIDI drums on noise [default: -nodrums]

=item -logsnd <filename>

Write soundtrack to a MIDI file [default: LOG.MID]

=item -palette <number>

Use given color palette [default: 0]

=over 4

=item Z<>0

Scaled VDP colors

=item Z<>1

Original VDP colors

=item Z<>2

Faded NTSC colors

=back

=item -sound [<quality>]

Sound emulation quality [default: 22050]

=item -nosound

Don't emulate sound [default: emulate sound]

=item -trap <address>

Trap execution when PC reaches address [default: FFFFh]

=item -sync <frequency>

Sync screen updates to <frequency> [default: 60]

=item -nosync

Do not sync screen updates [default: -nosync]

=item -tv, -notv

Simulate/Don't simulate scanlines [default: -notv]

=item -soft, -nosoft

Scale screen up with softening [default: -nosoft]

=item -saver, -nosaver

Save/don't save CPU when inactive [default: -saver]

=item -shm, -noshm

Use/don't use MIT SHM extensions for X [default: -shm]

=item -scale <factor>

Scale window by <factor> [default: 2]

=back

=head1 KEYBOARD BINDINGS

[ALT] Hold to switch to the second controller

=over 4

=item [SPACE]

FIRE-R button (also: [SHIFT],A,S,D,F,G,H,J,K,L)

=item [CONTROL]

FIRE-L button (also: Z,X,C,V,B,N,M)

=item [Q] 

SuperAction PURPLE button (also: E,T,U,O)

=item [W] 

SuperAction BLUE button (also: R,Y,I,P)

=item [0]-[9]

Digit buttons

=item [-] 

[*] button

=item [=] 

[#] button

=item [PGUP]

Fast-forward emulation (also: [F9])

=item [ESC]

Quit emulation (also: [F12])

=item [F1] 

Go into the built-in debugger

=item [F2] 

Turn soundtrack log on/off

=item [F3] 

Toggle FIRE-R autofire on/off

=item [F4] 

Toggle FIRE-L autofire on/off

=item [F5] 

Invoke configuration menu

=item [F6] 

Load emulation state

=item [F7] 

Save emulation state

=item [F8] 

Turn scanline simulation on/off

=item [ALT]+[F8]

Toggle screen softening on/off

=item [F9] 

Fast-forward emulation (also: [PGUP])

=item [F11]

Reset hardware

=item [F12]

Quit emulation (also: [ESC])

=item [ALT]+[PGUP]

Increase audio volume

=item [ALT]+[PGDOWN]

Decrease audio volume

=back

=head1 FILES

=over 4

=item coleco.rom

ColecoVision BIOS ROM image (8192 bytes). This is the only ROM required for playing ColecoVision games.

=item writer.rom

SmartWriter ROM (32768 bytes), only required for emulating the Coleco ADAM system.

=item eos.rom

Extended OS ROM (8192 bytes), only required for emulating the Coleco ADAM system.

=back

The above ROM images may be named in all-lowercase or all-uppercase, and are searched for in:

1. The directory specified by -home, or the current directory if -home not given.

2. /usr/share/colem/

3. ~/.colem/

The coleco.rom file will occasionally be found on websites with the names "os7.rom" or "ColecoVision BIOS (1982).col". Its md5sum is one of:

 2c66f5911e5b42b8ebe113403548eee7 (original version)
 00fd13b66d39c69706aa48eb84a78411 (hacked version, different font)
 47f7180592a00b9631c97a12ff0fdd3c (hacked version, no title screen delay)

ColEm works with any of the above ROM images.

=head1 AUTHOR

ColEm is by Marat Fayzullin, (C)FMS 1994-2010

This man page is by B. Watson, for the SlackBuilds.org project (but may be used by anyone for any
purpose).
