#!/bin/sh

# Slackware build script for OpenOffice.org

# Copyright 2006-2010  Robby Workman, Northport, Alabama, ASA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Thanks to Sandman1, Larhzu, and MacIver for early assistance.
# Thanks to Fred Emmott (http://slamd64.com) for some better code in a few
#   places and ideas to include the Optimization Solver and disable javaldx.
# Thanks to hba for the idea to include support for other languages.
# Thanks to Nille Akerstrom for the diff to support w/JRE tarballs
# Thanks to ivo@linvo.org for hints on installing extensions
# Thsnks to necropresto for better x86_64 support

PRGNAM=openoffice.org
VERSION=3.2.0
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# This should allow you to either pass a different value of OOLANG when you
# run the script (OOLANG=pt-BR ./openoffice.org.SlackBuild for example) or
# change it in this script.  Note that you will need to have the correct
# tarball in the build directory for this to work...
# You can get localized tarballs from the following location:
# ftp://ftp.free.fr/mirrors/ftp.openoffice.org/localized/$OOLANG/$VERSION/
# Thanks to Niki Kovacs for finding this :-)
OOLANG=${OOLANG:-en-US}
PKG_LANG=${OOLANG//-/_}	# Leave this alone
# Some localized versions only ship with a bundled JRE, and we'd like this
# script to work on those as well...
WJRE=${WJRE:-no}

# If you want to disable java support by removing executable permissions
# form OOo's java loader (this will not affect other apps), set this
# variable to "YES"   Default is "NO"
DISABLE_JAVA=${DISABLE_JAVA:-NO}

# Change source package name
if [ "$ARCH" = "x86_64" ]; then
  SRCARCH="X86-64"
  PKGARCH="$ARCH"
  WJRE=yes #Overwrite WJRE option since the only x86_64 I see has jre
else
  SRCARCH="Intel"
  PKGARCH="i586"
fi

# Yes, I know there is a Slackware integration file in the desktop-integration
# directory, but it's worthless to us.  I'd prefer to do things correctly.

# Ignore this - it's just to get the toplevel directory name of the 
# extracted tarball archive
if [ $WJRE != no ]; then
  SOURCEDIR=$(tar tzf $CWD/OOo_${VERSION}_Linux${SRCARCH}_install_wJRE_${OOLANG}.tar.gz | head -1 | tr -d \/)
else
  SOURCEDIR=$(tar tzf $CWD/OOo_${VERSION}_Linux${SRCARCH}_install_${OOLANG}.tar.gz | head -1 | tr -d \/)
fi
# If the above operation failed for some reason, unset SOURCEDIR so that
# the "set -eu" below will cause us to bail out with an error
[ -z $SOURCEDIR ] && unset SOURCEDIR
  
set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
rm -rf $TMP/$SOURCEDIR

# Handle the tarballs that include a bundled JRE
if [ $WJRE != no ]; then
  tar xvf $CWD/OOo_${VERSION}_Linux${SRCARCH}_install_wJRE_${OOLANG}.tar.gz -C $TMP
  rm -rf $TMP/$SOURCEDIR/{JavaSetup.jar,installdata,setup}
  rm -rf $TMP/$SOURCEDIR/RPMS/{userland,jre-*-linux-*.rpm}
else
  tar xvf $CWD/OOo_${VERSION}_Linux${SRCARCH}_install_${OOLANG}.tar.gz -C $TMP
fi

cd $TMP/$SOURCEDIR/RPMS/
mv desktop-integration/openoffice.org3.2-freedesktop-menus-3.2-9472.noarch.rpm .
rm *onlineupdate*.rpm # We don't want this
for FILE in *.rpm ; do rpm2cpio < $FILE | cpio -imdv ; done
rm -rf desktop-integration *.rpm
mv opt usr $PKG
cd $PKG

# Kill a broken symlink
rm -f $PKG/usr/share/applications/openoffice.org3-startcenter.desktop

# Create symlinks in /usr/bin to actual binaries
cd $PKG/usr/bin
  for FILE in \
    sbase scalc sdraw simpress smath soffice spadmin swriter unopkg ; do 
      rm -f $FILE
      ln -sf ../../opt/openoffice.org3/program/$FILE $FILE ;
  done 
cd -

# Remove DejaVu and Liberation fonts - these are included in other packages
rm -f opt/openoffice.org/basis3.2/share/fonts/truetype/[DL]*.ttf

# Fix Exec commands in the desktop files
# See http://bugzilla.xfce.org/show_bug.cgi?id=2430 
cd $PKG//opt/openoffice.org3/share/xdg/
  for APP in base calc draw impress math writer; do
    sed -i 's%Exec=openoffice.org3 -%Exec=s%' $APP.desktop ;
  done
cd -

# Install extensions
UNOPKG_BIN=$PKG/opt/openoffice.org3/program/unopkg
DICT_DIR=$PKG/opt/openoffice.org3/share/extension/install
if [ -x "$UNOPKG_BIN" ]; then
  UNOPKG_TMP=$TMP/$$$$$$
  find $DICT_DIR -type f -name "*.oxt" \
    -exec $UNOPKG_BIN add --shared {} \
    "-env:UserInstallation=file:///$UNOPKG_TMP" \;
  rm -rf $UNOPKG_TMP 	# Clean up after ourselves
fi

# Move docs to their expected locations
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cd $PKG/opt/openoffice.org3
  mv README* *LICENSE* readmes licenses $PKG/usr/doc/$PRGNAM-$VERSION
cd -
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# Disable Java support if desired (see above)
if [ "$DISABLE_JAVA" = "YES" ]; then
  chmod -x $PKG/opt/openoffice.org/ure/bin/javaldx
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# Fix ownership and permissions and make the package
chown -R root:root .
find . -type d -exec chmod 755 {} \;
chmod -R u+rw,go+r-w,a-s .
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-${VERSION}_${PKG_LANG}-$PKGARCH-$BUILD$TAG.${PKGTYPE:-tgz}
