#!/bin/bash

# /usr/share/icewm/shutdown
# This script is used to execute additional commands at icewm session exit

# killall xscreensaver
# killall nm-applet
# killall polkit-gnome-authentication-agent-1

