#!/bin/sh
#
# Slackware build script for rsyslog
# Written by Christophe Trussardi (chris at teria dot org)
#

PRGNAM=rsyslog
VERSION=${VERSION:-5.8.6}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

[ "${MYSQL:-no}" = "no" ] || mysql_option="--enable-mysql"
[ "${PGSQL:-no}" = "no" ] || pgsql_option="--enable-pgsql"
[ "${LIBDBI:-no}" = "no" ] || libdbi_option="--enable-libdbi"
[ "${GNUTLS:-no}" = "no" ] || gnutls_option="--enable-gnutls"
[ "${RELP:-no}" = "no" ] || relp_option="--enable-relp"

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux \
  $mysql_option $pgsql_option $libdbi_option $gnutls_option $relp_option 

make
make install-strip DESTDIR=$PKG

mkdir -p $PKG/etc/rc.d/
cat $CWD/config/rsyslog.conf > $PKG/etc/rsyslog.conf.new
cat $CWD/config/rc.rsyslogd > $PKG/etc/rc.d/rc.rsyslogd.new
chmod 0755 $PKG/etc/rc.d/rc.rsyslogd.new

mkdir -p $PKG/etc/logrotate.d/
cat $CWD/config/rsyslog > $PKG/etc/logrotate.d/rsyslog.new

# Create log files in such a way that they won't clobber existing ones
mkdir -p $PKG/var/log
for i in cron debug maillog messages secure spooler syslog; do
 touch $PKG/var/log/$i.new ;
done

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
cp -a \
  AUTHORS COPYING COPYING.LESSER ChangeLog INSTALL NEWS README \
  $PKG/usr/doc/$PRGNAM-$VERSION 
cp -a doc/*.{jpg,html,png} $PKG/usr/doc/$PRGNAM-$VERSION/html
chmod -R 0644 $PKG/usr/doc/$PRGNAM-$VERSION/*
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/README.SLACKWARE > $PKG/usr/doc/$PRGNAM-$VERSION/README.SLACKWARE

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
