#!/bin/sh

# Slackware build script for ags

# Copyright 2015 Dugan Chen Canada
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=ags
VERSION=${VERSION:-3.3.4.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

# Dependency tarball versions.
ALLEGRO_VERSION=${ALLEGRO_VERSION:-4.4.2}
DUMB_VERSION=${DUMB_VERSION:-0.9.3}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP

rm -rf allegro-${ALLEGRO_VERSION}
rm -rf dumb-${DUMB_VERSION}
rm -rf allegro${ALLEGRO_VERSION}

# Build Allegro 4 first.

tar xvf $CWD/allegro-${ALLEGRO_VERSION}.tar.gz
cd allegro-${ALLEGRO_VERSION}

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir build
cd build
cmake \
	-DWANT_DOCS=OFF \
	-DWANT_EXAMPLES=OFF \
	-DWANT_TESTS=OFF \
	-DWANT_TOOLS=OFF \
	-DCMAKE_INSTALL_PREFIX=/opt/ags-$VERSION \
	-DCMAKE_BUILD_TYPE=Release \
	..
CFLAGS="$SLKCFLAGS" CXXFLAGS="$SLKCFLAGS" make
make install DESTDIR=$PKG

# Then build Dynamic Universal Music Bibliotheque.

cd $TMP
tar xvf $CWD/dumb-${DUMB_VERSION}.tar.gz
cd dumb-$DUMB_VERSION

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

cat << EOF > make/config.txt
include make/unix.inc
ALL_TARGETS := core core-examples core-headers
ALL_TARGETS += allegro allegro-examples allegro-headers
PREFIX := $PKG/opt/ags-$VERSION
EOF

PATH="$PATH:$PKG/opt/ags-$VERSION/bin" make \
	WFLAGS="-I$PKG/opt/ags-$VERSION/include $SLKCFLAGS" \
	LDFLAGS="-lm -L$PKG/opt/ags-$VERSION/lib $LDFLAGS"
make install

# And finaly install Adventure Game Studio.

cd $TMP
tar xvf $CWD/v.${VERSION}.tar.gz
cd ags-v.$VERSION

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

CFLAGS="-I$PKG/opt/ags-$VERSION/include $SLKCFLAGS" \
 CXXFLAGS="-I$PKG/opt/ags-$VERSION/include $SLKCFLAGS" \
 LDFLAGS="-L$PKG/opt/ags-$VERSION/lib -Wl,-rpath,/opt/ags-$VERSION/lib" \
 PATH="$PATH:$PKG/opt/ags-$VERSION/bin" \
 make --directory=Engine
mkdir -p $PKG/usr/bin
cp Engine/ags $PKG/opt/ags-$VERSION/bin

(
cd $PKG/usr/bin
ln -s ../../opt/ags-$VERSION/bin/ags .
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README.md $PKG/usr/doc/$PRGNAM-$VERSION
cp -a debian/README.md $PKG/usr/doc/$PRGNAM-$VERSION/README-debian.md
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
