.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH gmrun 1 "August  8, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gmrun \- Featureful CLI-like GTK+ application launcher
.SH SYNOPSIS
.B gmrun \fR\fI[TEXT]\fR
.br
.SH DESCRIPTION
This manual page documents briefly the
.B gmrun
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgmrun\fP is a program that allows a user to use a CLI-like interface to launch applications from within the X11 windowing environment. It is based on the GTK+ toolkit.
.SH OPTIONS
If gmrun is invoked with a command-line parameter, that will be the initial content of the dialog box.
.PP
gmrun can be customized using a configuration file, ~/.gmrunrc . The system-wide configuration file is /etc/gmrunrc .
.PP
The format of the configuration file is simple; "variable = value". To refer to a variable as opposed to setting it, enclose the variable in ${}.
.TP
.B Example:
variable1 = foobar
.br
newvariable = ${variable1} foobaz
.TP
Were this placed within the configuration file, the gmrun variable "newvariable" would contain the text "foobar foobaz". Some variables that are understood by gmrun, by default. These are:
.TP
.B Terminal
The command to run when Ctrl+Enter is pressed with no command entered; used to start a new terminal.
.TP
.B TermExec
The command to run when Ctrl+Enter is pressed with a command entered. The entered command is supplied as an argument to TermExec.
.TP
.B Width
Initial width of gmrun window.
.TP
.B Top, Left
Initial placement of gmrun window - specify both Top and Left variables such that the gmrun window is placed at pixel (Top,Left) of your desktop.
.TP
.B History
Number of entered commands which should be kept in gmrun's history(~/.gmrun_history). Using the Up and Down arrow keys within the gmrun window will cycle through the history. You can search backwards through the history with Ctrl+R or by writing \fB!\fP (exclamation mark), and forward with Ctrl+S. To cancel a search, hit Ctrl+G or the \fIESC\fP key. Otherwise, after you have found the history item you wish to run, hit Enter.
.TP
.B ShowLast
Whether to show the last command as initial text, or an empty textarea (1 or 0).
.TP
.B Selected
Whether the initial text should be selected or not (1 or 0).
.SH URL HANDLING
As opposed to entering a command, gmrun supports the entering of URLs. The included configuration file(/etc/gmrunrc) gives some examples. To set up your own url, create a variable in /etc/gmrunrc or ~/.gmrunrc with the format of "URL_protocol". For instance, URL_http. Here is an example:
.TP
.B URL_http = /usr/bin/mozilla %u
Using this, entering "http://www.slashdot.org" will run '/usr/bin/mozilla http://slashdot.org'.
.TP
gmrun may also strip the protocol and colon away from the entered URL before passing it to the defined program. For example:
.TP
.B URL_mailto = mutt %s
Using this, entering "mailto:david@eelf.ddts.net" will run the command 'mutt david@eelf.ddts.net'
.TP
The included configuration files has a few examples which you can work with. You should also note that the protocol part of URL_protocol can be *anything*. You can set up "URL_foobarbazcustom", and so long as you enter in "foobarbazcustom:<whatever>", it will use the given program. Have fun :)
.SH SEE ALSO
.BR /usr/share/doc/gmrun/README.gz,
.BR /etc/gmrunrc.
.br
.SH AUTHOR
gmrun was written and is maintained by
.B Mihai Bazon <mishoo@infoiasi.ro>
, the latest version is available from
\fIhttp://www.sourceforge.net/projects/gmrun/\fP
.PP
This manual page was written by David B Harris <david@eelf.ddts.net>,
for the Debian GNU/Linux system (but may be used by others).
