.TH TINT 6 "October 8, 2024" "@VERSION@" "SlackBuilds.org"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tint \- clone of the original Tetris
.SH SYNOPSIS
.B tint
.RI [ -h ]
.RI [ -l\  level ]
.RI [ -n ]
.RI [ -d ]
.RI [ -b\  char ]
.SH DESCRIPTION
This manual page documents the game
.B tint
(a tetris clone). As with all games (and especially with tint), you have to play it,
not read about it.
.P
A summary of options and keyboard controls is included below.
For a complete description, see the NOTES file in /usr/doc/tint-@VERSION@.
.SH OPTIONS
.TP
.B \-h
Show summary of options.
.TP
.B \-l <level>
Specify the starting level (1-9). The higher the level you're starting from,
the faster you'll earn points.
.TP
.B \-n
Draw next shape. When the next shape is drawn, you might find the game to be
easier, but it will be slower to earn points.
.TP
.B \-d
Draw dotted lines.
.TP
.B \-b <char>
Use the specified character (instead of spaces) to draw blocks.
.SH KEYBOARD
.TP
.B Left Arrow, j
Move piece left.
.TP
.B Right Arrow, l
Move piece right.
.TP
.B Up Arrow, Enter
Rotate piece.
.TP
.B Down Arrow, Space
Drop piece.
.TP
.B s
Show next piece (same as \-n option).
.TP
.B d
Show dotted lines (toggle \-d option).
.TP
.B a
Speed up game (next value of \-n option, up to 9).
.TP
.B p
Pause game.
.TP
.B q
Quit game and exit \fBtint\fR.
.SH FILES
.TP
.B /var/games/tint.scores
High scores are stored here. The file is group-owned by the \fBgames\fR
group, and the game runs setgid so that all users' high scores can be
written to the file.
.PP
To reset the high scores, you can truncate the file to zero bytes, but
don't delete it or change its permissions/ownership. One way to do this:
.PP
root@darkstar# truncate -s0 /var/games/tint.scores
.SH AUTHOR
This manual page was written by Abraham van der Merwe <abz@debian.org>,
for the Debian GNU/Linux system (but may be used by others). It has been
modified for use by the SlackBuilds.org project by B. Watson <urchlay@slackware.uk>.
