#!/bin/sh

# Slackware build script for newtonsoft-json
# Packager: Ronny Schmatzler
# http://www.schmatzler.de
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=newtonsoft-json
VERSION=${VERSION:-8.0.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

# Create building directory
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
# Make sure sbokpg can extract the source
tar xvf $CWD/Newtonsoft.Json-$VERSION.tar.gz || tar xvf $CWD/$VERSION.tar.gz
cd Newtonsoft.Json-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Build json
cd $TMP/Newtonsoft.Json-$VERSION/Src/Newtonsoft.Json
xbuild Newtonsoft.Json.csproj \
/property:SignAssembly=true                             \
/property:AssemblyOriginatorKeyFile=Dynamic.snk         \
/property:Configuration=Release                         \
/property:DefineConstants='SIGNED NET45 TRACE'
cd bin/Release/Net45
monodis Newtonsoft.Json.dll --output=Newtonsoft.Json.il
ilasm /dll /key:../../../Dynamic.snk Newtonsoft.Json.il


# Create package
cd "$TMP/Newtonsoft.Json-$VERSION"
# Install license doc
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
install -Dm644 LICENSE.md $PKG/usr/doc/$PRGNAM-$VERSION/LICENSE.md
cat $CWD/slack-desc > $PKG/usr/doc/$PRGNAM-$VERSION/slack-desc
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# Remove unneeded stuff
cd Src/Newtonsoft.Json/bin/Release/Net45
rm *.{xml,snk,il}

# Install Json into mono directory
# Libraries in the Global Assembly Cache are always in /usr/lib, regardless of the architecture
# /usr/lib64/mono doesn't even get created when running mono.SlackBuild
mkdir -p "$PKG/usr/lib/mono/newtonsoft-json/"
find . -type f -exec install -Dm644 {} "$PKG/usr/lib/mono/newtonsoft-json/"{} \;

# Install pkg-config file
install -Dm644 "$CWD/newtonsoft.json.pc.in" "$PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/newtonsoft.json.pc"

#patch file to get it recognized
sed -i "s,@VERSION@,$VERSION," "$PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/newtonsoft.json.pc"

# Also add the slack-desk file and this slackbuild to the package
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cat <<EOF > $PKG/install/doinst.sh
gacutil -i /usr/lib/mono/newtonsoft-json/Newtonsoft.Json.dll -root "/usr/lib/"
EOF

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
