#!/bin/bash

# Slackware build script for franny

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20210825 bkw: BUILD=2, make the man page names match the scripts.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=franny
VERSION=${VERSION:-1.1.3}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tgz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# doubleplusungood refs unfiles.
sed -i 's,\$(PACKAGE)\.\(mo\|pot\|1\),,g' Makefile

# ugh.
sed -i "s,-g\\>,$SLKCFLAGS," Makefile

# -L/lib is the default already on 32-bit slack, and doesn't cause
# a problem on pure 64-bit slack... but it'll break the build on
# multilib, so get rid of it.
sed -i "s,-L/lib,," Makefile

# binary installed stripped by default.
make $PRGNAM install PREFIX=$PKG/usr

# extract.sh and insert.sh names are too generic, rename:
mv $PKG/usr/bin/extract.sh $PKG/usr/bin/$PRGNAM-extract.sh
mv $PKG/usr/bin/insert.sh $PKG/usr/bin/$PRGNAM-insert.sh

# fix hardcoded /usr/local paths...
sed -i 's,/local,,' $PKG/usr/bin/$PRGNAM-*.sh

# upstream's man page is missing, I made this from the homepage
# plus some of my own observations.
mkdir -p $PKG/usr/man/man1
gzip -9c < $CWD/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz
ln -s $PRGNAM.1.gz $PKG/usr/man/man1/$PRGNAM-extract.sh.1.gz
ln -s $PRGNAM.1.gz $PKG/usr/man/man1/$PRGNAM-insert.sh.1.gz

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a copying $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
