#!/bin/bash

# Slackware build script for stremio

# Copyright 2023 Martin Bångens Sweden
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=stremio
VERSION=${VERSION:-4.4.168}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

# git submodules
CHROMA=99045142479ba0e2fc3b9cccb72e348c67cd5829
LIBMPV=b0eae77cf6dc59aaf142b7d079cb13a0904fd3ee
SINGLEAPPLICATION=aede311d28d20179216c5419b581087be2a8409f

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf stremio-shell-$VERSION
tar xvf $CWD/stremio-shell-$VERSION.tar.gz
cd stremio-shell-$VERSION

tar xvzf $CWD/razerchroma-$CHROMA.tar.gz --strip-components=1 -C deps/chroma
tar xvzf $CWD/libmpv-$LIBMPV.tar.gz --strip-components=1 -C deps/libmpv
tar xvzf $CWD/SingleApplication-$SINGLEAPPLICATION.tar.gz --strip-components=1 -C deps/singleapplication

cp $CWD/server.js server.js
cp $CWD/stremio.asar stremio.asar
cat $CWD/no-js-download.patch | patch -Np1 --verbose || exit 1
sed -i 's|opt/stremio|usr/share/stremio|g' CMakeLists.txt

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

make -f release.makefile PREFIX="$PKG"
make -f release.makefile PREFIX="$PKG" install

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p "$PKG/usr/bin"
ln -sf /usr/share/stremio/stremio "$PKG/usr/bin/stremio"

while read -r -d '' _file
do
    _res="$(printf '%s' "$_file" | sed 's/\.png$//;s/^.*_//')"
    mkdir -p "$PKG/usr/share/icons/hicolor/${_res}x${_res}/apps"
    ln -sf /usr/share/stremio/icons/smartcode-stremio_${_res}.png \
          "$PKG/usr/share/icons/hicolor/${_res}x${_res}/apps/smartcode-stremio.png"
    ln -sf /usr/share/stremio/icons/smartcode-stremio-tray_${_res}.png \
          "$PKG/usr/share/icons/hicolor/${_res}x${_res}/apps/smartcode-stremio-tray.png"
done < <(find "$PKG/usr/share/stremio/icons" -maxdepth 1 -type f -name 'smartcode-stremio_*.png' -print0)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  LICENSE.md \
  README.md \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
