#!/bin/sh

# Slackware build script for font-unscii

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20210326 bkw: updated for v2.1, reflow README, new homepage/download

PRGNAM=font-unscii
VERSION=${VERSION:-2.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
ARCH=noarch

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

SRCNAM=unscii
SRCDIR=$SRCNAM-$VERSION-src

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCDIR
tar xvf $CWD/$SRCDIR.tar.gz
cd $SRCDIR
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

make
mkdir -p $PKG/usr/share/fonts/misc \
         $PKG/usr/share/fonts/OTF \
         $PKG/usr/share/fonts/TTF

cp *.otf $PKG/usr/share/fonts/OTF
cp *.ttf $PKG/usr/share/fonts/TTF
cp *.pcf $PKG/usr/share/fonts/misc
gzip -9 $PKG/usr/share/fonts/misc/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $SRCNAM.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
