--- Makefile.orig	2015-04-03 15:07:16.975046819 -0700
+++ Makefile	2015-04-03 15:08:21.383052670 -0700
@@ -150,15 +150,15 @@ INSTALL?= cp -a
 $(PKGCONFNAME): hiredis.h
 	@echo "Generating $@ for pkgconfig..."
 	@echo prefix=$(PREFIX) > $@
-	@echo exec_prefix=$${prefix} >> $@
+	@echo exec_prefix=\$${prefix} >> $@
 	@echo libdir=$(INSTALL_LIBRARY_PATH) >> $@
 	@echo includedir=$(INSTALL_INCLUDE_PATH) >> $@
 	@echo >> $@
 	@echo Name: hiredis >> $@
 	@echo Description: Minimalistic C client library for Redis. >> $@
 	@echo Version: $(HIREDIS_MAJOR).$(HIREDIS_MINOR).$(HIREDIS_PATCH) >> $@
-	@echo Libs: -L$${libdir} -lhiredis >> $@
-	@echo Cflags: -I$${includedir} -D_FILE_OFFSET_BITS=64 >> $@
+	@echo Libs: -L\$${libdir} -lhiredis >> $@
+	@echo Cflags: -I\$${includedir} -D_FILE_OFFSET_BITS=64 >> $@
 
 install: $(DYLIBNAME) $(STLIBNAME)
 	mkdir -p $(INSTALL_INCLUDE_PATH) $(INSTALL_LIBRARY_PATH)
