.TH PARTLS "1" "January 2011" "SlackBuilds.org" "User Commands"
.SH NAME
partls \- Lists partitions on Apple\-partitioned hard drives or CD-ROMs
.SH SYNOPSIS
.B partls
<\fI-l\fR>
[\fIfile-or-device\fR]
.SH DESCRIPTION
partls is distributed with the KEGS emulator.
.PP
partls displays the partition table on an Apple\-partitioned disk or
disk image file. Generally, these partitions will use the Apple HFS filesystem.
.PP
With the \fB\-l\fR option, more information is displayed.
.SH SEE ALSO
xkegs(1)
.br
to_pro(1)
.SH AUTHORS
KEGS and partls are by Kent Dickey <kadickey at princeton dot edu>.
.PP
This manual page was written by B. Watson for the SlackBuilds.org project (but
may be used by anyone for any reason).
