#!/bin/sh
#
# Slackware build script for rubygems
# Written by Vincent Batts, vbatts@batts.mine.nu

PRGNAM=rubygems
VERSION=1.3.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tgz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

GEM_HOME=$PKG/usr/lib/ruby/gems/1.8 \
  ruby setup.rb --destdir=$PKG/usr  

# Setting global GEM_PATH to get rdoc correct for gems installed
mkdir -p $PKG/etc/profile.d/
cat $CWD/profile.d/gem.sh > $PKG/etc/profile.d/gem.sh
cat $CWD/profile.d/gem.csh > $PKG/etc/profile.d/gem.csh
chmod 755 $PKG/etc/profile.d/gem.sh $PKG/etc/profile.d/gem.csh

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README ChangeLog LICENSE.txt TODO GPL.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
