#!/bin/sh

# Slackware build script for libcap
# Written by Menno Duursma
# Modified by the SlackBuilds.org project

PRGNAM=libcap
VERSION=1.97
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Bail out if we have a problem
set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP 
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION

chown -R root:root .
find . -type d | xargs chmod 0755
find . -type f | xargs chmod go-w

# Apply a patch to set the CFLAGS
if [ "$ARCH" = "i686" ]; then
  patch -p1 < $CWD/$PRGNAM-$VERSION-$ARCH.diff
elif [ "$ARCH" = "i486" ]; then
  patch -p1 < $CWD/$PRGNAM-$VERSION-$ARCH.diff
fi

make
make install FAKEROOT=$PKG man_prefix=/usr

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

# Glibc already has the capget/capset manpage
rm -rf $PKG/usr/man/man2

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README CHANGELOG License pgp.keys.asc \
  doc/capability.notes $CWD/capfaq-0.2.txt \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# Dont overwrite the header, as it may have been edited by the user; instead,
# leave the new copy for the admin to consider
mv $PKG/usr/include/sys/capability.h $PKG/usr/include/sys/capability.h.new

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
