#!/bin/sh

# Slackware build script for gmpc-plugins
# Written by Erik Hanson  erik@slackbuilds.org

set -eu

PRGNAM=gmpc-plugins
VERSION=${VERSION:-0.15.5.0}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Available Plugins:
#PLUGINS="autoplaylist avahi coveramazon extraplaylist favorites \
#last.fm libnotify lyrics magnatune mdcover mserver osd qosd \
#random-playlist serverstats shout stopbutton wikipedia"

# Plugins to build:
PLUGINS="autoplaylist coveramazon extraplaylist favorites \
last.fm lyrics magnatune mdcover mserver random-playlist \
serverstats shout stopbutton wikipedia"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

for plugin in $PLUGINS ; do
  cd gmpc-${plugin}-${VERSION}

  CFLAGS="$SLKCFLAGS" \
    ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var/lib \
    --disable-static

  make
  make install-strip DESTDIR=$PKG

  cd -
done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -a README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
