#!/bin/sh

# Slackware build script for Data2FCS

# Copyright 2017-2021 Petar Petrov slackalaxy@gmail.com
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=Data2FCS
PRGADD=FCS2Data
VERSION=${VERSION:-1.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

ARCH=noarch

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir $PRGNAM-$VERSION
cd $PRGNAM-$VERSION

# This is Data2FCS
mkdir $PRGNAM
cd $PRGNAM
unzip $CWD/${PRGNAM}\ ${VERSION}.zip
install -D -m755 $PRGNAM.jar $PKG/usr/bin/$PRGNAM.jar

# Rename these, so we include them as documentation
mv How\ to\ use.txt HOWTO-$PRGNAM.txt
mv Readme.txt Readme-$PRGNAM.txt

cd ..
# This is FCS2Data
mkdir $PRGADD
cd $PRGADD
unzip $CWD/${PRGADD}\ ${VERSION}.zip
install -D -m755 $PRGADD.jar $PKG/usr/bin/$PRGADD.jar

# Rename these, so we include them as documentation, too
mv How\ to\ use.txt HOWTO-$PRGADD.txt
mv Readme.txt Readme-$PRGADD.txt

cd ..
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  $PRGNAM/{HOWTO-$PRGNAM.txt,Readme-$PRGNAM.txt} \
  $PRGADD/{HOWTO-$PRGADD.txt,Readme-$PRGADD.txt}\
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/share/{applications,pixmaps}
cp $CWD/$PRGNAM.desktop $PKG/usr/share/applications
cp $CWD/$PRGADD.desktop $PKG/usr/share/applications
cp $CWD/$PRGNAM.png $PKG/usr/share/pixmaps
cp $CWD/$PRGADD.png $PKG/usr/share/pixmaps

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
