#!/bin/bash

# Slackware build script for JabRef

# Copyright 2008-2010, Antonio Hernández Blas <hba.nihilismus@gmail.com>
# Update by: Andre Barboza <bmg.andre@gmail.com>
# Copyright 2020, David O'Shaughnessy
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=JabRef
VERSION=${VERSION:-5.13}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
DEBBUILD=${DEBBUILD:-1}

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

# Upstream has binary support for x86_64
if [ "$ARCH" = "x86_64" ]; then
    DEBARCH="amd64"
else
    echo "Sorry, binary is available for x86_64 only."
    exit 1
fi

set -e

rm -rf "$PKG"
mkdir -p "$TMP" "$PKG" "$OUTPUT"
cd "$PKG"
ar p "$CWD"/${PRGNAM,,}_"$VERSION"_"$DEBARCH".deb data.tar.xz | tar xJv
#ar p "$CWD"/${PRGNAM,,}_"$VERSION"_"$DEBARCH".deb data.tar.zst | tar xv --zstd

# permissions
chown -R root:root .
find -L . \
     \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
     -o -perm 511 \) -exec chmod 755 {} \; -o \
     \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
     -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

find "$PKG" -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
    | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# create a symlink for program
mkdir -p "$PKG"/usr/bin
ln -s ../../opt/${PRGNAM,,}/bin/$PRGNAM "$PKG"/usr/bin/$PRGNAM

# desktop and icon
install -D -m 0644 opt/${PRGNAM,,}/lib/${PRGNAM,,}-$PRGNAM.desktop -t "$PKG"/usr/share/applications
install -D -m 0644 opt/${PRGNAM,,}/lib/$PRGNAM.png -t "$PKG"/usr/share/pixmaps
# docs
install -D -m 0644 opt/${PRGNAM,,}/share/doc/* "$CWD"/$PRGNAM.SlackBuild -t "$PKG"/usr/doc/$PRGNAM-"$VERSION"

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
