#!/bin/bash
#
# Slackware build script for fonts-agave
#
# Copyright 2026 r1w1s1
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=fonts-agave
VERSION=${VERSION:-38}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
ARCH=noarch
PKGTYPE=${PKGTYPE:-tgz}

if [ -n "$PRINT_PACKAGE_NAME" ]; then
  echo $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
SRCNAM=agave

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

cd "$TMP"
rm -rf "$SRCNAM-$VERSION"

if [ ! -f "$CWD/$SRCNAM-$VERSION.tar.gz" ]; then
  echo "Source archive $SRCNAM-$VERSION.tar.gz not found."
  exit 1
fi

tar xf "$CWD/$SRCNAM-$VERSION.tar.gz"
cd "$SRCNAM-$VERSION"

chown -R root:root .

mkdir -p "$PKG/usr/share/fonts/TTF" \
  "$PKG/usr/doc/$PRGNAM-$VERSION"

install -m 644 dist/Agave-Regular.ttf \
  dist/Agave-Bold.ttf \
  dist/Agave-Regular-slashed.ttf \
  dist/Agave-Bold-slashed.ttf \
  "$PKG/usr/share/fonts/TTF/"

install -m 644 README.md CHANGES AUTHORS.txt CONTRIBUTORS.txt \
  LICENSE LICENSE_MIT "$PKG/usr/doc/$PRGNAM-$VERSION/"
install -m 644 "$CWD/$PRGNAM.SlackBuild" "$CWD/README" \
  "$PKG/usr/doc/$PRGNAM-$VERSION/"

mkdir -p $PKG/install
install -m 644 "$CWD/slack-desc" "$PKG/install/"
install -m 644 "$CWD/doinst.sh" "$PKG/install/"

cd "$PKG"
/sbin/makepkg -l y -c n "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
