#!/bin/bash

# Slackware build script for ESS (Emacs Speaks Statistics)

# Written by Joel J. Adamson <adamsonj@email.unc.edu>
# Maintained by Nicky Chorley <nick.chorley@gmail.com>

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=ess
VERSION=${VERSION:-17.11}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG/usr $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tgz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

make all DOCDIR=/usr/doc/$PRGNAM-$VERSION
make install DESTDIR=$PKG/usr DOCDIR=$PKG/usr/doc/$PRGNAM-$VERSION

rm -f $PKG/usr/share/info/dir
gzip -9 $PKG/usr/share/info/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  VERSION COPYING OONEWS ANNOUNCE NEWS ONEWS \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
