#!/bin/bash

# Slackware build script for vitunes-mplayer

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=vitunes-mplayer
VERSION=${VERSION:-2.3}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

# This build is called vitunes-mplayer because there are 2 completely
# different projects called "vitunes". This one's a curses frontend
# for mplayer. The other one is a vim plugin that controls iTunes.
# Whoever wants to package the iTunes one, I recommend you call it
# vitunes-itunes.

TARNAME=vitunes

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $TARNAME-$VERSION
tar xvf $CWD/$TARNAME-$VERSION.tar.gz
cd $TARNAME-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# Use /tmp/.vitunes-$USER for the socket, rather that /tmp/.vitunes for
# every single user. Allows multiple users to use vitunes. Without this,
# the first user to run vitunes would own /tmp/.vitunes, and everyone
# else would be outta luck, because vitunes never deletes the socket!
# This patch has been sent upstream.
patch -p1 < $CWD/multiuser.diff

# Support SLKCFLAGS. Also, taglib requires libstdc++ (which isn't mentioned
# in `taglib-config --libs` output, presumably because taglib's expecting
# to be linked by g++, not gcc).
sed -i \
  -e "s,-Wextra,$SLKCFLAGS," \
  -e "/^LDEPS/s,$, -lstdc++," \
  Makefile.linux

make -f Makefile.linux PREFIX=/usr
mkdir -p $PKG/usr/bin $PKG/usr/man/man1
install -m0755 $TARNAME $PKG/usr/bin/$TARNAME
gzip -c < $TARNAME.1 > $PKG/usr/man/man1/$TARNAME.1.gz

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
install -m0644 *.txt LICENSE *.sh $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
