#!/bin/bash

# Slackware build script for man-pages-es

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=man-pages-es
VERSION=${VERSION:-1.55}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

EXTRAVER=${EXTRAVER:-0.8a}
EXTRAPRG=$PRGNAM-extra

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
mkdir -p $PRGNAM
cd $PRGNAM
rm -rf $PRGNAM-$VERSION $EXTRAPRG-$EXTRAVER
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
tar xvf $CWD/$EXTRAPRG-$EXTRAVER.tar.gz
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# in case of dupes between man-pages-es main package and -extra, we use the
# one from -extra.
mkdir -p $PKG/usr/man/es
for i in $PRGNAM-$VERSION/man? $EXTRAPRG-$EXTRAVER/man?; do
  dir=$PKG/usr/man/es/$( basename $i )
  mkdir -p $dir
  cp $i/* $dir
done

find $PKG/usr/man -type f -print0 | xargs -0 gzip -9

mv $EXTRAPRG-$EXTRAVER/README $EXTRAPRG-$EXTRAVER/README.extra

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a */LEEME* */README* */CHANGES* */CAMBIOS* */P* \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
