#!/bin/sh

# Slackware build script for SMPlayer
# Written by Erik Hanson  erik@slackbuilds.org

PRGNAM=smplayer
VERSION=${VERSION:-0.6.7}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

# Optional theme versions:
FREEVER=0.1.19
NONFVER=0.1.1

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fix DOC_PATH and CONF_PATH
sed -i "s%share/doc/packages/smplayer%doc/$PRGNAM-$VERSION%" Makefile
sed -i "s%^CONF_PREFIX%#CONF_PREFIX%" Makefile

make QMAKE=qmake-qt4 PREFIX=/usr
make QMAKE=qmake-qt4 PREFIX=/usr DESTDIR=$PKG install

strip --strip-unneeded $PKG/usr/bin/*

# Use CONF_PATH
mkdir -p $PKG/etc/smplayer
mv $PKG/usr/share/smplayer/input.conf $PKG/etc/smplayer/input.conf.new
ln -s /etc/smplayer/input.conf $PKG/usr/share/smplayer/input.conf

mv $PKG/usr/share/man $PKG/usr
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# Add extra themes if they exist.
if [ -r $CWD/smplayer-themes-$FREEVER.tar.bz2 ] ; then
  cd $TMP
  rm -rf smplayer-themes-$FREEVER
  tar xvf $CWD/smplayer-themes-$FREEVER.tar.bz2
  cd smplayer-themes-$FREEVER
  make PREFIX=/usr DESTDIR=$PKG install
fi

if [ -r $CWD/smplayer-themes-nonfree-$NONFVER.tar.bz2 ] ; then
  cd $TMP
  rm -rf smplayer-themes-nonfree-$NONFVER
  tar xvf $CWD/smplayer-themes-nonfree-$NONFVER.tar.bz2
  cd smplayer-themes-nonfree-$NONFVER
  make PREFIX=/usr DESTDIR=$PKG install
fi

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
