#!/bin/sh
# A script to run TextMaker.

GUI=-gui:$( \
if [ -r ~/.smoffice_gui.conf ]; then \
  cat ~/.smoffice_gui.conf; \
else \
  [ -r /etc/smoffice_gui.conf ] && cat /etc/smoffice_gui.conf; \
fi | grep -o -m1 "gnome\|kde" | head -n1)

case "$GUI" in
  -gui:gnome|-gui:kde) 
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/smoffice2016/dpf \
    /opt/smoffice2016/textmaker "$GUI" "$@"
  ;;
  *)
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/smoffice2016/dpf \
    /opt/smoffice2016/textmaker "$@"
  ;;
esac	
