#!/bin/sh

# Slackware build script for xtuple

# Copyright 2008 Heinz Wiesinger <pprkut@liwjatan.at>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=xtuple
VERSION=3.0.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-source
tar xvf $CWD/$PRGNAM-$VERSION-source.tar.bz2
cd $PRGNAM-$VERSION-source
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

cd xtuple
  qmake-qt4 OPENRPT_DIR=/usr/include/openrpt

  make qmake_all

  for i in common/Makefile widgets/Makefile \
   widgets/Makefile.dll guiclient/Makefile; do
    sed -i "s/-O2/$SLKCFLAGS/" $i
    sed -i "s|..//usr/include/|/usr/include/|g" $i
  done

  dest="DESTDIR       = \$(DESTDIR)"
  qtversion=$(ls -l /usr/lib/qt4 | cut -d "-" -f 5 | cut -d "/" -f 1)

  # libxtuplewidgets.so is installed during make, so we change the path here
  # so that it's included in the package
  sed -i "s|/usr/lib/qt-$qtversion/plugins/designer/|$\(DESTDIR\) |g" \
    widgets/Makefile.dll

  # As long as we rely on SBo's version of qt4, place the designer-plugin
  # in qt-$qtversion, as it's easier on upgrades. Once we rely on slackware's
  # qt4 this can be changed to something more accurate.
  sed -i "s|$dest|DESTDIR       = $PKG/usr/lib/qt-$qtversion/plugins/designer/|" \
    widgets/Makefile.dll

  make

  mkdir -p $PKG/usr/bin $PKG/usr/share/xtuple

  install -m 0755 bin/* $PKG/usr/bin/

cd -

mkdir -p $PKG/usr/share/applications

install -m 0644 $CWD/xtuple.desktop \
    $PKG/usr/share/applications/xtuple.desktop

for i in 16 32 48 128; do
  mkdir -p $PKG/usr/share/icons/hicolor/${i}x${i}/apps
  install -m 0644 xtuple/guiclient/images/icon${i}x32.png \
    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/xtuple.png
done

cp -f $CWD/init.sql $PKG/usr/share/xtuple/init.sql

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a INSTALL.TXT LICENSE.txt README_FIRST.txt \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
