#!/bin/sh

# Slackware build script for python3
# Written by Audrius Kažukauskas <audrius@neutrino.lt>
# Based on Patrick Volkerding's official build script for python

PRGNAM=python3
VERSION=${VERSION:-3.1.3}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Don't set any SLKCFLAGS here, or OPT="$SLKCFLAGS" before the ./configure.
# Python gets the compile options right without any help.
if [ "$ARCH" = "i486" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
else
  LIBDIRSUFFIX=""
fi

set -eu

# Location for Python site-packages:
SITEPK=$PKG/usr/lib${LIBDIRSUFFIX}/python3.1/site-packages
# same as above without $PKG
TOOLSDIR=/usr/lib${LIBDIRSUFFIX}/python3.1/site-packages

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf Python-$VERSION
tar xvf $CWD/Python-$VERSION.tar.bz2
cd Python-$VERSION

patch -p1 < $CWD/patches/python3.readline.set_pre_input_hook.diff

if [ "$ARCH" = "x86_64" ]; then
  # Install to lib64 instead of lib:
  patch -p1 < $CWD/patches/python3.x86_64.diff
  # Python must report /usr/lib64/python3.1/site-packages as python_lib_dir:
  patch -p1 < $CWD/patches/python3.pure64.diff
fi

chown -R root:root .
chmod -R u+w,go+r-w,a-s+X .

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-ncurses \
  --with-threads \
  --enable-ipv6 \
  --enable-shared \
  --with-computed-gotos \
  --build=$ARCH-slackware-linux

make
make altinstall DESTDIR=$PKG

# Create a symlink for convenience.
( cd $PKG/usr/bin ; ln -sf python3.1 python3 )

# We'll install the python-tools under site-packages:
mkdir -p $SITEPK
cp -a Tools/* $SITEPK

# Python 2.6 already has this script.
rm -f $PKG/usr/bin/2to3

# Install docs and demos:
mkdir -p $PKG/usr/doc/python3-$VERSION
cp -a README LICENSE Demo Doc Misc $PKG/usr/doc/python3-$VERSION
mv $SITEPK/README $PKG/usr/doc/python3-$VERSION/README.python-tools
( cd $PKG/usr/doc/python3-$VERSION ; ln -sf $TOOLSDIR Tools )

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
