#!/bin/bash

# Slackware build script for anorack

# Original author: Donald Cooley, South Haven, Indiana, USA.
# Formerly maintained by: Brandon Pribula, BC Canada.
# Now maintained by B. Watson (urchlay@slackware.uk).

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20230914 bkw:
# - take over maintenance.
# - update for v0.2.8.
# - relicense as WTFPL.
# - tweak README and slack-desc slightly.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=anorack
VERSION=${VERSION:-0.2.8}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +

[ "${MAKETEST:-no}" = "yes" ] && make test
make install PREFIX=/usr mandir=/usr/man DESTDIR=$PKG
gzip -9 $PKG/usr/man/man1/$PRGNAM.1

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
cp -a doc/LICENSE doc/README doc/changelog $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
