#!/bin/sh

# Slackware build script for jag

# Written by Larry Hajali <larryhaja[at]gmail[dot]com>

PRGNAM=jag
VERSION=${VERSION:-0.3.2}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-src
unzip $CWD/$PRGNAM-$VERSION-src.zip
unzip $CWD/$PRGNAM-$VERSION-data.zip
mv $PRGNAM-$VERSION-data/data $PRGNAM-$VERSION-src
cd $PRGNAM-$VERSION-src
# Correct permissions on all files/folders.
find . -type f -exec chmod 0644 '{}' \;
find . -type d -exec chmod 0755 '{}' \;
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fix directory locations.
sed -i \
  -e 's|/usr/local/bin|/usr/games|g' \
  -e 's|/usr/local/games|/usr/share|g' \
  Game.pro main.cpp editor/editor.pro

qmake LIBS+=-lX11 -o Makefile Game.pro
make \
  CFLAGS="-pipe $SLKCFLAGS -Wall -W -D_REENTRANT \$(DEFINES)" \
  CXXFLAGS="-pipe $SLKCFLAGS -Wall -W -D_REENTRANT \$(DEFINES)"
make install INSTALL_ROOT=$PKG

# Install the optional level editor.
if [ "${JAG_EDITOR:-no}" == "yes" ]; then
  cd editor
    qmake -o Makefile editor.pro
    make \
      CFLAGS="-pipe $SLKCFLAGS -Wall -W -D_REENTRANT \$(DEFINES)" \
      CXXFLAGS="-pipe $SLKCFLAGS -Wall -W -D_REENTRANT \$(DEFINES)"
    make install INSTALL_ROOT=$PKG
  cd ..
fi

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/share/applications
install -m 0644 $CWD/$PRGNAM.desktop $PKG/usr/share/applications
for i in 16 22 32 48 64 128; do
  convert images/icon256.png -resize ${i}x${i}! ${PRGNAM}${i}.png
  install -D -m 0644 ${PRGNAM}${i}.png \
    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/$PRGNAM.png
done
if [ "${JAG_EDITOR:-no}" == "yes" ]; then
  install -m 0644 $CWD/$PRGNAM-editor.desktop $PKG/usr/share/applications
  install -D -m 0644 editor/editoricon.png $PKG/usr/share/pixmaps/$PRGNAM-editor.png
fi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/COPYRIGHT > $PKG/usr/doc/$PRGNAM-$VERSION/COPYRIGHT
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
