#!/bin/sh

# Slackware build script for monkey http server.

# Copyright (c) 2014, Sergey Fedosov <eleksir@gmail.com>
# All rights reserved.
#
# Redistribution with or without modification, is permitted provided
# that the following conditions are met:
#
# 1. Redistributions of script must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
# OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.

# This script partially based on nginx slackbuild by
# Francisco Ambrozio <sbo@franciscoambrozio.com>
# and libev script by Šime Ramov <s@ramov.com>

PRGNAM=monkey
VERSION=${VERSION:-1.5.6}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

patch -p1 --verbose -i $CWD/config_values_fix.patch

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --sysconfdir=/etc/monkey \
  --datadir=/var/www/monkey \
  --logdir=/var/log/monkey \
  --pidfile=/var/run/monkey/monkey.pid \
  --malloc-libc \
  --bindir=/usr/sbin \
  --plugdir=/usr/lib${LIBDIRSUFFIX}/monkey \
  --default-port=80 \
  --default-user=apache \
  --safe-free

make
make install DESTDIR=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

# out of the box logging is disabled (and looks like this part in configure script is broken),
# enable it to audit http server's life
sed -i 's/# Load \/usr\/lib\/monkey\/monkey\-logger\.so/Load \/usr\/lib\/monkey\/monkey\-logger\.so/g' $PKG/etc/monkey/plugins.load

# make log dir
mkdir -p $PKG/var/log/monkey

# make run dir
mkdir -p $PKG/var/run/monkey

# move init script to it's dir
mkdir -p $PKG/etc/rc.d
mv $PKG/usr/sbin/rc.monkey $PKG/etc/rc.d/rc.monkey.new

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README LICENSE NOTICE ChangeLog CONTRIBUTING.md $PKG/usr/doc/$PRGNAM-$VERSION
install -m 644 $CWD/$PRGNAM.SlackBuild $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/etc/logrotate.d
install -m 644 $CWD/monkey.logrotate $PKG/etc/logrotate.d/monkey.new

mv $PKG/etc/monkey/monkey.conf $PKG/etc/monkey/monkey.conf.new
mv $PKG/etc/monkey/plugins.load $PKG/etc/monkey/plugins.load.new
mv $PKG/etc/monkey/sites/default $PKG/etc/monkey/sites/default.new
mv $PKG/etc/monkey/plugins/auth/monkey.users $PKG/etc/monkey/plugins/auth/monkey.users.new
mv $PKG/etc/monkey/plugins/cgi/cgi.conf $PKG/etc/monkey/plugins/cgi/cgi.conf.new
mv $PKG/etc/monkey/plugins/cheetah/cheetah.conf $PKG/etc/monkey/plugins/cheetah/cheetah.conf.new
mv $PKG/etc/monkey/plugins/dirlisting/dirhtml.conf $PKG/etc/monkey/plugins/dirlisting/dirhtml.conf.new
mv $PKG/etc/monkey/plugins/fastcgi/fastcgi.conf $PKG/etc/monkey/plugins/fastcgi/fastcgi.conf.new
mv $PKG/etc/monkey/plugins/logger/logger.conf $PKG/etc/monkey/plugins/logger/logger.conf.new
mv $PKG/etc/monkey/plugins/mandril/mandril.conf $PKG/etc/monkey/plugins/mandril/mandril.conf.new
mv $PKG/var/www/monkey/404.html $PKG/var/www/monkey/404.html.new
mv $PKG/var/www/monkey/favicon.ico $PKG/var/www/monkey/favicon.ico.new
mv $PKG/var/www/monkey/index.html $PKG/var/www/monkey/index.html.new

mkdir -p $PKG/install
install -m 644 $CWD/slack-desc $PKG/install/slack-desc
install -m 644 $CWD/doinst.sh $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
