#!/bin/sh

## Slackware build script for mod_wsgi
## 
## Copyright 2008 Adis Nezirovic <adis _at_ linux.org.ba>
## Licensed under GNU GPL v2

PRGNAM=mod_wsgi
VERSION=3.1
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# CFLAGS are automatically picked from Python
if [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64" 
else
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP 
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

./configure

# libtool can't find shared Python library;
# there should be symlink to libpython in /usr/lib${LIBDIRSUFFIX}/python2.6/config
# see http://code.google.com/p/modwsgi/wiki/InstallationIssues
make LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}"
make install DESTDIR=$PKG

# Strip binaries:
find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mkdir -p $PKG/etc/httpd/extra
sed "s%@baselibdir@%lib${LIBDIRSUFFIX}%" $CWD/mod_wsgi.conf > \
  $PKG/etc/httpd/extra/mod_wsgi.conf.new

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a LICENCE README $PKG/usr/doc/$PRGNAM-$VERSION/
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README.Slackware

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
