#!/bin/sh

# Slackware build script for rhino
# Written by Vincent Batts, vbatts@hashbangbash.com

PRGNAM=rhino
VERSION=1_7R2
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ANTHOME="/usr/share/ant"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf ${PRGNAM}${VERSION}
unzip $CWD/${PRGNAM}${VERSION}.zip
cd ${PRGNAM}${VERSION}
chown -R root:root .

mkdir -p $PKG/$ANTHOME/lib/ $PKG/usr/share/java
cp js.jar $PKG/$ANTHOME/lib/$PRGNAM.jar

cd $PKG/usr/share/java
  ln -s ../../../$ANTHOME/lib/$PRGNAM.jar
cd -

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
zip -9 -r $PKG/usr/doc/$PRGNAM-$VERSION/examples.zip examples/
cp -a LICENSE.txt javadoc/ $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
