.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH JACK-RACK 1 "June 6, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jack-rack \- a LADSPA effects rack
.SH SYNOPSIS
.B jack-rack
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B jack-rack
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.

The jack-rack program allows you to load several LADSPA plugins
and stack them together in order to build a virtual effects box.
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Display this help info
.TP
.B \-p, \-\-pid-name 
Use the pid in the JACK client name (default)
.TP
.B \-s, \-\-string-name
Use <string> in the JACK client name
.TP
.B \-n, \-\-name
Use just jack_rack as the client name
.TP
.B \-i, \-\-input
Connected inputs to the first two physical capture ports
.TP
.B \-o, \-\-output
Connected outputs to the first two physical playback ports
.TP
.B \-c, \-\-channels <int>
How many input and output channels the rack should use (default: 2)
.TP
.B \-D, \-\-tmpdir <dir>
Tell JACK to use <dir> for its temporary files
.SH SEE ALSO
.BR jackd (1),
.br
.SH AUTHOR
This manual page was written by Guenter Geiger <geiger@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
