.TH JAPA 1 "January 14, 2014"
.SH NAME
japa \- JACK or ALSA perceptual analyser
.SH SYNOPSIS
.B japa
.RI { -h | -A | -J }
.RI [ options ]
.br
.SH DESCRIPTION
.B Japa
(JACK and ALSA Perceptual Analyser), is a 'perceptual' or 'psychoacoustic'
audio spectrum analyser. Possible uses include spectrum monitoring while mixing
or mastering, evaluation of ambient noise, and (using pink noise), equalisation
of PA systems. For more information see /usr/doc/japa-@VERSION@/README.
.SH OPTIONS
One out of
.B \-A
and
.B \-J
must be given.
.TP
.B \-h
Show summary of options.
.TP
.B \-J
Use JACK.
.TP
.B \-s <server>
Select JACK server. Default is 'default' or $JACK_DEFAULT_SERVER environment variable.
Only valid with
.B \-J
option.
.TP
.B \-A
Use ALSA. Options
.B \-d
,
.B \-C
,
.B \-P
,
.B \-r
,
.B \-p
, and
.B \-n
are only valid with this option.
.TP
.B \-d <device>
Specify ALSA device. Defaults to hw:0.0. This option sets the
playback and capture devices to the same device. For separate capture and playback,
use
.B \-C
and
.B \-P
instead.
.TP
.B \-C <device>
Specify alsa capture device.
.TP
.B \-P <device>
Specify alsa playback device.
.TP
.B \-r <rate>
Specify sample frequency. Defaults to 48000.
.TP
.B \-p <period>
Specify period size. Defaults to 1024.
.TP
.B \-n <nfrags>
Specify number of fragments. Defaults to 2.
.SH SEE ALSO
.BR jackd (1).
.SH AUTHOR
japa was written by Fons Adriaensen <fons@kokkinizita.net>.
.PP
This manual page was written by Helmut Grohne <helmut@subdivi.de>,
for the Debian project (but may be used by others). It was modified
by B. Watson <yalhcry@gmail.com) for the SlackBuilds.org project,
and may still be used by others.
