.TH OPENBOX-MENU "1" "November 2013"
.SH NAME
openbox-menu \- Openbox pipe-menu to display entries in *.desktop files
.SH DESCRIPTION
.SS "Usage:"
.TP
openbox\-menu [OPTION...] [file.menu]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.SS "Application Options:"
.TP
\fB\-c\fR, \fB\-\-comment\fR
Show generic name instead of application name
.TP
\fB\-t\fR, \fB\-\-terminal\fR=\fIcmd\fR
Terminal command (default xterm \fB\-e\fR)
.TP
\fB\-g\fR, \fB\-\-gnome\fR
Show GNOME entries
.TP
\fB\-k\fR, \fB\-\-kde\fR
Show KDE entries
.TP
\fB\-x\fR, \fB\-\-xfce\fR
Show XFCE entries
.TP
\fB\-r\fR, \fB\-\-rox\fR
Show ROX entries
.TP
\fB\-p\fR, \fB\-\-persistent\fR
stay active
.TP
\fB\-s\fR, \fB\-\-sn\fR
Enable startup notification
.TP
\fB\-o\fR, \fB\-\-output\fR
file to write data to
.TP
\fB\-i\fR, \fB\-\-noicons\fR
Don't display icons in menu
.PP
This manual page was written by Mateusz Łukasik <mati75@linuxmint.pl>,
for the Debian project (and may be used by others).
