#!/bin/sh

# Slackware build script for Microsoft VSCode

# Copyright 2017 Andre Barboza, Belo Horizonte
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=vscode
VERSION=${VERSION:-1.11.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

ARCH=${ARCH:-$(uname -m)}
case "$ARCH" in
  i?86)
    ARCH=i586
    BUILDARCH=ia32
    ;;
  x86_64)
    BUILDARCH=x64
    ;;
  *)
    echo "$ARCH is not supported"
    exit 1
    ;;
esac

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCDIR
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

patch -p1 < $CWD/vscode-$VERSION.patch
./scripts/npm.sh install --arch=$BUILDARCH --unsafe-perm
node --max_old_space_size=1024 ./node_modules/.bin/gulp vscode-linux-${BUILDARCH}-min

cd $TMP/VSCode-linux-$BUILDARCH

# Copy binary files
mkdir -p "${PKG}/opt/${PRGNAM}-${VERSION}"
cp -rvf * "${PKG}/opt/${PRGNAM}-${VERSION}" -R

# Link executable to usr/bin
mkdir -p "${PKG}/usr/bin"
ln -s "/opt/${PRGNAM}-${VERSION}/bin/code-oss" "${PKG}"/usr/bin/code-oss

# copy desktop shortcut
mkdir -p "${PKG}/usr/share/applications"
install -m644 "${CWD}/${PRGNAM}.desktop" "${PKG}/usr/share/applications/${PRGNAM}.desktop"

# copy vscode icon
mkdir -p "${PKG}/usr/share/icons"
install -m644 "${PKG}/opt/${PRGNAM}-${VERSION}/resources/app/resources/linux/code.png" \
        "${PKG}/usr/share/icons/${PRGNAM}.png"

# copy license and slackbuild
mkdir -p "$PKG/usr/doc/$PRGNAM-$VERSION"
( cd resources/app
  cp -raf LICENSE.txt ThirdPartyNotices.txt "$PKG/usr/doc/$PRGNAM-$VERSION"
)
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
