.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EXIQGREP 8 "March 26, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" \(oqthis text is enclosed in single quotes\(cq
.\" \(lqthis text is enclosed in double quotes\(rq
.SH NAME
exiqgrep \- Search in the exim queue
.SH SYNOPSIS
.B exiqgrep
.I [\-a] [\-c]

.SH DESCRIPTION
The
.B exiqgrep
utility is a Perl script which offers possibilities to grep in the
exim queue output. Unlike exiqsumm, it invokes exim \-bpu itself and
does not need to be invoked in a pipe.

.SH OPTIONS
.TP 10
\fB\-h\fR
Print help
.TP
\fB\-f <regexp>\fR
Match sender address (field is \(lq< >\(rq wrapped)
.TP
\fB\-r <regexp>\fR
Match recipient address
.TP
\fB\-s <regexp>\fR
Match against the site field from long output
.TP
\fB\-y <seconds>\fR
Message younger than
.TP
\fB\-o <seconds>\fR
Message older than
.TP
\fB\-z\fR
Frozen messages only (exclude non-frozen)
.TP
\fB\-x\fR
Non-frozen messages only (exclude frozen)
.TP
\fB\-c\fR
Display match count
.TP
\fB\-l\fR
Long Format [Default]
.TP
\fB\-i\fR
Message IDs only
.TP
\fB\-b\fR
Brief Format
.TP
\fB\-R\fR
Reverse order

.SH BUGS
This manual page needs a major re-work. If somebody knows better groff
than us and has more experience in writing manual pages, any patches
would be greatly appreciated.

.SH SEE ALSO
.BR exim (8)

.SH AUTHOR
This manual page was stitched together from the source code by Marc
Haber <mh+debian\-packages@zugschlus.de>, using the exiqsumm man page by
Andreas Metzler <ametzler at downhill.at.eu.org>,
for the Debian GNU/Linux system (but may be used by others).
