#!/bin/bash

# Slackware build script for mesen-x

# Copyright 2022-2023 Steven Voges <Oregon, USA>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=mesen-x
SRCNAM=Mesen-X
VERSION=${VERSION:-0.9.9.3364}
SRCVER=${SRCVER:-9760d07474881588051d620b3c230bcdf5be08ec}
MESENPLATFORM=${MESENPLATFORM:-x64}
LIBRETRO=${LIBRETRO:-no}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
  MESENPLATFORM="x86"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
  MESENPLATFORM="x86"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
  MESENPLATFORM="x64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
  MESENPLATFORM="x86"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$SRCVER
tar xvf $CWD/$SRCNAM-$SRCVER.tar.gz
cd $SRCNAM-$SRCVER
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

export CC=clang
export CXX=clang++
export CFLAGS="$SLKCFLAGS"
  LTO=true \
  MESENPLATFORM=$MESENPLATFORM \
  make
  install -Dm755 bin/$MESENPLATFORM/Release/Mesen.exe $PKG/usr/bin/$SRCNAM
  install -Dm755 $CWD/$PRGNAM $PKG/usr/bin/$PRGNAM
  install -Dm644 InteropDLL/obj.$MESENPLATFORM/libMesenCore.$MESENPLATFORM.dll \
    $PKG/usr/lib$LIBDIRSUFFIX/libMesenCore.dll
  install -Dm644 $CWD/$PRGNAM.desktop $PKG/usr/share/applications/$PRGNAM.desktop
  install -Dm644 GUI.NET/Resources/MesenIconSmall.png $PKG/usr/share/icons/hicolor/16x16/apps/$PRGNAM.png
  install -Dm644 GUI.NET/Resources/MesenIconMedium.png $PKG/usr/share/icons/hicolor/32x32/apps/$PRGNAM.png
  install -Dm644 GUI.NET/Resources/MesenIcon.png $PKG/usr/share/icons/hicolor/64x64/apps/$PRGNAM.png
  chmod 755 $PKG/usr/lib$LIBDIRSUFFIX/libMesenCore.dll
if [ $LIBRETRO = "yes" ]; then
  cd Libretro
    make
    install -Dm755 Libretro/mesen_libretro.so $PKG/usr/lib$LIBDIRSUFFIX/libretro/${PRGNAM}_libretro.so
    install -Dm644 $CWD/${PRGNAM}_libretro.info.in $PKG/usr/lib$LIBDIRSUFFIX/libretro/info/${PRGNAM}_libretro.info
  cd ..
fi

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  LICENSE README.md \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
