.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PLASMIDOMICS 1 "November 24, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Plasmidomics \- draw plasmids and vector maps with PostScript export
.SH SYNOPSIS
plasmidomics
.br
python /usr/bin/plasmidomics
.SH DESCRIPTION
This manual page briefly describes Plasmidomics.
.PP
Plasmidomics is written for easy drawing of plasmids and vector maps to use them in theses, presentations or other forms of publications. It natively supports PostScript as output format.
.SH OPTIONS
There are no options!
.PP
.SH SEE ALSO
The program is documented fully in the README,
available in /usr/doc/plasmidomics-$VERSION folder.
.SH AUTHOR
Plasmidomics was written by Robert Winkler <robert.winkler@bioprocess.org>.
.PP
This manual page was written by Robert Winkler <robert.winkler@bioprocess.org>,
for the Debian project (but may be used by others). It was adapted for Slackware,
with minor modifications by Petar Petrov <ppetrov@paju.oulu.fi> (2011)