#!/bin/sh

# Slackware build script for epson-inkjet-printer-stylus-tx550w-series

# Written by Mark Grocock <mark@grocock.me.uk>

PRGNAM=epson-inkjet-printer-stylus-tx550w-series
VERSION=${VERSION:-1.0.0}
EXTRAVERSION=${EXTRAVERSION:-1lsb3.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
rpm2cpio $CWD/$PRGNAM-$VERSION-$EXTRAVERSION.src.rpm | cpio -idmv
tar xvf epson-inkjet-printer-filter-$VERSION.tar.gz
tar xvf $PRGNAM-$VERSION.tar.gz
rpm2cpio $CWD/$PRGNAM-$VERSION-$EXTRAVERSION.$ARCH.rpm | cpio -idmv
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

cd epson-inkjet-printer-filter-$VERSION

autoreconf -fi
chmod a+x configure

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

sed -i "s|/usr/resource|/usr/share/$PRGNAM/resource|" config.h

make

mkdir -p $PKG/usr/lib${LIBDIRSUFFIX}/cups/filter
cp -a src/epson_inkjet_printer_filter $PKG/usr/lib${LIBDIRSUFFIX}/cups/filter

cd ../$PRGNAM-$VERSION

find ppds -name '*.ppd' | while read ppd; do
  sed -i -e "s|/opt/$PRGNAM/cups/lib/filter|/usr/lib${LIBDIRSUFFIX}/cups/filter|" \
   -e "s|/opt/$PRGNAM/watermark|/usr/share/$PRGNAM/watermark|" "$ppd"
  gzip -9 "$ppd"
done

mkdir -p $PKG/usr/share/cups/model/Epson
cp -a ppds/*.ppd.gz $PKG/usr/share/cups/model/Epson

mkdir -p $PKG/usr/share/$PRGNAM
cp -a resource watermark $PKG/usr/share/$PRGNAM

install -m 755 ../opt/$PRGNAM/lib${LIBDIRSUFFIX}/*.so.* $PKG/usr/lib${LIBDIRSUFFIX}

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  AUTHORS COPYING COPYING.EPSON Manual.txt README \
  ../epson-inkjet-printer-filter-$VERSION/COPYING.LIB \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
