#!/bin/sh

# Slackware build script for meme-suite

# Copyright 2017 Petar Petrov slackalaxy@gmail.com
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=meme-suite
SRCNAM=meme
VERSION=${VERSION:-4.12.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf ${SRCNAM}_${VERSION}
tar xvf $CWD/${SRCNAM}_${VERSION}.tar.gz
cd ${SRCNAM}_${VERSION}
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Fix a few paths
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" Makefile.in
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/css/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/images/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/js/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/examples/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/examples/compute_prior_dist_example_output_files/Makefile.*
sed -i "s:share/doc:doc/$PRGNAM-$VERSION/doc/:g" doc/examples/sample_opal_scripts/Makefile.*
sed -i "s:\\$(libdir)/perl:&/vendor_perl:g"      scripts/Makefile.*
sed -i "s:\\$(libdir)/python:$(libdir)/python2.7/site-packages:g" scripts/Makefile.*

./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-url="http://meme-suite.org" \
  --datarootdir=/usr/share/$PRGNAM/data \
  --sysconfdir=/usr/share/$PRGNAM/etc \
  --localstatedir=/var \
  --with-db=/var/lib/$PRGNAM \
  --with-logs=/var/log/$PRGNAM \
  --with-temp=/tmp

# CFLAGS should be specified here, otherwise they are not accepted
make CFLAGS="$SLKCFLAGS -std=gnu89"

# The tests are recommended, but take quite some time. Be patient or comment out the line below.
# Also, some tests fail on a 32bit system, therefore it is listed as unsupported. If you find a
# fix, let me know.
make test
make install DESTDIR=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# The databases directory should contain folders for motif, gomo and fasta databases
mkdir -p $PKG/var/lib/$PRGNAM/{motif_databases,gomo_databases,fasta_databases}

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  AUTHORS COPYING INSTALL README \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/References > $PKG/usr/doc/$PRGNAM-$VERSION/References

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
