.TH SMS_SDL "1" "February 2009" "SMS Plus/SDL v0.9.4aR7" "User Commands"
.SH NAME
sms_sdl \- Sega Master System and Game Gear emulator.
.SH SYNOPSIS
.B sms_sdl
\fR[\fI--options\fR] \fI<filename.<SMS|GG>> 
.SH DESCRIPTION
SMS Plus/SDL v0.9.4aR7
.br
(C) Charles Mac Donald in 1998, 1999, 2000
.br
SDL Version by Gregory Montoir (cyx@frenchkiss.net)
.SH OPTIONS
.PP
\fINote:\fR The filename may appear anywhere on the command line.
.TP
\fB\-\-fm\fR
Enable YM2413 sound.
.TP
\fB\-\-japan\fR
Set the machine type as DOMESTIC instead of OVERSEAS.
.TP
\fB\-\-usesram\fR
Load/save SRAM contents before starting/exiting.
.TP
\fB\-\-fskip\fR <n>
Specify the number of frames to skip.
.TP
\fB\-\-fullspeed\fR
Do not limit to 60 frames per second.
.TP
\fB\-\-fullscreen\fR
Start in fullscreen mode.
.TP
\fB\-\-joystick\fR
Use joystick.
.TP
\fB\-\-nosound\fR
Disable sound.
.TP
\fB\-\-filter\fR <mode>
Render using a filter. Available modes:
.RS
.IP "2xsai"
.PD 0
.IP "super2xsai"
.IP "supereagle"
.IP "advmame2x"
.IP "tv2x"
.IP "2x"
.IP "bilinear"
.IP "dotmatrix"
.RE
.PD 1
.SH CONFIG FILE
\fBsms_sdl\fR is launched by a shell script wrapper which reads the
file \fI~/.sms_sdl/config\fR if it exists. Any of the options above may
be placed in this file (one option per line, with or without the leading \fB--\fR characters). These options
will be passed as command\-line arguments to the real \fBsms_sdl\fR
binary every time it runs.
.PP
See \fB/usr/doc/sms_sdl-@VERSION@/sample_config\fR for further information.
.SH KEYBOARD
.TP
\fBF1\fR
Screenshot in BMP format
.TP
\fBF2\fR
Save state
.TP
\fBF3\fR
Load state
.TP
\fBF4/F5\fR
Dec/inc frame skip value
.TP
\fBF6/F7\fR
Dec/inc state slot
.TP
\fB1..8\fR
Switch rendering filter
.TP
\fBC\fR
Button 1
.TP
\fBV\fR
Button 2
.TP
\fBENTER\fR
Start (GG) / pause (SMS)
.TP
\fBARROWS\fR
Directional pad
.TP
\fBTAB\fR
Console hard reset
.PP
The key bindings may not be remapped.
.SH FILES
.PP
ROM image files may be in raw dump format, or may have a header (details
are system-specific). Also, ROM images may be zipped (not gzipped), in
which case the first file in the zip file's directory must be the
ROM image (any other files are ignored).
.PP
\fBsms_sdl\fR looks at the filename to determine the type of ROM image
in use. Any file whose name ends in \fI.gg\fR (case-insensitive match)
is considered to be a Game Gear ROM. Any other file is treated as a
Sega Master System ROM. In the case of a zipped image, this refers to the
file inside the zip file; the zip file itself doesn't have any special
naming requirements.
.PP
Screenshot filenames (F1 key) are generated by replacing the filename
extension with \fI-NNN.bmp\fR, where NNN is a 3-digit number (000 for
the first screenshot, 001 for the second, etc). The numbering starts
at 000 every time the emulator is started, and existing files will be
overwritten without confirmation.
.PP
State save filenames (F2 key) are generated by replacing the filename
extension with \fI.stN\fR, where N is the number of the save slot (one
or more digits). Again, existing files are overwritten without confirmation.
.PP
For both types of file, the filename is considered to be the entire
path to the ROM image file. This means that the emulator expects to
be able to write savestate and screenshot files in the directory where
the ROM files reside. If the directory is not writable, no files will
be created.
.SH BUGS
.PP
\fBsms_sdl\fR will exit with failure status if it's given a filename that
contains no . (dot/period) characters (in other words, a filename
without an extension). So don't do that. (This applies to the file
inside the zip file, for zipped images)
.PP
Screenshot and state-save files should really be written in the
current directory, or else a hypothetical ~/.sms_sdl directory.
.PP
There should be a config file, so the user doesn't have to pass his
favorite set of options on the command line every time (of course,
a shell alias, wrapper script, or GUI file manager
can work around this easily enough).
.SH AUTHORS
.PP
(C) Charles Mac Donald in 1998, 1999, 2000
.br
SDL Version by Gregory Montoir (cyx@frenchkiss.net)
