#!/bin/sh

# Slackware build script for XView

# Copyright 2014 Tomasz Konojacki <email removed>
# Copyright 2020 B. Watson <yalhcru@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# 20200524 bkw:
# - take over maintenance, BUILD=2
# - add partial 64-bit support (olwm and olvwm work, apps don't)
# - add xinitrc.ol[v]wm
# - add MAKEFLAGS=-j1
# - remove XVIEW_BROKEN_X11_WORKAROUND from README, not needed on 14.2

PRGNAM=xview
VERSION=${VERSION:-3.2p4}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  if [ "${WARN64:-yes}" = "yes" ]; then
      cat <<"EOF"
************************************************************************
Warning: xview doesn't fully support 64-bit systems. The window managers
(olwm and olvwm) work, but the applications (olclock, oledit, etc) crash
on startup. Please don't report this as a bug, we already know.
Press Enter or wait 5 seconds to continue, or press ^C to abort.
************************************************************************
EOF
    read -t 5 || true
  fi
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.Z
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# Apply our CFLAGS. There might be a simpler way to do it, but this works:
sed -i "s|-O2|$SLKCFLAGS -fcommon -I/usr/include/tirpc -Wl,-ltirpc|g" \
  clients/olvwm-4.1/compiler.tmpl \
  clients/olwm/Makefile.simple \
  config/XView.tmpl

script=Build-XView.bash

# lib64 support, and stop creating /usr/config outside of $TMP.
sed -i \
    -e "s|/lib/X11/config|/lib$LIBDIRSUFFIX/X11/config|g" \
    -e '/instlibs)/,+1s|install-sh|#&|' \
  $script

# 20200524 bkw: Yes, we do need -j1 here.
X11DIR=/usr
OPENWINHOME=/usr
DESTDIR=$PKG
XVIEW_USE_GCC=1
MAKEFLAGS=-j1
export X11DIR OPENWINHOME DESTDIR XVIEW_USE_GCC MAKEFLAGS

# "all" builds/installs everything according to the env vars set above.
sh $script all

# This conflicts with /sbin/clock from Slackware:
mv $PKG/usr/bin/clock $PKG/usr/bin/olclock
mv $PKG/usr/man/man1/clock.1x $PKG/usr/man/man1/olclock.1x

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

gzip -9 $PKG/usr/man/man?/*

mkdir -p $PKG/etc/X11/xinit
install -m0755 -oroot -groot $CWD/xinitrc.* $PKG/etc/X11/xinit

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README CHANGELOG LEGAL_NOTICE $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
