.TH "RUBBERBAND" "1" 
.SH "NAME" 
rubberband \(em an audio time-stretching and pitch-shifting utility program 
.SH "SYNOPSIS" 
.PP 
\fBrubberband\fR [\fB\fIoptions\fR\fP]  [\fB\fIinput file\fR\fP]  [\fB\fIoutput file\fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBrubberband\fR command. 
.PP 
Rubber Band is a program that permits you to change the 
tempo and pitch of an audio recording independently of one 
another. 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-\-').  A summary of 
options is included below. 
.PP 
You must specify at least one of the following time and 
pitch ratio options. 
.IP "\fB-t\fP, \fB\-\-time\fP \fIX\fR" 10 
Stretch to \fIX\fR times original duration, or 
.IP "\fB-T\fP, \fB\-\-tempo\fP \fIX\fR" 10 
Change tempo by multiple \fIX\fR (equivalent to \-\-time 1/X), or 
.IP "\fB-T\fP, \fB\-\-tempo\fP \fIX\fR:\fIY\fR" 10 
Change tempo from \fIX\fR to \fIY\fR (same as \-\-time X/Y), or 
.IP "\fB-D\fP, \fB\-\-duration\fP \fIX\fR" 10 
Stretch or squash to make output file \fIX\fR seconds long 
.IP "\fB-p\fP, \fB\-\-pitch\fP \fIX\fR" 10 
Raise pitch by \fIX\fR semitones, or 
.IP "\fB-f\fP, \fB\-\-frequency\fP \fIX\fR" 10 
Change frequency by multiple \fIX\fR 
.PP 
The following options provide ways of making the time and frequency ratios 
change during the audio: 
.IP "\fB-M\fP, \fB\-\-timemap\fP \fIF\fR" 10 
Use file F as the source for time map 
.PP 
A time map (or key-frame map) file contains a series of lines, each with two 
sample frame numbers separated by a single space. These are source and 
target frames for fixed time points within the audio data, defining a varying 
stretch factor through the audio. When supplying a time map you must specify 
an overall stretch factor using \-t, \-T, or \-D as well, to determine the 
total output duration. 
.IP "    \fB\-\-pitchmap\fP \fIF\fR" 10 
Use file F as the source for pitch map 
.PP 
A pitch map file contains a series of lines, each with two values: the input 
sample frame number and a pitch offset in semitones, separated by a single 
space. These specify a varying pitch factor through the audio. The offsets 
are all relative to an initial offset specified by the pitch or frequency 
option, or relative to no shift if neither was specified. Offsets are 
not cumulative. This option implies realtime mode (\-R) and also enables a 
high-consistency pitch shifting mode, appropriate for dynamic pitch changes. 
Because of the use of realtime mode, the overall duration will not be exact. 
.IP "    \fB\-\-freqmap\fP \fIF\fR" 10 
Use file F as the source for freq map 
.PP 
A frequency map file is like a pitch map, except that its second column 
lists frequency multipliers rather than pitch offsets (like the difference 
between pitch and frequency options above) 
.PP 
The following options affect the sound manipulation and quality 
.IP "\fB-2\fP, \fB\-\-fast\fP" 10 
Use the R2 (faster) engine 
.PP 
This is the default (for backward compatibility) when this tool is invoked 
as "rubberband". It was the only engine available in versions prior to v3.0. 
.IP "\fB-3\fP, \fB\-\-fine\fP" 10 
Use the R3 (finer) engine 
.PP 
This is the default when this tool is invoked as "rubberband-r3". It almost 
always produces better results than the R2 engine, but with significantly 
higher CPU load. 
.IP "\fB-F\fP, \fB\-\-formant\fP" 10 
Enable formant preservation when pitch shifting 
.PP 
This option attempts to keep the formant envelope unchanged when changing 
the pitch, retaining the original timbre of vocals and instruments in a 
recognisable way. 
.IP "\fB-c\fP, \fB\-\-crisp\fP \fIN\fR" 10 
Crispness (N = 0,1,2,3,4,5); default 4 (see below) 
.PP 
This option only has an effect when using the R2 (faster) engine. See below 
for details of the different levels. 
.PP 
The remaining options fine-tune the processing mode and stretch algorithm. 
The default is to use none of these options. 
The options marked (2) currently only have an effect when using the R2 engine 
(see \-2, \-3 options above). 
.IP "\fB-R\fP, \fB\-\-realtime\fP" 10 
Select realtime mode (implies \-\-no-threads). 
This utility does not do realtime stream processing; 
the option merely selects realtime mode for the 
stretcher it uses 
.IP "\fB\-\-no-threads\fP" 10 
No extra threads regardless of CPU and channel count (R2) 
.IP "\fB\-\-threads\fP" 10 
Assume multi-CPU even if only one CPU is identified (R2) 
.IP "\fB\-\-no-transients\fP" 10 
Disable phase resynchronisation at transients (R2) 
.IP "\fB\-\-bl-transients\fP" 10 
Band-limit phase resync to extreme frequencies (R2) 
.IP "\fB\-\-no-lamination\fP" 10 
Disable phase lamination (R2) 
.IP "\fB\-\-smoothing\fP" 10 
Apply window presum and time-domain smoothing (R2) 
.IP "\fB\-\-detector-perc\fP" 10 
Use percussive transient detector (as in pre-1.5) (R2) 
.IP "\fB\-\-detector-soft\fP" 10 
Use soft transient detector (R2) 
.IP "\fB\-\-window-long\fP" 10 
Use longer processing window (actual size may vary) (R2) 
.IP "\fB\-\-window-short\fP" 10 
Use shorter processing window (with the R3 engine 
this is effectively a quick "draft mode") 
.IP "\fB\-\-pitch-hq\fP" 10 
In RT mode, use a slower, higher quality pitch shift 
.IP "\fB\-\-centre-focus\fP" 10 
reserve focus of centre material in stereo 
(at a cost in width and individual channel quality) 
.IP "\fB\-\-ignore-clipping\fP" 10 
Ignore clipping at output; the default is to restart 
with reduced gain if clipping occurs 
.IP "\fB-L\fP, \fB\-\-loose \fP" 10 
[Accepted for compatibility but ignored; always off] 
.IP "\fB-P\fP, \fB\-\--precise \fP" 10 
[Accepted for compatibility but ignored; always on] 
.IP "\fB-d\fP, \fB\-\-debug\fP \fIN\fR" 10 
Select debug level (N = 0,1,2,3); default 0, full 3 
(N.B. debug level 3 includes audible ticks in output) 
.PP 
The following options are for output control and administration: 
.IP "\fB-q\fP, \fB\-\-quiet\fP" 10 
Suppress progress output 
.IP "\fB-V\fP, \fB\-\-version\fP" 10 
Show version number and exit 
.IP "\fB-h\fP, \fB\-\-help\fP" 10 
Show the normal help output 
.IP "\fB-H\fP, \fB\-\-full-help\fP" 10 
Show the full help output 
.PP 
"Crispness" levels: 
.IP "0" 10 
equivalent to \-\-no-transients \-\-no-lamination \-\-window-long 
.IP "1" 10 
equivalent to \-\-detector-soft \-\-no-lamination \-\-window-long (for piano) 
.IP "2" 10 
equivalent to \-\-no-transients \-\-no-lamination 
.IP "3" 10 
equivalent to \-\-no-transients 
.IP "4" 10 
equivalent to \-\-bl-transients 
.IP "5" 10 
default processing options 
.IP "6" 10 
equivalent to \-\-no-lamination \-\-window-short (may be good for drums) 
.SH "AUTHOR" 
.PP 
Rubber Band was written by Chris Cannam <cannam@all-day-breakfast.com>. 
.PP 
This manual page was written by Székelyi Szabolcs <cc@mail.3d.hu> and 
revised in October 2022 by Dennis Braun <snd@y0o.de> for 
the \fBDebian\fP system (but may be used by others), because the 
original program does not have a manual page.  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
.PP 
On Debian systems, the complete text of the GNU General 
Public License can be found in 
/usr/share/common-licenses/GPL. 
.\" created by instant / docbook-to-man 
