#!/bin/sh

# Slackware build script for nvidia-kernel

# Copyright 2007-2011 Heinz Wiesinger, Amsterdam, The Netherlands
# Copyright 2011-2013 Edward W. Koenig, Vancouver, WA, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Thanks to Robby Workman for suggestions to improve this script.
#
# ChangeLog
# ------------------------------------------------------------------------------
# 1.0	20-MAR-2011	New Maintainer: Edward W. Koenig <kingbeowulf@gmail.com>
# 1.1	10-APR-2011	updated to new version, testing 13.37rc4.6692
# 1.2   27-MAY-2011	new version, blacklist nouveau, fix ups, tested 13.37-stable
# 1.5   01-JULY-2011	new version, kill SRCSUFFIX nonsense, use blacklist in /extra
# 1.6   30-AUG-2011     version bump, typo clean ups
# 1.7	21-OCT-2011	version bump.
# 1.7	26-DEC-2011	version bump
# 1.8   24-MAR-2012	new version
# 1.9	15-JUL-2012	new version - Short Lived Branch
# 2.0	25-SEP-2012	new version - Long Lived Branch
# 3.0   06-JUL-2013	Legacy 304 branch
# 3.1   22-SEP-2013	version update
# 3.1a	04-NOV-2013	remove missing docs, check for 14.1 release

PRGNAM=nvidia-legacy304-kernel
VERSION=304.108
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

KERNEL=${KERNEL:-$(uname -r)}
KERNELPATH=${KERNELPATH:-/lib/modules/${KERNEL}/build}

PKGVER=${VERSION}_$(echo $KERNEL | tr - _)

COMPAT32=""

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i486" ]; then
  TARGET="x86"
  SRCSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  TARGET="x86"
  SRCSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  TARGET="x86_64"
  COMPAT32="-no-compat32"
fi

unset ARCH

SRCNAM=NVIDIA-Linux-$TARGET-${VERSION}$COMPAT32

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=${PKG:-$TMP/package-$PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
rm -rf $SRCNAM
sh $CWD/$SRCNAM.run --extract-only || exit 1
cd $SRCNAM || exit 1
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

cd kernel || exit 1

make SYSSRC=$KERNELPATH module || exit 1

mkdir -p $PKG/lib/modules/$KERNEL/kernel/drivers/video
install -m 0664 nvidia.ko $PKG/lib/modules/$KERNEL/kernel/drivers/video/

# Make sure the X is specified to automagically load the 
# correct driver, since I always forget. 

mkdir -p $PKG/usr/share/X11/xorg.conf.d/
cat $CWD/10-nvidia.conf > $PKG/usr/share/X11/xorg.conf.d/10-nvidia.conf

mkdir -p $PKG/usr/doc/$PRGNAM-$PKGVER
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$PKGVER/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
sed "s%@KERNEL@%$KERNEL%" $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$PKGVER-$TARGET-$BUILD$TAG.${PKGTYPE:-tgz}
