--- Makefile.orig	2014-09-14 07:05:46.000000000 -0400
+++ Makefile	2014-09-15 21:55:08.071351667 -0400
@@ -160,7 +160,6 @@
 	@$(MAKE) -C argparse libargparse.a
 
 argparse/argparse.h:
-	git submodule update --init argparse
 
 $(LIB_OBJS): $(LIB_H)
 
