#!/bin/sh

# Slackware build script for mlt.

# Written by stormtracknole - stormtracknole@gmail.com

# Modified by Erik Hanson (erik@slackbuilds.org) with
# help from Jonathan Larsen (agentc0re@learnix.net)
#
# Feb 16, 2010 - Modified the script and defined the $PYTHON variable
#	outside of the if statement because it was causing issues with
#	the other if statement that also relies on it's answer.
#	- Fixed the second PYTHON if statement that finds the site package
#	directory.  Added parentheses around the part that cd's into the
#	python swig src to copy the files to the site packages so that it
#	would interfere with the CWD before it
#

# +---------------------------------------+
# Mar 3rd, 2010
#   *Version upgrade to 0.5.2
#	*fixed the "strip" for bash 4 
#	 compatability
# +---------------------------------------+
# Sept 12, 2010
#	*Version upgrade to 0.5.6
#	*Bug fixes and enhancements added
# +---------------------------------------+
# May 16, 2011
#	*Version upgrade to 0.7.2
# +---------------------------------------+
# Dec 14, 2011
#	*Version upgrade to 0.7.6
#	*Bug fixes
# +---------------------------------------+

PRGNAM=mlt
VERSION=${VERSION:-0.7.6}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

PYTHON=${PYTHON:-yes}

# SWIG Languages:
if [ "${JAVA:-no}" = "no" ]; then java=""; else java="java"; fi
if [ "${LUA:-no}" = "no" ]; then lua=""; else lua="lua"; fi
if [ "${PERL:-no}" = "no" ]; then perl=""; else perl="perl"; fi
if [ "${PHP:-no}" = "no" ]; then php=""; else php="php"; fi
if [ "${PYTHON:-yes}" = "yes" ]; then python="python"; else python=""; fi
if [ "${RUBY:-no}" = "no" ]; then ruby=""; else ruby="ruby"; fi
if [ "${TCL:-no}" = "no" ]; then tcl=""; else tcl="tcl"; fi

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --disable-debug \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --qimage-libdir=${QT4DIR}/qt/lib \
  --qimage-includedir=${QT4DIR}/qt/include \
  --enable-gpl \
  --avformat-swscale \
  --luma-compress \
  --enable-motion-est \
  --swig-languages="$java $lua $perl $php $python $ruby $tcl" \
  --build=$ARCH-slackware-linux

make clean
CFLAGS="$SLKCFLAGS" CXXFLAGS="$SLKCFLAGS" make
make install DESTDIR=$PKG

if [ $PYTHON = "yes" ]; then
  PYTHONSITEPKG=$(python -c "import sys, os; print os.path.join('/usr/lib${LIBDIRSUFFIX}', 'python%s' % sys.version[:3], 'site-packages')")
  mkdir -p $PKG/$PYTHONSITEPKG
  (
  cd $TMP/$PRGNAM-$VERSION/src/swig/python || true
  cp -a _mlt.so mlt.py mlt_wrap.o $PKG/$PYTHONSITEPKG || true
  )
fi

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp AUTHORS ChangeLog NEWS COPYING README GPL \
$PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
