#!/bin/bash

# Slackware build script for findimagedupes

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20210910 bkw: update for v2.19.1.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=findimagedupes
VERSION=${VERSION:-2.19.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG $TMP/$PRGNAM
mkdir -p $TMP/$PRGNAM $PKG $OUTPUT
cd $TMP/$PRGNAM
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
# 2.18 has an enclosing dir in the tarball, 2.19 doesn't, this worx with both:
[ -d $PRGNAM-$VERSION ] && cd $PRGNAM-$VERSION
chown -R root:root .
chmod 644 *

# use private per-user dirs for Inline's compiled code.
sed -i \
  -e '/^use *Inline/iBEGIN { mkdir("$ENV{HOME}/.findimagedupes-inline"); }' \
  -e '/DIRECTORY/s,=>.*,=> "$ENV{HOME}/.findimagedupes-inline";,' \
  $PRGNAM

install -D -m0755 $PRGNAM $PKG/usr/bin/$PRGNAM
mkdir -p $PKG/usr/man/man1
pod2man -s1 --stderr -cSlackBuilds.org -r$VERSION $PRGNAM | \
  gzip -9c > $PKG/usr/man/man1/$PRGNAM.1.gz

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README* COPYING $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
