#!/bin/sh

# Slackware build script for rss-glx
# Written by Erik Hanson  erik@slackbuilds.org

set -eu

PRGNAM=rss-glx
VERSION=0.8.2
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf ${PRGNAM}_${VERSION}
tar xvf $CWD/${PRGNAM}_${VERSION}.tar.bz2
cd ${PRGNAM}_${VERSION}
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Magick Wand detection is broken.
./autogen.sh
Wand_CFLAGS=$(pkg-config --cflags "Wand >= 6.2") \
Wand_LIBS=$(pkg-config --libs "Wand >= 6.2") \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --with-configdir=/usr/share/xscreensaver/config \
  --disable-static \
  --disable-sound

make
make install-strip DESTDIR=$PKG

gzip -9 $PKG/usr/man/man?/*.?
rm $PKG/usr/lib/*.a

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README README.xscreensaver \
      $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
