.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CONVERTLIT 1 "Feb 20, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
convertlit \- program to manipulate Microsoft Reader .LIT files
.SH SYNOPSIS
.RB "1.  " convertlit
.RI [ options ] " litfile.lit" " " subdir/
.br
.RB "2.  " convertlit
.RI [ options ] " oldfile.lit" " " newfile.lit
.br
.RB "3.  " convertlit
.RI [ options ] " oldfile.lit" " " newfile.lit " " inscription
.SH DESCRIPTION
This manual page documents briefly the \fBconvertlit\fP command.
.PP
\fBconvertlit\fP is a program to convert Microsoft Reader format eBooks
[\fILIT\fP] into an open format.  \fBconvertlit\fP supports three modes
of operation:
.IP 1.
\fBExplosion\fP: expanding a \fILIT\fP file into an OEBPS compliant package,
that is the original \fIXML\fP / \fIHTML\fP source.
.IP 2.
\fBDownconverting\fP: converts to \fIDRM1\fP format, also known as
\fBsealing\fP the \fILIT\fP file.
.IP 3.
\fBInscribing\fP: similar to #2, this adds a label, or \fIinscription\fP,
to the ebook to mark that it belongs to you.
.SH OPTIONS
A summary of options is included below.
For a complete description, run the program without any arguments.
.TP
.B \-d
Disable creating multiple subdirectories.
.TP
.B \-h
Show summary of options.
.TP
.B \-k " " \fI/path/to/keys.txt\fP
The \fIDRM5\fP key file is assumed to be called \fIkeys.txt\fP and located in
the current directory.  If not, use this option to instruct \fBconvertlit\fP
where to find the key file.
.SH AUTHOR
\fBconvertlit\fP was written by Dan A. Jackson <drs@convertlit.com>.
.PP
This manual page was written by Joe Nahmias <jello@debian.org>,
for the Debian project (but may be used by others). It was modified
slightly by B. Watson <yalhcru@gmail.com> for use with the SlackBuild.org
project.
