.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SCID 1 "January 12, 2009"
.SH NAME
scid, pgnfix, pgnscid, sc_addmove, sc_eco, sc_epgn, sc_import, sc_remote,
sc_spell, sc_tree, scidlet, scidpgn, scmerge, spliteco, tcscid,
tkscid, twic2scid - chess database and utility programs
.SH SYNOPSIS
.B scid
.SH DESCRIPTION
This manual page documents briefly 
.B Shane's Chess Information Database.
This manual page was originally written for the Debian GNU/Linux
distribution because the original program does not have a manual
page. It does have documentation in a README file, which is available
as /usr/doc/scid-@VERSION@/README. It also has extensive HTML
documentation, which is available at
/usr/doc/scid-@VERSION@/help/Index.html .
.PP
Scid is a chess database application. With it you can browse databases
of chess games, edit games, and search for games by various criteria.
Scid uses its own compact and fast database format, but can convert to and
from PGN format.
.PP
The command 'scid' starts the graphical user interface.
.PP
The spell-checking file is placed in
/usr/share/scid/data/ratings_2008_4.ssp (in case Scid can't find it), 
while the books for scidlet is in /usr/share/scid/books/scidlet40k.sbk. 
Scid should show a photo whenever a game by a player with a photograph is
loaded. This should happen automatically. If not, copy or link the files in
/usr/share/scid/photos to your Scid user options directory (~/.scid)
and run Scid. To see the photos you must load the spell-checking file.

.SH SLACKWARE-SPECIFIC INFORMATION
As packaged with the script from SlackBuilds.org, the directories 
/usr/share/scid/books and /usr/share/scid/bases are owned by root:games
and with permissions of 775, which means that they are readable by anyone,
but writable by only members of the "games" group.  This makes it possible
for members of the "games" group to add/change/delete books and bases for
scid.  However, a much better approach is something along these lines:

 mkdir -p $HOME/.scid
 cp -r /usr/share/scid/{bases,books} $HOME/.scid

Then, in the Options menu of the scid interface, set the bases directory 
to $HOME/.scid/bases and the books directory to $HOME/.scid/books, and 
restart scid. Try with F11 to see if the book works.  If not, then you may
have to set the permissions of $HOME/.scid/bases/* and $HOME/.scid/books/* 
to 0666.

.SH AUTHOR
Scid was written by Shane Hudson <sgh@users.sourceforge.net>.  This
manual page was written by Peter van Rossum <petervr@debian.org>, for
the Debian GNU/Linux system, and subsequently modified by Marco Pessotto
<melmothx@gmail.com> and Robby Workman <rworkman@slackware.com> with 
Slackware-specific information and other minor tweaks.
