.TH NUMLOCKX "1" "March 2010" "NumLockX 1.2" "Start Options"
.SH NAME
NumLockX 1.2 - How to make your X start with NumLock on
.SH SYNOPSIS
numlockx [ \fIon\fR | \fIoff\fR | \fItoggle\fR ]
.SH OPTIONS
\fIon\fR       turns NumLock on in X (default)

\fIoff\fR      turns NumLock off in X

\fItoggle\fR   toggles the NumLock on and off in X
.SH AUTHOR
(C) 2000\-2010 Lubos Lunak <l.lunak@kde.org>
.br
(C) 2001      Oswald Buddenhagen <ossi@kde.org>
.SH SEE ALSO
http://ktown.kde.org/~seli/numlockx/
