#!/bin/sh
# Slackware wrapper for the vcv rack executable.
runme(){
    cd /opt/rack
    ./Rack

}

if [ $UID == 0 ]; then
    read -p "You are currently running as root...\
 Are you sure you want to proceed? (N/y): " resp
    case "$resp" in
	y|yes)
	    runme
	    ;;
	*)
	    echo Exiting
	    exit 0
	    ;;
    esac
else
    runme
fi
