#!/bin/sh

# Slackware build script for LDView:
# a program to visualize LDraw files

# Written by Niels Horn - niels.horn@gmail.com
# revision date 2009/12/09

PRGNAM=LDView
VERSION=4.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
  LDVDEV64=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
  LDVDEV64=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
  LDVDEV64=YES
fi

set -e

rm -rf $TMP/$PRGNAM-$VERSION $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# the 'makeall' script is in the QT directory
cd QT
export LDVDEV64
QTDIR=$QT4DIR TESTING=$SLKCFLAGS ./makeall

# Install manually
mkdir -p $PKG/usr/bin
cp -a $PRGNAM $PKG/usr/bin/${PRGNAM}_bin
strip --strip-unneeded $PKG/usr/bin/${PRGNAM}_bin
cat $CWD/$PRGNAM.sh > $PKG/usr/bin/$PRGNAM
chmod 0755 $PKG/usr/bin/$PRGNAM
cd ..

# Sample files, font, translations
mkdir -p $PKG/usr/share/$PRGNAM
cp 8464.mpd m6459.ldr Textures/SansSerif.fnt \
   $PKG/usr/share/$PRGNAM/
cp Translations/Czech/LDViewMessages.ini \
   $PKG/usr/share/$PRGNAM/LDViewMessages_cz.ini
cp Translations/EnglishUS/LDViewMessages.ini \
   $PKG/usr/share/$PRGNAM/LDViewMessages_en_US.ini
cp Translations/German/LDViewMessages.ini \
   $PKG/usr/share/$PRGNAM/LDViewMessages_de.ini
cp Translations/Hungarian/LDViewMessages.ini \
   $PKG/usr/share/$PRGNAM/LDViewMessages_hu.ini
cp Translations/Italian/LDViewMessages.ini \
   $PKG/usr/share/$PRGNAM/LDViewMessages_it.ini
cat LDViewMessages.ini LDExporter/LDExportMessages.ini \
   > $PKG/usr/share/$PRGNAM/LDViewMessages.ini

# Copy icon & desktop file to package
mkdir -p $PKG/usr/share/{applications,mime/packages,pixmaps}
cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop
convert Icons/LDViewIcon.gif $PKG/usr/share/pixmaps/$PRGNAM.png
cat QT/desktop/ldraw.xml > $PKG/usr/share/mime/packages/ldraw.xml

# Documentation
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
cp -a license.txt install.txt Readme.txt QT/todo.txt \
      $PKG/usr/doc/$PRGNAM-$VERSION
cp -a ChangeHistory.html Help.html $PKG/usr/doc/$PRGNAM-$VERSION/html/
find $PKG/usr/doc/$PRGNAM-$VERSION/ -type f -exec chmod 644 {} \;
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
