.TH GEM 8 "12 November 2024"

.SH NAME
gem \- a simple gemini server

.SH SYNOPSIS
.B gem
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION
gemini server with TLS and script for generating working TLS certs

It supports: mime types; directory listing; chunked file transfer;
passes most gemini-diagnostics tests; user-defined charset/lang meta
attributes.

.SH OPTIONS
.TP 5
\fB\,-k\/\fR [\fI\,pub key path\/\fR]
(default: /var/gmi/tls/server.crt)
.TP 5
\fB\,-c\/\fR [\fI\,priv key path\/\fR]
(default: /var/gmi/tls/server.key)
.TP 5
\fB\,-h\/\fR [\fI\,hostname\/\fR]
(default: localhost)
.TP 5
\fB\,-p\/\fR [\fI\,port\/\fR]
(default: 1965)
.TP 5
\fB\,-d\/\fR [\fI\,doc root\/\fR]
(default: \fB\,null\/\fR)
.TP 5
\fB\,-i\/\fR [\fI\,index file\/\fR]
(default: index.gmi)
.TP 5
.BR -e
enumerate directories without an index file
.TP 5
.BR -a
permit requests with a different hostname
.TP 5
.BR -v
verbose: print request information

.SH AUTHOR
William Clark <wrvc96@gmail.com>
