#!/bin/bash

# Slackware build script for distrobuilder

# Copyright 2025-2026 Vijay Marcel
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=distrobuilder
VERSION=${VERSION:-3.3.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" -o "$ARCH" = "i686" ]; then
  SLKCFLAGS="-march=$ARCH -mtune=i686 -pipe -O2 -fPIC -fPIE"
  SLDFLAGS="-pie"
  LIBDIRSUFFIX=""
  GARCH=386
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC -fPIE"
  SLDFLAGS="-pie"
  LIBDIRSUFFIX="64"
  GARCH=amd64
else
  echo "This SlackBuild will not run on $ARCH" && exit 1
fi

set -euo pipefail
trap 'echo "$0 FAILED at line $LINENO!" | tee -a $OUTPUT/error-${PRGNAM}.log' ERR

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \+ -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+

mkdir -pv $TMP/$PRGNAM-$VERSION/go/{cache,mod,tmp}
mkdir -pv $TMP/$PRGNAM-$VERSION/build
mkdir -pv $PKG/usr/bin

export GOOS=linux
export GOARCH="$GARCH"
export GOPATH="$TMP/$PRGNAM-$VERSION/go"
export GOCACHE=$TMP/$PRGNAM-$VERSION/go/cache
export GOMODCACHE=$TMP/$PRGNAM-$VERSION/go/mod
export GOTMPDIR=$TMP/$PRGNAM-$VERSION/go/tmp
export GOBIN=$TMP/$PRGNAM-$VERSION/build
export GO111MODULE=on
export CGO_ENABLED=1
export CGO_CFLAGS="${SLKCFLAGS}"
export CGO_CXXFLAGS="${SLKCFLAGS}"
export CGO_LDFLAGS="${SLDFLAGS}"
dver=$(grep '^var Version' shared/version/version.go | cut -d'"' -f2)
modnam=$(grep '^module' go.mod | awk '{print $2}')

gofmt -s -w .
go install -v \
    -buildmode=pie \
    -trimpath \
    -mod=readonly \
    -modcacherw \
    -tags="containers_image_storage_stub,containers_image_docker_daemon_stub,containers_image_openpgp" \
    -ldflags "-s -w \
    -linkmode external \
    -extldflags '${SLDFLAGS}' \
    -X '${modnam}/shared/version.Version=${dver}'" \
	./...

install -vm0755 $GOBIN/distrobuilder -t $PKG/usr/bin

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a doc AUTHORS COPYING README.md $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n --remove-rpaths --remove-tmp-rpaths $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
