#!/bin/bash

# Slackware build script for MTASC

# Written by Andres Fuentes (rafu@riseup.net)
# This script is public domain

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=mtasc
VERSION=${VERSION:-1.15}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SRCTAR="$PRGNAM-$VERSION-linux.tgz"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SRCTAR="$PRGNAM-$VERSION-linux-$ARCH.tgz"
  LIBDIRSUFFIX="64"
else
  printf "\n$ARCH is not supported.\n\n" ; exit 1
fi

set -e

rm -rf $PKG
mkdir -p $PKG/opt/$PRGNAM $OUTPUT
tar xvf $CWD/$SRCTAR -C $PKG/opt/$PRGNAM

chown -R root:root $PKG
find $PKG \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p $PKG/etc/profile.d/
cat << EOF > $PKG/etc/profile.d/mtasc.sh
#!/bin/sh
export PATH="\${PATH}:/opt/mtasc"
EOF
cat << EOF > $PKG/etc/profile.d/mtasc.csh
#!/bin/csh
setenv PATH \${PATH}:/opt/mtasc
EOF

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/opt/$PRGNAM/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
