#!/bin/sh

## Written by hollywoodb (hollywoodb@fastmail.fm)

## Feel free to use, modify, redistribute this script.
## If you make changes please modify the "Written by"
## so that I don't recieve emails about a script I
## did not write.  Thanks.

# Modified by the SlackBuilds.org project

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root!"
    exit
fi

NAME=swig
VERSION=1.3.31
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=${PKG:-$TMP/package-$NAME}
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG $TMP/$NAME-$VERSION
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
tar -zxvf $CWD/$NAME-$VERSION.tar.gz || exit 1
cd $NAME-$VERSION || exit 1

chown -R root:root .
chmod -R u+w,go+r-w,a-s .

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
    --prefix=/usr \
    --exec-prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    || exit 1

make || exit 1
make install DESTDIR=$PKG || exit 1

find $PKG | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find $PKG | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a ANNOUNCE CHANGES* FUTURE INSTALL LICENSE NEW README TODO Examples/ \
 Doc/Manual Doc/Devel  $PKG/usr/doc/$NAME-$VERSION
cat $CWD/$NAME.SlackBuild > $PKG/usr/doc/$NAME-$VERSION/$NAME.SlackBuild
# Fix permissions and wipe the pdf bloat
find $PKG/usr/doc/$NAME-$VERSION -type f -exec chmod 0644 {} \;
find $PKG/usr/doc/$NAME-$VERSION -name "*.pdf" -exec rm {} \;

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$NAME-$VERSION-$ARCH-$BUILD$TAG.tgz
