#!/bin/bash

# Slackware build script for Gambas 3

# Copyright 2018-2025  Tim Dickson dickson.tim@googlemail.com
# Copyright 2012-2015  Fridrich von Stauffenberg <cancellor2@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=gambas3
SRCNAM=gambas
VERSION=${VERSION:-3.20.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e
#check updated for slackware 15 for new package location
if [ "x$( ls -H /var/lib/pkgtools/packages|grep ^$PRGNAM|wc -l )" = "x1" ]; then
  #current installs of gambas should be uninstalled before
  #attempting to create this gambas3 package
  echo "you must uninstall $PRGNAM before creating package $PRGNAM ver $VERSION"
  exit 2
fi
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$VERSION
tar xvf $CWD/$SRCNAM-$VERSION.tar.bz2
cd $SRCNAM-$VERSION
chown -R root:root .

./reconf-all

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
LLVM_CONFIG=llvm-config \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --build=$ARCH-slackware-linux \
  $qt5

make
make -j1 install DESTDIR=$PKG XDG_UTILS=""

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mv $PKG/usr/share/man $PKG/usr
find $PKG/usr/man -type f -exec gzip -9 {} \;
mkdir -p $PKG/usr/share/icons/hicolor/{scalable/apps,48x48/apps,64x64/mimetypes}
chmod 644 app/desktop/$PRGNAM.svg
cp -a app/desktop/$PRGNAM.svg $PKG/usr/share/icons/hicolor/scalable/apps
convert -resize 48x48 app/desktop/$PRGNAM.png $PKG/usr/share/icons/hicolor/48x48/apps/$PRGNAM.png
convert -resize 64x64 app/mime/application-x-${SRCNAM}script.png $PKG/usr/share/icons/hicolor/64x64/mimetypes/script.png
convert -resize 64x64 app/mime/application-x-${SRCNAM}serverpage.png $PKG/usr/share/icons/hicolor/64x64/mimetypes/serverpage.png
convert -resize 64x64  main/mime/application-x-$PRGNAM.png $PKG/usr/share/icons/hicolor/64x64/mimetypes/application-x-$PRGNAM.png
mkdir -p $PKG/usr/share/{applications,mime/packages}
cp -a app/desktop/$PRGNAM.desktop $PKG/usr/share/applications
chmod 644 $PKG/usr/share/applications/$PRGNAM.desktop
cp -a app/mime/application-x-${SRCNAM}{script,serverpage}.xml \
  $PKG/usr/share/mime/packages
chmod -x $PKG/usr/share/appdata/$PRGNAM.appdata.xml
cp -a main/mime/application-x-$PRGNAM.xml $PKG/usr/share/mime/packages

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
#ChangeLog is empty so miss out for now
cp -a COPYING README TODO $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
