( cd /usr/bin                              ; rm -rf empty.wmi )
( cd /usr/bin                              ; ln -sf /usr/bin/bash-empty.wmi empty.wmi )
( cd /usr/doc/wminfo-4.1.0/plugins.binary  ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.binary  ; ln -sf /usr/bin/run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.conky   ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.conky   ; ln -sf /usr/bin/run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.offline ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.offline ; ln -sf /usr/bin/run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.online  ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.online  ; ln -sf /usr/bin/run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.system  ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/plugins.system  ; ln -sf /usr/bin/run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/samples         ; rm -rf run-all-wminfo-plugins )
( cd /usr/doc/wminfo-4.1.0/samples         ; ln -sf /usr/bin/run-all-wminfo-plugins )

