#!/bin/bash

# Allow users to override command-line options
# Based on Gentoo's chromium package (and by extension, Debian's)

if [[ -f /etc/opera-developer/default ]]; then
	. /etc/opera-developer/default
fi

# Prefer user defined CHROMIUM_USER_FLAGS (from env) over system
# default CHROMIUM_FLAGS (from /etc/chromium/default)

OPERA_FLAGS=${OPERA_USER_FLAGS:-$OPERA_FLAGS}

if [ "$ARCH" = "x86_64" ]; then
	exec /usr/lib64/opera-developer/opera-developer $OPERA_FLAGS "$@"
else
	exec /usr/lib/opera-developer/opera-developer $OPERA_FLAGS "$@"
fi
