.TH CGDB "1" "July 2026" "CGDB 0.8.0" "SlackBuilds.org"
.SH NAME
CGDB \- curses frontend to gdb
.SH SYNOPSIS
.IP
cgdb [cgdb options] [\-\-] [gdb options]
.SH DESCRIPTION
cgdb is a curses frontend for gdb.
.SH OPTIONS
.TP
\fB\-\-version\fR
Print version information and then exit.
.TP
\fB\-\-help\fR
Print help and then exit.
.TP
\fB\-d\fR
Set debugger to use.
.TP
\fB\-w\fR
Wait for debugger to attach before starting.
.TP
\fB\-\-\fR
Marks the end of CGDB's options.
.SH COPYRIGHT
Copyright 2002\-2010 Bob Rossi and Mike Mueller.
CGDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for CGDB.
.SH "SEE ALSO"
The full documentation for
.B CGDB
is maintained as a Texinfo manual.  If the
.B info
and
.B CGDB
programs are properly installed at your site, the command
.IP
.B info CGDB
.PP
should give you access to the complete manual.
