#!/bin/sh

# Slackware build script for jdk15

# Copyright 2019-2021 Igor Alexandrov <igor.alexandrov@outlook.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=jdk15
VERSION=${VERSION:-15.0.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$(uname -m)" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$(uname -m) ;;
  esac
fi

set -e

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" != "x86_64" ]; then
  echo "$ARCH is not supported for $PRGNAM-$VERSION"
  exit 1
fi
LIBDIRSUFFIX=64

rm -rf $PKG
mkdir -p $TMP $OUTPUT \
         $PKG/{install,etc/profile.d,usr/{bin,lib${LIBDIRSUFFIX},doc/$PRGNAM-$VERSION,man/man1}}

cd $PKG/usr/lib${LIBDIRSUFFIX}
tar -xvf $CWD/jdk-${VERSION}_linux*.tar.gz
mv $(tar -tf $CWD/jdk-${VERSION}_linux*.tar.gz | head -1 | cut -d/ -f1) $PRGNAM-$VERSION

chown -R root:root $PRGNAM-$VERSION
find -L $PRGNAM-$VERSION \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

find $PRGNAM-$VERSION -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PRGNAM-$VERSION/man -type f -exec gzip -9q {} \; 2> /dev/null || true
for i in $(find $PRGNAM-$VERSION/man -type l 2> /dev/null); do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
(cd ../man/man1; find ../../lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION/man/man1 -type f -exec ln -s {} \;)

(cd ../bin; find ../lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION/bin -type f -exec ln -s {} \;)

ln -sf $PRGNAM-$VERSION/lib/libjawt.so
ln -sf $PRGNAM-$VERSION/lib/server/libjvm.so
ln -sf $PRGNAM-$VERSION/lib/libjava.so
ln -sf $PRGNAM-$VERSION/lib/libawt.so
ln -sf $PRGNAM-$VERSION/lib/libawt_xawt.so
ln -sf $PRGNAM-$VERSION/lib/libjli.so

cd ../doc/$PRGNAM-$VERSION
ln -s ../../lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION/legal
ln -s ../../lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION/release
cat $CWD/$PRGNAM.SlackBuild > $PRGNAM.SlackBuild

cd $PKG
cat > etc/profile.d/$PRGNAM.sh << EOF
#!/bin/sh
export JAVA_HOME=/usr/lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION
EOF

cat > etc/profile.d/$PRGNAM.csh << EOF
#!/bin/csh
setenv JAVA_HOME /usr/lib${LIBDIRSUFFIX}/$PRGNAM-$VERSION
EOF

chmod 755 etc/profile.d/*
cat $CWD/slack-desc > install/slack-desc

/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
