'\" t
.\"     Title: YEAHCONSOLE
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: August 9, 2021
.\"    Manual: SlackBuilds.org
.\"    Source: yeahconsole 0.3.4
.\"  Language: English
.\"
.TH "YEAHCONSOLE" "1" "August 9, 2021" "yeahconsole 0.3.4" "SlackBuilds.org"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yeahconsole \- drop\-down X terminal emulator wrapper
.SH "SYNOPSIS"
.HP \w'\fByeahconsole\fR\ 'u
\fByeahconsole\fR [\fB\-h\fR] [\fB\-e\ \fR\fB\fIcommand\fR\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fByeahconsole\fR
command\&.
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\&.
.PP
\fByeahconsole\fR
is a wrapper for X terminal emulators that provides a drop\-down terminal embedding other terminal emulators
.SH "OPTIONS"
.PP
A summary of options is included below\&. Any other argument is passed to the X terminal emulator\&.
.PP
\fB\-h\fR
.RS 4
Show summary of options and supported X resources\&.
.RE
.PP
\fB\-e\fR \fIcommand\fR
.RS 4
\fIcommand\fR
will be run in the X terminal emulator used\&. If specified this must be the last option since everything after the \-e will be interpreted as the
\fIcommand\fR\&.
.RE
.SH "RESOURCES"
.PP
The resources from the embedded X terminal emulator will be used and are documented in the corresponding manpage for your X terminal emulator\&. The specific resources for yeahconsole follow:
.PP
\fBrestart\fR
.RS 4
0 or 1, 1 should restart the terminal\&. Default is 0\&.
.RE
.PP
\fBterm\fR
.RS 4
terminal to use, valid values: urxvt, urxvtc, xterm\&. Default is xterm\&.
.RE
.PP
\fBscreenWidth\fR
.RS 4
width of the terminal\&. Default is the display width\&.
.RE
.PP
\fBconsoleHeight\fR
.RS 4
number of lines of the console\&. Default is 10\&.
.RE
.PP
\fBxOffset\fR
.RS 4
x position\&. Default is 0\&.
.RE
.PP
\fBaniDelay\fR
.RS 4
delay for the slide animation\&. Default is 40\&.
.RE
.PP
\fBstepSize\fR
.RS 4
step size in pixels for the animation\&. 0 will disable the animation\&. Default is 1\&.
.RE
.PP
\fBhandleWidth\fR
.RS 4
width for the resize handle\&. Default is 3\&.
.RE
.PP
\fBhandleColor\fR
.RS 4
color for the resize handle\&. Default is grey70\&.
.RE
.PP
\fBtoggleKey\fR
.RS 4
key combo that toggles yeahconsole\&. Default is ControlAlt+y\&.
.RE
.PP
\fBkeyBigger\fR
.RS 4
increase height of yeahconsole\&. Default is Control+KP_Add\&.
.RE
.PP
\fBkeySmaller\fR
.RS 4
decrease height of yeahconsole\&. Default is Control+KP_Subtract\&.
.RE
.PP
\fBkeyFull\fR
.RS 4
toggle fullscreen mode\&. Default is Alt+F11\&.
.RE
.SH "SEE ALSO"
.PP
xterm (1), rxvt (1)\&.
.SH "AUTHOR"
.PP
This manual page was written by
Damián
Viano
<debian@damianv\&.com\&.ar>
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
This man page has been modified slightly by B\&. Watson for the SlackBuilds\&.org project\&.
.PP
The complete text of the GNU General Public License can be found at https://www\&.gnu\&.org/licenses/old\-licenses/gpl\-2\&.0\&.txt\&.
.SH "COPYRIGHT"
.br
Copyright \(co 2006 Damián Viano
.br
