#!/bin/sh

# Slackware build script for mendeleydesktop

# Copyright 2017 Dhaby Xiloj <slack.dhabyx@gmail.com>
# All rights reserved.
# Based on work of:
# Written by Grissiom <chaos.proton@gmail.com>
# Updated by Glenn Becker <glenn.becker@gmail.com>
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=mendeleydesktop
VERSION=${VERSION:-1.17.9}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i586" ] || [ "$ARCH" = "i686" ]; then
  ARCH="i486" # mendeleydesktop doesn't have i586/i686 pre-builds.
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-linux-$ARCH
tar xvf $CWD/$PRGNAM-$VERSION-linux-${ARCH}.tar.bz2
cd $PRGNAM-$VERSION-linux-$ARCH
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# removing QT5 bundled libraries
if [ "${SYSTEM_QT5:-no}" != "no" ]; then
  rm -rf lib/qt
  rm bin/qt.conf
  rm -rf lib/$PRGNAM/plugins
  (
   cd lib/$PRGNAM/libexec/
   rm QtWeb* icudtl.dat qtwebengine*
  )
fi

# Using /opt for installation and prevent conflicts with QT5 applications
mkdir -p $PKG/opt/$PRGNAM
cp -r bin lib share $PKG/opt/$PRGNAM

# make symlinks and moving some important files
mkdir -p $PKG/usr/{bin,share}
mv $PKG/opt/$PRGNAM/share/{applications,icons} $PKG/usr/share
if [ "${SYSTEM_QT5:-no}" != "no" ]; then
# configure all for use System QT installation
  cat <<-EOF > $PKG/usr/bin/$PRGNAM
#!/bin/sh
MENDELEY_BASE=/opt/mendeleydesktop
MENDELEY_LIB=lib

LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:\${MENDELEY_BASE}/\${MENDELEY_LIB}
export LD_LIBRARY_PATH
cd /opt/mendeleydesktop/lib/mendeleydesktop/libexec
./mendeleydesktop.$ARCH \$@
EOF
  chmod 755 $PKG/usr/bin/$PRGNAM
else
  (
   cd $PKG/usr/bin
   ln -s ../../opt/$PRGNAM/bin/$PRGNAM $PRGNAM
  )
fi


mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a share/doc/mendeleydesktop INSTALL LICENSE README \
    $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
