.\"                                      
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH JKMETER 1 "August 3, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jkmeter \- Jkmeter is a horizontal or vertical bargraph audio level meter for Jack Audio Connection Kit
.SH SYNOPSIS
.B jkmeter
.RI [ options ] 
.br
.SH DESCRIPTION
This manual page documents briefly the
.B jkmeter
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
This manual page was written for the Debian distribution because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBjkmeter\fP is a horizontal or vertical bargraph level meter based on the ideas of mastering guru Bob Katz. <http://www.digido.com/bob-katz/index.php>
.br
        This meter displays both the true RMS level and the digital peak level.
.SH OPTIONS
.PP
.B \  -h            
       Display short info
.PP
.B \  -name <name>  
       Name to use as jack client
.PP
.B \  -s <server>  
       Jack server name
.PP
.B \  -g <geometry> 
       Window position
.PP
.B \  -type <type>  
       Meter type, k20 or k14 (k20)
.PP
.B \  -rate <rate>  
       Update rate (30)
.PP
.B \  -A            
       Ambisonic (4ch) mode
.PP
.B \  -C            
       Add correlation meter
.PP
.B \  -V            
       Vertical layout
.PP
.B \  -H            
       Horizontal layout
.PP
.TP
.SH SEE ALSO
.BR jackd(1).
.br
.SH AUTHOR
jkmeter was written by Fons Adriaensen <fons@kokkinizita.net>.
.PP
This manual page was written by Debian Multimedia Maintainers <pkg-multimedia-maintainers@lists.alioth.debian.org>
for the Debian project (but may be used by others).
