#!/bin/sh

# Slackware build script for figlet

# Written by David Woodfall dave@unrealize.co.uk
# aka dive on irc.freenode.net/#slackware

PRGNAM=figlet
VERSION=${VERSION:-222}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

DESTDIR=$PKG/usr/bin
FONTDIR=$PKG/usr/share/figlet
MANDIR=$PKG/usr/man/man6

set -e # Exit on most errors

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM$VERSION
tar xvf $CWD/$PRGNAM$VERSION.tar.gz
cd $PRGNAM$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Sed the CFLAGs into the Makefile
if [ "$ARCH" = "i486" ]; then
    sed -i 's#CFLAGS = -g#CFLAGS=-O2 -march=i486 -mtune=i686#g' Makefile
elif [ "$ARCH" = "i686" ]; then
    sed -i 's#CFLAGS = -g#CFLAGS=-O2 -march=i686 -mtune=i686#g' Makefile
fi

# Need to fix the Makefile.
sed -i 's/local\///g' Makefile
sed -i '/DEFAULTFONTDIR\ =\ fonts/d' Makefile

make all
chmod +x figlist
mkdir -p $DESTDIR $FONTDIR $MANDIR
cp figlet chkfont figlist $DESTDIR
cp -a fonts/*.{flf,flc} $FONTDIR
cp -a figlet.6 $MANDIR

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null
)

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGES FAQ LICENSE README figfont.txt  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz


