.TH WOLF4SDL "6" "January 18 2023" "2.0+" "SlackBuilds.org"
.SH NAME
Wolf4SDL \- Game engine for Wolfenstein 3D and Spear of Destiny
.SH SYNOPSIS
.B wolf4sdl\-wolf\-demo
[\fIoptions\fR]
.br
.B wolf4sdl\-wolf\-full
[\fIoptions\fR]
.br
.B wolf4sdl\-spear\-demo
[\fIoptions\fR]
.br
.B wolf4sdl\-spear\-full
[\fIoptions\fR]
.br
.SH DESCRIPTION
Wolf4SDL is an open\-source port of id Software's classic first\-person
shooter Wolfenstein 3D to the cross\-platform multimedia library "Simple
DirectMedia Layer (SDL)" (http://www.libsdl.org). It is meant to keep
the original feel while taking advantage of some modern improvements.
.PP
Wolf4SDL is a game engine. To actually play the game, it requires the
data files from the original game (see \fBFILES\fR, below).
.PP
This man page is for the SlackBuilds.org \fBgames/wolf4sdl\fR build, which
is based on the last available community version from \fIhttps://github.com/11001011101001011/Wolf4SDL\fR, with additional patches ported from Debian.

.SH OPTIONS
.TP
\fB\-\-help\fR
Usage summary
.TP
\fB\-\-tedlevel\fR <level>
Starts the game in the given level
.TP
\fB\-\-baby\fR
Sets the difficulty to baby for tedlevel
.TP
\fB\-\-easy\fR
Sets the difficulty to easy for tedlevel
.TP
\fB\-\-normal\fR
Sets the difficulty to normal for tedlevel
.TP
\fB\-\-hard\fR
Sets the difficulty to hard for tedlevel
.TP
\fB\-\-nowait\fR
Skips intro screens
.TP
\fB\-\-windowed\fR
Starts the game in a window, without mouse support.
.TP
\fB\-\-windowed\-mouse\fR
Starts the game in a window, with mouse support. The mouse pointer will be unable to
leave the game window.
.TP
\fB\-\-novert\fR
Disables vertical mouse motion (see also \fB\-\-modern\fR).
.TP
\fB\-\-crosshair\fR
Shows a crosshair (see also \fB\-\-modern\fR).
.TP
\fB\-\-run\fR
Always run (press both Shift keys to toggle; see also \fB\-\-modern\fR).
.TP
\fB\-\-strafe\fR
Always strafe instead of turning left/right (press both Alt keys or Alt+RightShift to toggle; see also \fB\-\-modern\fR).
.TP
\fB\-\-modern\fR
Same as \fB\-\-novert\fR \fB\-\-crosshair\fR \fB\-\-run\fR \fB\-\-strafe\fR.
.TP
\fB\-\-res\fR <width> <height>
Sets the screen resolution
(must be multiple of 320x200 or 320x240). In fullscreen mode, the game switches
to the smallest available fullscreen mode that's equal to or larger than the
chosen resolution (e.g. 960x720 usually results in a 1024x768 display with black
borders).
.TP
\fB\-\-resf\fR <width> <height>
Sets any screen resolution >= 320x200
(which may result in graphic errors, and occasional crashes)
.TP
\fB\-\-bits\fR <b>
Sets the screen color depth
(use this when you have palette/fading problems.
allowed: 8, 16, 24, 32; default: "best" depth)
.TP
\fB\-\-joystick\fR <index>
Use the index\-th joystick if available
(\fB\-1\fR to disable joystick, default: 0)
.TP
\fB\-\-joystickhat\fR <index>
Enables movement with the given coolie hat
.TP
\fB\-\-samplerate\fR <rate>
Sets the sound sample rate (given in Hz, default: 44100)
.TP
\fB\-\-audiobuffer\fR <size>
Sets the size of the audio buffer (\-> sound latency)
(given in bytes, default: 2048 / (44100 / samplerate))
.TP
\fB\-\-ignorenumchunks\fR
Ignores the number of chunks in VGAHEAD.*
(may be useful for some broken mods)
.TP
\fB\-\-mission\fR <mission>
\fBwolf4sdl\-spear\-full only:\fR Mission number to play (0\-3, default: 0).
.br
0 \- Original release of Spear of Destiny
.br
1 \- Re\-elease of Spear of Destiny by Steam
.br
2 \- Return to Danger
.br
3 \- Ultimate Challenge
.TP
\fB\-\-goodtimes\fR
\fBwolf4sdl\-spear\-full only:\fR Disable copy protection quiz
.TP
\fB\-\-goobers\fR
\fBwolf4sdl\-wolf\-full and wolf4sdl\-wolf\-demo:\fR Enable cheat/debug mode (then press \fIShift\-Alt\-Backspace\fR while playing)
.TP
\fB\-\-debugmode\fR
\fBwolf4sdl\-spear\-full and wolf4sdl\-spear\-demo:\fR Enable cheat/debug mode (then press \fIShift\-Alt\-Backspace\fR while playing)
.SH ENVIRONMENT
.TP
\fBWOLF4PATH\fR
Sets the directory where game data files are searched for. When this
variable is not set, the default directory is
\fIPREFIX\fR\fB/share/games/wolf3d\fR (\fIPREFIX\fR was set at
compile time, and defaults to \fB/usr\fR).
.PP
Note that data files are always searched for in the current directory
first, regardless of this setting.
.SH FILES
Per\-user config files and saved games are stored in \fB~/.wolf4sdl\fR
.PP
Game data files are searched for \fBfirst\fR in the current directory,
then in \fB$WOLF4PATH\fR (see above). Each game binary uses a different
set of data files:
.TS
box;
cB cB cB
l c r
l c r
l c r
l c r
r s r.
Game	Executable	Files
Wolf3D Shareware	wolf4sdl\-wolf\-demo	*.wl1
Wolf3D Registered	wolf4sdl\-wolf\-full	*.wl6 or *.wl3
Spear Demo	wolf4sdl\-spear\-demo	*.sdm
Spear Full Version	wolf4sdl\-spear\-full	*.sod
wolf4sdl\-spear\-full \-\-mission 1	*.sd1
wolf4sdl\-spear\-full \-\-mission 2	*.sd2
wolf4sdl\-spear\-full \-\-mission 3	*.sd3
.TE
.PP
All filenames must be in lowercase (e.g. \fIvgahead.wl1\fR, not \fIVGAHEAD.WL1\fR).
.PP
The Wolf3D and Spear demo/shareware data files can be downloaded from
.br
\fIhttp://sourceforge.net/projects/wolfgl/files/\fR
.br
The files are called \fBwolfdata.zip\fR and \fBsdmdata.zip\fR.
.PP
The full/registered versions are available commercially. After installing
the game (perhaps using DOSBox), the data files will be found in the game's
install directory.
.PP
To play modified versions of the game ("mods"), place the mod's files in
their own directory, cd to that directory, and run the appropriate game
binary. The files in the current directory will be used instead of (or in
addition to) the ones in \fB/usr/share/games/wolf3d\fR. Remember that only
lowercase filenames will work (use "unzip -LL" when extracting). Unfortunately,
many available mods include modified versions of the game engine, which
are only distributed as Windows or DOS executables, with no source. These
are generally unplayable with Wolf4SDL :(
.SH CONTROLS
The controls can be modified from within the game menus. The default
controls are:
.TS
box;
cB s
lB l.
Keyboard Controls
Up	Move Forward
Down	Move Back
Left	Turn Left (or Strafe Left, with Alt)
Right	Turn Right (or Strafe Right, with Alt)
Space	Open Door
Control	Fire Weapon
Alt	Strafe
Shift	Run
1	Use Knife
2	Use Pistol
3	Use Machine Gun
4	Use Chaingun
Esc	Go to Main Menu
F1	Help
F2	Save Game
F3	Load Game
F4	Sound Menu
F5	Resize View
F6	Controls Menu
F7	End Game
F8	Quick Save
F9	Quick Load
F10	Exit
.TE
.PP
.TS
box;
cB s
lB l.
Joystick Controls
X Axis	Turn/Strafe Left/Right
Y Axis	Move Forward/Backward
Button 1	Fire Weapon
Button 2	Strafe
Button 3	Open Door
Button 4	Run
.TE
.PP
.TS
box;
cB s
lB l.
Mouse Controls
X Axis	Turn/Strafe Left/Right
Y Axis	Move Forward/Backward
Left Button (#1)	Fire Weapon
Right Button (#2)	Strafe
Center Button (#3)	Open Door
.TE
.PP
.TS
box;
cB s
lB l.
Other Controls (non-remappable)
Left Shift + Right Shift	Toggle autorun
Left Alt + Right Alt	Toggle autostrafe
Left Alt + Right Shift	Toggle autostrafe (same as above)
.TE
.PP
Also, if the game was run with \fB\-\-goobers\fR (Wolf)
or \fB\-\-debugmode\fR (Spear), the standard cheat codes are
available. Remember to press Alt\-Shift\-Backspace first, and \fBbe
careful\fR not to accidentally hit Alt\-Ctrl\-Backspace instead (*boom*,
there goes your X session...)
.SH AUTHORS
Ported by Chaos\-Software: http://www.chaos\-software.de.vu
.PP
Original Wolfenstein 3D by id Software.
.PP
The Wolf4SDL project was started by Ripper, and continued by various
authors. See https://wl6.fandom.com/wiki/Wolf4SDL for more information.
.PP
This man page written for the SlackBuilds.org project
by B. Watson, and is licensed under the WTFPL.
