.TH DOLPHIN-EMU 1 "December 10, 2010"
.SH NAME
dolphin-emu \- A Gamecube, Wii and Triforce (the arcade machine based on the
Gamecube) emulator.
.SH SYNOPSIS
.B dolphin-emu
.RI [ options ]
.SH DESCRIPTION
.B dolphin-emu
is a Gamecube, Wii and Triforce (the arcade machine based on the
Gamecube) emulator.
.P
Gamecube compatibility is okay - lots of games work, many games don't work.
.P
Wii compatibility is also good - a lot of games do work. Wii emulation
generally requires a bit more computing power than Gamecube emulation, though.
.P
Triforce compatibility is not really known yet, but at least one game runs,
with minor glitches. 
.SH OPTIONS
.TP
.BI "\-A, \-\-audio-plugin="plugin
Specify an audio plugin
.TP
.B \-b, \-\-batch
Exit application when emulator closes
.TP
.B \-d, \-\-debugger
Open the debugger
.TP
.BI "\-e, \-\-exec="file
Loads the specified file (DOL, ELF, WAD, GCM, ISO)
.TP
.B \-l, \-\-logger
Open the logger
.TP
.BI "\-V, \-\-video-plugin="plugin
Specify a video plugin
.SH AUTHOR
This manual page was written by Glenn Rice <glennricster@gmail.com>,
for the Debian system (but may be used by others).
