.TH WGETPASTE "1" "Dec 2012" "wgetpaste v2.20" "SlackBuilds.org"
.SH NAME
wgetpaste \- Command\-line interface to various pastebin sites
.SH SYNOPSIS
.B wgetpaste
[\fIoptions\fR] [\fIfile\fR[\fIs\fR]]
.SH OPTIONS
.TP
\fB\-l\fR, \fB\-\-language\fR LANG
set language (defaults to "Plain Text")
.HP
\fB\-d\fR, \fB\-\-description\fR DESCRIPTION set description (defaults to "stdin" or filename)
.TP
\fB\-n\fR, \fB\-\-nick\fR NICK
set nick (defaults to your username)
.TP
\fB\-s\fR, \fB\-\-service\fR SERVICE
set service to use (defaults to "bpaste")
.TP
\fB\-e\fR, \fB\-\-expiration\fR EXPIRATION
set when it should expire (defaults to "30 days")
.TP
\fB\-S\fR, \fB\-\-list\-services\fR
list supported pastebin services
.TP
\fB\-L\fR, \fB\-\-list\-languages\fR
list languages supported by the specified service
.TP
\fB\-E\fR, \fB\-\-list\-expiration\fR
list expiration setting supported by the specified service
.TP
\fB\-u\fR, \fB\-\-tinyurl\fR URL
convert input url to tinyurl
.TP
\fB\-c\fR, \fB\-\-command\fR COMMAND
paste COMMAND and the output of COMMAND
.TP
\fB\-i\fR, \fB\-\-info\fR
append the output of `wgetpaste_info`
.TP
\fB\-I\fR, \fB\-\-info\-only\fR
paste the output of `wgetpaste_info` only
.TP
\fB\-x\fR, \fB\-\-xcut\fR
read input from clipboard (requires xclip)
.TP
\fB\-X\fR, \fB\-\-xpaste\fR
write resulting url to the X primary selection buffer (requires xclip)
.TP
\fB\-C\fR, \fB\-\-xclippaste\fR
write resulting url to the X clipboard selection buffer (requires xclip)
.TP
\fB\-r\fR, \fB\-\-raw\fR
show url for the raw paste (no syntax highlighting or html)
.TP
\fB\-t\fR, \fB\-\-tee\fR
use tee to show what is being pasted
.TP
\fB\-v\fR, \fB\-\-verbose\fR
show wget stderr output if no url is received
.TP
\fB\-\-completions\fR
emit output suitable for shell completions (only affects \fB\-\-list\-\fR*)
.TP
\fB\-\-debug\fR
be *very* verbose (implies \fB\-v\fR)
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help
.TP
\fB\-g\fR, \fB\-\-ignore\-configs\fR
ignore /etc/wgetpaste.conf, ~/.wgetpaste.conf etc.
.TP
\fB\-\-version\fR
show version information
.PP
Defaults (DEFAULT_{NICK,SERVICE,LANGUAGE,EXPIRATION}[_${SERVICE}]) can be overridden
globally in /etc/wgetpaste.conf or /etc/wgetpaste.d/*.conf or per user in any of
~/.wgetpaste.conf or ~/.wgetpaste.d/*.conf.
.SH AUTHOR
Copyright (c) 2007 Bo Ørsted Andresen <bo.andresen@zlin.dk>
.br
Distributed as-is. With no warranties.
.PP
Man page created by B. Watson <yalhcru@gmail.com>, for the SlackBuilds.org project (but
it may be used by anyone).
