#!/bin/sh

# Slackware build script for libanculus-sharp
# Written by Erik Hanson  erik@slackbuilds.org

set -eu

PRGNAM=libanculus-sharp
VERSION=0.3.1
ARCH=i486 # Unless you built Mono with a different ARCH, leave this alone.
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

sh autogen.sh \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var/lib \
  --mandir=/usr/man \
  --disable-static

make
make install DESTDIR=$PKG

rmdir $PKG/usr/bin # This is empty.
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -ar AUTHORS INSTALL LICENSE docs/api $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
