# Remove data generated by doinst.sh
if [ -d /usr/bin/Resources ]; then
  rm /usr/bin/Resources/QtLanguage.qm
  rm /usr/bin/Resources/QtLanguage.ts
  rm /usr/bin/Resources/QtLanguage_ja.qm
  rm /usr/bin/Resources/QtLanguage_ja.ts
  rm /usr/bin/Resources/QtLanguage_ru.qm
  rm /usr/bin/Resources/QtLanguage_ru.ts
  rm /usr/bin/Resources/QtLanguage_uk.qm
  rm /usr/bin/Resources/QtLanguage_uk.ts
  rm /usr/bin/Resources/cables.txt
  rm /usr/bin/Resources/itu-regions-defaults.txt
  rm /usr/bin/Resources/itu-regions.txt
  rmdir /usr/bin/Resources
fi
