#!/bin/sh

# Copyright 2008  Robby Workman  Northport, AL, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# I should give a big thanks to Adam Blackburn and Dan O'Reilly (wicd devs)
# for their outstanding work on this, not the least of which was their
# cooperation in making it very Slackware-friendly.  Thanks, guys!

PRGNAM=wicd
VERSION=${VERSION:-1.5.4}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

PMUTILS=${PMUTILS:-NO}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .

python setup.py configure
python setup.py install --root=$PKG

# This sets dhcpcd as the default dhcp client in the Preferences dialog
cat << EOF > $PKG/etc/wicd/manager-settings.conf.new
[Settings]
dhcp_client = 2
EOF

# Don't clobber init script on upgrade
mv $PKG/etc/rc.d/rc.wicd $PKG/etc/rc.d/rc.wicd.new

# Compress the man pages and add a couple of things to the package docs
find $PKG/usr/man -type f -exec gzip -9 {} \;
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild 
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README.SLACKWARE

# If pm-utils is installed, or the user wants support for it later, then
# we'll install the hook; otherwise, this defaults to NO
if ls /var/log/packages/pm-utils-* 1>/dev/null 2>/dev/null ; then
  PMUTILS=YES
fi
if [ "$PMUTILS" = "YES" ]; then
  mkdir -p $PKG/usr/lib/pm-utils/sleep.d
  cp -a other/55-wicd $PKG/usr/lib/pm-utils/sleep.d
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
