'\" t
.\"     Title: NTDPAL
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/30/2011
.\"    Manual: Primer3 User Manuals
.\"    Source: ntdpal 1.1.4
.\"  Language: English
.\"
.TH "NTDPAL" "1" "11/30/2011" "ntdpal 1.1.4" "Primer3 User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ntdpal \- Provides Primer3\*(Aqs alignment functionality
.SH "SYNOPSIS"
.HP \w'\fBntdpal\fR\ 'u
\fBntdpal\fR [\-g\ \fIgval\fR] [\-l\ \fIlval\fR] [\-m\ \fImval\fR] [\-f1,\ f2,\ f3] [\-p] [\-s] [\-e] {\fIseq1\fR} {\fIseq2\fR} {\fImode\fR}
.SH "DESCRIPTION"
.PP
Ntdpal (NucleoTide Dynamic Programming ALignment) is a stand\-alone program that provides Primer3\*(Aqs alignment functionality (local, a\&.k\&.a\&. Smith\-Waterman, global, a\&.k\&.a\&. Needleman\-Wunsch, plus "half global")\&.
.SH "OPTIONS"
.PP
\fB\-g\fR \fIgval\fR
.RS 4
\fIgval\fR
is a (positive) float (\&.01 precision) specifying penalty for creating a gap respectively (the penalties are subtracted from the output score)
.RE
.PP
\fB\-l\fR \fIval\fR
.RS 4
\fIlval\fR
is a (positive) float (\&.01 precision) specifying penalty for lengthening a gap respectively (the penalties are subtracted from the output score)
.RE
.PP
\fB\-a\fR
.RS 4
Causes the scoring matrix to be modified by dpal_set_ambiguity_codes\&.
.RE
.PP
\fB\-e\fR
.RS 4
Causes the end position of the alignment in both sequences to be printed\&. Do not confuse with the \*(Aqe\*(Aq
\fImode\fR\&.
.RE
.PP
\fB\-f1, \-f2, \-f3\fR
.RS 4
Force specific implementations\&. \-f2 forces use an implementation that might provide more informative error messages, possibly at the expense of some speed\&.
.RE
.PP
\fB\-h\fR
.RS 4
Use a different scoring matrix: G and C matches = 3, A and T = 2, and mismatches = \-0\&.5\&. (The default scoring matrix assigns 1 to a match, and \-1 to a mismatch\&.)
.RE
.PP
\fB\-p\fR
.RS 4
Causes the alignment to be displayed on stderr\&.
.RE
.PP
\fB\-s\fR
.RS 4
causes
\fIonly\fR
the score to printed\&.
.RE
.PP
\fB\-m\fR \fImval\fR
.RS 4
is the maximum allowed gap (default is 3)\&.
.RE
.PP
\fIseq1\fR and \fIseq2\fR
.RS 4
are the sequences to be aligned\&.
.RE
.PP
\fImode\fR
.RS 4
is one of
\fIg\fR,
\fIG\fR,
\fIl\fR, or
\fIL\fR
specifying a global, global end\-anchored, local, or local end\-anchored alignment respectively\&. For backward compatibility
\fIe\fR
is equivalent to
\fIG\fR\&.
.RE
.SH "REFERENCE"
.PP
Please cite Rozen, S\&., Skaletsky, H\&. "Primer3 on the WWW for general users and for biologist programmers\&." In S\&. Krawetz and S\&. Misener, eds\&. Bioinformatics Methods and Protocols in the series Methods in Molecular Biology\&. Humana Press, Totowa, NJ, 2000, pages 365\-386\&.
.SH "SEE ALSO"
.PP

\fBprimer3_core\fR(1)
\fBoligotm\fR(1)
.SH "COPYRIGHT"
.br
Copyright \(co 1996,1997,1998,1999,2000,2001,2004,2006,2007,2008 Whitehead Institute for Biomedical Research, Steve Rozen (http://jura.wi.mit.edu/rozen), Helen Skaletsky
.br
.PP
All rights reserved\&. On Debian\-based systems, please consult
/usr/share/doc/primer3/copyright
to read the licence of ntdpal\&.
.PP
This manual page was written by Charles Plessy <plessy@debian\&.org> for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the same terms as oligotm itself\&.

.sp
