'\" t
.\"     Title: OLIGOTM
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 11/30/2011
.\"    Manual: Primer3 User Manuals
.\"    Source: oligotm 1.1.4
.\"  Language: English
.\"
.TH "OLIGOTM" "1" "11/30/2011" "oligotm 1.1.4" "Primer3 User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
oligotm \- Prints oligo\*(Aqs melting temperature on stdout
.SH "SYNOPSIS"
.HP \w'\fBoligotm\fR\ 'u
\fBoligotm\fR [OPTIONS] {oligo}
.PP
where oligo is a DNA sequence of between 2 and 36 bases
.SH "DESCRIPTION"
.PP

\fBoligotm\fR
prints the melting temperature of a given deoxyribonucleotide on the standard output\&. It is part of the oligotm library\&.
.SH "OPTIONS"
.PP
\fB\-mv\fR \fImonovalent_conc\fR
.RS 4
Concentration of monovalent cations in mM, by default 50\ \&mM\&.
.RE
.PP
\fB\-dv\fR \fIdivalent_conc\fR
.RS 4
Concentration of divalent cations in mM, by default 0\ \&mM\&.
.RE
.PP
\fB\-n\fR \fIdNTP_conc\fR
.RS 4
Concentration of deoxynucleotide triphosphate in mM, by default 0\ \&mM\&.
.RE
.PP
\fB\-d\fR \fIdna_conc\fR
.RS 4
Concentration of DNA strands in nM, by default 50\ \&nM\&.
.RE
.PP
\fB\-tp\fR \fI[0|1]\fR
.RS 4
Specifies the table of thermodynamic parameters and the method of melting temperature calculation:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
Breslauer et al\&., 1986 and Rychlik et al\&., 1990 (used by primer3 up to and including release 1\&.1\&.0)\&. This is the default, but
\fInot\fR
the recommended value\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
Use nearest neighbor parameter from SantaLucia 1998\&.
\fIThis is the recommended value\fR\&.
.RE
.RE
.PP
\fB\-sc\fR \fI[0\&.\&.2]\fR
.RS 4
Specifies salt correction formula for the melting temperature calculation:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
Schildkraut and Lifson 1965, used by primer3 up to and including release 1\&.1\&.0\&. This is the default, but
\fInot\fR
the recommended value\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
SantaLucia 1998\&.
\fIThis is the recommended value\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
Owczarzy et al\&., 2004\&.
.RE
.RE
.PP
\fB\-i\fR
.RS 4
prints references to publications which were used for thermodynamic calculations\&.
.RE
.SH "REFERENCE"
.PP
Please cite Rozen, S\&., Skaletsky, H\&. "Primer3 on the WWW for general users and for biologist programmers\&." In S\&. Krawetz and S\&. Misener, eds\&. Bioinformatics Methods and Protocols in the series Methods in Molecular Biology\&. Humana Press, Totowa, NJ, 2000, pages 365\-386\&.
.SH "SEE ALSO"
.PP

\fBprimer3_core\fR(1)
\fBntdpal\fR(1)
.SH "COPYRIGHT"
.br
Copyright \(co 1996,1997,1998,1999,2000,2001,2004,2006,2007,2008 Whitehead Institute for Biomedical Research, Steve Rozen (http://jura.wi.mit.edu/rozen), Helen Skaletsky
.br
.PP
All rights reserved\&. On Debian\-based systems, please consult
/usr/share/doc/primer3/copyright
to read the licence of oligotm\&.
.PP
This manual page was written by Charles Plessy <plessy@debian\&.org> for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the same terms as oligotm itself\&.

.sp
