.\"     Title: PRIMER3_CORE
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/09/2008
.\"    Manual: Primer3 User Manuals
.\"    Source: primer3_core 1.1.4
.\"
.TH "PRIMER3_CORE" "1" "05/09/2008" "primer3_core 1.1.4" "Primer3 User Manuals"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
primer3_core \- Designs primers for PCR
.SH "SYNOPSIS"
.HP 13
\fBprimer3_core\fR [\-format_output] [\-strict_tags] [<\ \fIinput_file\fR]
.SH "DESCRIPTION"
.PP
primer3_core picks primers for PCR reactions, considering as criteria oligonucleotide melting temperature, size, GC content and primer\-dimer possibilities, PCR product size, positional constraints within the source sequence, and miscellaneous other constraints\&.
.PP
By default, primer3_core accepts input and produces output in Boulder\-io format, a pre\-XML text\-based input/output format for program\-to\-program data interchange format\&. The Boulder\-io format and the commands that primer3_core understands are described in the
\fIREADME\fR
file, which on Debian systems can be found in
\fI/usr/share/doc/primer3/\fR\&.
.SH "OPTIONS"
.PP
\fB\-format_output\fR
.RS 4
Prints a more user\-oriented report for each sequence\&.
.RE
.PP
\fB\-strict_tags\fR
.RS 4
primer3_core echoes and ignores any tags it does not recognize, unless the
\fB\-strict_tags\fR
flag is set on the command line, in which case primer3_core prints an error in the PRIMER_ERROR output tag, and prints additional information on stdout; this option can be useful for debugging systems that incorporate primer\&.
.RE
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
Note
.PP
The old flag \-2x_compat is no longer supported\&.
.SH "EXIT STATUS CODES"
.sp
.RS 4
\h'-04'\(bu\h'+03'0 on normal operation\&.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-1 under the following conditions: illegal command\-line arguments, unable to fflush stdout, unable to open (for writing and creating) a \&.for, \&.rev or \&.int file (probably due to a protection problem)\&.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-2 on out\-of\-memory\&.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-3 empty input\&.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-4 error in a "Global" input tag (message in PRIMER_ERROR)\&.
.RE
.SH "REFERENCE"
.PP
Please cite Rozen, S\&., Skaletsky, H\&. "Primer3 on the WWW for general users and for biologist programmers\&." In S\&. Krawetz and S\&. Misener, eds\&. Bioinformatics Methods and Protocols in the series Methods in Molecular Biology\&. Humana Press, Totowa, NJ, 2000, pages 365\-386\&.
.SH "SEE ALSO"
.PP

\fBntdpal\fR(1)
\fBoligotm\fR(1)
.SH "COPYRIGHT"
Copyright \(co 1996,1997,1998,1999,2000,2001,2004,2006,2007,2008 Whitehead Institute for Biomedical Research, Steve Rozen (http://jura.wi.mit.edu/rozen), Helen Skaletsky
.br
.PP
All rights reserved\&. On Debian\-based systems, please consult
\fI/usr/share/doc/primer3/copyright\fR
to read the licence of primer3_core\&.
.PP
This manual page was written by Steffen Moeller
<moeller@debian\&.org>
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the same terms as primer3_core itself\&.

.sp
