.TH SONIC-VISUALISER 1 "Novembre 17, 2010"
.SH NOM
sonic-visualiser \- affichage et analyse des contenus des fichiers audio de musique
.SH SYNOPSIS
.B sonic-visualiser
[\fIoptions\fR] [\fIfile\fR] ...
.SH DESCRIPTION
.B Sonic Visualiser
est un programme pour afficher et explorer les données audio pour de l'analyse
et des annontations de musique sémantique.
.PP
.B Sonic Visualiser
pourrait être utile pour les musicologues, les archivistes, les chercheurs dans
le domaine du traitement de signal, et toute autre personne recherchant un
moyen facile de jeter un oeil sur ce qui se trouve dans un fichier audio.
.PP
Après installatation, l'application est disponible à partir du menu
.B Applications
.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
affiche ce message d'aide et quitte
.TP
\fB\-\-no\-audio\fR
Ne pas essayer d'ouvrir un périphérique de sortie audio.
.TP
\fB\-\-no\-osc\fR
Ne pas fournir de port Open Sound Control pour le contrôle à distance.
.PP
Un, ou plusieurs, fichiers Sonic Visualiser (.sv) et audio peuvent être fournis.
.SH "VOIR ÉGALEMENT"
La documentation complète est disponible en ligne à
<https://www.sonicvisualiser.org/documentation.html>.
.SH "AUTEUR"
sonic-visualisera été écrit par Chris Cannam <cannam@users.sourceforge.net> et
d'autres.
.PP
Cette page de manuel a été écrite par Alessio Treglia <alessio@debian.org>, pour
le projet Debian (mais peut être utilisée par d'autres).
.PP
La version française de cette page de manuel a été traduite par Olivier Humbert
<trebmuh@tuxfamily.org>, pour le projet LibraZiK (mais peut être utilisée par
d'autres).