.TH SONIC-VISUALISER 1 "November 17, 2010"
.SH NAME
sonic-visualiser \- viewing and analysing the contents of music audio files
.SH SYNOPSIS
.B sonic-visualiser
[\fIoptions\fR] [\fIfile\fR] ...
.SH DESCRIPTION
.B Sonic Visualiser
is a program for viewing and exploring audio data for semantic music
analysis and annotation.
.PP
.B Sonic Visualiser
could be of particular interest to musicologists, archivists,
signal-processing researchers and anyone else looking for a friendly way to
take a look at what lies inside the audio file.
.PP
After the installation, the application is available from the
.B Applications
menu.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-no\-audio\fR
Do not attempt to open an audio output device.
.TP
\fB\-\-no\-osc\fR
Do not provide an Open Sound Control port for remote control.
.PP
One or more Sonic Visualiser (.sv) and audio files may be provided.
.SH "SEE ALSO"
The complete documentation is available online at:
.br
.B
http://www.sonicvisualiser.org/documentation.html
.SH "AUTHOR"
sonic-visualiser was written by Chris Cannam <cannam@users.sourceforge.net>
and others.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>,
for the Debian project (but may be used by others).
