'\" t
.\" Man page for wmmon
.\" Copyright (c) 2003  Software in the Public Interest, Inc.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or (at
.\" your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH wmmon 1 "Dec 2019" "WMMON 1.4"

.SH NAME
wmmon \- Window Maker dockapp for monitoring system information

.SH SYNOPSIS

.B wmmon
[
.I OPTION
]

.SH DESCRIPTION

.B WMMon
monitors the realtime CPU load as well as the average system load,
and gives you some nice additional features too. It is intended for
docking in Window Maker.

It currently provides:

.IP \(bu 4
a realtime CPU stress meter;
.IP \(bu
an auto-scaled average system load meter, like
.B xload
and
.BR wmavgload ;
.IP \(bu
hint lines change color as the system load increases.
.RS
.IP \(bu
green for multiples of 1
.IP \(bu
yellow for multiples of 10
.IP \(bu
red for multiples of 100
.RE
.IP \(bu
a realtime disk I/O stress meter;
.IP \(bu
auto-scaled disk I/O load meter;
.IP \(bu
realtime memory and swap usage meters;
.IP \(bu
a display for system uptime;
.IP \(bu
three user-defined commands to launch.

.SH OPTIONS

.TP
.BI \-display \ display
This option specifies the X server to contact; see
.IR X(7x) .

.TP
.BI \-geometry \ geometry
This option specifies the preferred position of window; see
.IR X(7x) .

.TP
.BR \-l
Lock the mode, so that it cannot be cycled by clicking on the upper-left
widget.  You can use this to open multiple copies of
.BR WMMon ,
each set to a different mode.

.TP
.BR \-c
Show average and max CPU usage for SMP machines. This is the default
if there are more than 10 processors.

.TP
.BR \-i
Start in disk I/O mode, which displays instantaneous disk usage and
average disk load.

.TP
.BR \-b
Include buffers and cache in memory usage calculations. The trend in
recent years has been to not include this in memory load monitors, but it
can be useful information.

.TP
.BR \-s
Start in system information mode, which displays memory usage, swap usage,
and uptime.

.TP
.B \-h
Show help information.

.TP
.B \-v
Print the version number.

.SH USAGE
The
.B WMMon
display can be cycled between CPU, disk I/O, and system
information displays by clicking on the upper-left widget.  This
displays CPU information by default.

WMMon can also be used to launch programs.  You may click either left,
middle, or right mouse buttons in the average-load section of the
window.  The pre-configured program will be launched according to the
mouse button clicked.  (see
.B CONFIGURATION FILE
below.)

In order to move
.BR WMMon ,
drag on the outer edges.  These are not sensitive to mouse clicks.

.SH "DOCKING IN WINDOW MANAGERS"

.TP
Window Maker

Window Maker users should drag and drop the
.B WMMon
window on the Dock.  Then, right-click on the border of the window and
select \*(lqSettings...\*(rq.  Check \*(lqStart when Window Maker
is started\*(rq.

.TP
AfterStep

AfterStep users should put the following in their
.I $HOME/.steprc

.RS 16
Wharf wmmon \- MaxSwallow "wmmon" wmmon &
.RE

.TP
Other window managers

.B WMMon
runs nicely as a 64x64 shaped icon on your desktop.

.SH "CONFIGURATION FILE"

.B WMMon
can launch three user-defined commands, triggered by left, middle and
right mouse button clicks.  You can define the commands to launch in
.I $HOME/.wmmonrc

.RS
.PD 0
left: xterm
.PP
middle: xload
.PP
right: xcalc
.PP
.PD
.RE

If
.B WMMon
detects a
.I $HOME/.wmmonrc
file, it will launch the appropriate command when you click on the window.

The system administrator can define default commands in
.IR /etc/wmmonrc .
The administrator may also choose to \*(lqfix\*(rq particular commands,
making it impossible for users to change.  These commands can be defined in
.IR /etc/wmmonrc.fixed ,
although this isn't a nice thing to do.

.SH FILES

.I /etc/wmmonrc
.br
.I $HOME/.wmmonrc
.br
.I /etc/wmmonrc.fixed

.SH AUTHORS

.B WMMon
was written by Martijn Pieterse and Antoine Nulle.

This manual page was written by Simon Law <sfllaw@debian.org> for the
.B Debian
system (but may be used by others), and was modified for WMMon 1.4 by
B. Watson <urchlay@slackware.uk>. It is based on the documentation provided
by the original program.

This manual is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
