#!/bin/sh

# Slackware build script for eaccelerator
# Written by javivf@gmail.com 2008/07/27

APP=eaccelerator
VERSION=0.9.5.3
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$APP
OUTPUT=${OUTPUT:-/tmp}

DOCS="AUTHORS COPYING NEWS README"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
rm -rf $TMP/$APP-$VERSION
cd $TMP || exit 1
tar -xjvf $CWD/$APP-$VERSION.tar.bz2 || exit 1
cd $APP-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
   ./configure \
   --prefix=/usr \
   --libdir=/usr/lib$LIBDIRSUFFIX \
   --sysconfdir=/etc \
   --localstatedir=/var \
   --build=$ARCH-slackware-linux \
  || exit 1

make || exit 1
make install DESTDIR=$PKG || exit 1

install -D -m 755 modules/eaccelerator.so $PKG/usr/lib$LIBDIRSUFFIX/php/extensions/eaccelerator.so || exit 1

mkdir -p $PKG/usr/doc/$APP-$VERSION
cp -a $DOCS $PKG/usr/doc/$APP-$VERSION
find $PKG/usr/doc/$APP-$VERSION -type f -exec chmod 644 {} \;
cat $CWD/$APP.SlackBuild > $PKG/usr/doc/$APP-$VERSION/$APP-SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs \
    strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs \
    strip --strip-unneeded 2> /dev/null
)

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$APP-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
