.TH ZOOM "1" "November 2012" "SlackBuilds.org" "User Commands"
.SH NAME
zoom \- interpreter for interactive fiction games
.SH SYNOPSIS
.B zoom
[\fIOPTION\fR...] [\fIstory-file\fR] [\fIsave-file\fR]
.SH DESCRIPTION
Interactive Fiction is a fancy name for 'text adventures', thought up by
a company called called 'Infocom' circa 1979.
.PP
Zoom is an advanced player for interactive fiction stories written in four major formats:
.SS Z\-Code
The format used by Infocom in the 1980s for games including Zork and Trinity, as well as new games written using the Inform language.
.SS Glulx
A modern language intended to be the successor to Z\-Code.
.SS TADS
A modern language developed by Mike Roberts.
.SS HUGO
A modern language developed by The General Coffee Compnay.
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debugmode\fR
Enable source\-level debugger (requires gameinfo.dbg)
.TP
\fB\-w\fR, \fB\-\-warnings\fR
Display interpreter warnings
.TP
\fB\-W\fR, \fB\-\-fatal\fR
Warnings are fatal
.TP
\fB\-?\fR, \fB\-\-help\fR
Give this help list
.TP
\fB\-\-usage\fR
Give a short usage message
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version
.SH FILES
.TP
\fB/usr/share/zoom/games/\fR
When zoom is called without a story-file argument, it presents a menu of
the games found here, if any.
.TP
\fB/usr/share/zoom/zoomrc\fR
System\-wide config file, mostly for setting fonts and colors.
.TP
\fB$HOME/.zoomrc\fR
Per\-user config file.
.SH "SEE ALSO"
Full documentation is installed in
.nh
\fB/usr/doc/zoom-@VERSION@/manual/index.html\fR
.hy
.SH BUGS
Report bugs to bugs@logicalshift.co.uk.
.SH AUTHOR
Zoom was written by Andrew Hunter
