.TH ZOOM "1" "October 2021" "SlackBuilds.org" "User Commands"
.SH NAME
zoom \- interpreter for Z\-Code interactive fiction games
.SH SYNOPSIS
.B zoom
[\fIOPTION\fR ...] [\fIstory-file\fR] [\fIsave-file\fR]
.SH DESCRIPTION
Interactive Fiction is a fancy name for 'text adventures', thought up by
a company called called 'Infocom' circa 1979.
.PP
Zoom is an advanced player for interactive fiction stories written Z\-Code format.
This is the format used by Infocom in the 1980s for games including Zork and Trinity, as well as new games written using the Inform language.
.B zoom
supports all versions of the Z-Machine, including version 6 with graphical resources (converted to Blorb format).
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debugmode\fR
Enable source\-level debugger (requires gameinfo.dbg).
.TP
\fB\-w\fR, \fB\-\-warnings\fR
Display interpreter warnings
.TP
\fB\-W\fR, \fB\-\-fatal\fR
Make warnings fatal.
.TP
\fB\-?\fR, \fB\-\-help\fR
Give a list of command\-line options.
.TP
\fB\-\-usage\fR
Give a short usage message.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SH FILES
.TP
\fB/usr/share/zoom/games/\fR
When \fBzoom\fR is called without a story-file argument, it presents a menu of
the games found here, if any.
.TP
\fB/etc/zoom/zoomrc\fR
System\-wide config file, mostly for setting fonts and colors. Only
used if \fB$HOME/.zoomrc\fR doesn't exist.
.TP
\fB$HOME/.zoomrc\fR
Per\-user config file. If this file exists, it is used instead of
the system config file, above. So for personalizing your settings, you
will want to start out by copying \fB/etc/zoom/zoomrc\fR to \fB~/.zoomrc\fI.
.PP
Note that it's a \fIfatal error\fR if \fBzoom\fR can't read either of these
config files!
.SH NOTE
If you were expecting to be able to play TADS, HUGO, or Glulx games with
\fBzoom\fR, I hate to disappoint you... but the Linux build of \fBzoom\fR
only supports Z\-Code. The \fIMacintosh\fR (OSX/Cocoa) build does support
the other formats, but the support code would be difficult to port to
Linux \fBzoom\fR. I incorrectly stated that the other formats were
available in a previous version of this man page. Sorry about that.
.SH BUGS
Report bugs to bugs@logicalshift.co.uk.
.PP
There's one "bug" with this man page: it's installed in manual section 1.
It should be section 6 (games), but there's a \fBzoom\fR(6) man page in the
xscreensaver package, and we don't want to conflict with it.
.SH AUTHOR
Zoom was written by Andrew Hunter. See
.nh
\fB/usr/doc/zoom-@VERSION@/COPYING\fR
.hy
for license information.
.PP
This man page was written by B. Watson <yalhcru@gmail.com> for
the SlackBuilds.org project. It's licensed under the WTFPL, so
do WTF you want with it.
.SH "SEE ALSO"
\fBzork\fR(6), \fBfrotz\fR(6), \fBfizmo\fR(6), \fBinform\fR(6).
.PP
Full documentation is installed in
.nh
\fB/usr/doc/zoom-@VERSION@/manual/index.html\fR
.hy
