#!/bin/sh

# Slackware build script for libvmime-zarada:
# a library for working with MIME messages
# (with patches from zarafa)

# Written by Niels Horn - niels.horn@gmail.com
# revision date 2009/12/17

PRGNAM=libvmime-zarafa
PRGSRC=libvmime
VERSION=0.7.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $TMP/$PRGSRC-$VERSION $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar xvf $CWD/$PRGSRC-$VERSION.tar.bz2
cd $PRGSRC-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Apply zarafa patches in order of release-date
for patch in $(ls -rt $CWD/zarafa-patches/vmime*.diff); do
  patch -p1 < $patch
done

# Patch "configure" so that it respects CFLAGS / CXXFLAGS
patch -p1 < $CWD/patches/flags.patch
# Patch "configure" & src/Makefile.in to rename the library to "libvmime-zarafa"
patch -p1 < $CWD/patches/name.patch

CFLAGS=$SLKCFLAGS \
CXXFLAGS=$SLKCFLAGS \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --localstatedir=/var \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

make docdir=/usr/doc/$PRGNAM-$VERSION
make install docdir=/usr/doc/$PRGNAM-$VERSION DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
)

# correct program name.
# We're moving some files so that this special version of libvmime
# can coexist with the standard version, if needed.
mkdir -p $PKG/usr/include/vmime-zarafa
mv $PKG/usr/include/vmime $PKG/usr/include/vmime-zarafa

mv $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/vmime.pc \
   $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/vmime-zarafa.pc
sed -i "s/vmime/vmime-zarafa/g" \
   $PKG/usr/lib${LIBDIRSUFFIX}/pkgconfig/vmime-zarafa.pc

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
