#!/bin/sh

# Slackware build script for hatari

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://sam.zoy.org/wtfpl/ for details.

PRGNAM=hatari
VERSION=${VERSION-1.7.0}
BUILD=${BUILD-1}
TAG=${TAG-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
else
  SLKCFLAGS="-O2"
fi

set -e

rm -rf $PKG $TMP/$PRGNAM-$VERSION
mkdir -p $PKG $PKG/install $PKG/etc/$PRGNAM

# configure script is really a wrapper for cmake, doesn't support
# --libdir, --mandir, --docdir. We'll just move everything where it
# goes after the 'make install'. (If there were shared libs to deal
# with, this likely wouldn't be good enough)

cd $TMP
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
./configure --prefix=/usr

make
make install/strip DESTDIR=$PKG

# amazingly, the man pages are already gzipped (but in the wrong place)
mv $PKG/usr/share/man $PKG/usr/man

# Also, the docs are in the wrong place:
WRONGDOCDIR=$PKG/usr/share/doc/$PRGNAM
DOCDIR=$PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $DOCDIR
mv $WRONGDOCDIR/* $DOCDIR
rmdir $WRONGDOCDIR

# However, the doc location is hardcoded in the UI. This works
# because /usr/share/doc is really a symlink to /usr/doc on Slackware.
ln -s $PRGNAM-$VERSION $PKG/usr/doc/$PRGNAM

cat $CWD/$PRGNAM.SlackBuild > $DOCDIR/$PRGNAM.SlackBuild

# these docs don't get installed for some reason:
cp tools/hmsa/readme-hmsa.txt readme.txt gpl.txt $DOCDIR

# Make sure hatariui shows up in desktop menu:
echo 'Categories=Game;Emulator;' >> $PKG/usr/share/applications/${PRGNAM}ui.desktop

( cd $PKG/usr/share/$PRGNAM && mv tos.img emutos.img && ln -s emutos.img tos.img )

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh  > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
