#!/bin/sh

# Slackware build script for pekwm
# Written by Vasilis Papavasileiou <el03020 at mail dot ntua dot gr>
# Modified by the SlackBuilds.org project
# (assumed to be in the public domain per our submission policy)

PRGNAM=pekwm
VERSION=0.1.5
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Sorry, no COPYING or LICENSE files in source
DOCS="README AUTHORS ChangeLog INSTALL NEWS TODO"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
rm -rf $PRGNAM-$VERSION
tar -xjvf $CWD/$PRGNAM-$VERSION.tar.bz2 || exit 1
cd $PRGNAM-$VERSION || exit 1
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# for xft-config (not necessary)
PATH=$PATH:/usr/X11/bin

CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/usr/share \
  || exit 1

make || exit 1
make install DESTDIR=$PKG || exit 1

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

# Add xinitrc.pekwm so that pekwm will show up as an option in xwmconfig
install -D -m 0755 $CWD/xinitrc.pekwm $PKG/etc/X11/xinit/xinitrc.pekwm

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
