#!/bin/sh

# Slackware build script for lv2file

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20141021 bkw:
# update for 0.84, get rid of argtable patch as it's no longer needed.

PRGNAM=lv2file
VERSION=${VERSION:-0.84}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

# The man page is in the debian archive, which might be an older
# version than the release. For 0.84, the 0.83 man page is still valid.
MANVER=0.83

# download file has different name depending whether the Content-Disposition
# header is honored.
[ -e $CWD/$PRGNAM-upstream-$VERSION.tar.gz ] && \
  mv $CWD/$PRGNAM-upstream-$VERSION.tar.gz $CWD/$VERSION.tar.gz

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-upstream-$VERSION
tar xvf $CWD/$VERSION.tar.gz
cd $PRGNAM-upstream-$VERSION
chown -R root:root .

# egregious permissions, instead of find/chown do this:
chmod 755 .
chmod 644 *

if [ "${FORCE_SLACK_FLAGS:-no}" = "yes" ]; then
  sed -i "s/-O3/$SLKCFLAGS/" Makefile
else
  sed -i "s/-O3/-O3 -fPIC/" Makefile
fi

make
strip $PRGNAM
make install DESTDIR=$PKG

# Use the debian man page (which is actually by the lv2file author,
# I dunno why it's not in the lv2file source distrib to begin with)
tar xvf $CWD/${PRGNAM}_$MANVER-1.debian.tar.gz debian/$PRGNAM.1
mkdir -p $PKG/usr/man/man1
gzip -9c < debian/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
