# POD source for lsX man page. Convert with:
# pod2man --stderr -s1 -c"Suckless.org Tools" -r0.1 lsx.pod > lsx.1

=pod

=head1 NAME

B<lsX> - List executables in one or more directory trees.

=head1 SYNOPSIS

B<lsX> [dir] {[dir] ...}

=head1 DESCRIPTION

B<lsX> lists the executables in the given directories, non-recursively.
Non-directory arguments are ignored. If no arguments are given, B<lsX>
exits without doing anything.

B<lsX> always exits with zero status.

=head1 OPTIONS

B<-v> prints the version number and exits.

=head1 NOTES

When using B<lsX> with multiple directory arguments, the 2nd and any
further directories must be absolute paths (this counts as a bug).

B<lsX> may also be installed as B<lsx>. The name change is to avoid
conflicting with the B<lsx> symlink included in Slackware's minicom
package. If minicom isn't installed, B</usr/bin/lsx> will be a
symlink to B<lsX>.

=head1 AUTHORS

B<lsX> was written by Anselm R. Garbe (garbeam at gmail dot com) and
Sander van Dijk (a dot h dot vandijk at gmail dot com).

This man page written by B. Watson for the SlackBuilds.org project. It
may be used by anyone.
=cut
