# POD source for sselp man page. Convert with:
# pod2man --stderr -s1 -c"Suckless.org Tools" -r0.1 sselp.pod > sselp.1

=pod

=head1 NAME

B<sselp> - Simple X selection printer.

=head1 SYNOPSIS

B<sselp>

=head1 DESCRIPTION

B<sselp> prints the X selection to stdout. If there is no X client owning
the selection it just exits. Useful for scripts where you can query the
X selection without pressing mouse Button2 in cumbersome ways.

B<sselp> always exits with zero status.

=head1 OPTIONS

B<-v> prints the version number and exits.

=head1 ENVIRONMENT

B<DISPLAY> - used in the usual way.

=head1 AUTHORS

B<wmname> was written by Anselm R. Garbe (garbeam at gmail dot com).

This man page written by B. Watson for the SlackBuilds.org project. It
may be used by anyone.
=cut
