# POD source for ssid man page. Convert with:
# pod2man --stderr -s1 -c"Suckless.org Tools" -r0.1 ssid.pod > ssid.1

=pod

=head1 NAME

B<ssid> - Simple setsid replacement.

=head1 SYNOPSIS

B<ssid> [-v] cmd [arg ...]

=head1 DESCRIPTION

B<ssid> runs a program in a new session.

=head1 OPTIONS

B<-v> prints the version number and exits.

=head1 SEE ALSO

setsid(2)

setsid(1)

=head1 AUTHORS

B<ssid> was written by Anselm R. Garbe (garbeam at gmail dot com).

This man page written by B. Watson for the SlackBuilds.org project. It
may be used by anyone.
=cut
