# POD source for swarp man page. Convert with:
# pod2man --stderr -s1 -c"Suckless.org Tools" -r0.1 swarp.pod > swarp.1

=pod

=head1 NAME

B<swarp> - simple pointer warp

=head1 SYNOPSIS

B<swarp> [x] [y]

B<swarp> -v

=head1 DESCRIPTION

B<swarp> is a generic pointer warping utility for X. Example:

# B<swarp 100 100>

will warp the pointer to (100, 100) on your screen.

=head1 OPTIONS

B<-v> prints the version number and exits.

=head1 ENVIRONMENT

B<DISPLAY> - used in the usual way.

=head1 AUTHORS

B<ssid> was written by Anselm R. Garbe (garbeam at gmail dot com)
and Sander van Dijk (a dot h dot vandijk at gmail dot com).

This man page written by B. Watson for the SlackBuilds.org project. It
may be used by anyone.
=cut
