#!/bin/bash

# Slackware build script for sage-bin

# Copyright 2018 Duncan Roe, Melbourne, Australia
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=sage-bin
VERSION=${VERSION:-9.4}
DEBVERSION=${DEBVERSION:-11}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
SLK_VERSION=${SLK_VERSION:-$(cat /etc/slackware-version|cut -d' ' -f2)}
[ $SLK_VERSION = 14.2 ] && PYTHON=python || PYTHON=python2

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i686 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" != "x86_64" ] && [ "$ARCH" != "i686" ]; then
  echo "Architecture $ARCH is not supported" >&2
  exit 1
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $PKG
mkdir root proc opt
tar xvf $CWD/sage-$VERSION-Debian_GNU_Linux_$DEBVERSION-$ARCH.tar.bz2 -C $PKG/opt
[ ! -r $CWD/$VERSION.patch ] || patch -p0 < $CWD/$VERSION.patch
[ ! -r $CWD/${VERSION}_sh ] || . $CWD/${VERSION}_sh
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkchroot .
addchroot . $PYTHON sed util-linux
chroot . <<////
export SAGE_BANNER=bare
mount -t proc proc proc
opt/SageMath/sage < /dev/null # Run sage patch system
umount proc
exit
////

# Remove mkchroot leftovers
rm -rf Tools bin dev etc lib64 proc root sbin usr
# and other junk
rm -rf $PKG/opt/SageMath/.git

mkdir -p $PKG/etc/profile.d
install -D -m0755 $CWD/profile.d/sage.sh  $PKG/etc/profile.d
install -D -m0755 $CWD/profile.d/sage.csh $PKG/etc/profile.d

mkdir -p $PKG/usr/share/texmf/tex/latex
ln -sf /opt/SageMath/local/share/texmf/tex/latex/sagetex $PKG/usr/share/texmf/tex/latex

mkdir -p $PKG/usr/share/applications
for d in $PKG/opt/SageMath/local/share/applications/*.desktop ; do
  ln -sf /opt/SageMath/local/share/applications/$(basename $d) $PKG/usr/share/applications
done

for res in 16x16 32x32 64x64 128x128 ; do
  mkdir -p $PKG/usr/share/icons/hicolor/$res/{apps,mimetypes}
  ln -sf /opt/SageMath/local/share/icons/hicolor/$res/xcas.png \
    $PKG/usr/share/icons/hicolor/$res/apps
  ln -sf /opt/SageMath/local/share/icons/hicolor/$res/application-x-xcas.png \
    $PKG/usr/share/icons/hicolor/$res/mimetypes
done

# Some man pages and their symlinks are already gzipped
find $PKG/opt/SageMath/local/share/man -type f ! -name '*.gz' -exec gzip -9 {} \;
for i in $( find $PKG/opt/SageMath/local/share/man -type l ! -name '*.gz' ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a opt/SageMath/*.{md,txt} $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
