#!/bin/sh

# Slackware build script for avidemux

# Copyright 2007  Adnan Hodzic <AbsintheSyringe@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Modified by Niklas "Nille" Åkerström to use cmake since thats what the
# project will use in the future.   No additional license terms added

PRGNAM=avidemux
VERSION=${VERSION:-2.5.6}
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/${PRGNAM}_${VERSION}.tar.gz
mv ${PRGNAM}_${VERSION} $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

if [ "$ARCH" = "x86_64" ]; then
  # Some paths are incorrectly hardcoded to "lib":
  sed -i -e "s/Dir=\"lib\"/Dir=\"lib${LIBDIRSUFFIX}\"/" $(grep -lr 'Dir="lib"' .)
fi

# Cut away jobs number from the MAKEFLAGS
MAKEFLAGS=$(echo "$MAKEFLAGS" | sed "s/-j[0-999]//g")

mkdir build
cd build

  CFLAGS="$SLKCFLAGS" \
  CXXFLAGS="$SLKCFLAGS" \
  cmake . \
    -DCMAKE_INSTALL_PREFIX:STRING="/usr" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL="TRUE" \
    -DLIB_SUFFIX:STRING="$LIBDIRSUFFIX" ..

# Here are some valid options for cmake to build or not build against a dep
# (for those who aren't very familiar with cmake)
# Note that none of them should be needed though, as cmake automatically
# detects what is and isn't on the system.
# They're all boolean values, so it uses TRUE 1 YES or FALSE 0 NO
# (TRUE, 1, and YES all mean the same thing and you should only use one of them)
#	alsa || -DNO_ALSA:BOOL=
#	oss || -DNO_OSS:BOOL=
#	nls || -DNO_NLS:BOOL=
#	sdl || -DNO_SDL:BOOL=
#	fontconfig || -DNO_FontConfig:BOOL=
#	xv || -DNO_Xvideo:BOOL=
#	esd || -DNO_Esd:BOOL=
#	jack || -DNO_Jack:BOOL=
#	aften || -DNO_Aften:BOOL=
#	libsamplerate || -DNO_libsamplerate:BOOL=
#	lame || -DNO_Lame:BOOL=
#	faac -DNO_FAAC:BOOL=
#	xvid || -DNO_Xvid:BOOL=
#	amrnb || -DNO_AMRNB:BOOL=
#	dts || -DNO_libdca:BOOL=
#	x264 || -DNO_x264:BOOL=
#	aac || -DNO_FAAD:BOOL=
#	aac || -DNO_NeAAC:BOOL=
#	vorbis || -DNO_Vorbis:BOOL=
#	png || -DNO_libPNG:BOOL=
#	arts || -DNO_ARTS:BOOL=
#	truetype || -DNO_FREETYPE:BOOL=
#	gtk || -DNO_GTK:BOOL=
#	qt4 || -DNO_QT4:BOOL=

  make -j1
  make DESTDIR=$PKG install/strip
cd ..

mkdir -p build_plugins
cd build_plugins
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DMAN_INSTALL_DIR=/usr/man \
    -DSYSCONF_INSTALL_DIR=/etc \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DAVIDEMUX_SOURCE_DIR=$(cd .. ; pwd) \
    -DAVIDEMUX_CORECONFIG_DIR=$(cd .. ; pwd)/build/config \
    -DAVIDEMUX_INSTALL_PREFIX=$(cd .. ; pwd)/build \
    ../plugins
  make -j1
  make DESTDIR=$PKG install/strip
cd -

mkdir -p $PKG/usr/man/man1
cat man/avidemux.1 | gzip -9c > $PKG/usr/man/man1/avidemux.1.gz

cd $TMP/$PRGNAM-$VERSION
mkdir -p $PKG/usr/share/{applications,pixmaps}
mkdir -p $PKG/usr/share/icons/hicolor/{16x16,32x32,48x48,64x64}/apps
# If the qt4 binary was built, we prefer to use that over the gtk version:
if [ -x $PKG/usr/bin/avidemux2_qt4 ]; then
  cat avidemux2.desktop | sed -e 's/_gtk/_qt4/' \
    > $PKG/usr/share/applications/avidemux2.desktop
else
  install -m644 avidemux2.desktop $PKG/usr/share/applications/avidemux2.desktop
fi
install -m644 avidemux_icon.png $PKG/usr/share/pixmaps/avidemux.png
install -m644 avidemux_icon.png \
  ${PKG}/usr/share/icons/hicolor/64x64/apps/avidemux.png
convert avidemux_icon.png -resize 16x16 \
  ${PKG}/usr/share/icons/hicolor/16x16/apps/avidemux.png
convert avidemux_icon.png -resize 32x32 \
  ${PKG}/usr/share/icons/hicolor/32x32/apps/avidemux.png
convert avidemux_icon.png -resize 48x48 \
  ${PKG}/usr/share/icons/hicolor/48x48/apps/avidemux.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS COPYING README TODO \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

