#!/bin/sh

# Slackware build script for avidemux

# Copyright 2007  Adnan Hodzic <AbsintheSyringe@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Modified by Niklas "Nille" Åkerström to use cmake since thats what the
# project will use in the future.   No additional license terms added
# Modified by the SlackBuilds.org project

PRGNAM=avidemux
VERSION=${VERSION:-2.6.8}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

# Following upstream, by default the qt4 and the cli versions are built
if [ "${GTK:-no}" = "no" ]; then gtk="out"; else gtk=""; fi
if [ "${QT4:-yes}" = "yes" ]; then qt4=""; else qt4="out"; fi
if [ "${CLI:-yes}" = "yes" ]; then cli=""; else cli="out"; fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf ${PRGNAM}_$VERSION
tar xvf $CWD/${PRGNAM}_$VERSION.tar.gz
cd ${PRGNAM}_$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Cut away jobs number from the MAKEFLAGS and log to stdout
MAKEFLAGS=$(echo "$MAKEFLAGS" | sed "s/-j[0-999]//g")
sed -i -e "s|-j\ 2|-j 1|" -e "s|>&.*||" bootStrap.bash

export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"
bash bootStrap.bash \
  --with-core \
  --with-plugins \
  --with${gtk}-gtk \
  --with${qt4}-qt4 \
  --with${cli}-cli

mv install/* $PKG/

mkdir -p $PKG/usr/man/man1
cat man/avidemux.1 | gzip -9c > $PKG/usr/man/man1/avidemux.1.gz

mkdir -p \
  $PKG/usr/share/applications \
  $PKG/usr/share/pixmaps \
  $PKG/usr/share/icons/hicolor/16x16/apps \
  $PKG/usr/share/icons/hicolor/32x32/apps \
  $PKG/usr/share/icons/hicolor/48x48/apps \
  $PKG/usr/share/icons/hicolor/64x64/apps
if [ -x $PKG/usr/bin/avidemux3_gtk ]; then
  cat avidemux2.desktop | sed -e "s/2_gtk/3_qt4/" -e "s/avidemux2$/avidemux_qt/" \
    > $PKG/usr/share/applications/avidemux_qt.desktop
fi
if [ -x $PKG/usr/bin/avidemux3_qt4 ]; then
  cat avidemux2.desktop | sed -e "s/2_gtk/3_gtk/" -e "s/avidemux2$/avidemux_gtk/" \
    > $PKG/usr/share/applications/avidemux_gtk.desktop
fi
install -m644 avidemux_icon.png $PKG/usr/share/pixmaps/avidemux.png
install -m644 avidemux_icon.png \
  $PKG/usr/share/icons/hicolor/64x64/apps/avidemux.png
convert avidemux_icon.png -resize 16x16 \
  $PKG/usr/share/icons/hicolor/16x16/apps/avidemux.png
convert avidemux_icon.png -resize 32x32 \
  $PKG/usr/share/icons/hicolor/32x32/apps/avidemux.png
convert avidemux_icon.png -resize 48x48 \
  $PKG/usr/share/icons/hicolor/48x48/apps/avidemux.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS COPYING README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
