.\" This file modified from the Debian version by B. Watson <yalhcru@gmail.com>
.TH PICO2WAVE "1" "June 2018" "pico2wave" "SlackBuilds.org"
.SH NAME
pico2wave \- Small Footprint TTS
.SH SYNOPSIS
.B pico2wave
\fB-w\fR
\fI<filename.wav>\fR
[ \fB-l\fR \fI<language>\fR ]
[ \fI<words>\fR ]
.SH DESCRIPTION
.B pico2wave
is a small footprint Text to Speech utility, using the SVOX Pico
engine \fB[*]\fR. It converts
text given on the command line (or standard input, if no
\fI<words>\fR on command line) to audible speech, and writes
to a RIFF .wav file.
.PP
The generated wav files are PCM, 16-bit mono, 16KHz sampling rate.
.PP
\fB[*]\fR The SVOX Pico engine is a software speech synthesizer for German, English
(GB and US), Spanish, French and Italian. SVOX produces a clear and
distinct speech output made possible by the use of Hidden Markov Model
(HMM) algorithms.
.SH OPTIONS
.TP
\fB\-w\fR, \fB\-\-wave\fR=\fIfilename\fR.wav
Write output to this WAV file (extension SHOULD
be .wav). This option is required: \fBpico2wave\fR
cannot write to standard output (not even if you
use \fB-w /dev/stdout\fR, sorry). If the file
already exists, it will be \fBoverwritten\fR with no
confirmation or warning.
.TP
\fB\-l\fR, \fB\-\-lang\fR=\fIlang\fR
Language (default: \fBen\-US\fR). The languages supported are
currently \fBde\-DE\fR, \fBen\-GB\fR, \fBen\-US\fR,
\fBes\-ES\fR, \fBfr\-FR\fR, \fBit\-IT\fR.
.SS "Help options:"
.TP
\-?, \fB\-\-help\fR
Show help message
.TP
\fB\-\-usage\fR
Display brief usage message
.SH EXAMPLES
.TP
.B
pico2wav -w test.wav 'Hello, world.'
.PP
Creates a file \fBtest.wav\fR containing the words "Hello, world."
.TP
.B
echo 'Hello, world.' | pico2wav -w test.wav
.PP
Same as above, reading from standard input.
.TP
.B
pico2wav -w test.wav < gettysburg_address.txt
.PP
Convert an entire text file to speech.
