.TH ODAMEX "6" "December 2011" "SlackBuilds.org" "Games"
.SH NAME
odamex \- Source port of Doom engine, with client/server multiplayer.
.SH SYNOPSIS
.B odamex
[\fIoptions...\fR]
.P
.B odasrv
[\fIoptions...\fR]
.P
.B odalaunch
.SH DESCRIPTION
Odamex (Online Doom Multiplayer Experience) is a modification of DOOM
to allow players to compete with each other over the Internet using the
client/server architecture.
.P
\fBodamex\fR is the client, also used for single\-player games.
.P
\fBodasrv\fR is the dedicated server (which runs in a tty).
.P
\fBodalaunch\fR is the server browser, used for finding multiplayer games
on the 'net. It launches \fBodamex\fR with appropriate arguments.
.P
\fBodamex\fR is a source port of the Doom engine. It requires the data (aka WAD)
file from one or more of the supported games. See \fBWAD FILES\fR, below, for a full
explanation.
.SH OPTIONS
.SS File Options
.TP
\fB\-iwad\fR \fI<wadfile>\fR
The IWAD file to use (in other words, which game to play). The filename extension
\fI.wad\fR or \fI.WAD\fR is not required, and the name is case\-insensitive. See
\fBWAD FILES\fR, below, for more information.
.TP
\fB\-waddir\fR
Colon\-separated list of directories to search for WAD files, including the IWAD. See
\fBWAD FILES\fR, below, for more information.
.TP
\fB\-file\fR \fI<wadfile>\fR
Add a PWAD (patch WAD). Used for custom levels, music, etc. Does NOT work
if using the shareware IWAD (doom1.wad).
.TP
\fB\-config\fR \fI<configfile>\fR
Use \fIconfigfile\fR instead of the default config file (which is
\fI~/.odamex/odamex.cfg\fR).
.TP
\fB\-confile\fR \fI<scriptfile>\fR
Execute the console commands in \fIscriptfile\fR at startup.
.TP
\fB\-deh\fR \fI<dehacked-file>\fR
Load a .deh file. Used for game mods.
.TP
\fB\-bex\fR \fI<bex-file>\fR
Load a .bex file. Used for game mods.
.SS Game Options
.TP
\fB\-warp\fR \fI<level>\fR
Skip the intro, start the game at the given level. For Doom I and its variants,
the level is given as a 2\-digit number (episode and map, e.g. \fB21\fR for
episode 2, map 1). For Doom II and variants,
the level is just the level number.
.TP
\fB\-nomonsters\fR
Self\-explanatory. Usually used for multiplayer deathmatch games.
.TP
\fB\-timer\fR \fI<minutes>\fR
Force levels to end after specified number of minutes.
.TP
\fB\-avg\fR
"Austin Virtual Gaming" mode, equivalent to \fB\-timer 20\fR.
.TP
\fB\-fast\fR
Fast monster mode (similar to "Nightmare" difficulty level).
.TP
\fB\-respawn\fR
Monsters respawn after being killed (similar to "Nightmare" difficulty level).
.TP
\fB\-skill\fR \fI<skill-level>\fR
Set skill level (useful with \fB\-warp\fR). Level is a number from 1 to 5, where
1 is "I'm Too Young To Die" and 5 is "Nightmare".
.SS Video/Audio Options
.TP
\fB\-width\fR \fI<pixels>\fR, \fB\-height\fR \fI<pixels>\fR
Set video mode.
.TP
\fB\-novideo\fR, \fB\-nosound\fR, \fB\-nomusic\fR, \fB\-nomouse\fR
Disable various features.
.SS Network Options
.TP
\fB\-port\fR \fI<port>\fR
Set the UDP port to use for netplay. Default is 10667.
.TP
\fB\-connect\fR \fI<server>\fR
Connect to netplay server \fIserver\fR on startup.
.TP
\fB\-maxclients\fR \fI<count>\fR
Set maximum number of allowed clients for dedicated server.
.SS Demo Options
.TP
\fB\-record \fI<demoname>\fR
Record a single\-player demo.
.TP
\fB\-playdemo \fI<demoname>\fR
Play a previously\-recorded single\-player demo.
.TP
\fB\-netrecord \fI<demoname>\fR
Record a network demo.
.TP
\fB\-netplay \fI<demoname>\fR
Play a previously\-recorded network demo.
.SS Undocumented Options
.TP
\fB\-heapsize \fI<size>\fR
Set the heap size. Not obvious what this is good for.
.TP
\fB\-devparm\fR
???
.TP
\fB\-blockmap\fR
???
.TP
\fB\-stepmode\fR
???
.TP
\fB\-bits\fR
???
.TP
\fB\-fork\fR
???
.SH WAD FILES
\fBodamex\fR (and Doom\-related games in general) load all game resources
such as graphics, sound, and levels from a file known as an IWAD file.
.P
\fBodamex\fR supports the following IWAD files:
.P
.TP
\fBdoom2f.wad\fR, \fBdoom2.wad\fR
Doom II v1.9
.TP
\fBplutonia.wad\fR
Final Doom: The Plutonia Experiment v1.9
.TP
\fBtnt.wad\fR
Final Doom: TNT Evilution Experiment v1.9
.TP
\fBdoomu.wad\fR, \fBdoom.wad\fR
Ultimate Doom v1.9
.TP
\fBdoom1.wad\fR
Shareware Doom v1.9
.TP
\fBfreedoom.wad\fR, \fBfreedm.wad\fR
FreeDoom v0.6.2
.TP
\fBchex.wad\fR
Chex Quest
.P
If no \-iwad argument is given, \fBodamex\fR looks for each IWAD file
in the order listed above, and uses the first one found.
If \-iwad is given, \fBodamex\fR looks only for the named IWAD file. In
either case,
the WAD filenames
can be in all\-lowercase or all\-uppercase.
.P
\fBodamex\fR also requires the file \fBodamex.wad\fR, which is part of \fBodamex\fR
and is installed with it. This file must be found at runtime, or the application
will abort.
.P
When searching for WAD files (odamex.wad, the IWAD, or a PWAD for the \-file option),
\fBodamex\fR searches the following directories, in order:
.P
The current directory.
.br
The argument of the \-waddir option, if given.
.br
The path(s) listed in the \fBDOOMWADDIR\fR environment variable.
.br
The path(s) listed in the \fBDOOMWADPATH\fR environment variable.
.br
The user's home directory.
.br
The contents of the \fBwaddirs\fR cvar.
.br
The hard\-coded path \fB/usr/share/games/doom\fR.
.P
\-waddir, the waddirs cvar, DOOMWADDIR, and DOOMWADPATH are colon\-separated
lists of directories.
.SH OTHER FILES
.TP
\fB~/.odamex/\fR
Config file \fBodamex.cfg\fR is located here. Will be created if it
doesn't already exist. Also, saved games and recorded demos are stored here.
.SH ENVIRONMENT
.TP
\fBDOOMWADDIR\fR, \fBDOOMWADPATH\fR
Colon\-separated lists of directories to search for WAD files.
.TP
\fBHOME\fR
WAD files are also searched for here.
\fB
.TP
\fBSDL_VIDEODRIVER\fR, \fBSDL_AUDIODRIVER\fR
See the SDL documentation for use of these.
.SH AUTHORS
Dean "deathz0r" Joseph
.br
Alex "AlexMax" Mayfield
.br
Ralph "Ralphis" Vickers
.P
This man page written by B. Watson for the SlackBuilds.org project,
but it may be freely used by anyone for any purpose.
