#!/bin/sh

# Slackware build script for bitmapfont2ttf

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# The source tarball contains code from 3 git repositories:
# https://github.com/dse/bitmapfont2ttf
# https://github.com/dse/exact-autotrace
# https://github.com/wernsey/bitmap.git
# ...plus some minor fixes by me to get exact-autotrace to compile.

PRGNAM=bitmapfont2ttf
VERSION=${VERSION:-20200215_03529d2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# 20200621 bkw: the fonts produced by some tools (notably psf2bdf)
# are missing the PIXEL_SIZE property. Patched code derives it from the
# ascent and descent properties, if necessary. This isn't always correct,
# but for the 670 fonts in /usr/share/fonts/misc (converted to BDF),
# it's correct for 654 (98%) of them.
if [ "${PRISTINE:-no}" != "yes" ]; then
  patch -p1 < $CWD/derive_pixel_size.diff
  PATCHDESC=" This package includes a patch for fonts without PIXEL_SIZE."
fi

make -C exact-autotrace CFLAGS="$SLKCFLAGS"
strip exact-autotrace/bin/exact-autotrace-c
mkdir -p $PKG/usr/bin
install -m0755 exact-autotrace/bin/* bin/$PRGNAM $PKG/usr/bin

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README.md exact-autotrace/LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
sed "16s/$/$PATCHDESC/" $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
