#!/bin/sh

# Slackware build script for sunpinyin

# Written by Grissiom <chaos.proton@gmail.com>

PRGNAM=libsunpinyin
VERSION=${VERSION:-2.0.3}
LMVER=${LMVER:-20120212}
DIVER=${DIVER:-20120830}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf sunpinyin-$VERSION
tar xvf $CWD/sunpinyin-$VERSION.tar.gz
cd sunpinyin-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fix building with gcc-4.7.x
patch -p1 < $CWD/gcc47.patch

# The dictionary and language model files are renamed with dates and the olds deleted
# Fix this so it won't break build
sed -i \
  -e "s|open-gram.*|ponce.cc/slackware/sources/repo/open-gram|" \
  -e "s|arpa\.tar|arpa-${LMVER}.tar|" \
  -e "s|utf8\.tar|utf8-${DIVER}.tar|" \
  raw/Makefile
cp -a $CWD/{lm_sc.t3g.arpa-${LMVER},dict.utf8-${DIVER}}.tar.bz2 raw/ || true

export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"
scons --prefix=/usr --libdir=/usr/lib$LIBDIRSUFFIX --libdatadir=/usr/lib$LIBDIRSUFFIX
scons install --prefix=/usr --install-sandbox=$PKG --libdir=/usr/lib$LIBDIRSUFFIX --libdatadir=/usr/lib$LIBDIRSUFFIX

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  AUTHORS ChangeLog COPYING LGPL.LICENSE NEWS OPENSOLARIS.LICENSE README TODO \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
