#!/bin/bash

INTERVAL="hourly"
RSNAPSHOT="/usr/bin/rsnapshot"
MOUNTPOINT="/backup"
LOGFILE="/var/log/rsnapshot"
PIDFILE="/var/run/rsnapshot.pid"

# Check to make sure rsnapshot isn't currently running

if [[ -f "$PIDFILE" ]]; then
   echo "$PIDFILE already exists, skipping "$INTERVAL" run" >> "$LOGFILE"
   exit
fi

# remount filesystem read/write
mount -o remount,rw "$MOUNTPOINT"

# call rsnapshot
"$RSNAPSHOT" "$INTERVAL"

# remount filesystem read-only
mount -o remount,ro "$MOUNTPOINT"
