#!/bin/sh -eu

# Slackware build script for dstat
# Written by Erik Hanson  erik@slackbuilds.org

PRGNAM=dstat
VERSION=0.6.9
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

make install DESTDIR=$PKG

# We want the examples and the man page.
rm -f examples/dstat.py # broken symlink
mkdir -p $PKG/usr/{man/man1,share/dstat/examples}
install -Dp -m0755 examples/*.py $PKG/usr/share/dstat/examples/
install -Dp -m0644 docs/dstat.1 $PKG/usr/man/man1/dstat.1
gzip -9 $PKG/usr/man/man1/dstat.1
rm -rf $PKG/usr/share/man

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -a AUTHORS COPYING ChangeLog LINKS README TODO WISHLIST \
  docs/*.html docs/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
