#!/bin/sh
 
# SlackBuild script for yaz
# Written by Michiel van Wessem (BP{k}) <michiel.van.wessem@gmail.com
# Modified by the SlackBuilds.org project

set -e

PRGNAM=yaz
VERSION=2.1.54
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
ARCH=${ARCH:-i486}
OUTPUT=${OUTPUT:-/tmp}

DOCFILES="LICENSE NEWS README TODO ChangeLog"

if [ "$ARCH" = "i486" ]; then
    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
rm -rf $TMP/$PRGNAM-$VERSION
cd $TMP
tar -xzvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure --prefix=/usr \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --program-prefix="" \
  --program-suffix="" \
  --disable-debug

make
make install-strip DESTDIR=$PKG 

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION 
cp -a $DOCFILES $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/usr/share/doc/yaz $PKG/usr/doc/$PRGNAM-$VERSION/html
rm -rf $PKG/usr/share/doc
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
find $PKG/usr/doc/$PRGNAM-$VERSION -type f -exec chmod 644 {} \;

mkdir $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
