#!/bin/sh

# Slackware build script for zulu-openjdk-lts

# Copyright (c) 2018, Sébastien Ballet <slacker6896 at gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=zulu-openjdk-lts
VERSION=${VERSION:-11.0.1}

# SRCNAM is the name (without extension) of the source archive and
# of the top directory in that archive.
#
SRCNAM=zulu11.2.3-jdk11.0.1-linux_x64

BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

ARCH=${ARCH:-$(uname -m)}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=${TMP}/package-${PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

if [ ! "${ARCH}" = "x86_64" ] ; then
  echo "Architecture ${ARCH} is not supported."
  exit 1
fi

set -e

rm -rf ${PKG}
mkdir -p ${TMP} ${PKG} ${OUTPUT}

mkdir -p ${PKG}/usr/lib64/
cd ${PKG}/usr/lib64/
tar xvf ${CWD}/${SRCNAM}.tar.gz
mv ${SRCNAM} ${PRGNAM}

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p ${PKG}/etc/profile.d
for SCRIPT in ${PRGNAM}.sh ${PRGNAM}.csh ; do
  cat ${CWD}/${SCRIPT} > ${PKG}/etc/profile.d/${SCRIPT}
  chmod 755 ${PKG}/etc/profile.d/${SCRIPT}
done

mkdir -p ${PKG}/usr/doc/${PRGNAM}-${VERSION}

# move folder demo/ in documentation directory
#
mv ${PKG}/usr/lib64/${PRGNAM}/demo ${PKG}/usr/doc/${PRGNAM}-${VERSION}

for CFILE in DISCLAIMER Welcome.html readme.txt ; do
  mv ${PKG}/usr/lib64/${PRGNAM}/${CFILE} ${PKG}/usr/doc/${PRGNAM}-${VERSION}
done

cat ${CWD}/${PRGNAM}.SlackBuild > ${PKG}/usr/doc/${PRGNAM}-${VERSION}/${PRGNAM}.SlackBuild

mkdir -p ${PKG}/install
cat ${CWD}/slack-desc > ${PKG}/install/slack-desc

cd ${PKG}
/sbin/makepkg -l y -c n ${OUTPUT}/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-tgz}
