perl-html-tagset
perl-lwp-mediatypes
perl-http-date
perl-html-parser
perl-encode-locale
perl-IO-HTML
perl-http-message
perl-extutils-pkgconfig
perl-extutils-depends
perl-www-robotrules
perl-net-http
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-glib
perl-file-listing
perl-common-sense
perl-cairo
perl-Net-LibIDN
Net-SSLeay
perl-Types-Serialiser
perl-Test-RequiresInternet
perl-PAR-Dist
perl-Mozilla-CA
perl-MIME-Charset
perl-List-MoreUtils-XS
perl-IO-Socket-SSL
perl-Glib-Object-Introspection
perl-Exporter-Tiny
perl-Class-Inspector
perl-Canary-Stability
perl-Cairo-GObject
libwww-perl
perl-lwp-useragent-cached
perl-data-dump
perl-Unicode-LineBreak
perl-Text-CharWidth
perl-Term-ReadLine-Gnu
perl-Module-Build
perl-List-MoreUtils
perl-LWP-Protocol-https
perl-JSON-XS
perl-JSON
perl-Gtk3
perl-File-ShareDir
straw-viewer
