#!/bin/sh

# Slackware build script for torcs

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20170704 bkw: fix build on -current

PRGNAM=torcs
VERSION=${VERSION:-1.3.7}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

patch -p1 < $CWD/gcc7.diff

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS -fpermissive" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib$LIBDIRSUFFIX \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --bindir=/usr/games \
  --mandir=/usr/man \
  --build=$ARCH-slackware-linux

make -j1
make -j1 install DESTDIR=$PKG
make -j1 datainstall DESTDIR=$PKG

# For some reason `make install' creates all the dirs 0777
find $PKG -type d | xargs chmod 0755

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Tenemos una pagina de man en español...
mkdir -p $PKG/usr/man/man6 $PKG/usr/man/es/man6
mv doc/man/$PRGNAM.es.6 $PKG/usr/man/es/man6
mv doc/man/*.6 $PKG/usr/man/man6
rm -rf doc/man
gzip $PKG/usr/man/man6/*.6 $PKG/usr/man/es/man6/*.6

# Docs are a bit of a mess...
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
find doc -type d -a -name CVS -print0 | xargs -0 rm -rf
mv doc/history/history.txt doc/testing/release.txt doc/faq/faq.html \
	doc/userman/*.html doc/userman/images \
	$PKG/usr/doc/$PRGNAM-$VERSION
rmdir doc/history doc/testing doc/faq doc/userman
mv doc/website/credits.html $PKG/usr/doc/$PRGNAM-$VERSION
rm -rf doc/website  # not very useful because the images are missing
cp -r README doc/* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/share/applications
cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop

mkdir -p $PKG/usr/share/pixmaps
( cd $PKG/usr/share/pixmaps ; ln -s ../games/$PRGNAM/Ticon.png $PRGNAM.png )

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
