.TH SAUERBRATEN 6 "January 9, 2007"
.SH NAME
sauerbraten \- a 3D first person shooter
.SH SYNOPSIS
.B sauerbraten
[\-d] [\-w\fIwidth\fP] [\-h\fIheight\fP] [\-z\fIdepth\fP] [\-b\fIbpp\fP] [\-a\fIsamples\fP] [\-t] [\-k\fIdirectory\fP] [\-f\fIshaderprecision\fP]
.SH DESCRIPTION
.PP
This manual page documents briefly the
.B sauerbraten
command.
.PP
\fBsauerbraten\fP is the client and map editor of the Sauerbraten game. Sauerbraten is a fast 3D first person shooter.
.SH OPTIONS
.TP
\fB\-d\fR
Run as a dedicated server and don't start the client.
.TP
\fB\-w\fR\fIwidth\fP
Set window width in pixels.
.TP
\fB\-h\fR\fIheight\fP
Set window height in pixels.
.TP
\fB\-z\fR\fIdepth\fP
Set the z-buffer precision to \fIdepth\fP in bits.
.TP
\fB\-b\fR\fIbpp\fP
Set the bits per pixel to \fIbpp\fP bits.
.TP
\fB\-a\fR\fIsamples\fP
Set Full Scene Antialiasing to \fIsamples\fP samples.
.TP
\fB\-t\fR
Run in windowed mode (default is fullscreen mode).
.TP
\fB\-k\fR\fIdirectory\fP
Adds \fIdirectory\fP to the list of paths, in which the engine searches for files.
.TP
\fB\-f\fR\fIshaderprecision\fP
Set the precision quality. Values from 0 to 3 are allowed. 0 disabled shaders. The lower the value, the faster sauerbraten will run.
.TP
\fB\-f\fR
Don't use any shaders.
.BR
.SH SEE ALSO
.BR sauerbraten-server (6)
.br
http://sauerbraten.org/docs/config.html
.br
.SH AUTHOR
Sauerbraten was written by
.br
Wouter "Aardappel" van Oortmerssen,
.br
Lee "Eihrul" Salzman
.br
Mike "Gilt" Dysart
.br
Adrian "driAn" Henke
.br
Jerry Siebe
.br
Julian Mayer
.PP
This manual page was written by Bruno "Fuddl" Kleinert <fuddl@tauware.de> for the Debian project (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/doc/sauerbrauten-2009_06_19/.
