.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GRAPHITE\-MANAGE" "1" "December 2012" "" ""
.
.SH "NAME"
\fBgraphite\-manage\fR \- manage\.py wrapper for the Graphite Webapp
.
.SH "SYNOPSIS"
graphite\-manage
.
.SH "DESCRIPTION"
graphite\-manage is an wrapper script to access Django manage\.py for the Graphite Webapp\.
.
.P
See \fBgraphite\-manage \-\-help\fR for complete help\.
.
.P
To create an new sqlite database and an superuser do:
.
.IP "\(bu" 4
graphite\-manage syncdb
.
.IP "\(bu" 4
chown graphite:graphite /var/lib/graphite/graphite\.db
.
.IP "" 0
.
.SH "AUTHOR"
Jonas Genannt
.
.P
This manual page was written by Jonas Genannt \fIjonas\.genannt@capi2name\.de\fR for the Debian Project\.
.br
Modified by Mario Preksavec \fImario@slackware\.hr\fR for Slackware
