.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GRAPHITE\-BUILD\-SEARCH\-INDEX" "1" "December 2012" "" ""
.
.SH "NAME"
\fBgraphite\-build\-search\-index\fR \- create search index for Graphite Webapp
.
.SH "SYNOPSIS"
graphite\-build\-search\-index
.
.SH "DESCRIPTION"
This script creates the search index of Whisper files for the Graphite Webapp\. It will run as hourly cronjob\. You don\'t need to run this command manual except you want to force generating the search index\.
.
.SH "AUTHOR"
Jonas Genannt
.
.P
This manual page was written by Jonas Genannt \fIjonas\.genannt@capi2name\.de\fR for the Debian Project\.
