.TH mess 6 "December 6, 2008" "" "mess"


.SH NAME
mess \- runs MESS(tm) with SDL library


.SH SYNOPSIS
\fBmess\fP [system] [device] [software] [options]


.SH DESCRIPTION
\fBMESS\fP is an acronym that stands for Multiple Emulator Super System and is based on MAME (Multiple Arcade Machine Emulator). \fBSDLMESS\fP is the official Linux port of \fBMESS\fP using the \fBSDL\fP (Simple Direct Media Layer) library.
.PP
\fBmess\fP will more or less faithfully reproduce computer and console systems on a PC. \fBmess\fP can currently emulate over 250 systems from the last 5 decades.
.br
\fBmess\fP emulates the hardware of the systems and sometimes utilizes \fBROM\fP images to
load programs and games. Therefore, these systems are NOT simulations, but the
actual emulations of the hardware.
.br
\fBSuch ROMs, like any other commercial software, are copyrighted material and it is therefore illegal to use them if you don't own the original machines\fP.
Needless to say, ROMs are not distributed together with mess.
Distribution of mess together with ROM images is a violation of copyright law and should be promptly reported to the authors so that appropriate legal action can be taken.



.SH OPTIONS
.PP
.B
MESS GENERAL OPTIONS:

.B
core configuration options
.IP -readconfig
enable loading of configuration files

.PP
.B
core search path options
.IP -rompath
path to ROMsets and hard disk images
.IP -hashpath
path to hash files
.IP -samplepath
path to samplesets
.IP -artpath
path to artwork files
.IP -ctrlrpath
path to controller definitions
.IP -inipath
path to ini files
.IP -fontpath
path to font files
.IP -cheatpath
path to cheat files

.PP
.B
core output directory options
.IP -cfg_directory
directory to save configurations
.IP -nvram_directory
directory to save nvram contents
.IP -memcard_directory
directory to save memory card contents
.IP -input_directory
directory to save input device logs
.IP -state_directory
directory to save states
.IP -snapshot_directory
directory to save screenshots
.IP -diff_directory
directory to save hard drive image difference files
.IP -comment_directory
directory to save debugger comments

.PP
.B
core state/playback options
.IP -state
saved state to load
.IP -autosave
enable automatic restore at startup, and automatic save at exit time
.IP -playback
playback an input file
.IP -record
record an input file
.IP -mngwrite
optional filename to write a MNG movie of the current session
.IP -aviwrite
optional filename to write an AVI movie of the current session
.IP -wavwrite
optional filename to write a WAV file of the current session
.IP -snapname
override of the default snapshot/movie naming; %g == gamename, %i == index
.IP -snapsize
specify snapshot/movie resolution (<width>x<height>) or 'auto' to use minimal size
.IP -snapview
specify snapshot/movie view or 'internal' to use internal pixel-aspect views

.PP
.B
core performance options
.IP -autoframeskip
enable automatic frameskip selection
.IP -frameskip
set frameskip to fixed value, 0-12 (autoframeskip must be disabled)
.IP -seconds_to_run
number of emulated seconds to run before automatically exiting
.IP -throttle
enable throttling to keep game running in sync with real time
.IP -sleep
enable sleeping, which gives time back to other applications when idle
.IP -speed
controls the speed of gameplay, relative to realtime; smaller numbers are slower
.IP -refreshspeed
automatically adjusts the speed of gameplay to keep the refresh rate lower than the screen

.PP
.B
core rotation options
.IP -rotate
rotate the game screen according to the game's orientation needs it
.IP -ror
rotate screen clockwise 90 degrees
.IP -rol
rotate screen counterclockwise 90 degrees
.IP -autoror
automatically rotate screen clockwise 90 degrees if vertical
.IP -autorol
automatically rotate screen counterclockwise 90 degrees if vertical
.IP -flipx
flip screen left-right
.IP -flipy
flip screen upside-down

.PP
.B
core artwork options
.IP -artwork_crop
crop artwork to game screen size
.IP -use_backdrops
enable backdrops if artwork is enabled and available
.IP -use_overlays
enable overlays if artwork is enabled and available
.IP -use_bezels
enable bezels if artwork is enabled and available

.PP
.B
core screen options
.IP -brightness
default game screen brightness correction
.IP -contrast
default game screen contrast correction
.IP -gamma
default game screen gamma correction
.IP -pause_brightness
 amount to scale the screen brightness when paused

.PP
.B
core vector options
.IP -antialias
use antialiasing when drawing vectors
.IP -beam
set vector beam width
.IP -flicker
set vector flicker effect

.PP
.B
core sound options
.IP -sound
enable sound output
.IP -samplerate
set sound output sample rate
.IP -samples
enable the use of external samples if available
.IP -volume
sound volume in decibels (-32 min, 0 max)

.PP
.B
core input options
.IP -coin_lockout
enable coin lockouts to actually lock out coins
.IP -ctrlr
preconfigure for specified controller
.IP -mouse
enable mouse input
.IP -joystick
enable joystick input
.IP -lightgun
enable lightgun input
.IP -multikeyboard
enable separate input from each keyboard device (if present)
.IP -multimouse
enable separate input from each mouse device (if present)
.IP -steadykey
enable steadykey support
.IP -offscreen_reload
convert lightgun button 2 into offscreen reload
.IP -joystick_map
explicit joystick map, or auto to auto-select
.IP -joystick_deadzone
center deadzone range for joystick where change is ignored (0.0 center, 1.0 end)
.IP -joystick_saturation
end of axis saturation range for joystick where change is ignored (0.0 center, 1.0 end)

.PP
.B
core input automatic enable options
.IP -paddle_device
enable (keyboard|mouse|joystick) if a paddle control is present
.IP -adstick_device
enable (keyboard|mouse|joystick) if an analog joystick control is present
.IP -pedal_device
enable (keyboard|mouse|joystick) if a pedal control is present
.IP -dial_device
enable (keyboard|mouse|joystick) if a dial control is present
.IP -trackball_device
enable (keyboard|mouse|joystick) if a trackball control is present
.IP -lightgun_device
enable (keyboard|mouse|joystick) if a lightgun control is present
.IP -positional_device
enable (keyboard|mouse|joystick) if a positional control is present
.IP -mouse_device
enable (keyboard|mouse|joystick) if a mouse control is present

.PP
.B
core debugging options
.IP -log
generate an error.log file
.IP -verbose
display additional diagnostic information
.IP -update_in_pause
keep calling video updates while in pause
.IP -debug
enable/disable debugger
.IP -debugscript
script for debugger

.PP
.B
core misc options
.IP -bios
select the system BIOS to use
.IP -cheat
enable cheat subsystem
.IP -skip_gameinfo
skip displaying the information screen at startup

.PP
.B
debugging options
.IP -oslog
output error.log data to the system debugger

.PP
.B
performance options
.IP -multithreading
enable multithreading; this enables rendering and blitting on a separate thread
.IP -sdlvideofps
show sdl video performance

.PP
.B
video options
.IP -video
video output method: soft or opengl
.IP -numscreens
number of screens to create; SDLMAME only supports 1 at this time
.IP -window
enable window mode; otherwise, full screen mode is assumed
.IP -maximize
default to maximized windows; otherwise, windows will be minimized
.IP -keepaspect
constrain to the proper aspect ratio
.IP -unevenstretch
allow non-integer stretch factors
.IP -effect
name of a PNG file to use for visual effects, or 'none'
.IP -centerh
center horizontally within the view area
.IP -centerv
center vertically within the view area
.IP -waitvsync
enable waiting for the start of VBLANK before flipping screens; reduces tearing effects
.IP -scalemode
Scale mode: none, async, yv12, yuy2, yv12x2, yuy2x2 (-video soft only)

.PP
.B
opengl.-specific options
.IP -filter
enable bilinear filtering on screen output
.IP -prescale
scale screen rendering by this amount in software
.IP -gl_forcepow2texture
force power of two textures  (default no)
.IP -gl_notexturerect
don't use OpenGL GL_ARB_texture_rectangle (default on)
.IP -gl_vbo
enable OpenGL VBO, if available (default on)
.IP -gl_pbo
enable OpenGL PBO, if available (default on)
.IP -gl_glsl
enable OpenGL GLSL, if available (default off)
.IP -gl_glsl_filter
enable OpenGL GLSL filtering instead of FF filtering 0-plain, 1-bilinear (default)
.IP -glsl_shader_mame0
custom OpenGL GLSL shader set mame bitmap 0
.IP -glsl_shader_mame1
custom OpenGL GLSL shader set mame bitmap 1
.IP -glsl_shader_mame2
custom OpenGL GLSL shader set mame bitmap 2
.IP -glsl_shader_mame3
custom OpenGL GLSL shader set mame bitmap 3
.IP -glsl_shader_mame4
custom OpenGL GLSL shader set mame bitmap 4
.IP -glsl_shader_mame5
custom OpenGL GLSL shader set mame bitmap 5
.IP -glsl_shader_mame6
custom OpenGL GLSL shader set mame bitmap 6
.IP -glsl_shader_mame7
custom OpenGL GLSL shader set mame bitmap 7
.IP -glsl_shader_mame8
custom OpenGL GLSL shader set mame bitmap 8
.IP -glsl_shader_mame9
custom OpenGL GLSL shader set mame bitmap 9
.IP -glsl_shader_screen0
custom OpenGL GLSL shader screen bitmap 0
.IP -glsl_shader_screen1
custom OpenGL GLSL shader screen bitmap 1
.IP -glsl_shader_screen2
custom OpenGL GLSL shader screen bitmap 2
.IP -glsl_shader_screen3
custom OpenGL GLSL shader screen bitmap 3
.IP -glsl_shader_screen4
custom OpenGL GLSL shader screen bitmap 4
.IP -glsl_shader_screen5
custom OpenGL GLSL shader screen bitmap 5
.IP -glsl_shader_screen6
custom OpenGL GLSL shader screen bitmap 6
.IP -glsl_shader_screen7
custom OpenGL GLSL shader screen bitmap 7
.IP -glsl_shader_screen8
custom OpenGL GLSL shader screen bitmap 8
.IP -glsl_shader_screen9
custom OpenGL GLSL shader screen bitmap 9
.IP -gl_glsl_vid_attr
enable OpenGL GLSL handling of brightness and contrast. Better RGB game performance for free. (default)

.PP
.B
per-window video options
.IP -screen
explicit name of the first screen; 'auto' here will try to make a best guess
.IP -aspect
aspect ratio for all screens; 'auto' here will try to make a best guess
.IP -resolution
preferred resolution for all screens; format is <width>x<height>[@<refreshrate>] or 'auto'
.IP -view
preferred view for all screens
.IP -screen0
explicit name of the first screen; 'auto' here will try to make a best guess
.IP -aspect0
aspect ratio of the first screen; 'auto' here will try to make a best guess
.IP -resolution0
preferred resolution of the first screen; format is <width>x<height>[@<refreshrate>] or 'auto'
.IP -view0
preferred view for the first screen
.IP -screen1
explicit name of the second screen; 'auto' here will try to make a best guess
.IP -aspect1
aspect ratio of the second screen; 'auto' here will try to make a best guess
.IP -resolution1
preferred resolution of the second screen; format is <width>x<height>[@<refreshrate>] or 'auto'
.IP -view1
preferred view for the second screen
.IP -screen2
explicit name of the third screen; 'auto' here will try to make a best guess
.IP -aspect2
aspect ratio of the third screen; 'auto' here will try to make a best guess
.IP -resolution2
preferred resolution of the third screen; format is <width>x<height>[@<refreshrate>] or 'auto'
.IP -view2
preferred view for the third screen
.IP -screen3
explicit name of the fourth screen; 'auto' here will try to make a best guess
.IP -aspect3
aspect ratio of the fourth screen; 'auto' here will try to make a best guess
.IP -resolution3
preferred resolution of the fourth screen; format is <width>x<height>[@<refreshrate>] or 'auto'
.IP -view3
preferred view for the fourth screen

.PP
.B
full screen options
.IP -switchres
enable resolution switching
.IP -useallheads
split full screen image across monitors

.PP
.B
sound options
.IP -audio_latency
set audio latency (increase to reduce glitches, decrease for responsiveness)

.PP
.B
sdl keyboard mapping
.IP -keymap
enable keymap
.IP -keymap_file
keymap filename
.IP -uimodekey
Key to toggle MESS keyboard mode

.PP
.B
sdl joystick mapping
.IP -remapjoys
enable physical to logical joystick mapping
.IP -remapjoyfile
joymap filename
.IP -sixaxis
Use special handling for PS3 Sixaxis controllers

.PP
.B
sdl lowlevel driver options
.IP -videodriver
sdl video driver to use ('x11', 'directfb', ... or 'auto' for SDL default
.IP -audiodriver
sdl audio driver to use ('alsa', 'arts', ... or 'auto' for SDL default
.IP -gl_lib
alternative libGL.so to use; 'auto' for system default

.PP
.B
MESS SPECIFIC OPTIONS:
.IP -ramsize
size of RAM (if supported by driver)
.IP -writeconfig
writes configuration to (driver).ini on exit
.IP -skip_warnings
skip displaying the warnings screen
.IP -natural
specifies whether to use a natural keyboard or not

.PP
.B
SDL MESS SPECIFIC OPTIONS:

.PP
.B
core commands
.IP -help
show help message
.IP -validate
perform driver validation on all game drivers

.PP
.B
configuration commands
.IP -createconfig
create the default configuration file
.IP -showconfig
display running parameters
.IP -showusage
show this help

.PP
.B
frontend commands
.IP -listxml
all available info on driver in XML format
.IP -listfull
short name, full name
.IP -listsource
driver sourcefile
.IP -listclones
show clones
.IP -listcrc
CRC-32s
.IP -listroms
list required roms for a driver
.IP -listsamples
list optional samples for a driver
.IP -verifyroms
report romsets that have problems
.IP -verifysamples
report samplesets that have problems
.IP -romident
compare files with known MAME roms
.IP -listdevices
list available devices


.SH FILES
.B /usr/share/games/mess/*/
Default location for roms/, artwork/, and other read-only data for mess.
Can be changed in mess.ini
.TP
.B $HOME/.mess
Default location for writable directories. Can be changed in mess.ini
.TP
.B mess.ini
Config file for mess. Searched for first as $HOME/.mess/mess.ini, then
/etc/mess.ini


.SH EXAMPLE
.B mess \fI3do\fP -cdrm \fIcrashnburn.chd\fP
will launch the game "Crash N' Burn" from the console "3DO".
.TP
.B mess \fI3do\fP -cdrm \fIcrashnburn.chd\fP -bios \fIgoldstar\fP
will launch the game "Crash N' Burn" from the "3DO" console model from "Goldstar".
.TP
.B mess \fIn64\fP -cart \fImariokart64.v64\fP
will launch the game "Mario Kart 64" from the console "Nintendo 64".
.TP
.B mess \fIn64\fP -cart \fImariokart64.v64\fP -inipath \fI~/.mess/mess.ini\fP
will launch the game "Mario Kart 64" from the console "Nintendo 64" using a custom "mess.ini" file stored in the folder ".mess" of your home directory (usually "/home/yourusername/").
.TP
.B mess -showconfig
will output all the mess current configuration.


.SH SEE ALSO
More informations on \fBMESS\fP(tm) available at http://www.mess.org/
.br
\fBSDLMESS\fP original sources are available at http://rbelmont.mameworld.info/


.SH COPYRIGHT
MAME(tm) - Copyright (c) 1997-2008, Nicola Salmoria and the MAME team.
.br
MESS(tm) - Copyright (c) 1998-2008, Nathan Woods and the MESS team.
.br
SDLMESS - Copyright (c) Olivier Galibert and R. Belmont.


.SH AUTHOR
MAME(tm) was written by Nicola Salmoria and the MAME team.
.br
MESS(tm) was written by Nathan Woods and the MESS team.
.br
SDLMAME was written by Olivier Galibert and R. Belmont.
.sp 3
This manual page was written by Ludovic Lechapt <ludomatic@gmail.com>,
for the Debian project but may be used by others!
.sp 3
This manual page was modified by B. Watson for use with SlackBuilds.org
