#!/bin/sh

# Slackware build script for Screenfetch
# Copyright 2012, 2013, 2014, 2015  Bojan Popovic, Belgrade, Serbia, <bocke@slackware-srbija.org>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#########################################################################
# ChangeLog
#
# IMPORTANT: update this if you change this script!)
#########################################################################
#
# 1.0   15-DEC-2012 Added (ver. 2.7.5)
# 1.1   08-JUL-2013 Updated to a new upstream ver. 3.0.5. Fixes Slack64
#                   detection.
# 1.2   06-DEC-2013 Updated to a new upstream ver. 3.2.2.
# 1.3   23-JUN-2014 Changed source URL (willysr).
# 1.4   25-JUN-2014 Updated slack-desc (willysr).
# 1.5   23-JUL-2014 Updated to a new upstream ver. 3.5.0.
# 1.6   07-DEC-2014 Updated to a new upstream ver. 3.6.5
# 1.7   30-JAN-2015 Added a source alternative (willysr).
# 1.8   31-JAN-2015 Updated changelog. Synced changelog to git history.
#                   Updated changelog formating. Updated tar extraction line
#                   to eliminate (harmless but annoying) extraction errors.

PRGNAM=screenfetch
VERSION=${VERSION:-3.6.5}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}
DIRNAME=screenFetch

ARCH=noarch

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

DOCS="CHANGELOG COPYING README.mkdn TODO"

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
( tar xvf $CWD/$PRGNAM-$VERSION.tar.gz || tar xvf $CWD/v$VERSION.tar.gz || tar xvf $CWD/$DIRNAME-$VERSION.tar.gz ) 2>/dev/null || ( echo "Error: Source archive extraction failed!" && exit 1)
cd $DIRNAME-$VERSION
chmod 644 $DOCS

install -m 755 -D $PRGNAM-dev $PKG/usr/bin/$PRGNAM

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
