.TH pentagram 1 "29 Oct 2011" "20110229_svn" "Pentagram"

.SH NAME
\fBpentagram\fR \- A reimplemented engine for the game
.B Ultima VIII: Pagan

.SH SYNOPSIS
.B pentagram
.RI [ options ]

.SH DESCRIPTION
.B pentagram
is an engine for playing the game
.B Ultima 8
on modern operating systems.
The files from the original game are required for
.B pentagram
to work. Since
.B Ultima 8
is a commercial work, this means you must own a
copy of the original game to legally play it with
\fBpentagram\fR.
.SH OPTIONS
.TP
.B \-h, \-\-help
Shows command\-line option help
.TP
.B \-q
Silence general logging messages.
.TP
.B \-qq
Silence general logging messages and non\-critical
warnings/errors.
.TP
.B \-\-game [gamename]
Select a game. This option is currently useless, since only Ultima 8 is supported.
.SH FILES
.TP
.B ~/.pentagram/
Config and savegame data.
.TP
.B ~/.pentagram/pentagram.ini
Configuration. Specifies the path to the game data, among other things.
The SlackBuilds.org build of pentagram uses a shell script wrapper to
create a default \fBpentagram.ini\fR if the user doesn't have one already.
See \fI/usr/doc/pentagram\-@VERSION@/README\fR for full details of the options
available in the config file.
.TP
.B ~/.pentagram/u8\-save/
Saved games. Not compatible with the original Ultima 8.
.TP
.B /usr/share/pentagram
This is the default location where
.B pentagram
looks for the Ultima 8 data files. This directory should contain
a complete installation of the game, including the file
.B U8.exe
(case\-insensitive;
.B u8.exe
or
.B U8.EXE
are also OK). This location can be changed by editing
.B ~/.pentagram/pentagram.ini
.SH CONTROLS
.SS Movement
Double\-click with the right mouse button will make the Avatar find a path to the selected spot.
.br
Left\-click on NPCs or objects to identify them.
.br
Double\-left\-click on NPCs or objects to initiate conversations or use the item.
.br
On pressing the right mouse button down the Avatar walks or runs (depending on distance between cursor and Avatar).
.br
Pressing right and left mouse button, makes the Avatar jump or while running a running jump.
.br
You can also move the Avatar with the keypad. Details are in the keycommands table below.
.SS Keyboard Commands
These are the default keyboard commands; they can be changed from the
options menu in the game, or by creating/editing
the file \fI~/.pentagram/u8bindings.ini\fR.
.TP
.B ~ 
hides/restores console. See \fI/usr/doc/pentagram\-@VERSION@/README\fR for
available console commands.
.TP
.B arrow keys 
moves Avatar around the map (no walking)
.TP
.B home,end 
moves Avatar vertically
.TP
.B Keypad 
Avatar walks (one animation cycle)
.TP
.B Shift+Keypad 
Avatar runs (one animation cycle)
.TP
.B Ctrl+Keypad 
Avatar makes a little step (one animation cycle)
.TP
.B Alt+Keypad 
Avatar jumps long (one animation cycle)
.TP
.B s 
toggles "avatarInStasis"
.TP
.B t 
outputs kernel/usecode/world/location stats to the console
.TP
.B e 
toggles editor items
.TP
.B h 
highlights any item you are "hitting", colliding with
.TP
.B i 
open backpack
.TP
.B z 
open paperdoll/status
.TP
.B r 
recall
.TP
.B c 
switches combat mode on/off
.TP
.B ESC 
main menu
.TP
.B alt+x 
quit
.TP
.B ctrl+q 
quits without confirmation
.TP
.B backspace 
close all open containers
.TP
.B F7 
Quicksave (savegames are not yet stable!)
.TP
.B F8 
Quickload
.TP
.B F11 
Shapeviewer
.TP
.B F12 
toggles frame by frame
.TP
.B shift 
quarter speed mode. needs to be held down
.TP
.B [ 
clears the screen, multiple presses show the paint order
.TP
.B ] 
Same as above, backwards
.SH AUTHORS
The
.B
Ultima
games were created by Richard Garriott, AKA Lord British,
and are copyrighted by Electronic Arts.
.PP
.B pentagram
written by
The Pentagram Team:
.br
Willem Jan Palenstijn <wjpalenstijn@users.sourceforge.net>
.br
Patrick Burke <takhisis@users.sourceforge.net>
.br
Max Horn <max@quendi.de>
.br
Ryan Nunn <colourles@users.sourceforge.net>
.br
Dominik Reichardt <dominus@users.sourceforge.net>
.br
Matthew Jimenez <mjimenez@users.sourceforge.net>
.br
Brian Tietz <btietz@broadcom.com>
.PP
Man page created by B. Watson, for the SlackBuilds.org
project. Permission hereby granted to use this man page anywhere, for any purpose.
