#!/bin/sh

# Slackware build script for openrpt

# Copyright 2008 Heinz Wiesinger <hmwiesinger@gmx.at>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=openrpt
VERSION=${VERSION:-2.3.0}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-source
tar xvf $CWD/$PRGNAM-$VERSION-source.tar.bz2
cd $PRGNAM-$VERSION-source
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

qmake-qt4

make qmake_all

for i in common graph MetaSQL OpenRPT/export OpenRPT/import \
 OpenRPT/import_gui OpenRPT/renderapp OpenRPT/renderer \
 OpenRPT/writer OpenRPT/wrtembed; do
  sed -i "s/-O2/$SLKCFLAGS/" $i/Makefile
done

make

mkdir -p $PKG/usr/{bin,lib}
mkdir -p $PKG/usr/include/openrpt
mkdir -p $PKG/usr/share/applications

install -m 0755 bin/* $PKG/usr/bin/

# Yes, I know, these are only static libraries, but
# xtuple will need it...
install -m 0655 lib/* $PKG/usr/lib/

for i in common MetaSQL OpenRPT/renderer OpenRPT/wrtembed; do
    for j in `find $i -name "*.h";`;do
      install -m 0655 -D $j $PKG/usr/include/openrpt/$j
    done
done

rm -rf $PKG/usr/include/openrpt/common/tmp*
rm -rf $PKG/usr/include/openrpt/MetaSQL/tmp*
rm -rf $PKG/usr/include/openrpt/OpenRPT/wrtembed/tmp*

install -m 0644 $CWD/openrpt.desktop \
    $PKG/usr/share/applications/openrpt.desktop

for i in 16 32 48 128; do
  mkdir -p $PKG/usr/share/icons/hicolor/${i}x${i}/apps
  install -m 0644 OpenRPT/images/OpenReportsIcon$i.png \
    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/openrpt.png
done

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING README \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
