#!/bin/bash

# Slackware build script for nextcloud-server

# Copyright 2017 David Spencer, Baildon, West Yorkshire, U.K.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Maintained by Roberto Puzzanghera - <admin {at} sagredo [dot] eu>

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=nextcloud-server
SRCNAM=nextcloud
VERSION=${VERSION:-29.0.16}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

DOCROOT=${DOCROOT:-/srv/httpd/htdocs}
PHPUSER=${PHPUSER:-apache}
PHPGROUP=${PHPGROUP:-apache}

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

mkdir -p $PKG/$DOCROOT
cd $PKG/$DOCROOT
tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $SRCNAM
chown -R $PHPUSER:$PHPGROUP .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p data
chown -R $PHPUSER:$PHPGROUP data/
chmod -R o-rwx data/
chmod +x cron.php occ

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS 3rdparty/'LICENSE INFO' \
  $PKG/usr/doc/$PRGNAM-$VERSION
chown root:root $PKG/usr/doc/$PRGNAM-$VERSION/AUTHORS $PKG/usr/doc/$PRGNAM-$VERSION/LICENSE\ INFO
chmod 644 $PKG/usr/doc/$PRGNAM-$VERSION/AUTHORS $PKG/usr/doc/$PRGNAM-$VERSION/LICENSE\ INFO
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/etc/php-fpm.d
cat $CWD/nextcloud.php-fpm > $PKG/etc/php-fpm.d/nextcloud.conf.new

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh  > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
