#!/bin/sh

# Slackware build script for the io language
# Written by Thiago Coutinho <thiagocoutinho1[@]gmail.com>

# Modified by the SlackBuilds.org project.

PRGNAM=io
VERSION=2008.03.30
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

set -e 

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf stevedekorte-io-*
tar xvf $CWD/stevedekorte-io-*.tar.gz
cd stevedekorte-io-*
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
  make vm \
  INSTALL_PREFIX=$PKG/usr
make install \
  INSTALL_PREFIX=$PKG/usr

# Wow.  That's all I'll say. --rworkman
# These are the same file - 2.7 MB each...
cd $PKG/usr/bin
  rm -f libiovmall.so
  ln -s /usr/lib/libiovmall.so .
cd -

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a docs/* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
