'\" t
.\"     Title: TREEVIEW X
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 06/23/2011
.\"    Manual: User Manuals
.\"    Source: TreeView X 0.5
.\"  Language: English
.\"
.TH "TREEVIEW X" "1" "06/23/2011" "TreeView X 0.5" "User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
TreeView_X \- displays and prints phylogenetic trees
.SH "SYNOPSIS"
.HP \w'\fBtv\fR\ 'u
\fBtv\fR [\fIfilename\fR]
.SH "DESCRIPTION"
.PP
\fBtv\fR
is the program that starts the TreeView X GUI\&.
.PP
TreeView X is an open source and multi\-platform program to display phylogenetic trees\&. It can read and display NEXUS and Newick format tree files (such as those output by PAUP*, ClustalX, TREE\-PUZZLE, and other programs)\&. It allows one to order the branches of the trees, and to export the trees in SVG format\&.
.PP
If started from the command line with
filename
as an argument, TreeView X will open the tree stored in
filename\&.
.SH "SEE ALSO"
.PP
At present there is is no documentation for TreeView X\&. In the meantime please see the online documentation for TreeView (remember that TreeView X has only a subset of the features of TreeView)\&. http://taxonomy\&.zoology\&.gla\&.ac\&.uk/rod/treeview/treeview_manual\&.html
.SH "REFERENCE"
.PP
Page, R\&. D\&. M\&. 1996\&. TREEVIEW: An application to display phylogenetic trees on personal computers\&. Computer Applications in the Biosciences 12: 357\-358\&.
.SH "AUTHOR"
.PP
TreeView X
was written by Rod Page (r\&.page@bio\&.gla\&.ac\&.uk) URL: http://darwin\&.zoology\&.gla\&.ac\&.uk/~rpage/treeviewx\&.
.PP
This manual page was written by Charles Plessy (plessy@debian\&.org) for the
Debian(TM)
system (but may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify TreeView\ \&X and this document under the terms of the
GNU
General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License version 2 can be found in /usr/share/common\-licenses/GPL\-2\&.
