#!/bin/bash

# Slackware build script for avahi

# Copyright 2008-2012  David Somero (dsomero@hotmail.com) Athens, TN, USA
# Copyright 2008, 2009  Patrick J. Volkerding, Sebeka, Minnesota, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# 20220301 bkw: Modified by SlackBuilds.org, BUILD=7:
# - don't include empty /run dir in package.
# - remove useless INSTALL from doc dir.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=avahi
VERSION=${VERSION:-20240306_709e60f}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

warn_accounts() {
  echo "  You must have an avahi user and group to run this script. "
  echo "  Something like this should suffice for most systems: "
  echo "      # groupadd -g 214 avahi"
  echo "      # useradd -u 214 -g 214 -c "Avahi" -d /dev/null -s /bin/false avahi"
 exit 1
}

# Bail if user and/or group isn't valid on your system
if ! getent passwd avahi &>/dev/null; then
  warn_accounts
fi
if ! getent group avahi &>/dev/null; then
  warn_accounts
fi

if [ "${ARCH}" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.lz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \+ -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+

# This patch is mine --rworkman
patch -p1 --verbose < $CWD/patches/fixup_avahi-dnsconfd.action.patch

NOCONFIGURE=1 ./autogen.sh

export PYTHON=python3
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-systemdsystemunitdir=no \
  --enable-tests \
  --disable-static \
  --disable-mono \
  --disable-monodoc \
  --disable-autoipd \
  --disable-libsystemd \
  --enable-compat-libdns_sd \
  --enable-python-dbus \
  --enable-glib \
  --enable-dbus \
  --enable-python \
  --enable-gtk \
  --enable-gtk3 \
  --enable-qt5 \
  --disable-qt4 \
  --disable-qt3 \
  --enable-core-docs \
  --disable-manpages \
  --with-dbus-sys=/usr/share/dbus-1/system.d \
  --with-avahi-user=avahi \
  --with-avahi-group=avahi \
  --with-avahi-priv-access-group=netdev \
  --with-distro=slackware \
  --program-prefix= \
  --program-suffix= \
  --build=$ARCH-slackware-linux

make
make install-strip DESTDIR=$PKG

# 20220414 bkw: if this dir is empty, it doesn't need to be included
# in the package.
rmdir $PKG/run &> /dev/null || true

rm -rf $PKG/usr/lib${LIBDIRSUFFIX}/*.la

mkdir -p $PKG/usr/man/man1 $PKG/usr/man/man5 $PKG/usr/man/man8
for i in $CWD/man/man1/* ; do cat $i > $PKG/usr/man/man1/$(basename $i) ; done
for i in $CWD/man/man5/* ; do cat $i > $PKG/usr/man/man5/$(basename $i) ; done
for i in $CWD/man/man8/* ; do cat $i > $PKG/usr/man/man8/$(basename $i) ; done
find $PKG/usr/man -type f -exec gzip -9 {} \;

mv $PKG/etc/rc.d/rc.avahidaemon $PKG/etc/rc.d/rc.avahidaemon.new
mv $PKG/etc/rc.d/rc.avahidnsconfd $PKG/etc/rc.d/rc.avahidnsconfd.new
mv $PKG/etc/avahi/avahi-daemon.conf $PKG/etc/avahi/avahi-daemon.conf.new

# Fix python3 shebangs:
sed -i "s|#!python3|#!/usr/bin/python3|g" $PKG/usr/bin/avahi-{discover,bookmarks}

# Don't ship .la files:
rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
rm -f docs/INSTALL
cp -a docs/* $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/usr/doc/$PRGNAM-$VERSION/README $PKG/usr/doc/$PRGNAM-$VERSION/README.too
cp -a LICENSE* README* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh  > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
