#!/bin/sh

# Slackware build script for ffmpeg

# Written by core (eroc@linuxmail.org)
# Modified by Robby Workman <rworkman@slackbuilds.org>

set -e

PRGNAM=ffmpeg
VERSION=${VERSION:-20071003}
# To use today's svn checkout, comment the line above and uncomment 
# the line below.  See the README for more information.
#VERSION=${VERSION:-$(date +"%Y%m%d")}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar -jxvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --mandir=/usr/man \
  --disable-debug \
  --enable-shared \
  --disable-static \
  --enable-pthreads \
  --enable-libogg \
  --enable-libtheora \
  --enable-libvorbis \
  --enable-gpl \
  --enable-pp \
  --enable-swscaler \
  --enable-x11grab \
  --enable-libmp3lame \
  --enable-libfaac \
  --enable-libfaad \
  --enable-libxvid \
  --enable-liba52 \
  --enable-libx264

make
make install DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

if [ -d $PKG/usr/man ]; then
( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
)
fi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a Changelog* COPYING* CREDITS* INSTALL* MAINTAINERS* \
  README* doc/TODO* doc/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

if [ -e $CWD/$PRGNAM-mksrctarball.sh ]; then
  cat $CWD/$PRGNAM-mksrctarball.sh > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM-mksrctarball.sh
fi

if [ -e $CWD/svn-$PRGNAM-$VERSION.log ]; then
  cat $CWD/svn-$PRGNAM-$VERSION.log > $PKG/usr/doc/$PRGNAM-$VERSION/svn-$PRGNAM-$VERSION.log
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
