#!/bin/bash

# Slackware build script for bowtie2

# Copyright 2013-2016 Petar Petrov slackalaxy@gmail.com
# Copyright 2018-2024 Rob van Nues sborg63@disroot.org
#
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=bowtie2
VERSION=${VERSION:-2.5.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  printf "\n$ARCH is unsupported by $PRGNAM\n"
  exit 1
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar -xvzf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

#Use our FLAGS
RELEASE_FLAGS+="$SLKCFLAGS" \
make

install -D -m755 $PRGNAM	 $PKG/usr/bin/$PRGNAM
install -D -m755 $PRGNAM-align-l	 $PKG/usr/bin/$PRGNAM-align-l
install -D -m755 $PRGNAM-build-l	 $PKG/usr/bin/$PRGNAM-build-l
install -D -m755 $PRGNAM-align-s	 $PKG/usr/bin/$PRGNAM-align-s
install -D -m755 $PRGNAM-build-s	 $PKG/usr/bin/$PRGNAM-build-s
install -D -m755 $PRGNAM-build	 $PKG/usr/bin/$PRGNAM-build
install -D -m755 $PRGNAM-inspect-l	$PKG/usr/bin/$PRGNAM-inspect-l
install -D -m755 $PRGNAM-inspect-s	$PKG/usr/bin/$PRGNAM-inspect-s
install -D -m755 $PRGNAM-inspect	$PKG/usr/bin/$PRGNAM-inspect

# Copy examples and scripts
mkdir -p $PKG/usr/share/$PRGNAM
cp -a \
  example scripts \
  $PKG/usr/share/$PRGNAM

# Let's compress the reads and indexes
gzip $PKG/usr/share/$PRGNAM/example/reads/*.fq
gzip $PKG/usr/share/$PRGNAM/example/index/*.bt2

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  AUTHORS LICENSE MANUAL NEWS TUTORIAL BOWTIE2_VERSION doc \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
