.TH ZITA-REV1 "1" "May 2011"
.SH NAME
zita-rev1 \- pro-audio reverb effect
.SH SYNOPSIS
.B zita-rev1
.RI [ options ]
.SH DESCRIPTION
REV1 is a reworked version of the reverb originally developed for Aeolus.
Its character is more 'hall' than 'plate', but it can be used on a wide
variety of instruments or voices. It is not a spatialiser \- the early
reflections are different for the L and R inputs, but do not correspond
to any real room. They have been tuned to match left and right sources to
some extent.
.PP
In Stereo mode a dry/wet mix control is provided, so it can be used either
as an insert or in send/return mode. For mono just connect one of the
two channels.
.PP
In Ambisonic mode (selected by the \-B command line option) the only option
is the send/return mode.
.SH OPTIONS
.TP
\fB\-B\fR
Ambisonic mode
.TP
\fB\-name\fR name
Jack client name
.TP
\fB\-s\fR server
Jack server name
.TP
\fB\-g\fR geometry
Window position
.TP
\fB\-h\fR
Display this text
.PP
.SH "SEE ALSO"
A quick guide is available at
<http://kokkinizita.linuxaudio.org/linuxaudio/zita-rev1-doc/quickguide.html>
.SH "AUTHOR"
zita-rev1 was written by Fons Adriaensen <fons@linuxaudio.org>.
.PP
This manual page was written by Alessio Treglia <alessio@debian.org>
for the Debian project (but may be used by others).
