#!/bin/sh

# Slackware build script for Openbox 

# Written by Chess Griffin <chess@chessgriffin.com>
# Modifications for KDE and GNOME xinitrc scripts 
#  by Phillip Warner <pc_warner@yahoo.com>

PRGNAM=openbox
VERSION=3.4.6.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Set these to "YES" if you want your package to include a xinitrc file 
# for running Openbox in KDE or GNOME, respectively.
# Otherwise, you can add the xinitrc files manually to /etc/X11/xinit and 
# the openbox-kde-session and openbox-gnome-session files to /usr/bin.
# The files can be found under /usr/doc/openbox
# Don't forget to make them executable if you copy them from /usr/doc!
#
# This can be specified on the command line when calling the build script:
#   KXINIT=YES ./openbox.SlackBuild
KXINIT=${KXINIT:-NO}
GXINIT=${GXINIT:-NO}

DOCS="ABOUT-NLS AUTHORS CHANGELOG COMPLIANCE COPYING README"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --enable-startup-notification

make
make install DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
)

# Add xinitrc.openbox so that openbox will show up as an option in xwmconfig
install -D -m 0755 $CWD/xinitrc.openbox $PKG/etc/X11/xinit/xinitrc.openbox

# Optionally install xinitrc scripts for running Openbox in KDE or GNOME
# Move the scripts from /usr/bin if the xinitrc scripts are not installed.
if [ "$KXINIT" == "YES" ]; then
	install -D -m 0755 $CWD/xinitrc.kde-openbox $PKG/etc/X11/xinit/xinitrc.kde-openbox
else
	cat $PKG/usr/bin/openbox-kde-session > $PKG/usr/share/doc/$PRGNAM/openbox-kde-session
	rm -vf $PKG/usr/bin/openbox-kde-session
fi
if [ "$GXINIT" == "YES" ]; then
	install -D -m 0755 $CWD/xinitrc.gnome-openbox $PKG/etc/X11/xinit/xinitrc.gnome-openbox
else
	cat $PKG/usr/bin/openbox-gnome-session > $PKG/usr/share/doc/$PRGNAM/openbox-gnome-session
	rm -vf $PKG/usr/bin/openbox-gnome-session
fi

mkdir -p $PKG/usr/doc
mv $PKG/usr/share/doc/$PRGNAM $PKG/usr/doc/$PRGNAM-$VERSION
rmdir $PKG/usr/share/doc
cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
for i in $CWD/xinitrc.*openbox ; do
	cat $i > $PKG/usr/doc/$PRGNAM-$VERSION/$(basename $i) ;
done
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
( cd $PKG/usr/doc ; ln -s $PRGNAM-$VERSION $PRGNAM )

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
