#!/bin/bash

## Written by halflife (vzdorovenco@yahoo.com)

## Feel free to use, modify, redistribute this script.
## If you make changes please modify the "Written by"
## so that I don't recieve emails about a script I
## did not write. Thanks.

# Modified by Robby Workman 20071027
# I won't change the "Written by" line, because I didn't
# change who wrote the script.  If there are questions as
# to whether my changes caused a problem, feel free to
# send mail to me first.

# Package adaptation in order to rename it from otp-R11B
# to erlang-otp, by LukenShiro <Lukenshiro@ngi.it>

# Modified by Ryan S. Northrup <northrup@yellowapple.us> on
# 28 November 2016 to reflect the use of README.md instead
# of README in upstream

# 20220415 bkw: Modified by SlackBuilds.org, BUILD=2:
# - strip binaries/libraries.

# 20260918 bkw: Modified by SlackBuilds.org, BUILD=3:
# - rename some man pages to avoid conflicts with Slackware packages.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=erlang-otp
VERSION=${VERSION:-27.3.4.18}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

SRC_NAME_VERSION=otp_src_${VERSION}
DOC_NAME_VERSION=otp_doc_man_${VERSION}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRC_NAME_VERSION
tar xvf $CWD/${SRC_NAME_VERSION}.tar.gz --no-same-owner
cd $SRC_NAME_VERSION
find . ! -type l    -a \( \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \) \)

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --with-ssl-rpath=no \
  --disable-year2038 \
  --build=$ARCH-slackware-linux

make
make DESTDIR=$PKG install

rm -f $PKG/usr/lib${LIBDIRSUFFIX}/erlang/Install
find $PKG -type d -empty -delete

tar xvf $CWD/$DOC_NAME_VERSION.tar.gz -C $PKG/usr/lib${LIBDIRSUFFIX}/erlang
chown -R root:root $PKG/usr/lib${LIBDIRSUFFIX}/erlang
chmod -R u+w,go+r-w,a-s $PKG/usr/lib${LIBDIRSUFFIX}/erlang
mv $PKG/usr/lib${LIBDIRSUFFIX}/erlang/man $PKG/usr

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
cp -a \
  LICENSE.txt README.md CONTRIBUTING.md SECURITY.md \
  $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
