.TH ucr 6 "28 Oct 2011" "0.1.2" "Ultima Classics Revisited"

.SH NAME
\fBucr\fR \- A modern reimplementation of the classic Ultima role\-playing games.

.SH SYNOPSIS
.B ucr

.SH DESCRIPTION
.B ucr
(Ultima Classics Revisited)
is a remake of the computer games Akalabeth (aka "Ultima 0") and
Ultima 1.
.PP
.B ucr
accepts no command\-line arguments.
.PP
The current version of
.B ucr
contains a complete rewrite of Akalabeth, which is fully playable, and
a partial engine for Ultima I (not fully playable). To use the Ultima I
engine, you will need the data files from the original PC release of
Ultima I (place them in \fI/usr/share/ucr/games/u1\fR).
.PP
Although Akalabeth is fully playable, it has no support for saving the
game or loading saved games (unlike the original PC release of Akalabeth).
Ultima I, while not fully playable, does support saving/loading the game.
.SH KEYBOARD CONTROLS
Only the keyboard controls for Akalabeth are documented here.
.PP
Akalabeth
is played entirely with the keyboard. To make choices from menus,
press the first letter of the menu choice (e.g. \fBF\fR to buy Food
at the Adventure Shop menu).
.PP
During gameplay, the following keystrokes are supported:
.TP
.B S
Show character stats (hit points, equipment, etc)
.TP
.B P
Pause/Resume
.TP
.B Space
Pass
.TP
.B F11
Toggle original/enhanced graphics
.TP
.B
F12
Enable/disable music
.SS Outdoors
.TP
.B Up/Down/Left/Right Arrows
Move North/South/East/West
.TP
.B E
Enter Town or Castle
.SS In Dungeons
.TP
.B
Up
Move Forward
.TP
.B
Down
Turn Around
.TP
.B
Left/Right
Turn Left/Right
.TP
.B
A
Attack
.TP
.B
E
Climb Ladder or Descend into Hole
.SH FILES
.TP
.B /etc/ucr/ucr.conf
Config file for \fBucr\fR. Sets the paths to the game data, the screen
size, and a few other variables. Not well documented, but fairly self\-explanatory.
The settings for u2 through u6 don't do anything, as these games were never
implemented in \fBucr\fR.
.SH AUTHORS
.B Akalabeth
and the
.B
Ultima
games were created by Richard Garriott, AKA Lord British.
.PP
.B ucr
written by Gregory Maculo <prmths@emptyspaces.net>
.PP
Man page created by B. Watson, for the SlackBuilds.org
project. Permission hereby granted to use this man page anywhere, for any purpose.
