.TH zennode "6" "March 2012" "SlackBuilds.org" "Games"
.SH NAME
zennode \- build nodes for Doom and related games
.SH SYNOPSIS
.B zennode
.I [ \-options ]
input.wad
.I [ level[+level] ]
.I [ -o|x output.wad ]
.SH DESCRIPTION
.B zennode
builds NODES, BLOCKMAP, REJECT resources for ID Software's Doom
and related games. This includes both "vanilla" resources and OpenGL\-specific resources used
by GL\-based source ports such as gzdoom.
.SH OPTIONS
For any option \fI\-x\fR, use \fI\-x\-\fR to disable and \fI\-x+\fR to enable.
.TP
.B \-b
(re)build BLOCKMAP.
.TP
.B \-bc
(re)build BLOCKMAP, compressed. Enabled by default.
.TP
.B \-n[a=1,2,3|q|u|i]
(re)build NODES, enabled by default. Sub\-options:
.br
\fBa=\fR\fIn\fR
\- Select partition algorithm.
.I n
is one of: 1 (Minimize splits), 2 (Minimize BSP depth), or 3 (Minimize time).
Default is \fBa=1\fR.
.br
.B q
\- Quiet. Don't display progress bar. Enabled by default, use \fB\-q\-\fR to see progress bar.
.br
.B u
\- Ensure all sub\-sectors contain only one sector.
.br
.B i
\- Ignore non\-visible linedefs.
.TP
.B \-r[zfgm]
(re)build REJECT resource. Enabled by default. Sub\-options:
.br
.B z
\- Insert empty REJECT resource.
.br
.B f
\- Rebuild even if REJECT effects are detected.
.br
.B g
\- Use graphs to reduce LOS calculations (enabled by default).
.br
.B m
.I filename
\- Process RMB option file (.rej).
.TP
.B \-t
Test mode. Don't write output file.
.SH SUPPORTED GAMES
Doom, Doom II, Ultimate Doom, Heretic, Hexen, Strife
.SH "SEE ALSO"
The main documentation at
.nh
.B @DOCDIR@
.hy
.br
The
.B ZenNode
homepage at
.nh
.B http://mrousseau.org/programs/ZenNode/
.hy
.br
.B idbsp(6)
.br
.B wreject(6)
.br
.B warm(6)
.br
.B glbsp(6)
.br
.SH AUTHOR
ZenNode is copyright (c) 1994-2004 Marc Rousseau
.P
This man page was written by B. Watson for the SlackBuilds.org project, but
it can be used by anyone.
