.TH ircflush 1 "September 2021" "ircII @VERSION@" "SlackBuilds.org"
.SH NAME
ircflush \- a little program that tricks another program into line buffering its output
.SH SYNOPSIS
.B ircflush
.RB [ program ]
.RB [ arguments to program
.SH DESCRIPTION
What's the deal here?  Well, it's like this.  First we find an open
tty/pty pair.  Then we fork three processes.  The first reads from stdin
and sends the info to the master device.  The next process reads from the
master device and sends stuff to stdout.  The last processes is the rest
of the command line arguments exec'd.  By doing all this, the exec'd
process is fooled into flushing each line of output as it occurs.
.P
This program is intended as a 'helper' for ircII scripts.
.SH OPTIONS
.TP
.B [ program ]
.TP
.B [ arguments to program]
.TP
.RE
.SH AUTHOR
.EX
Michael Sandrof
.EE
.SH SEE ALSO
.BR ircII (1),
.BR irc (1)
