.TH ircio 1 "September 2021" "ircII @VERSION@" "SlackBuilds.org"
.SH NAME
ircio \- A quaint little program to make irc life PING free
.SH DESCRIPTION
This little program connects to the server (given as arg 1) on
the given port (given as arg 2).  It then accepts input from stdin and
sends it to that server. Likewise, it reads stuff sent from the server and
sends it to stdout.  Simple?  Yes, it is.  But wait!  There's more!  It
also intercepts server PINGs and automatically responds to them.   This
frees up the process that starts ircio (such as IRCII) to pause without
fear of being pooted off the net.
.P
.B ircio
is not intended to be run by itself. It's started by ircII's -S command\-line
option.
.P
.SH BUGS
.B ircio
doesn't work at all with SSL\-enabled IRC connections. It also
doesn't work properly with the
.B libera.chat
network even without SSL: you can connect, but you'll get disconnected
before the MOTD is sent.
.P
There are better ways to solve the problem
.B ircio
solves, such as
.BR screen (1),
.BR tmux (1),
or just multiple X terminals. There's no need to suspend
.B ircII
in such environments.
.SH AUTHOR
.EX
Michael Sandrof
.EE
.SH SEE ALSO
.BR ircII (1),
.BR ircflush (1)
