.TH wserv 1 "September 2021" "ircII @VERSION@" "SlackBuilds.org"
.SH NAME
wserv \- little program that acts as a pipe between a screen or xterm window to the calling ircII process
.SH SYNOPSIS
.B wserv
.RB [ /path/to/socket ]
.RB [ /path/to/control ]
.SH DESCRIPTION
Works by opening up the unix domain socket that ircII binds
before calling wserv, and which ircII also deletes after the
connection has been made.
.P
.B wserv
is not useful by itself. It gets run as needed by ircII when the
.B /window create
command is executed.
.P
.SH OPTIONS
.TP
.B [ /path/to/socket ]
.TP
.B [ /path/to/control ]
.SH AUTHOR
.EX
Michael Sandrof
.EE
.SH SEE ALSO
.BR ircII (1),
.BR ircio (1),
.B /help window create
