#!/bin/sh

# Slackware build script for dropbox

# Copyright 2017 cmyster amit.ugol@gmail.com
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# Public changelog can be found in: https://www.dropboxforum.com
# SlackBuild changelog:
# 19/Nov/2017 * Updated to latest version 39.4.49
# 25/Oct/2017 * Updated to latest version 37.4.29
#             * Icons have changed:
#               https://www.dropbox.com/help/desktop-web/sync-icons#desktop
# 25/Sep/2017 * Updated to latest version 35.4.20
# 13/Aug/2017 * Updated to latest version 32.4.23
# 22/Jun/2017 * Updated to latest version 28.4.14
# 03/May/2017 * Updated to latest version 25.4.28
# 18/Apr/2017 * Updated to latest version 24.4.16
#             * Old RSS is dead, my build script now parses the forum.
#             * Added /usr/doc/dropbox-$VER/folders to explain folder layout.
# 13/Mar/2017 * Updated to latest version 21.4.25
#             * Rewrote this script.
# 09/Feb/2017 * Updated to latest version 19.4.13
# 29/Nov/2016 * Updated to latest version 15.4.22
# 25/Oct/2016 * Updated to latest version 13.4.21
#               Later versions will be packaged to a txz. It saves ~18mb.
# 20/Sep/2016 * Updated to latest version 10.4.25
# 28/Aug/2016 * Updated to latest version 8.4.21
# 07/Aug/2016 * Updated to latest version 7.4.30
# 31/Jul/2016 * Updated to latest version 6.4.14
#             * Fixed my script to pick up Stable from the rss.
###

PRGNAM=dropbox
VERSION=${VERSION:-39.4.49}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

case "$ARCH" in
    x86_64) EXTPACKNAME="_64" ;;
         *) EXTPACKNAME=""   ;;
esac

set -e

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM
mkdir $PRGNAM
cd $PRGNAM
tar xvf $CWD/$PRGNAM-lnx.x86$EXTPACKNAME-$VERSION.tar.gz
cd .dropbox-dist
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p $PKG/opt/dropbox $PKG/usr/bin
cp -R . $PKG/opt/dropbox
ln -s /opt/dropbox/dropboxd $PKG/usr/bin/dropboxd
install -D -m 644 $CWD/dropbox.desktop $PKG/usr/share/applications/dropbox.desktop
install -D -m 644 $CWD/dropbox.png $PKG/usr/share/pixmaps/dropbox.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp $CWD/policies $PKG/usr/doc/$PRGNAM-$VERSION/
cp $CWD/folders $PKG/usr/doc/$PRGNAM-$VERSION/
cp $CWD/$PRGNAM.SlackBuild $PKG/usr/doc/$PRGNAM-$VERSION/

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
