#!/bin/sh

# Slackware build script for mit-scheme
# Originally by Jockey S. Kyd (jockey dot kyd at gmail dot com)
#
# Ryan P.C. McQuen | Everett, WA | ryanpcmcquen@member.fsf.org
# Copyright (C) 2018,2020 Jason Graham <jgraham@compukix.net>, USA
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version, with the following exception:
# the text of the GPL license may be omitted.

# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of
# merchantability or fitness for a particular purpose. Compiling,
# interpreting, executing or merely reading the text of the program
# may result in lapses of consciousness and/or very being, up to and
# including the end of all existence and the Universe as we know it.
# See the GNU General Public License for more details.

# You may have received a copy of the GNU General Public License
# along with this program (most likely, a file named COPYING).  If
# not, see <http://www.gnu.org/licenses/>.


PRGNAM=mit-scheme
VERSION=${VERSION:-10.1.11}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$(uname -m)" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$(uname -m) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
  TARARCH="i386"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
  TARARCH="i386"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
  TARARCH="x86-64"
else
  printf "$ARCH is not supported.\n" 1>&2
  exit 1
fi

X11=${X11:-yes}
EDWIN=${EDWIN:-yes}
IMAIL=${IMAIL:-yes}
DOCS=${DOCS:-no}

# Sanitize build settings and set additional flags
[ "$X11" != "yes" ] && X11="no" || WITH_X="--with-x"
[ "$EDWIN" != "yes" ] && EDWIN="no"
[ "$IMAIL" != "yes" ] && IMAIL="no"

set -e
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION-$TARARCH.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

cd src
CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      ./configure \
      --prefix=/usr \
      --libdir=/usr/lib$LIBDIRSUFFIX \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --mandir=/usr/man \
      --infodir=/usr/info \
      --docdir=/usr/doc/$PRGNAM-$VERSION \
      --disable-static \
      --build=$ARCH-slackware-linux \
      --enable-default-plugins=no \
      --enable-x11=${X11} \
      --enable-edwin=${EDWIN} \
      --enable-imail=${IMAIL} \
      $WITH_X
make
make install DESTDIR=$PKG

cd ../doc
CFLAGS="$SLKCFLAGS" \
      CXXFLAGS="$SLKCFLAGS" \
      ./configure \
      --prefix=/usr \
      --libdir=/usr/lib$LIBDIRSUFFIX \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --mandir=/usr/man \
      --infodir=/usr/info \
      --docdir=/usr/doc/$PRGNAM-$VERSION \
      --build=$ARCH-slackware-linux \
      --htmldir=/usr/doc/$PRGNAM-$VERSION/html \
      --pdfdir=/usr/doc/$PRGNAM-$VERSION/pdf \
      --enable-html=${DOCS} \
      --enable-pdf=${DOCS} \
      --enable-ps=no

    make install DESTDIR=$PKG
cd ../

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

rm -f $PKG/usr/info/dir
gzip -9 $PKG/usr/info/*.info*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a changelog.txt src/COPYING src/README.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
for i in usr/info/*.info*; do echo "info_install /$i" >> $PKG/install/doinst.sh; done

/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
