#!/bin/sh

# Slackware build script for icon

# Copyright 2013 Kyle Guinn <elyk03@gmail.com>, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=icon
VERSION=${VERSION:-9.5.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
	case "$(uname -m)" in
		i?86) ARCH=i486 ;;
		arm*) ARCH=arm ;;
		   *) ARCH=$(uname -m) ;;
	esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM-$VERSION
OUTPUT=${OUTPUT:-/tmp}

# Removed "-O2"; enabling optimization seems to cause
# "Run-time error 302", "memory violation"
# whenever running icon programs.
if [ "$ARCH" = "i486" ]; then
	SLKCFLAGS="-march=i486 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS=""
	LIBDIRSUFFIX=""
fi

PKGVERSION=$(echo $VERSION | tr -d .)
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-v${PKGVERSION}src
tar xvf $CWD/$PRGNAM-v${PKGVERSION}src.tgz || exit 1
cd $PRGNAM-v${PKGVERSION}src
chown -R root:root .
chmod -R u+w,go-w,a+rX-st .

# Let's put the package in /opt/icon instead of filling /usr/lib
# (and not a '/usr/lib/icon' subdirectory) with icon-related files.
# The makefile will attempt to create the /opt/icon directory, but
# doesn't use the -p option with mkdir, so we have to create only
# its parent directory first.
mkdir -p $PKG/opt
make X-Configure name=linux
make CFLAGS="$SLKCFLAGS"
make Install dest=$PKG/opt/icon

# Create symlinks from /usr/bin to /opt/icon/bin.
mkdir -p $PKG/usr/bin
for i in icon icont iconx vib; do
	ln -s ../../opt/icon/bin/$i $PKG/usr/bin/$i
done

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Move man pages and docs to their usual locations.
mkdir -p $PKG/usr/doc
mv $PKG/opt/icon/man $PKG/usr/man
mv $PKG/opt/icon/doc $PKG/usr/doc/$PRGNAM-$VERSION
mv $PKG/opt/icon/README $PKG/usr/doc/$PRGNAM-$VERSION

find $PKG/usr/man -type f -exec gzip -9 {} \;

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
