# pod source for jaaa man page
# pod2man -s1 -r0.8.4 --stderr -nJAAA -cSlackBuilds.org < jaaa.pod > jaaa.1

=pod

=head1 NAME

jaaa - JACK and ALSA Audio Analyser

=head1 SYNOPSIS

jaaa I<options>

=head1 DESCRIPTION

jaaa is an audio signal generator and spectrum analyser designed to make
accurate measurements.

=head1 OPTIONS

Either B<-J> or B<-A> is required.

=over

=item -h

Display this text

=item -name <name>

JACK and X11 name

=item -J

Use JACK, with options:

=over

=item -s <server>

Select JACK server

=back

=item -A

Use ALSA, with options:

=over

=item -d <device>

ALSA device [hw:0]

=item -C <device>

Capture device

=item -P <device>

Playback device

=item -r <rate>

Sample frequency [48000]

=item -p <period>

Period size [1024]

=item -n <nfrags>

Number of fragments [2]

=back

=back

=head1 AUTHOR

(C) 2004-2010 Fons Adriaensen  <fons@kokkinizita.net>
