#!/bin/bash
#
#          DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                   Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#          DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#
# 0. You just DO WHAT THE FUCK YOU WANT TO.
#
# SlackBuild script for aerc
# ===========================
# By:          r1w1s1 (https://fosstodon.org/@r1w1s1)
# For:         aerc
# Descr:       aerc is an email client that runs in your terminal
# URL:         https://aerc-mail.org/
# Changelog:
# v0.17.0:     29/jun/2024 by r1w1s1 - Initial build.
# v0.18.0:     02/jul/2024 by r1w1s1
# v0.18.2:     09/sep/2024 by r1w1s1
# v0.19.0:     15/jan/2025 by r1w1s1
# v0.20.0:     25/jan/2025 by r1w1s1
# v0.20.1:     01/feb/2025 by r1w1s1
# v0.21.0:     28/ago/2025 by r1w1s1

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=aerc
VERSION=${VERSION:-0.21.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

set -e

TMP=${TMP:-/tmp/SBo}
PKG=${TMP}/package-${PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

rm -rf "$PKG"
mkdir -p "$TMP" "$PKG" "$OUTPUT"
cd "$TMP"

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "aarch64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

rm -rf ${PRGNAM}-${VERSION}
tar xvf $CWD/${PRGNAM}-${VERSION}.tar.gz || tar xvf $CWD/$VERSION.tar.gz
cd ${PRGNAM}-${VERSION}
make PREFIX=/usr

make install PREFIX=/usr DESTDIR="$PKG"

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p "$PKG/usr/doc/${PRGNAM}-${VERSION}"
cp -a CHANGELOG.md CONTRIBUTING.md README.md LICENSE MAINTAINERS \
    $PKG/usr/doc/${PRGNAM}-${VERSION}

mv $PKG/usr/share/man $PKG/usr/
find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

cat $CWD/${PRGNAM}.SlackBuild > $PKG/usr/doc/${PRGNAM}-${VERSION}/${PRGNAM}.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
