#!/bin/sh

# Slackware build script for MultiTail
# Written by Erik Hanson  erik@slackbuilds.org

set -eu

PRGNAM=multitail
VERSION=5.2.2
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tgz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Fix our destination
sed -i "s|DESTDIR=/|DESTDIR=$PKG|" Makefile
sed -i "s|/usr/share|/usr|" Makefile

# Create a landing pad
mkdir -p $PKG/usr/{bin,doc,man/man1} $PKG/etc $PKG/install

# Compile and Install
CFLAGS="$SLKCFLAGS" make install
strip --strip-unneeded $PKG/usr/bin/multitail

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
