.\"                                      Hey, EMACS: -*- nroff -*-
.TH VSID 1 "August 19, 2021" SlackBuilds.org
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
vsid \- Play Commdore 64 SID music files
.SH SYNOPSIS
.B vsid
.RI [vice-options]
.RI musicfile.sid
.SH DESCRIPTION
.B vsid
passes a Commodore 64 SID music file to the VICE x64 emulator, which
then plays the default song. Any options given will also be passed to
the emulator; in particular, use \fB\-sounddev <pulse|alsa|sdl>\fR
to choose audio driver.
.SH SEE ALSO
.BR x64 (1),
.BR sidplay (1).
.SH AUTHOR
This manual page was written by Zed Pobre <zed@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
It was modified by B. Watson <yalhcru@gmail.com> for the
SlackBuilds.org project.
