#!/bin/bash
# Slackware build script for Android Studio for Platform

# Copyright 2012-2017  Roberto Metere, Cagliari (CA), Italy <roberto@metere.it>
# Updated 2025, Lockywolf
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=android-studio-for-platform
VERSION=${VERSION:-2025.1.3.7}
BUILD=${BUILD:-1}
ARCH=${ARCH:-$(uname -m)}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

PKGNAM="asfp-*-$VERSION-linux.deb"


if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=${TMP}/package-${PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

if [ "${ARCH}" != "x86_64" ]; then
  echo "Architecture ${ARCH} is not supported."
  exit 1
fi

set -e

rm -rf ${PKG}
mkdir -p ${TMP} ${PKG}/opt ${OUTPUT}
cd ${PKG}/opt

cd "$TMP"
mkdir -p "$PRGNAM"-temp
cd "$PRGNAM"-temp

ar x ${CWD}/${PKGNAM}
tar xvf data.tar.gz
cd tmp
mv -- * ${PKG}/opt

cd ${PKG}/opt

chown -R root:root .

find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
    -o -perm 511 \) -exec chmod 755 {} + -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
    -o -perm 440 -o -perm 400 \) -exec chmod 644 {} +

(
  cd android-studio-for-platform-Stable.3.7
  chmod +x plugins/webp/lib/libwebp/linux/libwebp_jni.so \
 plugins/design-tools/resources/layoutlib/data/linux/lib64/libandroid_runtime.so \
 plugins/design-tools/resources/layoutlib/data/linux/lib64/layoutlib_jni.so \
plugins/c-clangd/bin/clang/linux/x64/bin/libc++.so.1 \
plugins/android-ndk/resources/lldb/lib64/libxml2.so.2 \
plugins/android-ndk/resources/lldb/lib64/libpython3.11.so.1.0 \
plugins/android-ndk/resources/lldb/lib64/libpanel.so.6 \
plugins/android-ndk/resources/lldb/lib64/libncurses.so.6 \
plugins/android-ndk/resources/lldb/lib64/liblldb.so \
plugins/android-ndk/resources/lldb/lib64/libform.so.6 \
plugins/android-ndk/resources/lldb/lib64/libedit.so.0 \
plugins/android-ndk/resources/lldb/lib64/libc++abi.so.1 \
plugins/android-ndk/resources/lldb/lib64/libc++.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/zlib.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/xxlimited_35.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/xxlimited.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/unicodedata.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/termios.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/syslog.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/spwd.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/select.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/resource.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/pyexpat.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/ossaudiodev.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/nis.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/mmap.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/math.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/grp.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/fcntl.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/cmath.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/binascii.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/audioop.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/array.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_zoneinfo.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_xxtestfuzz.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_xxsubinterpreters.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_typing.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testmultiphase.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testinternalcapi.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testimportmultiple.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testclinic.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testcapi.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_testbuffer.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_struct.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_statistics.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_socket.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_sha512.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_sha3.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_sha256.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_sha1.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_random.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_queue.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_posixsubprocess.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_posixshmem.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_pickle.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_opcode.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_multiprocessing.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_multibytecodec.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_md5.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_lsprof.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_json.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_heapq.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_elementtree.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_decimal.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_datetime.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_curses_panel.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_curses.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_ctypes_test.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_ctypes.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_csv.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_crypt.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_contextvars.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_tw.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_kr.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_jp.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_iso2022.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_hk.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_codecs_cn.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_bz2.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_blake2.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_bisect.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/python3.11/lib-dynload/_asyncio.cpython-311-x86_64-linux-gnu.so \
plugins/android-ndk/resources/lldb/lib/libc++.so \
plugins/android/resources/transport/x86_64/transport \
plugins/android/resources/transport/x86/transport \
plugins/android/resources/transport/native/agent/x86_64/libjvmtiagent.so \
plugins/android/resources/transport/native/agent/x86/libjvmtiagent.so \
plugins/android/resources/screen-sharing-agent/x86_64/libscreen-sharing-agent.so \
plugins/android/resources/screen-sharing-agent/x86/libscreen-sharing-agent.so \
plugins/android/resources/process-tracker-agent/native/x86_64/process-tracker \
plugins/android/resources/process-tracker-agent/native/x86/process-tracker \
plugins/android/resources/native/libjni_object_tagger.so \
plugins/android/resources/native/libimage_converter.so \
plugins/android/resources/installer/x86_64/installer \
plugins/android/resources/installer/x86/installer \
lib/pty4j/linux/x86-64/libpty.so \
lib/native/linux-x86_64/libsqliteij.so \
lib/jna/amd64/libjnidispatch.so \
jbr/lib/server/libjvm.so \
jbr/lib/server/libjsig.so \
jbr/lib/libzip.so \
jbr/lib/libwlsplashscreen.so \
jbr/lib/libverify.so \
jbr/lib/libsyslookup.so \
jbr/lib/libsplashscreen.so \
jbr/lib/libsctp.so \
jbr/lib/libsaproc.so \
jbr/lib/librmi.so \
jbr/lib/libprefs.so \
jbr/lib/libnio.so \
jbr/lib/libnet.so \
jbr/lib/libmlib_image.so \
jbr/lib/libmanagement_ext.so \
jbr/lib/libmanagement_agent.so \
jbr/lib/libmanagement.so \
jbr/lib/lible.so \
jbr/lib/liblcms.so \
jbr/lib/libjsound.so \
jbr/lib/libjsig.so \
jbr/lib/libjli.so \
jbr/lib/libjimage.so \
jbr/lib/libjdwp.so \
jbr/lib/libjawt.so \
jbr/lib/libjavajpeg.so \
jbr/lib/libjava.so \
jbr/lib/libjaas.so \
jbr/lib/libj2pkcs11.so \
jbr/lib/libj2pcsc.so \
jbr/lib/libj2gss.so \
jbr/lib/libinstrument.so \
jbr/lib/libfontmanager_xawt.so \
jbr/lib/libfontmanager.so \
jbr/lib/libextnet.so \
jbr/lib/libdt_socket.so \
jbr/lib/libawt_xawt.so \
jbr/lib/libawt_wlawt.so \
jbr/lib/libawt_headless.so \
jbr/lib/libawt.so \
jbr/lib/libattach.so
)

# Add android studio to KDE/GNOME/XFCE menu
install -D -m 644 ${CWD}/${PRGNAM}.desktop \
        ${PKG}/usr/share/applications/${PRGNAM}.desktop
sed -i 's|@TEMPLATE@|/opt/android-studio-for-platform-Stable.3.7/bin/studio.sh|g' ${PKG}/usr/share/applications/${PRGNAM}.desktop

install -D -m 644 $PKG/opt/${PRGNAM}-Stable.3.7/bin/studio.svg ${PKG}/usr/share/pixmaps/${PRGNAM}.svg

install -D -m 755 ${CWD}/${PRGNAM}.bash ${PKG}/usr/bin/${PRGNAM}
install -D -m 755 ${CWD}/${PRGNAM}-inspect.bash ${PKG}/usr/bin/${PRGNAM}-inspect

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p ${PKG}/usr/doc/${PRGNAM}-${VERSION}
cp -a \
  $PKG/opt/${PRGNAM}-Stable.3.7/{Install-Linux-tar.txt,LICENSE.txt,NOTICE.txt,build.txt,product-info.json} \
  ${PKG}/usr/doc/${PRGNAM}-${VERSION}
cat ${CWD}/${PRGNAM}.SlackBuild > \
  ${PKG}/usr/doc/${PRGNAM}-${VERSION}/${PRGNAM}.SlackBuild

mkdir -p ${PKG}/install
cat ${CWD}/slack-desc > ${PKG}/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd ${PKG}
/sbin/makepkg -l y -c n ${OUTPUT}/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.$PKGTYPE
