#!/bin/bash

# Slackware build script for man-pages-ja

# Written by B. Watson (urchlay@slackware.uk)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20260830 bkw: BUILD=2, fix conflicts with core Slackware.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=man-pages-ja
VERSION=${VERSION:-20221215}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz --no-same-owner
cd $PRGNAM-$VERSION
find . ! -type l    -a \( \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \) \)

# I'm almost certain this is correct, based on how other distros do it.
# The other possibility was "ja.UTF-8". A /usr/man/jp dir does exist on
# Slackware (containing cdparanoia's man pages), but it shouldn't.
MANLANG=ja

# this thing uses an interactive script with lots of prompts, not
# suited to automated builds. the patch just makes the script read
# from the environment instead of stdin, and gets rid of the 120 or
# so prompts for the sub-package conflicts (just taking the default).

patch -p1 < $CWD/noninteractive_install.diff
MANROOT=$PKG/usr/man/$MANLANG make config
make install

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
cp -a README $PKGDOC
cat $CWD/README > $PKGDOC/README_SBo.txt
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG

# 20260830 bkw: Lots of conflicts with Slackware.
rm -f $( cat $CWD/conflicts )

# 20260830 bkw: Don't need this either:
rmdir usr/man/ja/man9

/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
