#!/bin/bash

# Slackware build script for RapidSVN

# Written by <youngmug@animeneko.net>
# Currently maintained by David Delansay

# 20220308 bkw: Modified by SlackBuilds.org, BUILD=4:
# - fix wxPython/wxGTK3 conflict.
# - don't try to build API docs with doxygen (it fails).
# - fix download URL (original went away).

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=rapidsvn
VERSION=${VERSION:-0.12.1}
BUILD=${BUILD:-4}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \+ -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+

# Thanx Archlinux!
patch -p1 < $CWD/rapidsvn-wx3.0.patch

# Reworked from KDE kdevplatform to build with subversion 1.9
# https://quickgit.kde.org/?p=kdevplatform.git&a=commit&h=8117ca137b45816865554d6e86b96d9e633a7e08
patch -p1 < $CWD/subversion1.9.patch

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS -std=c++14" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --with-apr-config=apr-1-config \
  --with-apu-config=apu-1-config \
  --with-wx-config=/usr/lib$LIBDIRSUFFIX/wx/config/gtk3-unicode-3.0 \
  --without-doxygen \
  --disable-static \
  --build=$ARCH-slackware-linux

make
make install-strip DESTDIR=$PKG

# Add a desktop file and the program icon
mkdir -p $PKG/usr/share/{applications,pixmaps}
install -m 0644 $CWD/rapidsvn.desktop $PKG/usr/share/applications
cat src/res/bitmaps/rapidsvn_128x128.png > $PKG/usr/share/pixmaps/rapidsvn.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS CHANGES COPYING ChangeLog FDL.txt GPL.txt HACKING.txt INSTALL \
  LICENSE.txt NEWS README TRANSLATIONS  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

rm -f $PKG/usr/lib*/*.la

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
