#!/bin/sh
# Slackware build script for thunderpad
# Ryan P.C. McQuen | Everett, WA | ryan.q@linux.com

# Thanks to B. Watson

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version, with the following exception:
# the text of the GPL license may be omitted.

# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of
# merchantability or fitness for a particular purpose. Compiling,
# interpreting, executing or merely reading the text of the program
# may result in lapses of consciousness and/or very being, up to and
# including the end of all existence and the Universe as we know it.
# See the GNU General Public License for more details.

# You may have received a copy of the GNU General Public License
# along with this program (most likely, a file named COPYING). If
# not, see <http://www.gnu.org/licenses/>.

PRGNAM=thunderpad
SRCNAM=Thunderpad
VERSION=${VERSION:-20150716}
SRCVERSION=${SRCVERSION:-5d3cbbc3d885fc5eabf0c2e50f25c76403706c08}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

DOCS="contributors.txt license.txt readme.md"

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -pv $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$SRCVERSION
if [ -e $CWD/$SRCVERSION.tar.gz ]; then
  tar xvf $CWD/$SRCVERSION.tar.gz
else
  tar xvf $CWD/$SRCNAM-$SRCVERSION.tar.gz
fi
cd $SRCNAM-$SRCVERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

## remove CR line endings
sed -i 's,\r,,' data/linux/$PRGNAM.desktop *.txt *.md

mkdir -p build
cd build

qmake \
  PREFIX=/usr \
  LIBDIR=/usr/lib${LIBDIRSUFFIX} \
  QMAKE_CFLAGS="$SLKCFLAGS" \
  QMAKE_CXXFLAGS="$SLKCFLAGS" \
  ../thunderpad.pro CONFIG+=release

make \
  OPTS="$SLKCFLAGS" \
  LIBDIR=/usr/lib${LIBDIRSUFFIX} \
  PREFIX=/usr

make install \
  INSTALL_ROOT=$PKG \
  DESTDIR=$PKG

cd ../

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
