.TH GUITARIX "1" "October 2012" "SlackBuilds.org" "User Commands"
.SH NAME
guitarix \- guitar amp simulator and effects processor
.SH SYNOPSIS
.B guitarix
.RI [ options ]
.SH DESCRIPTION
.B Guitarix
is a rock guitar amplifier for Jack (Jack Audio Connection Kit) with one input
and two outputs. It is designed to get nice trash/metal/rock guitar sounds.
Guitarix comes with a GTK+ graphical user interface and a set of LADSPA
plugins. This manual page describes the GTK+ interface.
.PP
Guitarix provides one JACK input port and two JACK output ports.
Controls for bass, treble, gain, compressor, preamp, balance, distortion,
freeverb, crybaby (wah) and echo are available. A fixed resonator is
used when distortion is disabled. To modify the sound 'pressure', you
can use the feedback and feedforward sliders.
.PP
Guitarix includes an experimental tuner and a JACK MIDI output port
with 3 channels. They are fed by a mix from a pitch tracker and a
beat detector. You can pitch the octave (2 octaves up or down), choose the
MIDI channel, the MIDI program, the velocity and the sensitiviy, which
translates into how fast the note will read after the beat detector
emits a signal. Values for the beat detector can be set for all
channels.
.SH OPTIONS
All parameters are optional. Examples:
.IP
guitarix
.br
guitarix \fB\-r\fR gx4\-black \fB\-i\fR system:capture_3
.br
guitarix \fB\-c\fR \fB\-o\fR system:playback_1 \fB\-o\fR system:playback_2
.SS "Help Options"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-style\fR
GTK style configuration options
.TP
\fB\-\-help\-jack\fR
JACK configuration options
.TP
\fB\-\-help\-file\fR
File options
.TP
\fB\-\-help\-debug\fR
Debug options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.SS
GTK style configuration options
.TP
\fB\-c\fR, \fB\-\-clear\fR
Use 'default' GTK style
.TP
\fB\-r\fR, \fB\-\-rcset\fR=\fISTYLE\fR
Style to use, 'gx1\-alloy', 'gx2\-emerald', 'gx3\-dezert', 'gx4\-black', 'gx5\-gree'
.SS "JACK Configuration Options"
.TP
\fB\-i\fR, \fB\-\-jack\-input\fR=\fIPORT\fR
Guitarix JACK input
.TP
\fB\-o\fR, \fB\-\-jack\-output\fR=\fIPORT\fR
Guitarix JACK outputs
.TP
\fB\-m\fR, \fB\-\-jack\-midi\fR=\fIPORT\fR
Guitarix JACK MIDI control
.TP
\fB\-J\fR, \fB\-\-jack\-no\-conect\fR
dissable self\-connect JACK ports
.TP
\fB\-n\fR, \fB\-\-name\fR=\fINAME\fR
instance name (default gx_head)
.TP
\fB\-U\fR, \fB\-\-jack\-uuid\fR
JackSession ID
.TP
\fB\-A\fR, \fB\-\-jack\-uuid2\fR
JackSession ID
.TP
\fB\-s\fR, \fB\-\-server\-name\fR=\fINAME\fR
JACK server name to connect to
.SS "File Options"
.TP
\fB\-f\fR, \fB\-\-load\-file\fR=\fIFILE\fR
load state file on startup
.TP
\fB\-P\fR, \fB\-\-plugin\-dir\fR=\fIDIR\fR
directory with guitarix plugins (.so files)
.TP
\fB\-K\fR, \fB\-\-dissable\-auto\-save\fR
dissable auto save to state file when quit
.SS "Debug Options"
.TP
\fB\-B\fR, \fB\-\-builder\-dir\fR=\fIDIR\fR
directory from which .glade files are loaded
.TP
\fB\-S\fR, \fB\-\-style\-dir\fR=\fIDIR\fR
directory with skin style definitions (.rc files)
.TP
\fB\-t\fR, \fB\-\-log\-terminal\fR
print log on terminal
.TP
\fB\-d\fR, \fB\-\-dump\-parameter\fR
dump parameter table in JSON format
.SS "GTK+ Options"
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-gtk\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.SS "Application Options"
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version string and exit
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH AUTHORS
Guitarix is Copyright (c) 2010 Hermman Meyer \- James Warden \- Andreas Degert
.PP
This man page was created for the SlackBuilds.org project by B. Watson, but it can
be used by anyone.
