#!/bin/sh

# Slackware build script for gp2fasta
# Written by Petar Petrov, <ppetrov@paju.oulu.fi> and 
# hereby submitted to the public domain

# The icon used by the gp2fasta.desktop file is taken from 
# http://kde-look.org/content/show.php/Fasta+icons?content=54012 
# Author is Luis-Miguel Rodriguez. Thank you!

# THIS SLACKBUILD IS DISTRIBUTETD IN THE HOPE OF BEING 
# USEFUL BUT WITHOUT ANY WARRANTY. THE AUTHOR IS _NOT_ 
# RESPONSIBLE FOR ANY DAMAGE OR DATA LOSS CAUSED BY IT.

PRGNAM=gp2fasta			
VERSION=${VERSION:-0.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}	

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
unzip $CWD/$PRGNAM.zip
cd $PRGNAM
# Remove the precompiled binary just in case
rm gp2fasta

chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

qmake -project
qmake

# Use our CFLAGS
sed -i "/^C.*.*FLAGS/s/=/+=/" Makefile

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
  make

install -D -m755 gp2fasta $PKG/usr/bin/gp2fasta

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  example.gp README \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# Menu item and icon
mkdir -p $PKG/usr/share/{applications,pixmaps}
cp $CWD/$PRGNAM.desktop $PKG/usr/share/applications/
cp $CWD/$PRGNAM.png $PKG/usr/share/pixmaps/ 

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
