#!/bin/sh

# Slackware build script for fortune_firefly

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20180209 bkw: homepage went away again, use someone's github mirror
# of the now-vanished fedora repo.

# 20140825 bkw:
# - update for 2.1.2, which fixes some typos
# - hosting the source myself now
# - homepage went away, so use fedora's cgit for homepage

PRGNAM=fortune_firefly
SRCNAM=firefly
VERSION=${VERSION:-2.1.2}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $PKG $OUTPUT

mkdir -p $PKG/usr/share/games/fortunes
cd $PKG/usr/share/games/fortunes
xzcat $CWD/$SRCNAM-$VERSION.xz > $SRCNAM

rm -f $SRCNAM.dat
strfile $SRCNAM

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
