#!/bin/sh

# Slackware build script for podofo

# Written by Larry Hajali <larryhaja[at]gmail[dot]com>

PRGNAM=podofo
VERSION=0.9.1
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX="FALSE"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX="FALSE"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="TRUE"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX="FALSE"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fix mandir directory.
sed -i 's|share/man|man|' CMakeLists.txt

# Fix building with gcc-4.7.x
# http://sourceforge.net/tracker/?func=detail&aid=3474494&group_id=154028&atid=790130
patch -p1 < $CWD/podofo-0.9.1-unistd.patch

mkdir build
cd build
  cmake -G "Unix Makefiles" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DPODOFO_BUILD_STATIC:BOOL=FALSE \
    -DPODOFO_BUILD_SHARED:BOOL=TRUE \
    -DPODOFO_USE_VISIBILITY=1 \
    -DWANT_BOOST:BOOL=0 \
    -DWANT_LIB64:BOOL=$LIBDIRSUFFIX \
    -DCMAKE_BUILD_TYPE=Release ..

  make VERBOSE=1
  make install DESTDIR=$PKG
cd -

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  AUTHORS ChangeLog CODING* CONTRIBUTIONS* COPYING* FAQ* INSTALL README* TODO \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
