diff -Naur blobAndConquer-0.7.orig/makefile blobAndConquer-0.7/makefile
--- blobAndConquer-0.7.orig/makefile	2006-12-06 14:42:21.000000000 -0600
+++ blobAndConquer-0.7/makefile	2006-12-17 02:33:14.000000000 -0600
@@ -13,7 +13,7 @@
 PREFIX = $(DESTDIR)/usr
 BINDIR = $(PREFIX)/games
 DATADIR = $(PREFIX)/share/games/blobAndConquer
-DOCDIR = $(PREFIX)/share/doc/$(PROG)
+DOCDIR = $(PREFIX)/doc/$(PROG)-$(VERSION).$(RELEASE)
 ICONDIR = $(PREFIX)/share/icons
 MENUDIR = $(PREFIX)/share/applications
 
@@ -81,6 +81,8 @@
 	mkdir -p $(BINDIR)
 	mkdir -p $(DATADIR)
 	mkdir -p $(DOCDIR)
+	mkdir -p $(ICONDIR)
+	mkdir -p $(MENUDIR)
 
 	cp $(PROG) $(BINDIR)/$(PROG)
 	
@@ -90,7 +92,7 @@
 	cp -R sound $(DATADIR)
 	cp -R textures $(DATADIR)
 	
-	cp -R doc $(DOCDIR)
+	cp -R doc/* $(DOCDIR)
 		
 	cp icons/blobAndConquer.png $(ICONDIR)
 	cp icons/blobAndConquer.desktop $(MENUDIR)
