.TH ATARICOM "1" "April 2009" "ataricom (atarisio 0.30)" "HiassofT Atari 8-bit Tools"
.SH NAME
ataricom \- utility for manipulating Atari 8\-bit executable files
.SH SYNOPSIS
ataricom [\fIoptions\fR]... file [outfile]
.SH DESCRIPTION
ataricom performs various useful operations on Atari 8\-bit executable
files. These files are also known as binary load files, or COM, BIN, XEX, OBJ, OBX, et al. These
are only names; there is only one Atari 8\-bit executable file format.
.SH OPTIONS
.TP
\fB\-c\fR address
create COM file from raw data file
.TP
\fB\-r\fR address
add RUN block with specified address at end of file
.TP
\fB\-i\fR address
add INIT block with specified address at end of file
.TP
\fB\-b\fR start[\-end]
only process specified blocks
.TP
\fB\-x\fR start[\-end]
exclude specified blocks
.TP
\fB\-m\fR start\-end
merge specified blocks
.HP
\fB\-s\fR block,adr... split block at given addresses
.TP
\fB\-n\fR
write raw data blocks (no COM headers)
.SH AUTHOR
Matthias Reichl <\fBhias@horus.com\fR>
.PP
Man page by B. Watson <\fBurchlay@urchlay.com\fB>
.SH SEE ALSO
\&\fIatariserver\fR\|(1), \&\fIdir2atr\fR\|(1), \&\fIadir\fR\|(1).
.PP
AtariSIO home page: \fBhttp://www.horus.com/~hias/atari/\fR
