.TH ATR2ATP "1" "April 2009" "atr2atp (atarisio 0.30)" "HiassofT Atari 8-bit Tools"
.SH NAME
atr2atp \- converts a ATR\-format Atari 8\-bit disk image to the experimental
ATP format supported by atariserver.
.SH SYNOPSIS
atr2atp [input-file] [output-file]
.SH DESCRIPTION
The ATP format is intended as an open source replacement for the proprietary
APE PRO and VAPI formats. Currently, ATP is very limited in its capabilities.
atr2atp is primarily useful for testing, and for development of the ATP
format itself.
.SH AUTHOR
Matthias Reichl <\fBhias@horus.com\fR>
.PP
Man page by B. Watson <\fBurchlay@urchlay.com\fB>
.SH SEE ALSO
\&\fIatariserver\fR\|(1), \&\fIdir2atr\fR\|(1), \&\fIadir\fR\|(1), \&\fIatpdump\fR\|(1).
.PP
AtariSIO home page: \fBhttp://www.horus.com/~hias/atari/\fR
