.TH CASINFO "1" "April 2009" "casinfo (atarisio 0.30)" "HiassofT Atari 8-bit Tools"
.SH NAME
casinfo \- Get information on an Atari 8\-bit cassette image file
.SH SYNOPSIS
casinfo file [file] ...
.SH DESCRIPTION
For each valid cassette image (CAS file) on the command line, casinfo
will display the description (if any), the number of parts (aka load
stages), the number of blocks, and the block header information for
each block in the file.
.PP
casinfo takes no options.
.PP
For a complete specification of the CAS file format, see the documentation
for \fBcas2wav\fR, \fBwav2cas\fR, and/or \fBcassio\fR, all available
at a web browser near you...
.SH AUTHOR
Matthias Reichl <\fBhias@horus.com\fR>
.PP
Man page by B. Watson <\fBurchlay@urchlay.com\fB>
.SH SEE ALSO
\&\fIatariserver\fR\|(1), \&\fIdir2atr\fR\|(1), \&\fIadir\fR\|(1).
.PP
AtariSIO home page: \fBhttp://www.horus.com/~hias/atari/\fR
