#!/bin/sh

# Slackware build script for supertuxkart-extra-karts

# Written by Larry Hajali <larryhaja[at]gmail[dot]com>

PRGNAM=supertuxkart-extra-karts
SRCNAM=karts
VERSION=${VERSION:-0.6.1a}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
7z x $CWD/$SRCNAM.7z
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

install -d -m 0755 $PKG/usr/share/supertuxkart/data
cp -ar $SRCNAM $PKG/usr/share/supertuxkart/data

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Remove MacOSX specific files and misc. cleanup.
find $PKG -name ".DS_Store" -exec rm -f {} \;
find $PKG -name "*~" -exec rm -f {} \;

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/COPYING > $PKG/usr/doc/$PRGNAM-$VERSION/COPYING
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
