#!/bin/bash

# Slackware build script for doom_shareware_data

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20211005 bkw: original FTP site is gone, use new download link.
# Also, don't extract the files we don't need.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=doom_shareware_data
VERSION=${VERSION:-1.9}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir -p $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
unzip $CWD/doom19s.zip '*.1' '*.2'
chown -R root:root .
chmod 644 *

# Zip file is split into 2 chunks
cat DOOMS_19.1 DOOMS_19.2 > doomtmp.zip
unzip doomtmp.zip '*.WAD' 'DMFAQ*.*'
mkdir -p $PKG/usr/share/games/doom
install -m0644 DOOM1.WAD $PKG/usr/share/games/doom/doom1.wad

# Keep the Doom FAQ, but ditch the archaic DOS-specific docs.
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
sed 's/\r//' DMFAQ*TXT > $PKG/usr/doc/$PRGNAM-$VERSION/doomfaq-v6_666.txt

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
