.TH O2EM "1" "January 2011" "SlackBuilds.org" "User Commands"
.SH NAME
o2em \- Emulator for Odyssey II and VideoPac+ systems
.SH SYNOPSIS
.B o2em
<\fIfile\fR>
[\fI-options\fR]
.SH DESCRIPTION
O2EM is an open source Odyssey2 / Videopac console emulator.
.SH OPTIONS
.TP
\fBfile\fR
Cartridge ROM image.
.br
\fINOTE:\fR Unlike most programs, o2em requires the file argument
first, before any options.
.TP
\fB\-help\fR
Help display
.TP
\fB\-wsize\fR=n
Window size (1\-4)
.TP
\fB\-fullscreen\fR
Full screen mode
.TP
\fB\-help\fR
Show help
.TP
\fB\-scanlines\fR
Enable scanlines
.TP
\fB\-nosound\fR
Turn off sound emulation
.TP
\fB\-novoice\fR
Turn off voice emulation
.TP
\fB\-svolume\fR=n
Set sound volume (0\-100)
.TP
\fB\-vvolume\fR=n
Set voice volume (0\-100)
.TP
\fB\-filter\fR
Enable low-pass audio filter
.TP
\fB\-debug\fR
Start the emulator in 
debug mode
.TP
\fB\-speed\fR=n
Relative speed
(100 = original)
.TP
\fB\-nolimit\fR
Turn off speed limiter
.TP
\fB\-bios\fR=file
Set the O2 bios file name/dir
.TP
\fB\-biosdir\fR=path
Set the O2 bios path 
(default= bios/)
.TP
\fB\-romdir\fR=path
Set the O2 roms Path 
(default= roms/)
.TP
\fB\-scshot\fR=file
Set the screenshot file 
name/template
.TP
\fB\-euro\fR
Use European timing /
50Hz mode
.TP
\fB\-exrom\fR
Use special 3K program/
1K data ROM mode
Use 3K rom mapping mode
.TP
\fB\-s<n>\fR=mode/keys
Define stick n mode/keys (n=1\-2, see \fBo2em.txt\fR)
.TP
\fB\-c52\fR
Start the emulator with 
french Odyssey 2 BIOS
.TP
\fB\-g7400\fR
Start the emulator 
with VP+ BIOS
.TP
\fB\-jopac\fR
Start the emulator with 
french VP+ bios
.TP
\fB\-scoretype\fR=m
Set Scoretype to m (see \fBo2em.txt\fR)
.TP
\fB\-scoreadr\fR=n
Set Scoreaddress to n 
(decimal value)
.TP
\fB\-scorefile\fR=file
Set Output-Scorefile to 
file (highscore.txt)
.TP
\fB\-score\fR=n
Set Highscore to n
.TP
\fB\-savefile\fR=file
Load/Save State 
from/to file
.SH KEY BINDINGS
These are the default key bindings, and can be changed
on the command line or in the config file.
.TP
\fBArrow keys + L\fR
Default joystick 1 emulation
.TP
\fBW,D,S,A + Space\fR
Default joystick 2 emulation
.TP
\fBESC or F12\fR
Leave the emulator
.TP
\fBF1\fR
Pause/Information
.TP
\fBF2\fR
Save State\-File
.TP
\fBF3\fR
Load State\-File
.TP
\fBF4\fR
Enter debugger
.TP
\fBF5\fR
Reset emulator (same as pressing the reset on the O2 keyboard)
.TP
\fBF6\fR
Inject Highscore
.TP
\fBF8\fR
Make a screen shot
.TP
\fBCaps Lock\fR
Enables/Disables the O2 keyboard input of the keys used by
joystick emulation
.SH FILES
.TP
\fB/usr/bin/o2em\fR
Shell script wrapper. Sets up ~/.o2em if needed, runs the actual
binary. This is required because o2em was ported from DOS, and
expects to be run in its own directory; with the wrapper, it
behaves like a proper UNIX program (run anywhere, writes only
to ~/.o2em).
.TP
\fB/usr/libexec/o2em.bin\fR
The actual o2em binary. Normally, you don't want to run this
directly (let the wrapper run it for you).
.TP
\fB/usr/share/o2em/bios\fR
BIOS ROM images. At minimum, \fBo2rom.bin\fR must exist. To use the
\fB\-c52\fR,
\fB\-jopac\fR, or
\fB\-g7400\fR
options, the appropriate BIOS image must be located here (see below).
The emulator checks the CRC of the ROM images,
and will refuse to start with an image it doesn't recognize. The correct
files are:
.PP
c52.bin (md5sum f1071cdb0b6b10dde94d3bc8a6146387)
.br
g7400.bin (md5sum c500ff71236068e0dc0d0603d265ae76)
.br
jopac.bin (md5sum 279008e4a0db2dc5f1c048853b033828)
.br
o2rom.bin (md5sum 562d5ebf9e030a40d6fabfc2f33139fd)
.PP
These are the same files used by MESS, except o2rom.bin is called
o2bios.rom by MESS.
.TP
\fB/usr/share/o2em/voice\fR
Voice samples, used to emulate the Odyssey2's speech synthesis chip.
.TP
\fB~/.o2em/\fR
Working directory for o2em. Will be created by shell script wrapper
the first time it's run. All save\-state and screenshot files will be
written here. The BIOS image, cartridge images, and voice samples will
be symlinked into this directory by the wrapper script.
.TP
\fB~/.o2em/o2em_def.cfg\fR
Config file (optional). See o2em.txt for details.
.TP
\fB/usr/doc/o2em\-\fR\fI$VERSION\fR\fB/o2em.txt\fR
Full documentation for o2em.
.SH AUTHORS
o2em was originally created by Daniel Boris, and has been developed by
Andre de la Rocha since version 0.80 and Arlindo M. de Oliveira since version 1.16.
.PP
This manual page was written by B. Watson for the SlackBuilds.org project (but
may be used by anyone for any reason).
.PP
Wrapper script also by B. Watson.
