.TH SNES9X-GTK 6 "22 OCT 2009" "SlackBuilds.org Project" "Slackware Linux"
.SH NAME
snes9x-gtk \- Super Nintendo Entertainment System emulator
.SH SYNOPSIS
.B snes9x\-gtk
[\-filter \fItype\fR]
[\-mutesound]
[\fIrom\-file]
.SH DESCRIPTION
Snes9x is a portable, freeware Super Nintendo Entertainment System (SNES)
emulator. It basically allows you to play most games designed for the SNES
and Super Famicom Nintendo game systems on your PC or Workstation; they
include some real gems that were only ever released in Japan.
.PP
.B snes9x\-gtk
is an unofficial port of Snes9x with a GTK+ graphical frontend.
.PP
With no ROM file argument, snes9x\-gtk will start its graphical user interface.
When a ROM file is named on the command line, snes9x\-gtk will start
emulation immediately.
.PP
Unlike the original snes9x, snes9x\-gtk doesn't extensively use command\-line
options to affect its behaviour. Instead, use the GUI and/or keyboard
shortcuts from within the emulator.
.SS OPTIONS
.TP
\fB\-filter\fR \fItype\fR
Use a filter to scale the video. Filter types are:
.br
.nh
.I none
.I supereagle
.I 2xsai
.I super2xsai
.I hq2x
.I hq3x
.I hq4x
.I epx
.I ntsc
.hy
.PP
The \-filter option does the same thing as the GUI's "Apply Scaling Filter"
selection (under Preferences / Display).
.TP
.B \-mutesound
Disable audio output. The sound CPU is still emulated. Note that this
option will enable the "mute sound?" checkbox in the Preferences user
interface, whose value will be saved across sessions (you must use the GUI to
unmute the audio).
.SH FILES
.B ~/.snes9x/snes9x.xml
.br
Configuration file. Not intended to be edited directly; stores the settings
made in the GUI. To return all settings to their defaults, remove this file.
.PP
.B ~/.snes9x/snapshots/*
.br
Saved states, named after ROM filenames.
.PP
.B ~/.snes9x/*.png
.br
Screenshots, named after ROM filenames.
.SH AUTHOR
snes9x\-gtk was ported by Brandon Wright <bearoso@gmail.com>.
.PP
Snes9x was written by Gary Henderson and Jerremy Koot. It also includes code
from Ivar (Ivar@snes9x.com), zsKnight and _Demo_ and many others.
.PP
This manual page was written by B. Watson
for the SlackBuilds.org project (but may be used by others).
