#!/bin/bash

# Slackware build script for STAR

# Copyright 2018-2023 Rob van Nues <sborg63@disroot.org>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=STAR
VERSION=${VERSION:-2.7.11b}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

# This script is set for processors that support "Advanced Vector Extensions",
# (AVX), included since 2008 in Intel processors (Sandy Bridge) and since 2011
# in AMD cpus (Bulldozer). AVX is an implementation of "Single Instruction
# stream-Multiple Data streams" (SIMD) to process vector type data.
# If no AVX (`cat /proc/cpuinfo | grep 'avx'`) is present, specify the
# available SIMD architecture (https://en.wikichip.org/wiki/x86/extensions),
# e.g. with "Streaming SIMD Extensions" use 'sse', and uncomment the next line.
#SIMD=${SIMD:-sse}; echo "Using ${SIMD} as SIMD"

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC -fsigned-char"
  LIBDIRSUFFIX="64"
else
  echo "Sorry, this program does not run/compile on your architecture ($ARCH)"
  exit 0
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# for using shared, externally-installed htslib (as done on debian)
#rm -rf htslib
# from https://salsa.debian.org/med-team/rna-star/tree/master/debian/patches
#patch < $CWD/donotuse_own_htslib.patch

# but Alex Dobin, the developer of STAR does not advise this due to hacks he made in htslib
# https://github.com/alexdobin/STAR/issues/351
# https://github.com/alexdobin/STAR/issues/447
#so let's forget about this for now

#For processors that do not support AVX extensions, specify the target SIMD architecture
#make STAR CXXFLAGS_SIMD=sse
cd source
  if [ ! -z "${SIMD}" ]; then
    echo "make with CXXFLAG_SIMD=${SIMD}"
    make ${PRGNAM} CFLAGS="$SLKCFLAGS" CXXFLAGSextra="$SLKCFLAGS" CXXFLAGS_SIMD="$SIMD"
  else
    echo "default make"
    make ${PRGNAM} CFLAGS="$SLKCFLAGS" CXXFLAGSextra="$SLKCFLAGS"
  fi

  mkdir -p $PKG/usr/bin
  install -Dm755 $PRGNAM "$PKG/usr/bin/${PRGNAM}"

  #make clean
  #make ${PRGNAM}long CXXFLAGSextra="$CXXFLAGS"
  #install -Dm755 ${PRGNAM}long "$PKG/usr/bin/${PRGNAM}long"

cd ..

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  source/parametersDefault doc/${PRGNAM}manual.pdf CHANGES.md LICENSE README.md RELEASEnotes.md \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
chmod 644 $PKG/usr/doc/$PRGNAM-$VERSION/parametersDefault

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
