#!/bin/sh

# Slackware build script for Phoenix Firestorm
#
# This script will repackage the binary distribution into a Slackware package
#
# Martin Rogge <martin_rogge@users.sourceforge.net>

# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# NOTE: Since release 4.7.9 there is no Havoc version of Firestorm.
# Therefore this package now builds the Opensim version by default.

PRGNAM=firestorm
VERSION=${VERSION:-4.7.9.50527}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
 case "$( uname -m )" in
 i?86) ARCH=i686 ;;
 arm*) ARCH=arm ;;
 *) ARCH=$( uname -m ) ;;
 esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "x86_64" ]; then
  BUILDTYPE="OS-Releasex64"
else
  BUILDTYPE="OS-Release"
fi

set -e

BASENAME="Phoenix_Firestorm${BUILDTYPE}_${ARCH}_${VERSION}"

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $BASENAME
tar xvf $CWD/$BASENAME.tar.xz
cd $BASENAME
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

mkdir -p $PKG/opt/$PRGNAM
# copy files just like the install script would do
cp -a * $PKG/opt/$PRGNAM
# avoid overwriting the previous configuration
mv $PKG/opt/$PRGNAM/firestorm $PKG/opt/$PRGNAM/firestorm.new
# sound configuration for standard Slackware installation
cat firestorm | sed -e 's/^#export LL_BAD_OPENAL_DRIVER=x/export LL_BAD_OPENAL_DRIVER=x/' > $PKG/opt/$PRGNAM/firestorm.new

mkdir -p $PKG/usr/bin
cat << EOF > $PKG/usr/bin/$PRGNAM
#!/bin/bash
cd /opt/$PRGNAM
exec /opt/$PRGNAM/firestorm
EOF
chmod 755 $PKG/usr/bin/$PRGNAM

install -m 0644 -p -D $TMP/$BASENAME/firestorm_icon.png $PKG/usr/share/pixmaps/$PRGNAM.png

mkdir -p $PKG/usr/share/applications
cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a *.txt $PKG/usr/doc/$PRGNAM-$VERSION/
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
