#!/bin/sh

# Slackware build script for cmatrix
# Written by Phillip Warner <pc_warner@yahoo.com>

PRGNAM=cmatrix
VERSION=1.2a
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R a-s,u+rw,go-w .

# Patch configure to find the fonts correctly
patch -p1 < $CWD/cmatrix-1.2a-find_fonts.diff

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --disable-static \
  --build=$ARCH-slackware-linux

make

# Manual install - patching the Makefile not worth it
install -D -m 0755 $TMP/$PRGNAM-$VERSION/cmatrix \
  $PKG/usr/bin/cmatrix
install -D -m 0644 $TMP/$PRGNAM-$VERSION/cmatrix.1 \
  $PKG/usr/man/man1/cmatrix.1
install -D -m 0644 $TMP/$PRGNAM-$VERSION/matrix.fnt \
  $PKG/usr/share/kbd/consolefonts/matrix.fnt
install -D -m 0644 $TMP/$PRGNAM-$VERSION/matrix.psf.gz \
  $PKG/usr/share/kbd/consolefonts/matrix.psf.gz
install -D -m 0644 $TMP/$PRGNAM-$VERSION/mtx.pcf \
  $PKG/usr/share/fonts/misc/mtx.pcf

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Compress the man page
gzip -9 $PKG/usr/man/man1/cmatrix.1

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS COPYING README ChangeLog NEWS TODO $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
