.TH OPHCRACK "1" "March 2009" "3.2.0" "User Commands"

.SH NAME
Ophcrack - a Microsoft Windows password cracker using rainbow tables.

.SH DESCRIPTION
.B Ophcrack
is a Windows password cracker based on a time-memory trade-off using rainbow tables.
.br
This is a new variant of Hellman's original trade-off, with better performance.
.br
It recovers 99.9% of alphanumeric passwords in seconds.
.PP
.B Ophcrack
works for Windows NT/2000/XP/Vista.
.PP
.B Ophcrack
can be used with command line using the options below, or can be run as a pure graphical software.
.PP
If you have installed ophrack-cli package, graphical interface is not available.

.SH SYNOPSIS
ophcrack [options]

.SH OPTIONS
.TP
.I -a
disable audit mode (default)
.TP
.I -A
enable audit mode
.TP
.I -b
disable bruteforce
.TP
.I -B
enable bruteforce (default)
.TP
.I -c <file>
specify the config file to use
.TP
.I -D
display (lots of!) debugging information
.TP
.I -d <dir>
specify tables base directory
.TP
.I -e
do not display empty passwords
.TP
.I -f <file>
load hashes from the specified file (pwdump or session)
.TP
.I -g
disable GUI
.TP
.I -h
display this information
.TP
.I -i
hide usernames
.TP
.I -I
show usernames (default)
.TP
.I -l <file>
log all output to the specified file
.TP
.I -n <num>
specify the number of threads to use
.TP
.I -o <file>
write cracking output to file in pwdump format
.TP
.I -q
quiet mode
.TP
.I -r
launch the cracking when ophcrack starts (GUI only)
.TP
.I -s
disable session auto-saving
.TP
.I -S <session_file>
specify the file to use to automatically save the progress of the search
.TP
.I -u
display statistics when cracking ends
.TP
.I -t table1[,a[,b,...]][:table2[,a[,b,...]]]
specify which table to use in the directory given by \-d
.TP
.I -v
verbose
.TP
.I -w <dir>
load hashes from encrypted SAM file in directory dir
.TP
.I -x
export data in CSV format to the file specified by \-o

.SH EXAMPLES
.B ophcrack -g -d /path/to/tables -t xp_free_fast,0,3:vista_free -f in.txt
.PP
Launch ophcrack in command line using tables 0 and 3 in /path/to/tables/xp_free_fast and all tables in /path/to/tables/vista_free and cracks hashes from pwdump file in.txt

.SH "SEE ALSO"
Homepage: http://ophcrack.sourceforge.net/
.br
Free rainbow tables: http://ophcrack.sourceforge.net/tables.php

.SH AUTHOR
This manual page was written by Adam Cecile <gandalf@le-vert.net> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
