# Apache config for mod_evasive

LoadModule evasive_module @baselibdir@/httpd/modules/mod_evasive24.so

<IfModule mod_evasive24.c>
	DOSEnabled		true
	DOSHashTableSize	3079
	DOSPageCount		2
	DOSSiteCount		50
	DOSPageInterval		1
	DOSSiteInterval		1
	DOSBlockingPeriod	10
#	DOSEmailNotify		you@yourdomain.com
#	DOSSystemCommand	"su - someuser -c '/sbin/... %s ...'"
#	DOSLogDir		"/var/lock/mod_evasive"
#	DOSWhitelist		127.0.0.1
#	DOSWhitelistUri		white.*regex
#	DOSHTTPStatus		429
</IfModule>

