#!/bin/sh

# Slackware build script for x264 

# Written by core (eroc@linuxmail.org)

set -e

PRGNAM=x264
VERSION=20070722
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
GTKUI=${GTKUI:-no}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar -jxvf $CWD/$PRGNAM-*-$VERSION-*.tar.bz2
mv $PRGNAM-*-$VERSION-*/ $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

if [ "$GTKUI" = 'yes' ]; then
  GTKUIOPT='--enable-gtk'
else
  unset -v GTKUIOPT
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  $GTKUIOPT \
  --enable-pthread \
  --enable-visualize \
  --enable-shared

make
make install DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

if [ "$GTKUI" = 'yes' ]; then
  mkdir -p $PKG/usr/share/pixmaps
  cp gtk/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM.png
  mkdir -p $PKG/usr/share/applications
  cat $CWD/$PRGNAM.desktop > $PKG/usr/share/applications/$PRGNAM.desktop
fi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS COPYING doc/*.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
