#!/bin/sh

# Slackware build script for Conserver

# Written by Menno Duursma <druiloor@zonnet.nl>
# Modified by the SlackBuilds.org project

PRGNAM=conserver
VERSION=8.1.14
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# Bail out if we have a problem
set -e

# Set compiler flags
if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar -xzvf $CWD/$PRGNAM-$VERSION.tar.gz || exit 1
cd $PRGNAM-$VERSION

chown -R root:root .
find . -type d -exec chmod 0755 {} \;
chmod -R a-s,u+w,go+r-w .

# Bake-in: libwrap (TCP Wrapper) and SSL support
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --with-libwrap \
  --with-openssl \
  || exit 1

make || exit 1
make install DESTDIR=$PKG || exit 1

# Strip binaries and libraries
( cd $PKG
  find . -type f | \
    xargs file | \
    grep "executable" | \
    grep ELF | \
    cut -f 1 -d : | \
    xargs strip --strip-unneeded \
  2> /dev/null

  find . -type f | \
    xargs file | \
    grep "shared object" | \
    grep ELF | \
    cut -f 1 -d : | \
    xargs strip --strip-unneeded \
  2> /dev/null
)

if [ -d $PKG/usr/man ]; then
  gzip -9 $PKG/usr/man/man?/*
fi

# Documentation :
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp CHANGES  FAQ  INSTALL  LICENSE  PROTOCOL  README  TODO  conserver.html \
  $PKG/usr/doc/$PRGNAM-$VERSION
# We'll consider this a documentation here
cp -a autologin $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf
cd conserver.cf
cp INSTALL conserver.cf conserver.passwd label.ps test.cf \
  $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf
cp -a samples $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf

cd ../conserver
cp Sun-serial $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/contrib
cd ../contrib
cp README maketestcerts $PKG/usr/doc/$PRGNAM-$VERSION/contrib
# We'll consider this a documentation here too
cp -a chat $PKG/usr/doc/$PRGNAM-$VERSION/contrib
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# Toss redundant example config files included with source
rm -rf $PKG/usr/share

## Sample configuration files
mkdir -p $PKG/etc
cat $CWD/conserver.cf > $PKG/etc/conserver.cf.new
cat $CWD/conserver.passwd >$PKG/etc/conserver.passwd.new
cat $CWD/console.cf >$PKG/etc/console.cf.new

# Include sample rc file
mkdir -p $PKG/etc/rc.d
install -m 0755 $CWD/rc.conserver $PKG/etc/rc.d/rc.conserver.new

# Default directory console messages get logged to
mkdir -p $PKG/var/consoles

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# Prepend any symlinks and such to the existing doinst.sh file
cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz

# Clean up the extra stuff
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/$PRGNAM-$VERSION
  rm -rf $PKG
fi

