#!/bin/sh

# Slackware build script for Conserver
# Written by Menno Duursma <druiloor@zonnet.nl>

# This program is free software. It comes without any warranty.
# Granted WTFPL, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

PRGNAM=conserver
VERSION=8.1.17
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e # Bail out if we have a problem

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . -type d -exec chmod 0755 {} \;
chmod -R a-s,u+w,go+r-w .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --with-libwrap \
  --with-openssl \
  --build=$ARCH-slackware-linux

make
make install DESTDIR=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
)

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $( find . -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
)

# Include dist config files as documentation
install -D -m 0644 $PKG/usr/share/examples/conserver/conserver.cf $PKG/usr/doc/$PRGNAM-$VERSION/examples/conserver.cf
install -D -m 0644 $PKG/usr/share/examples/conserver/conserver.passwd $PKG/usr/doc/$PRGNAM-$VERSION/examples/conserver.passwd
install -D -m 0644 $PKG/usr/share/examples/conserver/conserver.rc $PKG/usr/doc/$PRGNAM-$VERSION/examples/conserver.rc

# Toss redundant dir included with source
rm -rf $PKG/usr/share

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/contrib
cp [A-Z][A-Z]*  conserver.html $PKG/usr/doc/$PRGNAM-$VERSION
cp -a autologin $PKG/usr/doc/$PRGNAM-$VERSION

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf
cd conserver.cf
  cp INSTALL conserver.cf conserver.passwd label.ps test.cf \
    $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf
  cp -a samples $PKG/usr/doc/$PRGNAM-$VERSION/conserver.cf
cd ../conserver
  cp Sun-serial $PKG/usr/doc/$PRGNAM-$VERSION
cd ../contrib
  cp README maketestcerts $PKG/usr/doc/$PRGNAM-$VERSION/contrib
  # We'll consider this a documentation here too
  cp -a chat $PKG/usr/doc/$PRGNAM-$VERSION/contrib
  cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
  cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README$TAG
cd -

## Sample configuration files
mkdir -p $PKG/etc
cat $CWD/config/conserver.cf > $PKG/etc/conserver.cf.new
cat $CWD/config/conserver.passwd > $PKG/etc/conserver.passwd.new
cat $CWD/config/console.cf > $PKG/etc/console.cf.new

# Include sample rc file
install -D -m 0755 $CWD/config/rc.conserver $PKG/etc/rc.d/rc.conserver.new

# Pre-create the default directory console messages get logged to
mkdir -p $PKG/var/consoles

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
