.\" Noobfarm \- The Code
.\" Contact noobfarm@noobfarm.org to correct errors or omissions. 
.TH noobfarm 7 "27 March 2008" "1.0" "Noobfarm - The Code"
.SH NAME
Noobfarm \- The Code
.SH SYNOPSIS
.\" 
Open a web browser and go to: http://noobfarm.org
.SH EXAMPLES
See above
.SH DESCRIPTION
IRC/everyday quotes site
.SH OPTIONS
None
.SH BUGS
No known bugs at this time. 
Short of many noobs and users in the various IRC channels.
.SH SEE ALSO
pom(6)
.SH AUTHOR
.nf
Matt Hayes, Martin Lefebvre, and Mark Walling.
.fi
.SH HISTORY
2008 \- Written as an idea from users in ##slackware on freenode.
       Basically see: http://noobfarm.org/?id=1123
