#!/bin/sh

# Slackware build script for Artistic Style

# Written by Dugan Chen (dugan_c@fastmail.fm)

set -e

PRGNAM=astyle
VERSION=1.22
SRCPK=astyle_$VERSION\_linux.tar.gz
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
tar -xzvf $CWD/$SRCPK
cd $PRGNAM
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

cd buildgcc
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
  make release shared static

mkdir -p $PKG/usr/bin
cp -a ../bin/astyle $PKG/usr/bin
mkdir -p $PKG/usr/lib
cp -a ../bin/libastyle.* $PKG/usr/lib

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $TMP/$PRGNAM/doc/* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
