#!/bin/bash

# Slackware build script for klick

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20211129 bkw: BUILD=2
# - fix build on -current. see Makefile.
# - autodetect rubberband and liblo.
# - enable terminal support.
# - add missing klick.pod (source for the man page).
# - dynamic slack-desc.
# - include klick2ardour.py, in case someone has a use for it.

# 20170620 bkw: add -fpermissive to cflags, for -current's gcc7.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=klick
VERSION=${VERSION:-0.12.2}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

RUBBERBAND=${RUBBERBAND:-yes}
LIBLO=${LIBLO:-yes}
pkg-config --exists rubberband || RUBBERBAND="no"
pkg-config --exists liblo || LIBLO="no"

# 20211129 bkw: wrote a Makefile because the SConstruct is too old
# for scons-4.0.1 and I hate scons anyway.
make -f $CWD/Makefile RUBBERBAND=$RUBBERBAND OSC=$LIBLO SLKCFLAGS="$SLKCFLAGS"

mkdir -p $PKG/usr/bin $PKG/usr/share/$PRGNAM/samples
install -oroot -groot -s -m0755 $PRGNAM $PKG/usr/bin
install -oroot -groot -m0755 $CWD/klick2ardour.py $PKG/usr/bin
install -oroot -groot -m0644 samples/* $PKG/usr/share/$PRGNAM/samples

# man page written for this SlackBuild (from --help output)
mkdir -p $PKG/usr/man/man1
gzip -9c < $CWD/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING NEWS README doc/manual.html $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

L=no; R=no
objdump -p $PKG/usr/bin/$PRGNAM > otmp
grep -q 'NEEDED.*liblo' otmp && L=yes
grep -q 'NEEDED.*librubberband' otmp && R=yes

mkdir -p $PKG/install
sed -e "s,@L@,$L," -e "s,@R@,$R," $CWD/slack-desc > $PKG/install/slack-desc

# Only add capability stuff if not disabled:
if [ "${SETCAP:-yes}" = "yes" ]; then
  cat $CWD/setcap.sh >> $PKG/install/doinst.sh
  # Only allow execution by audio group
  chown root:audio $PKG/usr/bin/$PRGNAM
  chmod 0750 $PKG/usr/bin/$PRGNAM
fi

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
