.TH CIRCUSLINUX "6" "April 2009" "New Breed Software" "Games"
.SH NAME
circuslinux \- Clone of the Atari 2600 game "Circus Atari"
.SH SYNOPSIS
.B circuslinux
[\fIoptions...\fR]
.SH DESCRIPTION
"Circus Linux!" is a clone of the Atari 2600 game "Circus Atari," produced
by Atari, Inc. (which is itself a clone of an earlier arcade game named,
simply "Circus").
.P
The object is to move a teeter-totter back and forth across the screen
to bounce clowns up into the air. When they reach the top, they pop rows
of balloons and then fall back down.
.P
(The gameplay is similar to the classics "Breakout" and "Arkanoid.")
.P
During gameplay, the mouse or joystick is used to move the teeter\-totter,
and any mouse/joystick button is used to launch a new clown (to start the
level) and to flip the teeter\-totter (after a clown has been launched).
.SH OPTIONS
.TP
\fB\-\-disable\-sound\fR, \fB\-\-nosound\fR, \fB\-q\fR
Disable sound and music.
.TP
\fB\-\-fullscreen\fR, \fB\-f\fR
Display in full screen instead of a window, if possible.
.TP
\fB\-\-digital\fR, \fB\-d\fR
Joystick will be seen as a digital game pad, not analog.
.TP
\fB\-\-paddle\fR, \fB\-p\fR
Joystick will be seen as a real Atari paddle.
.TP
\fB\-\-low\fR, \fB\-l\fR
Use less graphics to work on lower\-end hardware.
.TP
\fB\-\-help\fR, \fB\-h\fR
Display help on playing the game.
.TP
\fB\-\-usage\fR, \fB\-u\fR
Display this usage information.
.TP
\fB\-\-version\fR, \fB\-v\fR
Display what version you're running.
.TP
\fB\-\-copying\fR, \fB\-c\fR
Display copying (GPL) information.
.SH FILES
.TP
\fB/usr/share/circuslinux/data\fR
game data (images, music, sound)
.TP
\fB$HOME/.circuslinux\fR
per\-user settings and high\-score records
.SH AUTHORS
Programming: Bill Kendrick
.br
Graphics: Manu Parssinen and Bill Kendrick
.br
Music: Jarkko Rotsten
.P
New Breed Software's web site is located at
.br
.nh
\fBhttp://www.newbreedsoftware.com/\fR
.hy
.P
Man page created by B. Watson for SlackBuilds.org project (but others
are free to use it)
.SH COPYRIGHT
Copyright \(co 2000, New Breed Software
.P
Circus Linux! is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any
later version.
