#!/bin/bash

# Slackware build script for pathways-into-darkness

# Written by B. Watson (urchlay@slackware.uk)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=pathways-into-darkness
VERSION=${VERSION:-1.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

ZIPFILE=AOPID_v${VERSION}.zip
WRAPPER=$PRGNAM
DATADIR=$PKG/usr/share/AlephOne/gamedata

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
mkdir -p $DATADIR
unzip $CWD/$ZIPFILE -d $DATADIR
chown -R root:root $DATADIR

find $DATADIR \
 \( -type f -exec chmod 644 {} + \) -o \
 \( -type d -exec chmod 755 {} + \)

mkdir -p $PKG/usr/games
cat $CWD/$WRAPPER > $PKG/usr/games/$WRAPPER
chmod 0755 $PKG/usr/games/$WRAPPER

mkdir -p $PKG/usr/share/applications
cat $CWD/$WRAPPER.desktop > $PKG/usr/share/applications/$WRAPPER.desktop

mkdir -p $PKG/usr/share/icons/hicolor/{32x32,256x256}/apps
mv $DATADIR/*/icon.png $PKG/usr/share/icons/hicolor/32x32/apps/$PRGNAM.png
mv $DATADIR/*/iconHD.png $PKG/usr/share/icons/hicolor/256x256/apps/$PRGNAM.png

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
mv $DATADIR/*/*.{html,pdf} $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
