.\"     Title: MUSCLE
.\"    Author: Robert Elgar
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 02/06/2008
.\"    Manual: Muscle Manual
.\"    Source: muscle 3.7
.\"
.TH "MUSCLE" "1" "02/06/2008" "muscle 3.7" "Muscle Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
muscle - Multiple Protein Sequence Alignment
.SH "SYNOPSIS"
.HP 7
\fBmuscle\fR \fB\-in\ \fR\fB\fIinput\ file\ (fasta)\fR\fR [\fB\-out\ \fR\fB\fIoutput\ file\ (default\ fasta)\fR\fR] [\fB\-diags\fR] [\fB\-log\ \fR\fB\fIlog\ file\fR\fR] [\fB\-maxiters\ \fR\fB\fIn\fR\fR] [\fB\-maxhours\ \fR\fB\fIn\fR\fR] [\fB\-maxmb\ \fR\fB\fIm\fR\fR] [\fB\-html\fR] [\fB\-msf\fR] [\fB\-clw\fR] [\fB\-clwstrict\fR] [\fB\-log[a]\ \fR\fB\fIlogfile\fR\fR] [\fB\-quiet\fR] [\fB\-stable\fR] [\fB\-group\fR] [\fB\-version\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBmuscle\fR
command\.
.PP
\fBmuscle\fR
aligns protein sequences and is considered superior and faster than Clustal\ W\.
.SH "OPTIONS"
.PP
\fB\-in \fR\fB\fIinput file\fR\fR
.RS 4
Path to FASTA formatted input file
.RE
.PP
\fB\-out \fR\fB\fIoutput file\fR\fR
.RS 4
Path to output file, FASTA formatted by default
.RE
.PP
\fB\-diags\fR
.RS 4
Find diagonals (faster for similar sequences)
.RE
.PP
\fB\-maxiters \fR\fB\fIn\fR\fR
.RS 4
Maximum number of iterations (integer, default 16)
.RE
.PP
\fB\-maxhours \fR\fB\fIn\fR\fR
.RS 4
Maximum time to iterate in hours (default no limit)
.RE
.PP
\fB\-maxmb \fR\fB\fIm\fR\fR
.RS 4
Maximum memory to allocate in Mb (default 80% of RAM)
.RE
.PP
\fB\-html\fR
.RS 4
Write output in HTML format (default FASTA)
.RE
.PP
\fB\-msf\fR
.RS 4
Write output in MSF format (default FASTA)
.RE
.PP
\fB\-clw\fR
.RS 4
Write output in Clustal\ W format (default FASTA)
.RE
.PP
\fB\-clwstrict\fR
.RS 4
As \-clw, with \'CLUSTAL W (1\.81)\' header
.RE
.PP
\fB\-log[a] \fR\fB\fIlogfile\fR\fR
.RS 4
Log to file (append if \-loga, overwrite if \-log)
.RE
.PP
\fB\-quiet\fR
.RS 4
Do not write progress messages to stderr
.RE
.PP
\fB\-stable\fR
.RS 4
Output sequences in input order (default is \-group)
.RE
.PP
\fB\-group\fR
.RS 4
Group sequences by similarity (this is the default)
.RE
.PP
\fB\-version\fR
.RS 4
Display version information and exit
.RE
.SH "SEE ALSO"
.PP

\fBclustalw\fR(1),
\fBseaview\fR(1),
\fBt_coffee\fR(1)\.
.SH "AUTHORS"
.PP
\fBRobert Elgar\fR
.sp -1n
.IP "" 4
Wrote Muscle\.
.PP
\fBSteffen Moeller\fR <\&moeller@debian\.org\&>
.sp -1n
.IP "" 4
Wrote this manpage\.
.PP
\fBCharles Plessy\fR <\&charles\-debian\-nospam@plessy\.org\&>
.sp -1n
.IP "" 4
Updated this manpage\.
.SH "COPYRIGHT"
Copyright \(co 2003, 2004 Steffen Moeller (manpage)
.br
Copyright \(co 2007, 2008 Charles Plessy (manpage)
.br
.PP
Muscle is in the public domain, and therefore not subjected to copyright\.
.PP
This manual page was written by Steffen Moeller moeller@debian\.org for the
Debian(TM)
system (but may be used by others)\. Permission is granted to copy, distribute and/or modify this document as if it were in public domain\.
.sp
