# POD source for yturl man page. Convert with:
# pod2man --stderr -s1 -cSlackBuilds.org -r1.17.0 yturl.pod > yturl.1

=pod

=head1 NAME

yturl - Get direct URLs to YouTube videos.

=head1 SYNOPSIS

yturl [-h] [-q QUALITY] videoID/url

videoID/url is a YouTube url or bare video ID.

=head1 OPTIONS

=over 4

=item -h, --help

show help message and exit

=item -q QUALITY, --quality QUALITY

specify quality, can be "low", "medium", "high", or an itag (see
http://en.wikipedia.org/wiki/YouTube#Quality_and_formats)

=back

=cut
