#!/bin/sh

# Slackware build script for OfflineIMAP
# Home Page https://github.com/nicolas33/offlineimap

# Copyright (c) 2008-2011, Nishant Limbachia, Hoffman Estates, IL, USA <nishant _AT_ mnspace _DOT_ net>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of script must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

SRCNAM="nicolas33-offlineimap-v6.3.4-0-g61e50b3"
PRGNAM="offlineimap"
VERSION=${VERSION:-6.3.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e # Exit on most errors

rm -fr $TMP/$PRGNAM-$VERSION $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar xvf $CWD/$SRCNAM.tar.gz
mv nicolas33-offlineimap-94450e9 $PRGNAM-$VERSION
cd $PRGNAM-$VERSION

chown -R root.root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

### fix the manual file to build correctly
patch -p0 < $CWD/patches/manual.rst.patch

### Patch makefile to disable building dev docs
patch -p0 < $CWD/patches/doc_generation_fix.patch

### build and install
python setup.py install --root=$PKG

### make and install docs
make doc
mkdir -p $PKG/usr/{man/man1,doc/$PRGNAM-$VERSION/html} $PKG/etc

### install config file
install -m 0644 -D $PRGNAM.conf $PKG/etc/$PRGNAM.conf.new

### make and install man page and html docs
( cd docs; make man && make html )

install -m 0644 docs/$PRGNAM.1 $PKG/usr/man/man1
gzip -9 $PKG/usr/man/man1/$PRGNAM.1

cp -a \
  COPYING COPYRIGHT $PRGNAM.conf* \
    $PKG/usr/doc/$PRGNAM-$VERSION
cp -a readme.html docs/FAQ.html docs/INSTALL.html docs/MANUAL.html \
  docs/UPGRADE.html $PKG/usr/doc/$PRGNAM-$VERSION/html
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
