.\" 
.TH "nullidentd" "8" "January 24, 2001" "" ""
.SH "NAME"
nullidentd \- a bare minimum identd server

.SH "SYNOPSIS"
.B nullidentd
.RI [uid]
.br 

.SH "DESCRIPTION"
This manual page documents briefly the
.B nullidentd
command.  This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP 
.B Nullidentd
is intended to be a bare minimum identd server, suitable for a firewall or IP
Masq/NAT gateway.

.SH "OPTIONS"
.B nullidentd
takes only one optional argument, the username to answer with.
If this is omitted,
.B nullidentd
will reply with the username \*(lqfoobar\*(rq.
If the username is RANDOM, a random string is generated.

.SH "USAGE"
.B nullidentd
is typically invoked from inetd. The following
is a typical inetd.conf example:
.br 
.nh
auth stream tcp nowait nobody /usr/sbin/nullidentd nullidentd
.hy

.SH "AUTHOR"
.B 
nullidentd
is written by Brian Young <bayoung@acm.org>
.PP 
This manual page was written by John H. Robinson, IV <jaqque@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
