#!/bin/sh

# Slackware build script for mupdf

# Written by Hubert Hesse (slackbuilds@hubertscorner.de)

# Modified 20130618 by B. Watson (yalhcru@gmail.com):
# - Took over maintenance
# - Updated for mupdf 1.2
# - Build library shared, not static
# - Build with system zlib, libjpeg, openjpeg, jbig2dec, libtiff, libpng,
#   liblcms2 instead of bundled sources (which made the lib + exes *huge*).
#   Also, the included libjpeg is too new (it broke zathura-pdf-mupdf).
# - Include mutool in package (instead of just its man page)
# - Add CHANGES CONTRIBUTORS doc/* to /usr/doc
# - Use DESTDIR libdir mandir instead of patching makefile
# - Updated README & slack-desc to mention XPS and CBZ
# - Fix the man pages slightly

# Modified 20140224 by B. Watson (yalhcru@gmail.com):
# - backported security fix for CVE-2014-2013. I will be upgrading this
#   build to mupdf-1.3, but it'll take more work than I currently have
#   time for:
#   + mupdf's internals have changed, will have to redo my patches
#   + it depends on openjpeg 2.0 which SBo hasn't got yet. 2.0 uses an
#     incompatible API, so an openjpeg 2.0 SlackBuild would require
#     updates for everything that depends on it.
#   + zathura-pdf-mupdf will need updating (mupdf's API has changed)
#   + probably all the other zathura-* builds will need updating to
#     be compatible with new zathura-pdf-mupdf
#   The security fix is needed now, it's a tiny patch, and shouldn't have
#   to wait on all that other stuff.

# 20140318 bkw: fix permissions on headers and man pages

PRGNAM=mupdf
VERSION=${VERSION:-1.2}
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi
set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-source
unzip $CWD/$PRGNAM-$VERSION-source.zip
cd $PRGNAM-$VERSION-source
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# We want a shared library, not static.
# This patch based on http://bugs.ghostscript.com/show_bug.cgi?id=693009
# with the following changes:
# - actually applies to mupdf-1.2
# - links the applications dynamically
# - doesn't even build/install the static lib by default
# - adds mutool to list of stuff installed to $prefix/bin
patch -p1 < $CWD/shared_libfitz.diff

# 'see also' mentions nonexistent stuff (mupdfclean, mupdfshow), also
# the -b option to mupdf was missing.
patch -p1 < $CWD/man_page.diff

# Build against system libs instead of shipped ones
sed -i 's,libopenjpeg,libopenjpeg1,' Makerules
rm -rf thirdparty

# patch from upstream git, fix security vulnerability CVE-2014-2013.
# from here: http://git.ghostscript.com/?p=user/zeniko/mupdf.git;h=60dabde18d
# Patch is for mupdf-1.3, I've backported it to 1.2 for now.
patch -p1 < $CWD/xps_parse_color_overflow_fix.diff

make build=release prefix=/usr XCFLAGS="$SLKCFLAGS"
make \
  build=release \
  prefix=/usr \
  libdir=/usr/lib$LIBDIRSUFFIX \
  mandir=/usr/man \
  DESTDIR=$PKG \
  install

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

chmod -x $PKG/usr/include/*.h $PKG/usr/man/man?/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README COPYING CHANGES CONTRIBUTORS doc/* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
