# pod source for oblige-legacy4 man page. convert with:
# pod2man --stderr -s6 -cSlackBuilds.org -r4.28b oblige-legacy4.pod > oblige-legacy4.6

=head1 NAME

oblige-legacy4 - random level generator for Doom and related games

=head1 SYNOPSIS

B<oblige-legacy4> [-options]

=head1 DESCRIPTION

B<oblige-legacy4> creates a patch WAD file for use with Doom, Doom II, Heretic, Hexen, or Quake,
containing one or more randomly-generated levels. The generated WAD
files are ready to play (no separate node-building pass is needed).

Normally, B<oblige-legacy4> is controlled by its GUI, but it can be used
noninteractively (see the B<-b> option below).

=head1 OPTIONS

=over 4

=item B<-c,--config> <file>

Config file to use. Default is I<~/.oblige-legacy4/CONFIG.txt>.

=item B<-b,--batch> <output>

Batch mode (no GUI). Uses built-in default config (never reads the
normal config file used by the GUI), but the B<--config> option can be
used to override the defaults. I<output> will be a PWAD file and will
be overwritten without prompting if it exists.

=item B<-k,--keep>

Keep random seed from loaded settings. Normally the seed stored in the
config file is ignored, and a new seed is generated.

=item B<-d,--debug>

Enable verbose debugging messages in log.

=item B<-t,--terminal>

Print log messages to stdout (rather than I<~/.oblige-legacy4/LIGS.txt>). Disabled
by default, unless in B<--batch> mode.

=item B<-h,--help>

Show built-in help message.

=back

=head1 SEE ALSO

B<oblige>(6), a newer version of B<oblige> with an enhanced level-generation
algorithm, but with support for Doom and Doom II only.

The B<oblige-legacy4> home page: I<http://oblige-legacy4.sourceforge.net>

=head1 LICENSE

This program is free software, under the terms of the GNU General Public
License, and comes with ABSOLUTELY NO WARRANTY.  See the documentation
for more details, or visit http://www.gnu.org/licenses/gpl-2.0.txt

=head1 AUTHOR

B<oblige> is (c) 2006-2014 by Andrew Apted.

This man page created by B. Watson, for the SlackBuilds.org project.
