#!/bin/sh

## Written by hollywoodb (hollywoodb@fastmail.fm)

## Feel free to use, modify, redistribute this script.
## If you make changes please modify the "Written by"
## so that I don't recieve emails about a script I
## did not write.  Thanks.

# Modified by the SlackBuilds.org project
# Updated by Alex Word <alex_word86@yahoo.com>

PRGNAM=xmoto
VERSION=0.5.2
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=${PKG:-$TMP/package-$PRGNAM}
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG $TMP/$PRGNAM-$VERSION
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar xvf $CWD/$PRGNAM-$VERSION-src.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

patch -p1 < $CWD/patches/sqlite3.diff
patch -p1 < $CWD/patches/localedir.diff
patch -p0 < $CWD/patches/xmoto-amd64_gcc441.diff

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --localstatedir=/var \
  --mandir=/usr/man \
  --localedir=/usr/share/locale \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --with-localesdir=/usr/share/locale \
  --disable-dependency-tracking \
  --enable-threads=posix \
  --with-enable-zoom=1 \
  --with-renderer-sdlGfx=0 \
  --with-renderer-openGl=1 \
  --with-x \
  --build=$ARCH-slackware-linux

make
make install-strip DESTDIR=$PKG

mkdir -p $PKG/usr/share/{pixmaps,applications}
install -m 0644 extra/$PRGNAM.xpm $PKG/usr/share/pixmaps/
install -m 0644 extra/$PRGNAM.desktop $PKG/usr/share/applications/

gzip -9 $PKG/usr/man/man?/*.?

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  ABOUT-NLS AUTHORS COPYING INSTALL NEWS README TODO ChangeLog \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
