#!/bin/sh

## Written by hollywoodb (hollywoodb@fastmail.fm)

## Feel free to use, modify, redistribute this script.
## If you make changes please modify the "Written by"
## so that I don't recieve emails about a script I
## did not write.  Thanks.

# Modified by the SlackBuilds.org project

set -e

NAME=xmoto
VERSION=0.2.4
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=${PKG:-$TMP/package-$NAME}
OUTPUT=${OUTPUT:-/tmp}

rm -rf $PKG $TMP/$NAME-$VERSION
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar zxvf $CWD/$NAME-$VERSION-src.tar.gz
cd $NAME-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
    --prefix=/usr \
    --exec-prefix=/usr \
    --bindir=/usr/games \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --libdir=/usr/lib/games \
    --datadir=/usr/share/games \
    --datarootdir=/usr \
    --docdir=/usr/doc/$NAME-$VERSION \
    --enable-threads=posix \
    --with-enable-www=1 \
    --with-enable-zoom=1 

make
make install-strip DESTDIR=$PKG

mkdir -p $PKG/usr/share/{pixmaps,applications}
install -m 0644 extra/$NAME.xpm $PKG/usr/share/pixmaps/
install -m 0644 extra/$NAME.desktop  $PKG/usr/share/applications/

# X-Moto doesn't like to honour the locale options that
# the configure script says it does.
mv $PKG/usr/share/games/locale $PKG/usr/share

# Man pages are already gzipped, but there's one small problem
mv $PKG/usr/man/mang $PKG/usr/man/man6

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a ABOUT-NLS AUTHORS COPYING INSTALL NEWS README TODO ChangeLog \
  $PKG/usr/doc/$NAME-$VERSION
cat $CWD/$NAME.SlackBuild > $PKG/usr/doc/$NAME-$VERSION/$NAME.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$NAME-$VERSION-$ARCH-$BUILD$TAG.tgz
