#!/bin/sh

# Slackware build script for "libsidplay2".

# Copyright 2010-2015 Marcel Saegebarth <marc@mos6581.de>
# Copyright 2011-2012 Dominik Drobek <arcctgx@o2.pl>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# * Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=libsidplay2
VERSION=${VERSION:-2.1.1}
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}

SRCNAM=sidplay-libs
DIFFVER=${DIFFVER:-14}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $TMP/$PRGNAM $TMP/debian $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
tar xvf $CWD/${SRCNAM}_$VERSION.orig.tar.gz
tar xvf $CWD/${SRCNAM}_$VERSION-$DIFFVER.debian.tar.gz
cd $TMP/$SRCNAM-$VERSION
patch -p1 < $TMP/debian/patches/configure-fixes.patch
patch -p1 < $TMP/debian/patches/gcc4-fixes.patch
patch -p1 < $TMP/debian/patches/hardsid_4_bsd.patch
patch -p1 < $TMP/debian/patches/pkg-config.patch
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --enable-shared=yes \
  --enable-static=no \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --build=$ARCH-slackware-linux

make
make install-strip DESTDIR=$PKG

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
( cd $TMP/$SRCNAM-$VERSION/builders/hardsid-builder
    mkdir $PKG/usr/doc/$PRGNAM-$VERSION/hardsid-builder
    cp -a COPYING INSTALL $PKG/usr/doc/$PRGNAM-$VERSION/hardsid-builder
  cd $TMP/$SRCNAM-$VERSION/libsidplay
    mkdir $PKG/usr/doc/$PRGNAM-$VERSION/libsidplay
    cp -a AUTHORS COPYING ChangeLog INSTALL README TODO \
      $PKG/usr/doc/$PRGNAM-$VERSION/libsidplay
  cd $TMP/$SRCNAM-$VERSION/libsidutils
    mkdir $PKG/usr/doc/$PRGNAM-$VERSION/libsidutils
    cp -a AUTHORS COPYING ChangeLog INSTALL README TODO \
      $PKG/usr/doc/$PRGNAM-$VERSION/libsidutils
  cd $TMP/$SRCNAM-$VERSION/resid
    mkdir $PKG/usr/doc/$PRGNAM-$VERSION/resid
    cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README THANKS TODO \
      $PKG/usr/doc/$PRGNAM-$VERSION/resid
  cd $TMP/debian
    cp -a changelog $PKG/usr/doc/$PRGNAM-$VERSION/ChangeLog.Debian
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
