.TH ZDBSP "6" "March 2012" "SlackBuilds.org" "Games"
.SH NAME
ZDBSP \- nodes builder for Doom and related games
.SH SYNOPSIS
.B zdbsp
[\fIoptions\fR] \fIsourcefile.wad\fR
.SH DESCRIPTION
.B zdbsp
is a standalone version of ZDoom's internal node builder. Its most
important feature is that it knows about polyobjects, but it can also
build GL nodes if you don't want to wait for glBSP to do it. At the time
of writing, it is also the only nodebuilder with UDMF support.
.SH OPTIONS
.TP
\fB\-m\fR, \fB\-\-map\fR=\fIMAP\fR
Only affect the specified map
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Write output to FILE instead of tmp.wad
.TP
\fB\-q\fR, \fB\-\-no\-prune\fR
Keep unused sidedefs and sectors
.TP
\fB\-N\fR, \fB\-\-no\-nodes\fR
Do not rebuild nodes
.TP
\fB\-g\fR, \fB\-\-gl\fR
Build GL\-friendly nodes
.TP
\fB\-G\fR, \fB\-\-gl\-matching\fR
Build GL\-friendly nodes that match normal nodes
.TP
\fB\-x\fR, \fB\-\-gl\-only\fR
Only build GL\-friendly nodes
.TP
\fB\-5\fR, \fB\-\-gl\-v5\fR
Create v5 GL\-friendly nodes (overriden by \fB\-z\fR and \fB\-X\fR)
.TP
\fB\-X\fR, \fB\-\-extended\fR
Create extended nodes (including GL nodes, if built)
.TP
\fB\-z\fR, \fB\-\-compress\fR
Compress the nodes (including GL nodes, if built)
.TP
\fB\-Z\fR, \fB\-\-compress\-normal\fR
Compress normal nodes but not GL nodes
.TP
\fB\-b\fR, \fB\-\-empty\-blockmap\fR
Create an empty blockmap
.TP
\fB\-r\fR, \fB\-\-empty\-reject\fR
Create an empty reject table
.TP
\fB\-R\fR, \fB\-\-zero\-reject\fR
Create a reject table of all zeroes
.TP
\fB\-E\fR, \fB\-\-no\-reject\fR
Leave reject table untouched
.TP
\fB\-p\fR, \fB\-\-partition\fR=\fINNN\fR
Maximum segs to consider at each node (default 64)
.TP
\fB\-s\fR, \fB\-\-split\-cost\fR=\fINNN\fR
Cost for splitting segs (default 8)
.TP
\fB\-d\fR, \fB\-\-diagonal\-cost\fR=\fINNN\fR
Cost for avoiding diagonal splitters (default 16)
.TP
\fB\-P\fR, \fB\-\-no\-polyobjs\fR
Do not check for polyobject subsector splits
.TP
\fB\-w\fR, \fB\-\-warn\fR
Show warning messages
.TP
\fB\-t\fR, \fB\-\-no\-timing\fR
Suppress timing information
.TP
\fB\-V\fR, \fB\-\-version\fR
Display version information
.TP
\fB\-\-help\fR
Display this usage information
.SH "SEE ALSO"
\fBdoom\fR(6),
\fBglbsp\fR(6),
\fBzennode\fR(6),
\fBidbsp\fR(6),
\fBwarm\fR(6)
.br
.B http://zdoom.org
.SH AUTHOR
.B zdbsp
was written by Randy Heit
.P
This man page was created by B. Watson (mostly using help2man) for the
SlackBuilds.org project, but it may be used by anyone.
.\" man page generated like so:
.\" help2man -N -s 6 -n 'nodes builder for Doom and related games' \
.\"   -S SlackBuilds.org -o zdbsp.6 zdbsp
.\" ...and edited slightly (added DESCRIPTION, AUTHOR, SEE ALSO sections)
