.TH proxymini 1 "October 11, 2009"
.SH NAME
proxymini \- a proxy server that supports HTTP, HTTP CONNECT, SOCKS4 and SOCKS5
.SH SYNOPSIS
.B proxymini
[
.B \-h
] [
.B \-l IP
] [
.B \-L IP
] [
.B \-p PORT
] [
.B \-v
] [
.B \-o FILE
]
.SH DESCRIPTION
Proxy server that fully supports all the following protocols: HTTP, HTTP CONNECT (for HTTPS and so on), SOCKS4 (TCP and TCP bind) and SOCKS5 (TCP, TCP bind and UDP). It's designed to be small and for being used in trusted environments where there is no need of complex or advanced options and other boring things, double click on it and it will work immediately. It supports also some options like binding a specific interfaces for incoming or outgoing connections, custom port to bind (default is 8123), stdout and file verbose logging.
.SH OPTIONS
.TP
.B \-h
display a short help text
.TP
.B \-l IP
local interface to bind (default any)
.TP
.B \-L IP
as above but works only for the outgoing socket, this means you can decide to use a secondary interface for connecting to the hosts (for example using a Wireless connection instead of your main one) interface to use for outgoing connections
.TP
.B \-p PORT
local port to bind, default 8123
.TP
.B \-v
verbose logging on standard output (default is none)
.TP
.B \-o FILE
logs everything in the file FILE, it's just as \-v but for file
.SH EXAMPLES
bind to port 1080 on local host and fork into background
.PP
proxymini \-l 127.0.0.1 \-p 1080 &
.PP
.SH AUTHOR
Luigi Auriemma <aluigi@autistici.org>
