.TH MEH 1 "2013-12-28"
.SH NAME
meh \- simple, minimalist, super fast image viewer
.SH SYNOPSIS
.B meh
.IR FILE ...
.br
.B meh \-list
.RI [ LISTFILE ]
.br
.B meh \-ctl
.br
.B meh \-v
.SH DESCRIPTION
.B meh
is a small, simple, super fast image viewer using raw XLib.
It is similar to
.BR feh (1),
but faster and simpler.
.LP
.B meh
can use ImageMagick's
.BR convert (1)
to view almost 200 file formats, though it is slower for these formats.
Built-in formats are JPEG, PNG, BMP, and netpbm.
.SH OPTIONS
.TP
.BR \-list \ [\fILISTFILE\fR]
Treat \fILISTFILE\fR as list of images. Defaults to stdin.
.TP
.B \-ctl
Display files as they are received on stdin.
.TP
.B \-v
Print version and exit.
.SH KEY BINDINGS
While
.B meh
is displaying an image, the following key bindings are active:
.TP
.BR j
Next image.
.TP
.BR k
Previous image.
.TP
.BR r
Reload current image.
.TP
.BR Enter
Print current image's filename to stdout.
.TP
.BR \fBEscape\fR\ or \ \fBq\fR
Exit \fBmeh\fR.
