#!/bin/bash

# Slackware build script for fatrace

# Originally written by Leonardo Citrolo.
# Now maintained by B. Watson (urchlay@slackware.uk).

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20250916 bkw:
# - update for v0.19.1.
# - switch to upstream's github, instead of launchpad.
# - add a couple of post-release patches from upstream git.
# 20250126 bkw: update for v0.18.0.
# 20230509 bkw:
# - new maintainer.
# - relicense as WTFPL with permission from original author.
# - update for v0.17.0.
# - add RUNTESTS environment variable.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=fatrace
VERSION=${VERSION:-0.19.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
else
  SLKCFLAGS="-O2"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +

# 20250916 bkw: these patches will be in the next release. One is a
# fix for a real bug (the < and > thing) and one adds a *very* useful
# option (-d).
for i in $CWD/patches/*.patch; do
  echo "=== Applying $( basename $i )"
  patch -p1 < $i
done

sed -i -e "/^CFLAGS/s,-O2,$SLKCFLAGS," \
       -e 's,share/man,man,' \
       -e 's,-Werror,,' \
       Makefile

make
strip $PRGNAM
make install DESTDIR=$PKG PREFIX=/usr
gzip $PKG/usr/man/man*/*

# This is disabled by default because it takes a while to run,
# and will fail on a custom kernel that lacks btrfs.
if [ "${RUNTESTS:-no}" = "yes" ]; then
  python3 -m unittest -v
fi

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKGDOC
cp -a COPYING README* $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
