#!/bin/sh

# Slackware build script for mkslack

# Copyright 2010 David Woodfall <dave@dawoodfall.net>,
# Modifications copyright slakmagik <slakmagik@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=mkslack
VERSION=${VERSION:-5.2}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
README=$PKG/usr/doc/$PRGNAM-$VERSION/README

set -e

rm -rf $PKG
mkdir -p $TMP $PKG/usr/bin $PKG/usr/share/mkslack/templates $PKG/etc/mkslack \
  $PKG/usr/man/man1 $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION/$PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

gzip mkslack.1
install -m 644 mkslack.1.gz $PKG/usr/man/man1
install -m 755 mkslack $PKG/usr/bin
install -m 644 template* $PKG/usr/share/mkslack/templates
install -m 644 *SlackBuild $PKG/usr/share/mkslack/templates
install -m 644 mkslack.conf.new $PKG/etc/mkslack

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
# generate the README from some introductory text and a dump of the manual
cat << EOF > $README
mkslack - a SlackBuild generator script
Copyright 2010 David Woodfall, modification by slakmagik
mkslack is licensed under a "one-clause BSD/Slackware" license.
See the script for the full text.
Homepage: http://www.dawoodfall.net/files/slackbuilds/noversion/mkslack/
EOF
man ./mkslack.1.gz | col -b | expand | cat -s | sed '
    1d
    s/\([^[:space:]]\)[[:space:]][[:space:]]*/\1 /g
    /^$/N;/MKSLACK(1)$/D
    ' >> $README

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/ChangeLog.txt > $PKG/usr/doc/$PRGNAM-$VERSION/ChangeLog.txt

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
