.\"                                      Hey, EMACS: -*- nroff -*-
.TH GLEST 6 "May 4, 2008"
.SH NAME
glest \- A free 3d real-time customizable strategy game.
.SH SYNOPSIS
.B glest
.br
.PP
.B It is recommented to perform Config -> Auto Config before starting to play.
.SH DESCRIPTION
This manual page documents briefly the
.B glest
game commands and configuration.
.PP

.SH CONTROLS
.TP 
.B Camera
.br
m => toggle camera mode (game mode and free mode)
.br
w => move camera up (only on free camera more)
.br
s => move camera down (only on free camera more)
.br
a => rotate camera left (only on free camera more)
.br
d => rotate camera right (only on free camera more)
.br
up arrow or mouse on top => move camera forward
.br
down arrow or mouse on bottom => move camera backward
.br
left arrow or mouse on left => move camera left
.br
right arrow or mouse on right => move camera right
.TP
.B Orders and Unit selection
.br
left mouse button => select or deselect units
.br
shift + left mouse button => add unit to selection
.br
control + left mouse button => remove unit from selection
.br
left mouse double click => select nearby units of this type
.br
right mouse button => auto order
.br
menu click => activate order
.br
left mouse when order is activated => give order
.br
right mouse when order is activated => cancel state
.br
number => recall group
.br
control + number => assign group
.TP
.B Other Keys
.br
c => switch display color
.br
- + => adjust game speed
.br
p => pause game
.br
t => save screen to TGA file


.SH CONFIGURATION
.TP
.B Glest can be configured in three ways:
.br
- in-game config menu: basic parameters
.br
- configuration tool: advanced parameters
.br
- glest.ini: all parameters

.SH VIDEO CARD HINTS
.TP
.B Auto config.
.br
The first time you run the game it will try to detect the graphic settings most
suitable for your video card. It's highly recommended that you don't change them
unless you really know what you are doing. If you change the settings and you
want to reset to the recommended ones, you can do it by using the auto config
button in the in-game config menu.
.TP
.B Required card features.
.br
The game requires either OpenGL 1.4 or OpenGL 1.3 plus the GL_ARB_env_crossbar
extesion. Most video cards with recent drivers support this features. You can
bypass the feature check by replacing the "CheckGlCaps=1" line in glest.ini by
"CheckGlCaps=0", but the game may crash or have graphics errors.
.TP
.B ATI card problems.
.br
It seems to be bug in some ATI OpenGL drivers that makes the game crash with
certain card/driver configurations when using more than 1 light. Auto config  will
detect this issue and turn off all secondary lights when it detects an ATI card.
If you still want to try running the game using more than 1 light you can change
this setting in the in-game config menu.
.TP
.B Shadows.
.br
The game features real-time shadows using different algorithms. 1) Projected: Fast
shadows but they provide unit over terrain shadows only, and can produce incorrect
shadows in some circumstances. 2) Shadow mapping: Slow shadows but they are
always correct and provide everything over everything shadows. In ATI cards they
look aliased. Both types of shadows require a video card with 3 texture unit
support. Auto config will set the most suitable shadow mode for your video card.
.TP
.B 3D textures
.br
The game uses 3D textures for some effects like animated water. Some old video cards
(ie: GeForceMX) don't support this feature by hardware and the game runs really
slow when the camera is near a river.  Auto config will detect this and disable
3D textures when needed.


.SH AUTHOR
glest was written by Martino Figueroa et al (see readme.txt).
.PP
This manual page was written by Giuseppe Borzi <gborzi@ieee.org>,
for the Debian project (but may be used by others).
