#!/bin/sh

# Slackware build script for hamachi

# Written by Adam Swift vikepack@omnitude.net

PRGNAM=hamachi
SRCPKGNAM=logmein-$PRGNAM
VERSION=${VERSION:-2.0.1.13}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
  SRCPKGSUFFIX="x64"
else
  LIBDIRSUFFIX=""
  SRCPKGSUFFIX="x86"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCPKGNAM-$VERSION-$SRCPKGSUFFIX
tar xvf $CWD/$SRCPKGNAM-$VERSION-$SRCPKGSUFFIX.tgz
cd $SRCPKGNAM-$VERSION-$SRCPKGSUFFIX
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir -p $PKG/usr/share/$PRGNAM
cp -a hamachid dnsup dnsdown $PKG/usr/share/$PRGNAM

mkdir -p $PKG/etc/rc.d
cat $CWD/rc.hamachi > $PKG/etc/rc.d/rc.hamachi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README CHANGES LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

