# POD source for svkbd man page. Convert with:
# pod2man --stderr -s1 -c"Suckless.org Tools" -r20140130 svkbd.pod > svkbd.1

=pod

=head1 NAME

B<svkbd> - simple virtual keyboard

=head1 SYNOPSIS

B<svkbd>-I<layout> [-d] [-g geometry]

B<svkbd>-I<layout> [-v|-h]

=head1 DESCRIPTION

B<svkbd> is a simple mouse-operated virtual keyboard, intended to be
used in environments where no keyboard is available.

=head1 OPTIONS

=over

=item B<-d>

This tells B<svkbd> to announce itself being a dock window, which then
is managed differently between different window managers. If using dwm
and the dock patch, then this will make svkbd being managed by dwm and
some space of the screen being reserved for it.

=item B<-g geometry>

Sets starting size and position. Standard X11 geometry specification,
WxH[+-]X[+-Y], such as used by xterm(1).

=item B<-v>

Prints the version number and exits.

=item B<-h>

Prints usage message and exits.

=back

=head1 ENVIRONMENT

B<DISPLAY> - used in the usual way.

=head1 AUTHORS

B<svkbd> was written by Christoph Lohmann (20h@r-36.net)
and Enno Boland (g # s01 ' de)

This man page written by B. Watson for the SlackBuilds.org project. It
may be used by anyone.
=cut
