.TH LSAR 1 2011-09-26 "The Unarchiver" "User Commands"
.SH NAME
lsar \- list archive file contents
.SH SYNOPSIS
.B lsar
[\fIOPTION\fR]... \fIARCHIVE\fR...
.SH DESCRIPTION
List the contents of \fIARCHIVE\fRs.
.SH OPTIONS
.TP
.BR \-l ", " \-long
Print more information about each file in the archive.
.TP
.BR \-L ", " \-verylong
Print all available information about each file in the archive.
.TP
.BR \-t ", " \-test
Test the integrity of the files in the archive, if possible.
.TP
.BR \-p ", " \-password " \fIPASSWORD"
The password to use for decrypting protected archives.
.TP
.BR \-e ", " \-encoding " \fIENCODING"
The encoding to use for filenames in the archive, when it is not
known.  If not specified, the program attempts to auto-detect the
encoding used.  Use "help" or "list" as the argument to give a listing
of all supported encodings.
.TP
.BR \-E ", " \-password\-encoding " \fIENCODING"
The encoding to use for the password for the archive, when it is not
known.  If not specified, then either the encoding given by the
\-encoding option or the auto-detected encoding is used.
.TP
.BR \-pe ", " \-print\-encoding
Print the auto-detected encoding and the confidence factor after the
file list.
.TP
.BR \-i ", " \-indexes
Instead of specifying the files to list as filenames or wildcard
patterns, specify them as indexes.
.TP
.BR \-j ", " \-json
Print the listing in JSON format.
.TP
.BR \-ja ", " \-json\-ascii
Print the listing in JSON format, encoded as pure ASCII text.
.TP
.BR \-nr ", " \-no\-recursion
Do not attempt to list the contents of archives contained in other
archives.  For instance, when listing a .tar.gz file, only list
the .tar file and not its contents.
.TP
.BR \-h ", " \-help
Display help information.
.TP
.BR \-v ", " \-version
Print version and exit.
.SH SEE ALSO
.BR unar (1)
