.TH unar 1 2011-09-26 "The Unarchiver" "User Commands"
.SH NAME
unar \- extract archive file contents
.SH SYNOPSIS
.B unar
[\fIOPTION\fR]... \fIARCHIVE\fR [\fIFILE\fR]...
.SH DESCRIPTION
Extract \fIFILE\fRs or the contents of \fIARCHIVE\fR.
.SH OPTIONS
.TP
.BR \-o ", " \-output\-directory " \fIDIRECTORY"
The directory to write the contents of the archive to.  Defaults to
the current directory.
.TP
.BR \-f ", " \-force\-overwrite
Always overwrite files when a file to be unpacked already exists on
disk.  By default, the program asks the user if possible, otherwise
skips the file.
.TP
.BR \-r ", " \-force\-rename
Always rename files when a file to be unpacked already exists on disk.
.TP
.BR \-s ", " \-force\-skip
Always skip files when a file to be unpacked already exists on disk.
.TP
.BR \-d ", " \-force\-directory
Always create a containing directory for the contents of the unpacked
archive.  By default, a directory is created if there is more than one
top-level file or folder.
.TP
.BR \-D ", " \-no\-directory
Never create a containing directory for the contents of the unpacked
archive.
.TP
.BR \-p ", " \-password " \fIPASSWORD"
The password to use for decrypting protected archives.
.TP
.BR \-e ", " \-encoding " \fIENCODING"
The encoding to use for filenames in the archive, when it is not
known.  If not specified, the program attempts to auto-detect the
encoding used.  Use "help" or "list" as the argument to give a listing
of all supported encodings.
.TP
.BR \-E ", " \-password\-encoding " \fIENCODING"
The encoding to use for the password for the archive, when it is not
known.  If not specified, then either the encoding given by the
\-encoding option or the auto-detected encoding is used.
.TP
.BR \-i ", " \-indexes
Instead of specifying the files to list as filenames or wildcard
patterns, specify them as indexes, as output by lsar.
.TP
.BR \-nr ", " \-no\-recursion
Do not attempt to extract archives contained in other archives. For
instance, when unpacking a .tar.gz file, only unpack the .tar file and
not its contents.
.TP
.BR \-t ", " \-copy\-time
Copy the file modification time from the archive file to the
containing directory, if one is created.
.TP
.BR \-k ", " "\-forks visible" | hidden | skip
How to handle Mac OS resource forks.  \fBvisible\fR creates
AppleDouble files with the extension ".rsrc", \fBhidden\fR creates
AppleDouble files with the prefix "._", and \fBskip\fR discards all
resource forks.  Defaults to \fBvisible\fR.
.TP
.BR \-q ", " \-quiet
Run in quiet mode.
.TP
.BR \-v ", " \-version
Print version and exit.
.TP
.BR \-h ", " \-help
Display help information.
.SH SEE ALSO
.BR lsar (1)
