.TH "partimaged-passwd" "8" "0.1" "Michael Biebl <biebl@teco.edu>" "Partition Image Server Configuration"
.SH "NAME"
.LP 
partimaged\-passwd \- Manage partimaged user accounts
.SH "SYNTAX"
.LP 
partimaged\-passwd [\-Dhl] \fIusername\fP \fIpassword\fR
.br 
partimaged\-passwd [\-Dhl] \fIusername\fP
.SH "DESCRIPTION"
.LP 
partimaged can either authenticate against local user accounts (This needs
access to /etc/shadow. As this is a potential security risk this method is 
not recommended) or its own password database in 
\fI/etc/partimaged/passwd.db\fR. To simplify the management of the partimaged
user database this tool was written. It allows to easily add and remove users 
or list the users in the database. All users in this database are allowed to
access the partimaged server.
.SH "OPTIONS"
.LP 
.TP 
\fB\-D\fR username
Delete the specified user from the password file.
.TP 
\fB\-l\fR
List users in password file and exit.
.TP 
\fB\-h\fR
Output help information and exit.
.SH "FILES"
.LP 
\fI/etc/partimaged/passwd.db\fP 

.SH "AUTHORS"
.LP 
Michael Biebl <biebl@debian.org>
.SH "SEE ALSO"
.LP 
partimaged(8), partimagedusers(5), partimage(1)
