.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LASTFM 1 "2007-12-06"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lastfm - Audio player for last.fm streams
.SH SYNOPSIS
.B /usr/bin/last.fm [options] [URL]
.SH DESCRIPTION
This manual page documents briefly the
.B lastfm
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.B LASTFM
is the flagship product from the team that designed the Audioscrobbler
system, a music engine based on a massive collection of Music Profiles.
Each music profile belongs to one person, and describes their taste in music.
Last.fm uses these music profiles to make personalized recommendations, match
you up with people who like similar music, and generate custom radio
stations for each person.

This program will allow you to play your personalized radio station streams
from the last.fm website.

.SH OPTIONS
.SS Arguments:
.TP
URL
A station url beginning with
.I lastfm://
.SS Options:
.TP
.B \-\-sanity
Show the number of listeners instead of the number of plays scrobbled.
.TP
.B \-tray
Start the program minimized as a tray icon.
.SH FILES
.TP
.I ~/.config/Last.fm/Last.fm.conf
Application config file.
.TP
.I ~/.local/share/Last.fm/cache/*
Cache files for album artwork and artist descriptions.
.TP
.I ~/.local/share/Last.fm/IpodDevice.db
SQLite database of songs played on the iPod.
.TP
.I ~/.local/share/Last.fm/Last.fm.log
Application log file.
.TP
.I ~/.local/share/Last.fm/*_mediadevice.xml
Submission cache of songs played on the iPod.
.TP
.I ~/.local/share/Last.fm/*_submissions.xml
Submission cache of songs played with the client.
.SH AUTHOR
This manual page was written by Paul Telford <pxt@debian.org>,
for the Debian project (but may be used by others). It has been updated by
John Stamp <jstamp@users.sourceforge.net>.
