.TH "NJAM" "6"
.SH "NAME"
njam - Pacman-like game with multiplayer support
.SH "SYNOPSIS"
.PP
\fBnjam\fR [\-w]  [\-h]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBnjam\fR command.
.PP
\fBnjam\fR is a pacman-like game with multiplayer support.
.SH "OPTIONS"
.PP
.IP "\fB\-w\fP 	" 10
Start in windowed mode (as opposed to fullscreen)
.IP "\fB\-h\fP 	" 10
use hardware surfaces (faster, doesn't work well with all graphic cards)

