.TH wmDate(0.7) 1x
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
wmdate \- A Window Maker window manager Dock app
.SH SYNOPSIS
.B wmdate
.I "[options]"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR wmdate
commands.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B wmdate
displays a 64x64 pixel calendar that's suitible for Docking in window manager
docking bars.
.SH OPTIONS
The programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-') and short options starting with one.
A summary of options are included below.
.TP
.B \-h, \-\-help
Show help text.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-w, \-\-windowed
Run program in windowed mode.
.TP
.B \-d, \-\-display <string>
Display to use.
.TP
.B \-s, \-\-not-shape
No shaped window.
.TP
.B \-t, \-\-test
Testing Mode.
.SH AUTHOR
This manual page was written by Darren Benham <gecko@debian.org> and
modified by Cezary M. Kruk.

wmDate is Copyrighted (c) 1999 by Alban Hertroys
All rights reserved.  See enclosed file for license details.
