.TH PHALANX "6" "January 2008" "Phalanx XXII"
.SH NAME
Phalanx \- Chess playing program
.SH SYNOPSIS
.B phalanx
[\fIoptions\fR] [\fI<moves> <minutes> \fR[\fI<increment in seconds>\fR]]
.br
.B phalanx
[\fIoptions\fR] [\fI<seconds per move>\fR]
.br
.B phalanx
\fIbench\fR
.br
.B phalanx
\fIbcreate \fR[\fIoptions\fR]
.SH DESCRIPTION
This manual page documents briefly the
.BR phalanx
program.
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
.PP
.B phalanx
is a chess playing program.  It is partially xboard compatible. Under
xboard, it can play games, force & undo moves, and show thinking. In
this version, you cannot set positions with xboard.
.PP
It is also possible to run phalanx without xboard. Do
.B phalanx -?
to get a list of command line options.  One important command of
phalanx's ASCII interface is
.B help.
.PP
.B phalanx
uses (traditional) 10x12 board implementation. There are three often
used board implementations: "8x8" (GNU Chess), "bitboard" (Crafty), and
"10x12" (Nimzo, Phalanx). In short, "10x12" is easy to implement and the
code is small (==fast on PC).  Opening book is small, simple,
hand-written.
.PP
.SH OPTIONS
\fB\-t\fR <transposition table size in kilobytes>
.HP
\fB\-f\fR <fixed search time in seconds>
.TP
\fB\-x\fR <+/->
xboard mode on/off        default: on
.TP
\fB\-p\fR <+/->
permanent brain on/off    default: off
.TP
\fB\-s\fR <+/->
show thinking on/off      default: off
.TP
\fB\-c\fR <+/->
cpu time                  default: off
.TP
\fB\-o\fR <+/->
polling input             default: on
.TP
\fB\-b\fR <+/->
opening book              default: on
.TP
\fB\-r\fR <resign value in centipawns>
default: 0 (no resigning)
.TP
\fB\-e\fR <easy level 0...100>
default: 0 (best play)
.TP
\fB\-l\fR <+/->
learning on/off           default: on
.TP
\fB\-v\fR
print version and exit
.HP
\fB\-P\fR <primary book directory>
.HP
\fB\-S\fR <secondary book directory>
.HP
\fB\-L\fR <learning file directory>
.HP
\fB\-g\fR <log file name>
.PP
.SH EXAMPLES 
phalanx \fB\-c\fR+ \fB\-s\fR+ \fB\-o\fR - \fB\-x\-\fR \fB\-f\fR 60 \fB\-t4000\fR

xboard \fB\-fcp\fR "phalanx \fB\-l\fR+ \fB\-r800\fR"
.SH "SEE ALSO"
/usr/doc/Phalanx-*, 
.IR xboard(6)
.SH AUTHOR
Phalanx was written by Dusan  Dobes  <dobes@math.muni.cz>.  This manual
page was written by Stephen Stafford <bagpuss@debian.org> for the Debian
GNU/Linux project, but may be used by others.  It was written with the
assistance of 
.IR help2man(1) 
and then edited slightly to clean it up. Modified by Marco Pessotto.
