#!/bin/sh

# Slackware build script for SameBoy

# Copyright 2017-2018 Hunter Sezen California, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=SameBoy
LIBNAM=$(printf %s $PRGNAM | tr 'A-Z' 'a-z')_libretro
SRCNAM=${LIBNAM%%_*}
VERSION=${VERSION:-2018.04.12_51e3cb7}
RGBVERS=${RGBVERS:-0.3.6}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# requires patching the Makefile to properly use
# the default CFLAGS and CXXFLAGS are probably fine
if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
cd $PRGNAM-$VERSION
tar xvf $CWD/rgbds-$RGBVERS.tar.gz
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

if [ "${DEBUG:=0}" != 0 ]; then
  CONF=debug
  DEBUG=1
else
  CONF=release
fi

PATH="$TMP/$PRGNAM-$VERSION/rgbds-$RGBVERS/bin:$PATH"

make -C rgbds-$RGBVERS Q=
make -C rgbds-$RGBVERS install Q= \
  PREFIX=. \
  DESTDIR=./

if pkg-config --exists sdl2; then
  make CONF=$CONF
  mkdir -p $PKG/usr/games $PKG/usr/share/games
  cp -av build/bin/SDL $PKG/usr/share/games/$SRCNAM

# SameBoy SDL doesn't work with FHS paths yet
# https://github.com/LIJI32/SameBoy/issues/39
cat > $PKG/usr/games/$SRCNAM <<EOF
#!/bin/sh
set -euf
CWD="\$(pwd)"
cd /usr/share/games/$SRCNAM

if [ "\${1:-}" ]; then
  case "\$1" in
    /* ) ./$SRCNAM "\$1" ;;
    * ) ./$SRCNAM "\$CWD/\$1" ;;
  esac
else
  ./$SRCNAM
fi
EOF

  chmod 0755 $PKG/usr/games/$SRCNAM
else
  make bootroms
fi

make -C libretro DEBUG=$DEBUG GIT_VERSION="${VERSION#*_}"

install -Dm0644 build/bin/$LIBNAM.so $PKG/usr/lib${LIBDIRSUFFIX}/libretro/$LIBNAM.so
install -Dm0644 $LIBNAM.info $PKG/usr/lib${LIBDIRSUFFIX}/libretro/info/$LIBNAM.info

if [ $DEBUG = 0 ]; then
  find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
    | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
fi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGES.md LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
