.TH "AVOGADRO" "1" "22 January 2009" "" "User commands"

.SH NAME
avogadro \- Molecular Graphics and Modelling System

.SH SYNOPSIS
\fBavogadro\fR [\fBoptions\fR] [\fIfiles\fR]

.SH DESCRIPTION
.PP
\fBavogadro\fR is a molecular graphics and modelling system targeted at molecules
and biomolecules.  It can visualize properties like molecular orbitals or
electrostatic potentials and features an intuitive molecular builder.

.SH OPTIONS
.PP
Listed below are the command line options for \fBavogadro\fR:
.TP
.B \-\-help, \-h
Show help options.
.TP
.B \-\-version, \-v
Show version information.

.SH AUTHOR
.PP
This manual page was written by Jordan Mantha <\&laserjock@ubuntu.com\&>.
.PP
Released under the GNU General Public License, version 2 or later.
