.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SOLARWOLF 6 "Feb 22, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
solarwolf \- Collect the boxes and don't become mad
.SH SYNOPSIS
.B solarwolf
.SH DESCRIPTION
This manual page documents briefly the
.B solarwolf
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBsolarwolf\fP is an action/arcade game written entirely in Python.
It is is originally based on the SolarFox game on the Atari 2600.
.p
The point of the game is to scramble through 60 levels of patterns,
collecting all the boxes. The part that makes it tricky is avoiding
the relentless hailstorm of fire coming at you from all directions.
You can use the "-window" and/or "-nosound" flags to force some
of the options from the command line.
.SH AUTHOR
The solarwolf game was written by Pete Shinners <pete@shinners.org>.
