.TH MP3GAIN "1" "Jan 2018" "mp3gain version 1.6.1" "SlackBuilds.org"
.SH NAME
mp3gain \- analyzes and adjusts mp3 files so that they have the same volume
.SH SYNOPSIS
.B mp3gain
[\fIoptions\fR] \fI<infile> \fR[\fI<infile 2> \fR...]
.SH DESCRIPTION
Tired of reaching for your volume knob every time your mp3 player changes to a new song?
MP3Gain analyzes and adjusts mp3 files so that they have the same volume.
.PP
MP3Gain does not just do peak normalization, as many normalizers do. Instead, it does some statistical analysis to determine how loud the file actually sounds to the human ear.
.PP
Also, the changes MP3Gain makes are completely lossless. There is no quality lost in the change because the program adjusts the mp3 file directly, without decoding and re-encoding.
.SH OPTIONS
.TP
\fB\-v\fR
show version number
.TP
\fB\-g\fR <i> 
apply gain i to mp3 without doing any analysis
.TP
\fB\-l\fR 0 <i>
apply gain i to channel 0 (left channel) of mp3
without doing any analysis (ONLY works for STEREO mp3s,
not Joint Stereo mp3s)
.TP
\fB\-l\fR 1 <i>
apply gain i to channel 1 (right channel) of mp3
.TP
\fB\-e\fR 1 <i>
skip Album analysis, even if multiple files listed
.TP
\fB\-r\fR
apply Track gain automatically (all files set to equal loudness)
.TP
\fB\-k\fR
automatically lower Track/Album gain to not clip audio
.TP
\fB\-a\fR
apply Album gain automatically (files are all from the same
album: a single gain change is applied to all files, so
their loudness relative to each other remains unchanged,
but the average album loudness is normalized)
.TP
\fB\-m\fR <i>
modify suggested MP3 gain by integer i
.TP
\fB\-d\fR <n>
modify suggested dB gain by floating\-point n
.TP
\fB\-c\fR
ignore clipping warning when applying gain
.TP
\fB\-o\fR
output is a database\-friendly tab\-delimited list
.TP
\fB\-t\fR
mp3gain writes modified mp3 to temp file, then deletes original
instead of modifying bytes in original file
.TP
\fB\-T\fR
Assume input file is an MPEG 2 Layer III file (i.e. don't check for mis-named Layer I or Layer II files)
.TP
\fB\-q\fR
Quiet mode: no status messages
.TP
\fB\-p\fR
Preserve original file timestamp
.TP
\fB\-x\fR
Only find max. amplitude of mp3
.TP
\fB\-f\fR
Force mp3gain to assume input file is an MPEG 2 Layer III file
(i.e. don't check for mis\-named Layer I or Layer II files)
.TP
\-? or \fB\-h\fR
show built-in help message
.TP
\fB\-s\fR c
only check stored tag info (no other processing)
.TP
\fB\-s\fR d
delete stored tag info (no other processing)
.TP
\fB\-s\fR s
skip (ignore) stored tag info (do not read or write tags)
.TP
\fB\-s\fR r
force re\-calculation (do not read tag info)
.TP
\fB\-s\fR i
use ID3v2 tag for MP3 gain info
.TP
\fB\-s\fR a
use APE tag for MP3 gain info (default)
.TP
\fB\-u\fR
undo changes made by mp3gain (based on stored tag info)
.TP
\fB\-w\fR
"wrap" gain change if gain+change > 255 or gain+change < 0
(use "\-? wrap" switch for a complete explanation)
.PP
If you specify \fB\-r\fR and \fB\-a\fR, only the second one will work.
If you do not specify \fB\-c\fR, the program will stop and ask before
applying gain change to a file that might clip.
.SH AUTHORS
Coding by Glen Sawyer
.br
Unix-ification by Stefan Partheymüller
.br
DLL-ification by John Zitterkopf
.br
Additional tweaks by Artur Polaczynski, Mark Armbrust, and others
.PP
Man page created by B. Watson for the SlackBuilds.org project, but may
be used by others.
.SH COPYRIGHT
Copyright(c) 2001-2004 by Glen Sawyer.
.PP
mp3gain uses mpglib, which can be found at \fIhttp://www.mpg123.de\fR.
.PP
mp3gain is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
.SH SEE ALSO
\fBnormalize(1)\fR
