#!/bin/sh

# Slackware build script for superkey-launch

# Ryan P.C. McQuen | Everett, WA | ryan.q@linux.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version, with the following exception:
# the text of the GPL license may be omitted.

# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of
# merchantability or fitness for a particular purpose. Compiling,
# interpreting, executing or merely reading the text of the program
# may result in lapses of consciousness and/or very being, up to and
# including the end of all existence and the Universe as we know it.
# See the GNU General Public License for more details.

# You may have received a copy of the GNU General Public License along
# with this program (most likely, a file named COPYING).  If not, see
# <http://www.gnu.org/licenses/>.

PRGNAM=superkey-launch
VERSION=${VERSION:-1.6.3}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
mkdir -p $PKG/etc/xdg/autostart/
cd $TMP
rm -rf $PRGNAM-$VERSION
if [ -e $CWD/$PRGNAM-$VERSION.tar.gz ]; then
  tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
else
  tar xvf $CWD/$VERSION.tar.gz
fi
cd $PRGNAM-$VERSION

sed -i "s|MANDIR?=/local/man/man1|MANDIR?=/man/man1|" Makefile
make \
  OPTS="$SLKCFLAGS" \
  PREFIX=/usr \
  MANPREFIX=/usr/man \
  X11INC=/usr/include \
  X11LIB=/usr/lib${LIBDIRSUFFIX}/X11

make install \
  OPTS="$SLKCFLAGS" \
  PREFIX=/usr \
  MANPREFIX=/usr/man \
  X11INC=/usr/include \
  X11LIB=/usr/lib${LIBDIRSUFFIX}/X11 \
  DESTDIR=$PKG

install -m644 $PRGNAM.desktop $PKG/etc/xdg/autostart/

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp $CWD/README $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
