#!/bin/bash

# Slackware build script for Ted
# Copyright 2025 B. Watson (urchlay@gmail.com).
# Copyright 2019 GOSIKI Agiri <agiri@cocaine.ninja>.
# Previously written by Willy Sudiarto Raharjo <willysr@slackbuilds.org>.
# Originally written by Hannes Worst <hannesworst@gmail.com>.
# All right reserved
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# 20251123 bkw: BUILD=3
# - take over maintenance.
# - install docs to Slackware standard doc dir.
# - simplify script (it was a mess).
# - show GTK or MOTIF in slack-desc (if nothing else, it helps me).
# - use MOTIF=yes rather than a WIDGET variable.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=Ted
VERSION=${VERSION:-2.23}
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   MARCH=i386
elif [ "$ARCH" = "i686" ]; then
   SLKCFLAGS="-O2 -march=i686 -mtune=i686"
   MARCH=i386
elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   MARCH=amd64
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/ted-$VERSION.src.tar.gz
cd $PRGNAM-$VERSION
find . ! -type l    -a \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \)

# Set the right ARCH
sed \
  -e "/^M_MACHINE/s|=.*|=$ARCH|" \
  -e "/^M_ARCH/s|=.*|=$ARCH|" \
  -i tedPackage/configure

# select appropriate widget set
if [ "${MOTIF:-no}" = "yes" ]; then
  widgetopt=MOTIF
else
  widgetopt=GTK
fi

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
make -j1 CONFIGURE_OPTIONS="--with-$widgetopt"
make -j1 package

# 20251123 bkw: binary already stripped.

# Extract the tarball created by 'make package'
tar xvfC tedPackage/ted-$VERSION-linux-$MARCH.tar.gz $PKG/

PKGMAN1=$PKG/usr/man/man1/
mkdir -p $PKGMAN1
rm -f $PKG/usr/share/Ted/doc/Ted.1
mv $PKG/usr/share/Ted/doc/*.1 $PKGMAN1
gzip -9 $PKGMAN1/*.1
mv $PKG/usr/share/man/man1/Ted.1.gz $PKGMAN1
rm -rf $PKG/usr/share/Ted/doc/ $PKG/usr/share/man

# a couple of useful scripts to fix and convert documents
for i in $PKG/usr/share/Ted/examples/*.sh; do
  mv $i $PKG/usr/bin/$(basename -s .sh $i)
done
rm -rf $PKG/usr/share/Ted/examples

PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
mkdir -p $PKG/usr/doc
mv $PKG/usr/share/Ted/varia $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild
mv $PKG/usr/share/Ted/config/ $PKGDOC/

# 20251124 bkw: in case some(one|thing) depends on this:
ln -s ../../doc/$PRGNAM-$VERSION $PKG/usr/share/Ted/varia

mkdir -p $PKG/install
sed "s,@WIDGETS@,$widgetopt," < $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh >  $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
