#!/bin/sh

# Slackware build script for fceux

# Written by M.Dinslage (daedra1@charter.net)

PRGNAM=fceux
VERSION=${VERSION:-2.1.2}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-4}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.src.tar.bz2
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Build fceux
cd $TMP/fceu
scons
mkdir -p $PKG/usr/bin
install -m 0755 bin/fceux $PKG/usr/bin
mkdir -p $PKG/usr/man/man6
install -m 0644 documentation/fceux.6 $PKG/usr/man/man6
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/fceux
cp -a \
  bin/fceux.chm COPYING INSTALL NEWS README TODO-PROJECT \
  $PKG/usr/doc/$PRGNAM-$VERSION/fceux

# Buidl gfceux
cd $TMP/gfceux
python setup.py install --prefix=$PKG/usr
mkdir -p $PKG/usr/man/man1
mv $PKG/usr/share/man/man1/gfceux.1 $PKG/usr/man/man1
gzip -9 $PKG/usr/man/man?/*
rm -rf $PKG/usr/share/man
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/gfceux
cp -a \
  ChangeLog COPYING INSTALL TODO \
  $PKG/usr/doc/$PRGNAM-$VERSION/gfceux

# This is supposed to work with gtk+2-2.14.x as well...
sed -i "s%2.16%2.14%" $PKG/usr/share/gfceux/gfceux.glade

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
)

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
