# pod2man -r0.7 -s1 --stderr -cyae yae.pod > yae.1

=pod

=head1 NAME

B<yae> - Yet another Apple Emulator

=head1 SYNOPSIS

B<yae> [-2|-e|-+] [disk-image] ...

=head1 DESCRIPTION

B<yae> emulates the Apple II, II+, and //e 8-bit computers from Apple,
Inc. Standard .dsk images are supported. If B<yae> is run without any
disk image arguments, I</usr/share/yae/Master.dsk> will be booted.

ROM image files are required; see B<FILES> for details.

OSS audio is supported, using the /dev/audio device. For Linux systems
using ALSA, OSS audio is provided by the snd_pcm_oss and snd_mixer_oss
kernel modules. If /dev/audio can't be opened, the emulator will run
with sound disabled.

=head1 OPTIONS

=over

=item -2

Emulate the Apple II.

Note that the emulator uses the same ROM image for II and II+, so the
emulated II will have Applesoft and autostart (which the original II
didn't ship with).

=item -+

Emulate the Apple II+.

=item -e

Emulate the Apple //e (the default).

=back

=head1 KEYSTROKES

=over

=item Backspace

Alias for the left-arrow key.

=item Control+Delete

Apple Reset key.

=item Left Alt

The left (open) apple key on the //e keyboard.

=item Right Alt

The right (closed) apple key on the //e keyboard.

=item F1

Change disks in the first drive (slot 6, drive 0). This will either
read a filename on standard input (if kdialog can't be run), or display
a kdialog file-selector. Either way, the emulator stops and its window
becomes unresponsive until a file has been chosen.

=item F2

Exit the emulator immediately. No confirmation dialog, so
be careful.

=back

All other keystrokes are translated to their equivalent Apple II
keystrokes, or ignored if there is no equivalent key on the Apple
keyboard.

=head1 FILES

=over

=item B<.yaerc>, B<~/.yaerc>

Config file. Searched for first in the current directory,
then in user's home directory. For config file syntax, see
I</usr/share/yae/yaerc.sample>.

=item ROM files

For II and II+ emulation, the required ROM image is called B<APPLE2.ROM>.
For the //e, the image is B<APPLE2E.ROM>. For all modes, B<DISK.ROM> is
required.

ROM file locations can be set in the config file. By default, they're
searched for in the current directory. If the ROMs can't be found in
the configured location or the current directory, they will searched
for in I</usr/share/yae>.

If the required ROM files can't be found, the emulator will refuse
to start.

=back

=head1 SEE ALSO

B<kegs>(1), B<dos33fsutils>(1)

=head1 AUTHORS

B<yae> was originally written by Doug Kwan, and includes enhancements by
Warren Toomey. The version documented here also has some small bugfixes
and enhancements by B. Watson.

This man page was written by B. Watson.
