#!/bin/sh

# Copyright 2009  Robert Allen - slacker@slaphappygeeks.com
# All rights reserved including Creator Endowed Unalienable Rights.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Modified by Robby Workman <rworkman@slackbuilds.org>

PRGNAM=saxonb
VERSION=${VERSION:-9.1.0.5j}
ARCH=i486
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

# Upstream source uses dashes for the VERSION string
SRC_VERSION=$(echo $VERSION |tr '.' '-')

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir $PRGNAM-$VERSION
unzip -d $PRGNAM-$VERSION $CWD/${PRGNAM}${SRC_VERSION}.zip
cd $PRGNAM-$VERSION
chown -R root:root .

mkdir -p $PKG/usr/bin
cat $CWD/saxonbt > $PKG/usr/bin/saxonbt
cat $CWD/saxonbq > $PKG/usr/bin/saxonbq
chmod 0755 $PKG/usr/bin/*

mkdir -p $PKG/usr/lib/$PRGNAM-$VERSION
cp -a *.jar $PKG/usr/lib/$PRGNAM-$VERSION
# Add convenience symlink
( cd $PKG/usr/lib ; ln -s $PRGNAM-$VERSION $PRGNAM )

# We'll install profile scripts, and they will *not* be config()'d
mkdir -p $PKG/etc/profile.d
cat $CWD/sh.profile > $PKG/etc/profile.d/saxonb.sh
cat $CWD/csh.profile > $PKG/etc/profile.d/saxonb.csh
chmod 0755 $PKG/etc/profile.d/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a doc/* notices/* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/README.SLACKWARE > $PKG/usr/doc/$PRGNAM-$VERSION/README.SLACKWARE
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -c n -l y $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
