#!/bin/bash

# Slackware build script for wxFormBuilder

# Copyright 2024 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=wxFormBuilder
VERSION=${VERSION:-4.1.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}


if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}
BUILDDIR=$TMP/$PRGNAM-$VERSION


if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e
rm -rf $PKG $BUILDDIR
mkdir -p $TMP $PKG $OUTPUT $BUILDDIR
cd $TMP
tar xvfz $CWD/$PRGNAM-$VERSION-source-full.tar.gz
cd $BUILDDIR

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PKG/opt/wxFormBuilder" -DCMAKE_BUILD_TYPE=Release
cmake --build _build --config Release
cmake --install _build --config Release

#remove zero length files
rm $PKG/opt/wxFormBuilder/share/mime/XMLnamespaces
rm $PKG/opt/wxFormBuilder/share/mime/subclasses
rm $PKG/opt/wxFormBuilder/share/mime/generic-icons
rm $PKG/opt/wxFormBuilder/share/mime/aliases

# create program symlinks
mkdir -p $PKG/usr/bin
( cd $PKG/usr/bin ; rm -rf wxformbuilder )
( cd $PKG/usr/bin ; ln -sf ../../opt/wxFormBuilder/bin/wxformbuilder wxformbuilder )
mkdir -p $PKG/usr/share/applications
( cd $PKG/usr/share/applications ; rm -rf org.wxformbuilder.wxFormBuilder.desktop )
( cd $PKG/usr/share/applications ; ln -sf ../../../opt/wxFormBuilder/share/applications/org.wxformbuilder.wxFormBuilder.desktop org.wxformbuilder.wxFormBuilder.desktop )
mkdir -p $PKG/usr/share/pixmaps
( cd $PKG/usr/share/pixmaps ; rm -rf org.wxformbuilder.wxFormBuilder.png )
( cd $PKG/usr/share/pixmaps ; ln -sf ../../../opt/wxFormBuilder/share/icons/hicolor/48x48/apps/org.wxformbuilder.wxFormBuilder.png org.wxformbuilder.wxFormBuilder.png )



rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG -name perllocal.pod -o -name ".packlist" -o -name "*.bs" | xargs rm -f || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
