#!/bin/sh

# Copyright (c) 2014, Симонъ–Севаръ Болокановъ, Bulgaria <sbolokanov@abv.bg>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Written by: Симонъ Болокановъ <sbolokanov@abv.bg>
# Date: Unknown

# Changelog:
#    v1.3.3 - Re-done the sript and send it to SBo
#    27.2.2015 - no headers!? - thanks to Marcel Saegebarth for spotting this
#    3.3.2015 - added STATICLIB per Marcel Saegebarth request
#      П.П. Честит ден на Освобождението, българи!
#    10.3.2015 - made quiet the clean up, script actually broke on last update…
#      3 Мартъ 1878 – възстановѧване на Българиѧ, 3 Мартъ 1918 (40 г. по–късно) – победа надъ Русиѧ

PRGNAM=rhash
VERSION=${VERSION:-1.4.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

# Shall we compile with OpenSSL support?
OPENSSL=${OPENSSL:-yes}

# Shall we install static libraries?
STATICLIB=${STATICLIB:-no}

if [ "$OPENSSL" != "yes" ]; then
  ENABLEOSSL="--disable-openssl"
fi

if [ "$STATICLIB" = "yes" ]; then
  ENABLESTATICLIB="--enable-lib-static"
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i486 ;;
    arm*) export ARCH=arm ;;
       *) export ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -m32 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

cd $TMP
rm -rf RHash-$VERSION
tar xvf $CWD/RHash-$VERSION.tar.gz
cd RHash-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

if [ "$STATICLIB" = "yes" ]; then
  echo "+=============================+"
  echo "| STATIC LIBRARY ACTIVATED!!! |"
  echo "+=============================+"
fi

# enable-gettext - internationalization support
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  --enable-gettext \
  $ENABLESTATICLIB \
  $ENABLEOSSL \
  --extra-cflags="${SLKCFLAGS} ${OPTCFLAGS}" \
  --extra-ldflags="${OPTLDFLAGS}"

make DESTDIR=$PKG install install-gmo install-lib-so-link
# Don't clobber the default config
mv -v $PKG/etc/rhashrc $PKG/etc/rhashrc.new

# Copy docs
mkdir -pv $PKG/usr/doc/$PRGNAM-$VERSION
cp -a ChangeLog COPYING README.md INSTALL.md $PKG/usr/doc/$PRGNAM-$VERSION/
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -pv $PKG/install
cat $CWD/doinst.sh > $PKG/install/doinst.sh
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
