.TH u4 1 "26 Oct 2011" "Version 1.1+svn" "XU4 Manual"

.SH NAME
\fBu4\fR \- A modern reimplementation of the classic Ultima IV role\-playing game.

.SH SYNOPSIS
.B u4
.RI [ options ]

.SH DESCRIPTION
.B XU4
is a remake of the computer game Ultima IV.  The goal is to make
it easy and convenient to play this classic on modern operating
systems. 
.PP
This man page only describes the command\-line options and keyboard commands
supported by \fBu4\fR.
For full documentation, see the files in \fI/usr/doc/xu4\-@VERSION@/\fR. The
README is a good place to start. Also the "History of Britannia" and the "Book
of Mystic Wisdom" are found there (you should read them before playing).
.SH OPTIONS
\fBu4\fR accepts the following options:
.TP
.B "\-f, \-\-fullscreen"
Run in fullscreen mode.
.TP
.B \-filter <filt>
Apply a filter on the scaled images. The <filt>
parameter must be set to one of the following
case\-sensitive options:
.I point
.I 2xBi
.I 2xSaI
.I Scale2x
.TP
.B "\-i, \-skipintro"
Skip the intro, and go directly into the game.
This option requires the existance of a valid saved game.
.TP
.B "\-p <profname>, \-profile <profname>"
Activate a specific save game profile.  Using this
option, you may have multiple saved games at the
same time. Also, the game's config is stored on
a per\-profile basis, so different profiles could
have e.g. different screen resolutions.
Use quotation marks around profile names that
include spaces.
All profiles are stored in the
.I ~/.xu4/profiles
sub\-directory.
The active profile name is shown on the
introduction map view off the main menu.
.TP
.B "\-q, \-quiet"
Quiet mode \- no music.
.TP
.B \-scale <n>
Scale the original graphics by a factor of <n>.
Factor <n> must be 1, 2, 3, 4, or 5.
.TP
.B "\-v, \-verbose"
Verbose output; prints out information useful for
trouble\-shooting.
.SH KEYBOARD CONTROLS
XU4 is played entirely with the keyboard. To make choices from menus,
press the first letter of the menu choice (e.g. \fBJ\fR for "Journey Onward"
at the main menu). The Config menu also supports navigation with the arrow
keys and Enter.
.PP
During gameplay, the following keystrokes are supported (information taken
from Keyboard.txt and README):
.TP
.B A (Attack)
Attempt to engage thy foe with the weapon thou hast
readied (Ready Weapon command); must be followed by the
direction of thy foe.
.TP
.B B (Board)
Board a vessel or mount a horse.
.TP
.B C (Cast)
Cast a magical spell; must be followed by the number
of the player who wishes to cast it (not needed in combat or
in dungeon rooms), and then the first letter of the desired
spell.  Note: All spells must have reagents mixed in advance
of casting.
.TP
.B D (Descend)
Climb down ladder to next level of dungeon or
building.
.TP
.B E (Enter)
Go into such places as villages, townes, castles,
dungeons and shrines.
.TP
.B F (Fire)
Fire a ship's cannons (once thou hast Boarded); must
be followed by a direction.  Note: Broadsides only!
.TP
.B G (Get Chest)
Attempt to open (and disarm, if trapped) chest;
must be followed by the number of the player who wishes to
open the chest, except during combat and in dungeon rooms.
Note: 'Tis wisest to use the player with the highest
Dexterity when examining potentially dangerous chests as
this lessens the chances of setting off any traps.
.TP
.B H (Hole up and camp)
Set up camp to rest and recover from thy wounds.
Note: This command may only be used successfully with limited frequency.
.TP
.B 1 (Ignite a torch)
Light a torch for illumination in dungeons. Requires a special item.
.TP
.B J (Jimmy lock)
Use a magical key to unlock a sealed door. Must be followed by the direction of the door that thou dost wish to unlock.
.TP
.B K (Klimb)
Climb up a ladder to the next level of a building or dungeon, or to reach the surface from the topmost level of a dungeon.
.TP
.B L (Locate Position)
Requires a special item.
.TP
.B M (Mix Reagents)
Prepare material components of spells for later use.
Note: Thou must have reagents mixed ahead of time in
order to cast any spells.  When asked "Reagent:", type the
letter corresponding to the reagents desired and then type
[Return] when thou wishes to mix them.
.TP
.B N (New order)
Exchanges the position of two players indicated within thy party, except for player #1, for thou must lead the party.
.TP
.B O (Open door)
Open a door in the direction indicated.
.TP
.B P (Peer at gem)
Requires a special item.
.TP
.B Q (Quit & Save)
Saves the current game status to disk; thou may continue after this command or power down thy computer.
.TP
.B R (Ready a weapon)
Equip a player with the weapon of thy choice (if owned) for use in combat.
.TP
.B S (Search)
Search thy exact current location for unusual items.
.TP
.B T (Talk)
Allows a player to converse with merchants or townesfolk in the direction indicated.
.TP
.B U (Use)
Use an item thou hast found during play by means of the "Search" command.
.TP
.B V (Volume)
Toggles sound effects on or off.
.TP
.B W (Wear armour)
Outfits a player with the armour of thy choice if owned for defense in combat.
.TP
.B X (Xit)
That's (e)xit thy current form of transportation and continue on foot.
.TP
.B Y (Yell)
Yell "giddyup" or "whoa" to speed up or slow down thy horse.
.TP
.B Z (Ztats)
Displays the status and attributes of a
selected player; if 0 is pressed instead of a player number,
this command will display the lists of weapons, armour,
items, reagents and mixtures.  The left and right arrow
keys will scroll through these lists, while pressing any
other key will return thee to game play.
.TP
.B
ARROW KEYS
Control movement. North/South/East/West
.SH FILES
.TP
.B ~/.xu4/
Configuration and saved games are stored here, when \fB\-p\fR is not in use. The config file is
\fBxu4rc\fR. It is human\-readable and editable, but normally is
created and updated by the in\-game configuration menu. The savegames
are in a binary format.
.TP
.B ~/.xu4/profiles/<profname>/
When using the \fB\-p <profname>\fR option, config and savegame data are
stored here instead.
.SH AUTHORS
Ultima IV was created by Richard Garriott, aka Lord British.
.PP
.B XU4
authors:
.br
Andrew Taylor <andrewtaylor@users.sourceforge.net>
.br
        Main developer
.PP
Marc Winterrowd <nodling at yahoo dot com>
.br
        LZW decoder, tile animations, title screen fixes, and lots more
.PP
Daniel Browning\-Weber <dan_ultima@users.sourceforge.net>
.br
        Developer
.PP
Darren Janeczek <darren_janeczek@users.sourceforge.net>
.br
        Developer
.PP
Doug Day <dougday@users.sourceforge.net>
.br
        Developer
.PP
Travis Howell <kirben@users.sourceforge.net>
.br
        Windows port
.PP
Frank Wolter <FrankWolter@gmx.net>
.br
        Ultima IV icon used in xu4
.PP
Dennis De Marco <dennis@demarco.com>
.br
        Sound code
.PP
Steve Saunders <s_j_nevets@yahoo.com.au>
.br
        MacOSX port
.PP
Michael Ryan <solus@users.sourceforge.net>
.br
        Text colorization, profiles, enhanced LOS algorithm, title/intro sequence, general fixes
.PP
Gregory Saunders <grerfy@users.sourceforge.net>
.br
        Amiga file formats, minor enhancements
.PP
Man page created (from README contents) by B. Watson, for the SlackBuilds.org
project. Permission hereby granted to use this man page anywhere, for any purpose.
