#!/bin/bash

# Slackware build script for mmv

# Written by B. Watson (urchlay@slackware.uk)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20240813 bkw: update for v2.7.
# 20240314 bkw: update for v2.6.
# 20230822 bkw: update for v2.5.1.
# 20230711 bkw: update for v2.4.
# 20221228 bkw: update for v2.3.

# This is ancient software (1.01b was released in 1990), but recently
# someone started maintaining it on github (2.x series), which is
# excellent! It's now a lot easier to build, and some bugs have been
# fixed.

# Note to self: do not use the github /archive/ URLs; they require
# a bunch of cruft and the ./bootstrip script expects to clone git
# repos. Do use the /releases/download/ URLs; these Just Work with no
# extra deps.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=mmv
VERSION=${VERSION:-2.7}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} + -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} +

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --build=$ARCH-slackware-linux

make
rm mmv.1 ; make mmv.1 # breaks due to parallel build.
make install-strip DESTDIR=$PKG
gzip -9 $PKG/usr/man/man?/*.*

# multi-named executable, uses its name to decide what action to take.
# 'make install' creates the symlinks to the binary but not the man page.
# in 2.3, the "mad" symlink is gone. doubt anyone misses it.
# 20240314 bkw: in 2.6, "mad" is back (someone *did* miss it).
LINKS="mcp mln mad"
for i in $LINKS; do
  ln -s $PRGNAM.1.gz $PKG/usr/man/man1/$i.1.gz
done

# README.md is already installed in $PKGDOC. NEWS and ChangeLog
# are both "see git history at <url>", worth keeping one but not both.
PKGDOC=$PKG/usr/doc/$PRGNAM-$VERSION
cp -a AUTHORS ChangeLog $PKGDOC
cat $CWD/$PRGNAM.SlackBuild > $PKGDOC/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
