#!/bin/sh
#
# Slackware build script for android-tools
# Thanks to the Arch linux maintainers for the makefiles

# Copyright 2016, 2017 Philip van der Hoeven, Almere, NL
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


PRGNAM=android-tools
VERSION=${VERSION:-8.0.0_r24}
SRC1=core-6cd85e2a89347e0a107f59e38ece61fa19e6da78.tar.gz
SRC2=extras-af2dce5151ad478673401211dd71ae1579d2b5be.tar.gz
SRC3=selinux-be29c2550c3ff6551a56048c075a88da01b46cab.tar.gz
SRC4=f2fs-tools-b8baf1712d991541141bb0bdddd625f527e6d41f.tar.gz
SRC5=boringssl-58e449904e248f34bdfc2be7a609c58bcb0257b7.tar.gz

BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $TMP/android-tools
mkdir $TMP/android-tools
cd $TMP/android-tools

mkdir core
tar -xvf $CWD/$SRC1 -C core
mkdir extras
tar -xvf $CWD/$SRC2 -C extras
mkdir selinux
tar -xvf $CWD/$SRC3 -C selinux
mkdir f2fs-tools
tar -xvf $CWD/$SRC4 -C f2fs-tools
mkdir boringssl
tar -xvf $CWD/$SRC5 -C boringssl

#git clone --branch android-$VERSION --depth 1 https://android.googlesource.com/platform/system/core
#git clone --branch android-$VERSION --depth 1 https://android.googlesource.com/platform/system/extras
#git clone --branch android-$VERSION --depth 1 https://android.googlesource.com/platform/external/libselinux
#git clone --branch android-$VERSION --depth 1 https://android.googlesource.com/platform/external/f2fs-tools

# generate_build.rb borrowed from Arch Linux
# And thanks to Alan Alberghini for the make_ext4fs patch.
PKGVER=$VERSION ruby $CWD/generate_build.rb > build.ninja

cd core
patch -p1 < $CWD/fix_build_core.patch
cd ..

cd selinux
patch -p1 < $CWD/fix_build_selinux.patch
cd ..

chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Build boringssl
mkdir -p boringssl/build
cd boringssl/build
cmake -GNinja ..
ninja
cd ../..

ninja

mkdir -p $PKG/usr/bin
install -Dm 755 adb $PKG/usr/bin/adb
install -Dm 755 fastboot $PKG/usr/bin/fastboot
install -Dm 755 core/mkbootimg/mkbootimg $PKG/usr/bin/mkbootimg
install -Dm 755 make_ext4fs $PKG/usr/bin/make_ext4fs

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
