perl-Text-CharWidth
perl-MIME-Charset
perl-Unicode-LineBreak
perl-Term-ReadLine-Gnu
perl-html-tagset
perl-lwp-mediatypes
perl-http-date
perl-html-parser
perl-encode-locale
perl-IO-HTML
perl-http-message
perl-www-robotrules
perl-net-http
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-file-listing
perl-common-sense
perl-Net-LibIDN
Net-SSLeay
perl-Types-Serialiser
perl-Test-RequiresInternet
perl-PAR-Dist
perl-Mozilla-CA
perl-IO-Socket-SSL
perl-Canary-Stability
libwww-perl
perl-lwp-useragent-cached
perl-data-dump
perl-Module-Build
perl-LWP-Protocol-https
perl-JSON-XS
perl-JSON
perl-Class-Inspector
perl-File-ShareDir
perl-extutils-pkgconfig
perl-extutils-depends
perl-glib
perl-cairo
perl-pango
perl-gtk2
youtube-viewer
