#!/bin/bash

# Slackware build script for grace

# Written by B. Jogai <jogaib {at} comcast [dot] net>
# Substantially modified by Robby Workman <rworkman@slackware.com>
# Updated by Fellype do Nascimento <fellype (at) gmail (dot) com
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=grace
VERSION=${VERSION:-5.1.25}
BUILD=${BUILD:-1}
TAG=${TAG:-"_SBo"}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-"/tmp/SBo"}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-"/tmp"}

if [ "$ARCH" = "i586" ]; then
    SLKCFLAGS="-O2 -march=i586 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
else
    SLKCFLAGS="-O2"
    LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Fix paths to docs in src/xmgrace.c
sed -i "s%/usr/share/doc/packages/%/usr/lib${LIBDIRSUFFIX}/%g" src/xmgrace.c

CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --bindir=/usr/bin \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --enable-grace-home=/usr/lib${LIBDIRSUFFIX}/xmgrace \
  --with-x \
  --with-printcmd="lpr" \
  --with-helpviewer="firefox %s" \
  --build=$ARCH-slackware-linux

make
make DESTDIR=$PKG install
# Set up the links for /usr/bin, /usr/include, and /usr/lib
make DESTDIR=$PKG install links

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Fix hardcoding of /usr/lib in the "links" target
if [ "$ARCH" = "x86_64" ]; then
   mv $PKG/usr/lib/*.a $PKG/usr/lib${LIBDIRSUFFIX}
   rmdir $PKG/usr/lib 2>/dev/null || true
fi

# Add desktop menu entries
mkdir -p $PKG/usr/share/{applications,pixmaps}
cat $CWD/xmgrace.png > $PKG/usr/share/pixmaps/xmgrace.png
cat $CWD/xmgrace.desktop > $PKG/usr/share/applications/xmgrace.desktop

mkdir -p $PKG/usr/doc
mv $PKG/usr/lib${LIBDIRSUFFIX}/xmgrace/doc $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CHANGES ChangeLog README DEVELOPERS LICENSE \
    $PKG/usr/doc/$PRGNAM-$VERSION
find $PKG/usr/doc/$PRGNAM-$VERSION -type f -exec chmod 644 {} \;
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
( cd $PKG/usr/lib${LIBDIRSUFFIX}/xmgrace  # now make the compat symlink
  ln -s ../../doc/$PRGNAM-$VERSION doc
)

rm -f $PKG/usr/man/man1/*
cp -a $PKG/usr/doc/$PRGNAM-$VERSION/*.1 $PKG/usr/man/man1
gzip -9 $PKG/usr/man/man1/*.?

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
