.TH RHAPSODY 1 "April 2009" "Rhapsody @VERSION@"
.SH NAME
rhapsody \- light and full\-featured irc client based on ncurses
.SH SYNOPSIS
.B rhapsody
.RI
.br
.SH DESCRIPTION
.B rhapsody
is a text console irc client which has multi server support, easy to use menu driven interface, 
ignore lists, configurable interface color themes. Supports DCC chat, DCC file transfer and CTCP.
.P
.B rhapsody
takes no command-line arguments.
.PP
.SH FILES
.TP
/usr/doc/rhapsody-@VERSION@/help/*.hlp
On\-line help files, accessed within the program via the Help menu option
(control\-P).
.TP
~/.rhapsodyrc
Per\-user configuration. Normally modified via the menus within the program,
but may be hand\-edited if necessary.
.SH AUTHOR
Marcela Tiznado <mtiznado@linux.org.ar>
