.TH "MDF2ISO" 1 "10 December 2005" "mdf2iso 0.3.0" "User Commands"
.SH NAME
mdf2iso \- mdf to iso / cue / toc image converter
.SH SYNOPSIS
.HP 8
.B mdf2iso [OPTION] [BASENAME.MDF] [DESTINATION]
.SH DESCRIPTION
\fBmdf2iso\fR converts an Alcohol 120% .mdf image to other CD image formats.
It is able to write out plain .iso, .cue & .bin and .toc & .dat. If you do not
specifiy \-\-cue or \-\-toc, an .iso file gets generated. If you do not specifiy a
destination image name, BASENAME.ext is automatically used.
.SH MDF2ISO OPTIONS
.TP
\fB\-\-toc\fR file
creates a .dat image & .toc file from the .mdf image.
.TP
\fB\-\-cue\fR file
creates a .bin image & .cue sheet from the .mdf image.
.TP
\fB\-\-help\fR
shows the help text
.SH AUTHOR
This manual page was written by Lukas Fittl <lfittl@ixios-software.com>,
for the Ubuntu GNU/Linux system (but may be used by others),
because the original program does not have a manual page.
