#!/bin/sh

# Slackware build script for qemu

# Copyright 2009, 2010  Andrew Brouwers <abrouwers@gmail.com>
# Copyright 2013-2018  Edward Koenig, Vancouver, USA <kingbeowulf@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Changelog
# 1.0   27-FEB-2013     New SBo maintainer
# 1.0   07-MAR-2013     updated to 1.4, includes qemu-kvm; thanks to
#                       rworkman and ponce for script ideas.
# 1.1   28-MAR-2013     fix missing docs per C. Willing and
#                       add missing --libdir (patched in qemu-trivial upstream)
# 1.2   22-SEP-2013     updated to 1.6
# 1.3   03-NOV-2013     updated to 1.6.1
# 1.4   28-APR-2014     updated to 2.0.0 (thanks Callum Davies <calrogman@gmail.com>), added useful options,
#                       clean ups, libusb version check.
# 1.4a  04-MAY-2014     fixed typos thanks to sandb0y
# 1.5   10-AUG-2014     updated to new version, watch for legacy "gotchas"
# 1.6   18-NOV-2014     updated version, last of the 2.1 series, changed defaults per SBo list
# 1.6a  23-NOV-2014     added overlooked AUDIODRIVERS switch per SBo list
# 1.7   01-JAN-2015     updated to 2.2.0 ; build and link static libusb option (rw, tm, SBo list)
# 1.8   27-APR-2015     updated to version 2.3.0
# 1.9   14-MAY-2015     patched for "Venom" CVE-2015-3456 http://git.qemu.org/?p=qemu.git;a=commitdiff;h=e907746266721f305d67bc0718795fedee2e824c
# 2.0   11-JUL-2015     patched for Heap-based buffer overflow in the PCNET controller CVE-2015-3209 http://git.qemu.org/?p=qemu.git;a=commitdiff;h=9f7c594c006289ad41169b854d70f5da6e400a2a
# 2.1   27-JUL-2015     patched for heap overflow flaw while processing certain ATAPI commands CVE-2015-5154 http://git.qemu.org/?p=qemu.git;a=commitdiff;h=e40db4c6d391419c0039fe274c74df32a6ca1a28;hp=f793d97e454a56d17e404004867985622ca1a63b
# 3.0   05-SEP-2015     uprgraded to new version
# 3.1   13-DEC-2015     uprgraded to new version, minor clean ups
# 3.1   02-SEP-2016     upgraded.
# 3.2   15-OCT-2016     upgraded to 2.7 release
# 3.3   26-JAN-2017     upgraded to 2.8 release
# 4.0   28-JAN-2017	add bridge-helper option, README additions/cosmetics (thanks to Andrzej T.)
# 4.1   01-APR-2017	no foolin': various bug and CVE updates re: ponce https://lists.nongnu.org/archive/html/qemu-devel/2017-03/msg06332.html
# 4.2   05-JUN-2017	version update to 2.9 release
# 4.3	06-JAN-2018	version update to 2.10.x release
# 4.4	17-Feb-2018	version update to 2.11.x release, Spectre/Meltdown mitigation
# 4.5   03-Jun-2018     version update to 2.12.0 release, note new deps: sdl2, gtk+3
# 5.0   14-Dec-2018	version update to 3.1.0 release, note minimum dependency versions on release notes
# 6.0   14-JUL-2019	version update to 4.0.0 release, note minimum dependency versions on release notes, doc fixes
# 6.1   19-AUG-2019	version update
# 6.2   16-Nov-2020     version update, 14.2 final release.

PRGNAM=qemu
VERSION=${VERSION:-5.2.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

KVMGROUP=${KVMGROUP:-users}
TARGETS=${TARGETS:-some}
VNC_ENABLE=${VNC_ENABLE:-yes}
AUDIODRIVERS=${AUDIODRIVERS:-pa,alsa,oss,sdl}
BRIDGE_HELPER_SETUID=${BRIDGE_HELPER_SETUID:-no}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
  KVMARCH="i386"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
  KVMARCH="i386"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
  KVMARCH="x86_64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

# Needed to build man pages if built after plain "su"
export PATH=$PATH:/usr/share/texmf/bin

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.xz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Remove double CFLAGS
sed -i "s|^\ \ CFLAGS=\"-O2\ |  CFLAGS=\"|" configure

# Enable only x86* and arm emulation for qemu: if you want to build
# all the targets available use TARGETS=all
if [ "$TARGETS" = "all" ]; then
  targets=""
else
  targets="--target-list=i386-softmmu,x86_64-softmmu,i386-linux-user,x86_64-linux-user,arm-softmmu,arm-linux-user,armeb-linux-user"
fi

# To omit VNC capability, use VNC_ENABLE=no
if [ "$VNC_ENABLE" = "yes" ]; then
  with_vnc="--enable-vnc --enable-vnc-sasl --enable-vnc-jpeg"
else
  with_vnc="--disable-vnc"
fi

# temp fix until upstream catches up.
# ld: Error: unable to disambiguate: -no-pie (did you mean --no-pie ?)
# https://lists.gnu.org/archive/html/qemu-devel/2020-12/msg03684.html
patch -p1 < $CWD/linker-no-pie.patch

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --localstatedir=/var \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --enable-gtk \
  --enable-system \
  --enable-kvm \
  --disable-debug-info \
  --enable-virtfs \
  --enable-sdl \
  --enable-jemalloc \
  --enable-nettle \
  --audio-drv-list=${AUDIODRIVERS} \
  $with_vnc \
  $targets

make V=1
make install DESTDIR=$PKG

# Remove empty /var
rm -rf $PKG/var

# install some udev rules for /dev/kvm
# Note: no udev rules for usb pasthrough when running qemu as non-root on linux hosts. See Section 2.11.2
# https://qemu.weilnetz.de/doc/qemu-doc.html
mkdir -p $PKG/lib/udev/rules.d/
sed "s/@GROUP@/$KVMGROUP/" $CWD/65-kvm.rules \
  > $PKG/lib/udev/rules.d/65-kvm.rules

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# create a symlink for qemu-kvm to support aqemu and such frontends
# even though qemu now has a gtk gui.
[ ! -z $KVMARCH ] && ln -s qemu-system-$KVMARCH $PKG/usr/bin/qemu-kvm

# set qemu-bridge-helper setuid if requested
if [ "$BRIDGE_HELPER_SETUID" = "yes" ]; then
  chmod u+s $PKG/usr/libexec/qemu-bridge-helper
fi

# move any generated man pages to their proper location
if [ -d $PKG/usr/share/man ]; then
  mv $PKG/usr/share/man $PKG/usr
  gzip -9 $PKG/usr/man/man?/*.?
fi

# Add docs to the proper location
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING* CODING_STYLE.rst LICENSE MAINTAINERS README.rst docs/* \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
