#!/bin/sh

# Slackware build script for htmldoc

# Copyright 2009-2010  LukenShiro <lukenshiro@ngi.it>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Thanks to Gentoo htmldoc's .ebuild maintainer for hints about configure's
# workaround, and for a patch to fix CVE-2009-3050.

PRGNAM=htmldoc
VERSION=1.8.27
ARCH=${ARCH:-i486}
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

DOCFILES="CHANGES.txt README.txt COMPILE.txt COPYING.txt htmldoc.eula htmldoc.readme"

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION-source.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# workaround to avoid /usr/share/doc/htmldoc's use for help function
sed -i 's|^#define DOCUMENTATION "$prefix/share/doc/htmldoc"|\
 #define DOCUMENTATION "$prefix/doc/htmldoc-1.8.27"|g' ./configure

# --mandir seems to be ignored; --docdir doesn't exist
# internal jpeg/png/zlib libs disabled (using system ones)
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --enable-ssl \
  --with-gui \
  --disable-localjpeg \
  --disable-localzlib \
  --disable-localpng

# workaround to avoid /usr/share/doc/htmldoc's use for doc installation
sed -i 's|\$(datadir)/doc/htmldoc|\$(prefix)/doc/htmldoc-1.8.27|g' \
  doc/Makefile

# Apply patch to fix several insecure calls to sscanf().
# It's intended to resolve CVE-2009-3050 vulnerability.
patch -p0 < $CWD/insecure_sscanf_patch.diff

make all || exit 1

# DESTDIR= is not supported
make prefix=$PKG/usr install || exit 1

# Copy some files who are not automatically installed (main binary, .desktop, icons, etc..)
mkdir -p $PKG/usr/bin
install -m 755 htmldoc/$PRGNAM $PKG/usr/bin
mkdir -p $PKG/usr/man/man1
cp -a doc/$PRGNAM.1 $PKG/usr/man/man1
mkdir -p $PKG/usr/share/applications
cp -a desktop/$PRGNAM.desktop $PKG/usr/share/applications
mkdir -p $PKG/usr/share/mimelnk/application
cp -a desktop/vnd.htmldoc-book.desktop $PKG/usr/share/mimelnk/application
mkdir -p $PKG/usr/share/mime/packages
cp -a desktop/htmldoc.xml $PKG/usr/share/mime/packages
mkdir -p $PKG/usr/share/icons/hicolor/{16x16,24x24,32x32,48x48,64x64,96x96,128x128}/apps/
cp -a desktop/htmldoc-16.png $PKG/usr/share/icons/hicolor/16x16/apps/$PRGNAM.png
cp -a desktop/htmldoc-24.png $PKG/usr/share/icons/hicolor/24x24/apps/$PRGNAM.png
cp -a desktop/htmldoc-32.png $PKG/usr/share/icons/hicolor/32x32/apps/$PRGNAM.png
cp -a desktop/htmldoc-48.png $PKG/usr/share/icons/hicolor/48x48/apps/$PRGNAM.png
cp -a desktop/htmldoc-64.png $PKG/usr/share/icons/hicolor/64x64/apps/$PRGNAM.png
cp -a desktop/htmldoc-96.png $PKG/usr/share/icons/hicolor/96x96/apps/$PRGNAM.png
cp -a desktop/htmldoc-128.png $PKG/usr/share/icons/hicolor/128x128/apps/$PRGNAM.png

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null
)

( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $(readlink $i).gz $i.gz ; rm $i ; done
)

# Just in case ..
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/
cp -a $DOCFILES $PKG/usr/doc/$PRGNAM-$VERSION

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
