.TH RRD2WHISPER 1
.SH NAME
rrd2whisper \- convert an RRD database to a whisper database
.SH SYNOPSYS
.nf
.fam C
\fbwrrd2whisper\fP rrd_path
.fam T
.fi
.SH DESCRIPTION
This command converts an RRD database to a whisper fixed-size database.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-\-xFilesFactor
The fraction of data points in a propagation interval that must have known values for a propagation to occur.
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Elliot Murphy <elliot@ubuntu.com>, for the Debian
project (but may be used by others).
