.TH WHISPER-FETCH 1
.SH NAME
whisper-fetch \- extract records from a whisper database
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-fetch\fP [options] path
.fam T
.fi
.SH DESCRIPTION
This command retrieves records from a whisper fixed-size database.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-\-from
Unix epoch time of the beginning of your requested interval (default: 24 hours ago).
.TP
.B
\-\-until
Unix epoch time of the end of your requested interval (default: now).
.TP
.B
\-\-json
Output results in JSON form.
.TP
.B
\-\-pretty
Show human-readable timestamps instead of unix times.
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Elliot Murphy <elliot@ubuntu.com>, for the Debian
project (but may be used by others).
