.TH WHISPER-INFO 1
.SH NAME
whisper-info \- show information about a whisper database
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-info\fP path [field]
.fam T
.fi
.SH DESCRIPTION
This command displays information about a whisper fixed-size database.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Elliot Murphy <elliot@ubuntu.com>, for the Debian
project (but may be used by others).
