.TH WHISPER-CREATE 1
.SH NAME
whisper-create \- create a whisper database
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-create\fP path secondsPerPoint:pointsToStore [secondsPerPoint:pointsToStore]*
.fam T
.fi
.SH DESCRIPTION
This command creates a new whisper fixed-size database. For each database you specify one or more pairs of numbers describing how data points should be archived in this database. The first part of the pair is the precision, the second part of the pair is how many data points should be stored. You cannot configure two archives with the same precision inside a single database. Higher precision archives must evenly divide all lower precision archives' precision.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-\-overwrite
Overwrite an existing database.
.TP
.B
\-\-xFilesFactor
The fraction of data points in a propagation interval that must have known values for a propagation to occur.
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Elliot Murphy <elliot@ubuntu.com>, for the Debian
project (but may be used by others).
