.TH WHISPER-DUMP 1
.SH NAME
whisper-dump \- dump whisper database files
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-dump\fP path
.fam T
.fi
.SH DESCRIPTION
This command dumps an whisper database file.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de>, for
the Debian project (but may be used by others).
