.TH WHISPER-SET-AGGREGATION-METHOD 1
.SH NAME
whisper-set-aggregation-method \- set aggregationType field
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-set-aggregation-method\fP path <average|sum|last|max|min>
.fam T
.fi
.SH DESCRIPTION
This command sets the aggregationType field in an whisper database.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de>, for the Debian
project (but may be used by others).
