.TH WHISPER-RESIZE 1
.SH NAME
whisper-resize \- resize a whisper database
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-resize\fP path secondsPerPoint:pointsToStore [secondsPerPoint:pointsToStore]*
.fam T
.fi
.SH DESCRIPTION
This command resizes a whisper fixed-size database.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-\-force
Force a destructive change to an existing database.
.TP
.B
\-\-newfile
Create a new database file without removing the existing one.
.TP
.B
\-\-xFilesFactor
The fraction of data points in a propagation interval that must have known values for a propagation to occur.
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Elliot Murphy <elliot@ubuntu.com>, for the Debian
project (but may be used by others).
