.TH WHISPER-MERGE 1
.SH NAME
whisper-merge \- merge two whisper database files
.SH SYNOPSYS
.nf
.fam C
\fbwhisper-merge\fP from_path to_path
.fam T
.fi
.SH DESCRIPTION
This command merges two whisper database files.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.SH AUTHOR
\fBwhisper\fP is a fixed size database, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de>, for
the Debian project (but may be used by others).
