# pod source for zita-dpl1 man page
# pod2man -s1 -r0.0.2 --stderr -nZITA-DPL1 -cSlackBuilds.org < zita-dpl1.pod > zita-dpl1.1

=pod

=head1 NAME

zita-dpl1 - digital peak limiter for JACK

=head1 SYNOPSIS

zita-dpl1 B<[options]>

=head1 DESCRIPTION

Zita-dpl1 is a look-ahead digital peak level limiter using some special
algorithms to allow fast response without excessive LF distortion.

=head1 OPTIONS

=over

=item -h

Display this text

=item -k I<channels>

Number of channels [1]

=item -name I<name>

JACK client name [zita-dpl1]

=item -s I<server>

JACK server name [default]

=item -g I<geometry>

Set initial window size and position

=back

=head1 AUTHOR

B<zita-dpl1> is (C) 2006-2011 Fons Adriaensen <fons@linuxaudio.org>
