#!/bin/sh

# Slackware build script for tuxpaint

# Written by Pablo Santamaria (pablosantamaria@gmail.com)
# Modified by Willy Sudiarto Raharjo <willysr@slackware-id.org>
# Taken over maintenance (and some updates) by Tim Dickson (dickson.tim@googlemail.com)
# added tuxpaint-config 2019-02-11

PRGNAM=tuxpaint
VERSION=${VERSION:-0.9.23}
CONFVER=${CONFVER:-0.0.14}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
rm -rf $PRGNAM-config-$CONFVER
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

make PREFIX=/usr LIBDIRSUFFIX=$LIBDIRSUFFIX OPTFLAGS="$SLKCFLAGS"
make \
  MAN_PREFIX=$PKG/usr/man \
  DEVMAN_PREFIX=$PKG/usr/man \
  DOC_PREFIX=$PKG/usr/doc/$PRGNAM-$VERSION \
  DEVDOC_PREFIX=$PKG/usr/doc/$PRGNAM-$VERSION \
  PREFIX=/usr \
  LIBDIRSUFFIX=$LIBDIRSUFFIX \
  DESTDIR=$PKG \
  install

mv $PKG/etc/tuxpaint/tuxpaint.conf $PKG/etc/tuxpaint/tuxpaint.conf.new
mkdir -p $PKG/usr/share/applications
cp src/$PRGNAM.desktop $PKG/usr/share/applications/
#
#now for tuxpaint-config
#
cd ..
tar xvf $CWD/$PRGNAM-config-$CONFVER.tar.gz
cd $PRGNAM-config-$CONFVER
make
#unfortunately tuxpaint-config does not have DESTDIR configured, so we
#have to do things by hand. copy executable, icons and desktop file and man
mkdir -p $PKG/usr/bin
cp $PRGNAM-config $PKG/usr/bin/
mkdir -p $PKG/usr/share/pixmaps
cp data/images/icon.png $PKG/usr/share/pixmaps/$PRGNAM-config.png
cp data/images/icon32x32.xpm $PKG/usr/share/pixmaps/$PRGNAM-config.xpm
for i in "16x16" "32x32" "48x48"; do
  mkdir -p $PKG/usr/share/icons/hicolor/$i
  cp data/images/icon$i.png $PKG/usr/share/icons/hicolor/$i/$PRGNAM-config.png
done
mkdir -p $PKG/usr/share/applications
cp src/$PRGNAM-config.desktop $PKG/usr/share/applications/$PRGNAM-config.desktop
mkdir -p $PKG/usr/man/man1
cp src/$PRGNAM-config.1 $PKG/usr/man/man1/$PRGNAM-config.1
gzip -9f $PKG/usr/man/man1/$PRGNAM-config.1
#finally for translation files
for i in `ls trans`; do
  mkdir -p $PKG/usr/share/locale/$i/LC_MESSAGES
  cp trans/$i $PKG/usr/share/locale/$i/LC_MESSAGES/$PRGNAM-config.mo
done
#now sanitize stuff.
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
