#!/bin/sh
# This executable provides a well-known way to uninstall VirtualBox Guest
# Additions in order to re-install them from a different source.  A common case
# is uninstalling distribution-provide Additions to install the version provided
# by VirtualBox.  Distributions should put the right command in here to do the
# removal, e.g. "dnf remove VirtualBox-guest-additions".  Leaving kernel modules
# provided by the distribution kernel package in place is acceptable if the
# location does not clash with the VirtualBox-provided module location (misc).

/sbin/removepkg virtualbox-addons
