# This xorg.conf.d configuration snippet for Slackware configures
# the X server to automatically load the nvidia X driver when it
# detects a device driven by the nvidia-drm kernel driver.
# (Glommed from the Debian file)

Section "OutputClass"
        Identifier "NVidia"
        MatchDriver "nvidia-drm"
        Driver "nvidia"
        Option "AllowEmptyInitialConfiguration"
        # Slackware specific directory
        ModulePath "/usr/lib@LIBDIRSUFFIX@/xorg/modules"
EndSection
