.TH STEEM "6" "May 2009" "STeem 3.2" "SlackBuilds.org"
.SH NAME
steem - the Atari STE emulator for Linux/X11
.SH SYNOPSIS
.B steem [options] [disk_image_a [disk_image_b]] [cartridge] [tos_image]
.PP
.B steem [options] [state_file]
.SH DESCRIPTION
Steem is a Freeware Atari ST/STE emulator for Windows and Linux.
.SH OPTIONS
.SS Image Files
.TP
\fI[disk_image_a]\fR, \fI[disk_image_b]\fR
Optional disk images to be used for the ST's A: and B: drives. File types
supported are ST/MSA/DIM/STT/ZIP/RAR. If 2 disks are specified, the first
will be ST drive A: and the second drive B:.
.TP
\fI[cartridge]\fR
Optional name of a cartridge image (.STC) to be loaded.
.TP
\fI[state_file]\fR
state file: previously saved state file (.STS) to load.  If none is
specified, Steem will load "auto.sts" provided the relevant option is
checked in the Options dialog.
.TP
\fI[tos_image]\fR
TOS image file to use. By default, this is set in \fIsteem.ini\fR and does
not need setting on the command line. For most games and applications,
the TOS image should be the UK v1.02 image (tos102.img).
.SS Switches
Options are case-independent and can be prefixed by -, --, / or nothing.
.TP
\fBNOSHM\fR
disable use of Shared Memory.
.TP
\fBNOSOUND\fR
no sound output.
.TP
\fBSOF=<n>\fR
set sound output frequency to <n> Hz.
.TP
\fBPABUFSIZE=<n>\fR
set PortAudio buffer size to <n> samples.
.TP
\fBFONT=<string>\fR
use a different font.
.TP
\fBHELP\fR
print help message and quit.
.TP
\fBINI=<file>\fR
use <file> instead of steem.ini to initialise options.
.TP
\fBTRANS=<file>\fR
use <file> instead of searching for Translate.txt or Translate_*.txt to translate the GUI text.
.PP 
All of these options (except INI= and TRANS=) can be changed from the GUI
once steem is running.  It is easiest just to run steem and play with the GUI.
.SH FILES
.TP
\fI/usr/bin/steem\fR
Shell script wrapper that sets up the environment for the actual steem binary.
.TP
\fI/usr/libexec/steem\fR
Actual steem binary. Don't run directly, as it doesn't behave in a very Linux\-friendly way.
.TP
\fI~/.steem/\fR
Directory steem executes in. Contains \fIsteem.ini\fR and all save\-state files,
including \fIauto.sts\fR.
.SH AUTHORS
Steem was Written by Anthony and Russell Hayward.   
.PP
This man page and the steem wrapper script were written by B. Watson, for the SlackBuilds.org project (but
may be used by anyone)
