#!/bin/bash

# Slackware build script for dapper

# Copyright 2025 Antonio Leal <antonioleal@yahoo.com>
# Copyright 2023 Ivan Kovmir <i@kovmir.eu>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd "$(dirname "$0")" ; CWD=$(pwd)

PRGNAM=dapper
VERSION=${VERSION:-1.0.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
NAMVER=$PRGNAM-$VERSION

if [ -z "$ARCH" ]; then
	case "$(uname -m)" in
		i?86) ARCH=i586 ;;
		arm*) ARCH=arm ;;
		*) ARCH=$(uname -m) ;;
	esac
fi

if [ -n "${PRINT_PACKAGE_NAME}" ]; then
	echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
	exit 0
fi

TMP="${TMP:-/tmp/SBo}"
SRC="$TMP/$NAMVER"
PKG="$TMP/package-$PRGNAM"
OUTPUT="${OUTPUT:-/tmp}"

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
else
	SLKCFLAGS="-O2"
fi

set -e

rm -rf "$PKG"
mkdir -p "$TMP" "$PKG" "$OUTPUT"
cd "$TMP"
rm -rf "$PRGNAM-$VERSION"
tar xvf "$CWD/$PRGNAM-$VERSION.tar.gz"
cd "$PRGNAM-$VERSION"
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

INSTPREFIX='/usr'

./autogen.sh
./configure \
	--prefix="$INSTPREFIX" \
	--mandir="$INSTPREFIX/man"
make
make DESTDIR="$PKG" PREFIX="$INSTALL_PREFIX" install

# Strip binary.
strip "$PKG/usr/bin/dapper"

# Compress man pages.
find "$PKG$INSTPREFIX/man" -type f -exec gzip {} +;

mkdir -p "$PKG/install"
mkdir -p "$PKG/usr/doc/$NAMVER"
mkdir -p "$PKG/usr/share/$NAMVER"
cat "$CWD/$PRGNAM.SlackBuild" > "$PKG/usr/doc/$NAMVER/$PRGNAM.SlackBuild"
cat "$CWD/README"             > "$PKG/usr/doc/$NAMVER/README"
cat "$CWD/slack-desc"         > "$PKG/install/slack-desc"

# Copy useful things directly from the repository folder.
cat "$SRC/COPYING"    > "$PKG/usr/share/$NAMVER/LICENSE"
cat "$SRC/README.md"  > "$PKG/usr/doc/$NAMVER/repository-README.md"

# Delete useless garbage after `make install`.
rm -r "$PKG$INSTPREFIX/share/doc"

cd "$PKG"
/sbin/makepkg -l y -c n "$OUTPUT/$NAMVER-$ARCH-$BUILD$TAG.$PKGTYPE"
