#!/bin/sh

# Slackware build script for gradle

# Copyright 2014  Arun Mascarenhas, arunmascarenhas[at]yahoo[dot]com
# Copyright 2014  Arun Mascarenhas, Kansas City, MO, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Started by Arun Mascarenhas (arunmascarenhas[at]yahoo[dot]com)

PRGNAM=gradle
VERSION=${VERSION:-2.2.1}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

GRADLE_HOME=/usr/share/gradle

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG/usr/share/java $PKG/$GRADLE_HOME $OUTPUT $PKG/usr/bin
cd $TMP
rm -rf ${PRGNAM}-$VERSION
unzip $CWD/${PRGNAM}-$VERSION-all.zip
cd ${PRGNAM}-$VERSION
chown -R root:root .

cp -a bin lib init.d media $PKG/$GRADLE_HOME/

mkdir -p $PKG/etc/profile.d/
install -m755 $CWD/$PRGNAM.csh $PKG/etc/profile.d/$PRGNAM.csh
install -m755 $CWD/$PRGNAM.sh $PKG/etc/profile.d/$PRGNAM.sh

cd $PKG/usr/bin
  ln -s $GRADLE_HOME/bin/gradle
cd -

rm -f $PKG/usr/share/gradle/bin/gradle.bat

mkdir -p $PKG/usr/doc/${PRGNAM}-$VERSION
cp -a NOTICE LICENSE $PKG/usr/doc/${PRGNAM}-$VERSION
cat $CWD/${PRGNAM}.SlackBuild > $PKG/usr/doc/${PRGNAM}-$VERSION/${PRGNAM}.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
