.TH FLITE_TIME 1 "February 25, 2003"
.SH NAME
flite_time \- A talking clock based on a limited-domain voice
.SH SYNOPSIS
.B flite_time
.I HH:MM
.SH DESCRIPTION
.B flite_time
is a example talking clock based on a limited domain
voice from Festival Lite.

.SH OPTIONS
Specify the time you want to have announced at the
command-line using the format HH:MM.

.SH EXAMPLES
.IP "flite_time `date +%H:%M`" 4
Announce the current time.

.SH SEE ALSO
.BR flite (1), " " festival (1)
.SH AUTHOR
This manual page was written by Mario Lang <mlang@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
