.TH T2P 1 "February 25, 2003"
.SH NAME
t2p \- A text to phoneme converter
.SH SYNOPSIS
.B t2p
"word word word"
.SH DESCRIPTION
.B t2p
converts text specified on the command-line into US english phonemes.
Output is given to STDOUT.

.SH OPTIONS
No options.

.SH SEE ALSO
.BR flite (1), " " flite_time (1), " " festival (1)
.SH AUTHOR
This manual page was written by Mario Lang <mlang@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
