#!/bin/sh

# Slackware build script for open-adventure

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20180114 bkw:
# - Update for v1.4.
# - Include upstream's icon and .desktop.
# - New dependencies in .info file :(

PRGNAM=open-adventure
VERSION=${VERSION:-1.4}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

# Actual name of the program:
EXE=advent

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-*

# Download URL uses content disposition to set the filename, so we have to
# handle both possibilities here. I know how to avoid this with github
# downloads, but not gitlab. Also, notice the * in the 2nd filename
# (and in the 'cd' below): I'm *not* hard-coding the full git hash here.
tar xvf $CWD/archive.tar.bz2\?ref=$VERSION ||
tar xvf $CWD/$PRGNAM-$VERSION-*.tar.bz2

cd $PRGNAM-$VERSION-*
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# It'd be nice if I could pass my own CFLAGS without editing the Makefile...
sed -i "s,-O2,$SLKCFLAGS," Makefile
make
make $EXE.6

# no 'make install' target:
mkdir -p $PKG/usr/games $PKG/usr/man/man6
install -s -m0755 $EXE $PKG/usr/games/$EXE
gzip -9c < $EXE.6 > $PKG/usr/man/man6/$EXE.6.gz

# principle of least surprise:
ln -s $EXE.6.gz $PKG/usr/man/man6/$PRGNAM.6.gz
ln -s $EXE $PKG/usr/games/$PRGNAM

# icon converted from advent.svg (rather not script that here)
mkdir -p $PKG/usr/share/applications $PKG/usr/share/pixmaps
cat $EXE.desktop > $PKG/usr/share/applications/$EXE.desktop
cat $CWD/$EXE.png > $PKG/usr/share/pixmaps/$EXE.png

# don't bother with advent.adoc, it's the man page.
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a COPYING NEWS README.adoc TODO h*.adoc $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
#cat $CWD/doinst.sh > $PKG/install/doinst.sh # someday I may make a .desktop file

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
