.TH BRICKOUT "6" "April 2009" "New Breed Software" "Games"
.SH NAME
brickout \- Breakout\-style arcade game
.SH SYNOPSIS
.B brickout
.SH DESCRIPTION
"Brickout" is a ball-and-paddle game where it's your objective to destroy
bricks on the screen. Gameplay is similar to "Breakout" and "Arkanoid".
.P
brickout takes no command\-line options.
.P
Use the mouse to control the paddle during gameplay.
.SH FILES
.TP
\fB/usr/share/brickout/\fR
game data (images, music, sound)
.SH AUTHORS
Bill Kendrick (New Breed Software)
.P
New Breed Software's web site is located at
.br
.nh
\fBhttp://www.newbreedsoftware.com/\fR
.hy
.P
Man page created by B. Watson for SlackBuilds.org project (but others
are free to use it)
.SH COPYRIGHT
Copyright \(co 2002, New Breed Software
.P
Brickout is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any
later version.
