#!/bin/sh

# Slackware build script for cdrkit

# Written by <youngmug@animeneko.net>
# Modified by the SlackBuilds.org project

PRGNAM=cdrkit
VERSION=1.1.2
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

cd $TMP || exit 1
rm -rf $PRGNAM-$VERSION
tar xvzf $CWD/$PRGNAM-$VERSION.tar.gz || exit 1

cd $TMP/$PRGNAM-$VERSION || exit 1
chown -R root:root .
chmod -R a-s,u+rw,go-w+r .

# Make Makefile prefix
cmake -DCMAKE_INSTALL_PREFIX=/usr || exit 1

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
make || exit 1
make install DESTDIR=$PKG || exit 1

( cd $PKG/usr/bin
  #Add cdrecord symlink to wodim (compatibility)
    ln -s wodim cdrecord
  #The author of cdda2wav requested their program be renamed, so...
  #Add cdda2wav symlink to icedax (compatibility)
    ln -s icedax cda2wav
  #More renaming (due to legal concerns)
  #Add mkisofs symlink to genisoimage (compatibility)
    ln -s genisoimage mkisofs
)

# Remove the $PKG/usr/share directory - it's empty
rmdir $PKG/usr/share

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  ABOUT COPYING Changelog FAQ FORK INSTALL START TODO VERSION doc/* \
  $PKG/usr/doc/$PRGNAM-$VERSION

# Move manpages from /usr/share/man to /usr/man
mv $PKG/usr/share/man $PKG/usr/man
( cd $PKG/usr/man
  find . -type f -exec gzip -9 {} \;
  for i in $(find . -type l) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
)

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
