#!/bin/bash

# Slackware build script for Qbs

# Copyright 2025 Andrzej Telszewski, Koszalin
# Copyright 2014-2017 Nikos Giotis <nikos.giotis@mail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=qbs
VERSION=${VERSION:-3.1.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
elif [ "$ARCH" = "aarch64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

if which qbs &>/dev/null; then
  echo "Found \"qbs\" in PATH."
  echo "Please remove any previous Qbs installations before continuing."

  exit 1
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP

rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-src-$VERSION.tar.gz
mv $PRGNAM-src-$VERSION $PRGNAM-$VERSION
cd $PRGNAM-$VERSION

chown -R root:root .
chmod -R a-st,u+rwX,go-w+rX .

cmake -S . -B build                           \
  -GNinja                                     \
  -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS"         \
  -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS"       \
  -DCMAKE_INSTALL_PREFIX=/usr                 \
  -DQBS_LIB_INSTALL_DIR=lib$LIBDIRSUFFIX      \
  -DQBS_PLUGINS_INSTALL_BASE=lib$LIBDIRSUFFIX \
  -DQBS_DOC_INSTALL_DIR=doc/$PRGNAM-$VERSION  \
  -DCMAKE_BUILD_TYPE=Release                  \
  -DQBS_ENABLE_RPATH=OFF                      \
  -DWITH_TESTS=OFF                            \
  -DQBS_INSTALL_QCH_DOCS=ON                   \
  -DQBS_INSTALL_MAN_PAGE=ON                   \
  -DQBS_INSTALL_HTML_DOCS=ON                  \
  -Wno-dev

cmake --build build
cmake --install build --prefix=$PKG/usr

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/man/man1
mv $PKG/usr/share/man/man1/qbs.1 $PKG/usr/man/man1
gzip -9 $PKG/usr/man/man1/qbs.1
rm -r $PKG/usr/share/man

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a CONTRIBUTING.md LGPL_EXCEPTION.txt LICENSE.GPL3-EXCEPT \
  LICENSE.{LGPLv21,LGPLv3} README.md RELEASE.md $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/usr/share/applications
cat $CWD/qbs-config-ui.desktop > $PKG/usr/share/applications/qbs-config-ui.desktop

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
