#!/bin/sh

# Slackware build script for ssh-chat

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

PRGNAM=ssh-chat
VERSION=${VERSION:-1.10}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

case "$ARCH" in
  i?86)   SRCARCH="386"   ;;
  x86_64) SRCARCH="amd64" ;;
  *)      echo "Unsupported ARCH '$ARCH' (only i586, i686, x864_64 supported)" 1>&2
          exit 1 ;;
esac

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir -p $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-linux_$SRCARCH.tgz
cd $PRGNAM
chown -R root:root .

mkdir -p $PKG/usr/sbin $PKG/usr/doc/$PRGNAM-$VERSION
install -m0755 $PRGNAM $PKG/usr/sbin
install -m0644 README* LICENSE* $PKG/usr/doc/$PRGNAM-$VERSION

# man page by SlackBuild author
mkdir -p $PKG/usr/man/man8
gzip -9 < $CWD/$PRGNAM.8 > $PKG/usr/man/man8/$PRGNAM.8.gz

# include our README since it has Slack-specific stuff.
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README_SBo.txt
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
