.TH CARBON-RELAY 1
.SH NAME
carbon-relay \- replication and sharding data
.SH SYNOPSYS
.nf
.fam C
\fbcarbon-relay\fP [options] start
.fam T
.fi
.SH DESCRIPTION
carbon-relay serves two distinct purposes: replication and sharding.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.TP
.B
\-\-debug
Run in the foreground, log to stdout
.TP
.B
\-\-profile=PROFILE
Record performance profile data to the given file
.TP
.B
\-\-pidfile=PIDFILE
Write pid to the given file
.TP
.B
\-\-config=CONFIG
Use the given config file
.TP
.B
\-\-logdir=LOGDIR
Write logs in the given directory
.TP
.B
\-\-instance=INSTANCE
Manage a specific carbon instance
.TP
.B
\-\-rules=RULES
se the given relay rules file.
.SH AUTHOR
\fBcarbon-relay\fP, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de, for
the Debian project (but may be used by others).
