.TH CARBON-CLIENT 1
.SH NAME
carbon-client \- Graphite client to reroute carbon data
.SH SYNOPSYS
.nf
.fam C
\fbcarbon-client\fP [options]
.fam T
.fi
.SH DESCRIPTION
Graphite client to reroute carbon data
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.TP
.B
\-\-debug
Log debug info to stdout
.TP
.B
\-\-keyfunc=KEYFUNC
Use a custom key function (path/to/module.py:myFunc)
.TP
.B
\-\-replication=REPLICATION
Replication factor
.TP
.B
\-\-routing=ROUTING
Routing method: "consistent-hashing" (default) or "relay"
.TP
.B
\-\-relayrules=RELAYRULES
relay-rules.conf file to use for relay routing
.SH AUTHOR
\fBcarbon-client\fP, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de, for
the Debian project (but may be used by others).
