.TH CARBON-CACHE 1
.SH NAME
carbon-cache \- accepts metrics over various protocols and writes them to disk
.SH SYNOPSYS
.nf
.fam C
\fbcarbon-cache\fP [options] start
.fam T
.fi
.SH DESCRIPTION
carbon-cache accepts metrics over various protocols and writes them to disk as
efficiently as possible. This requires caching metric values in RAM as they are
received, and flushing them to disk on an interval using the underlying
whisper library.
.PP
The options are described below.
.SH OPTIONS
.TP
.B
\-h, \-\-help
Show the embedded help.
.TP
.B
\-\-debug
Run in the foreground, log to stdout
.TP
.B
\-\-profile=PROFILE
Record performance profile data to the given file
.TP
.B
\-\-pidfile=PIDFILE
Write pid to the given file
.TP
.B
\-\-config=CONFIG
Use the given config file
.TP
.B
\-\-logdir=LOGDIR
Write logs in the given directory
.TP
.B
\-\-instance=INSTANCE
Manage a specific carbon instance
.SH AUTHOR
\fBcarbon-cache\fP, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de, for
the Debian project (but may be used by others).
