.TH VALIDATE-STORAGE-SCHEMAS 1
.SH NAME
validate-storage-schemas \- validates the storage schemas
.SH SYNOPSYS
.nf
.fam C
\fbvalidate-storage-schemas\fP
.fam T
.fi
.SH DESCRIPTION
validates the storage schemas from the configuration
file /etc/carbon/storage-schemas.conf.
.SH AUTHOR
\fBvalidate-storage-schemas\fP, created by Chris Davis.
.PP
This manual page was written by Jonas Genannt <jonas.genannt@capi2name.de, for
the Debian project (but may be used by others).
