--- Makefile.old	2011-02-20 21:52:03.827462749 +0100
+++ Makefile	2011-02-20 21:52:16.847462674 +0100
@@ -79,9 +79,7 @@ releaseclean:
 	@rm -rf "build/tuxpaint-stamps-$(VER_DATE)" "build/tuxpaint-stamps-$(VER_DATE).tar.gz"
 	@-if [ -d build ] ; then rmdir build ; fi
 
-releasedir: build/tuxpaint-stamps-$(VER_DATE)
-
-build/tuxpaint-stamps-$(VER_DATE):
+releasedir: 
 	@echo
 	@echo "Creating release directory"
 	@echo
