.TH VDK 1 "" 2.0.0 SlackBuild.org
.SH NAME
vdk-config - The VDK (2)  C++ Library config script
.SH SYNOPSIS
.B vdk-config-2
[\-v
\-\-version]
[\-h
\-\-help]
[\-l
\-\-libs]
[\-\-libs\-only\-L]
[\-\-libs\-only\-l]
[\-c
\-\-cflags]
[\-d
\-\-define]
.SH DESCRIPTION
.PP
\fIvdk-config-2\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIVDK(2)\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIVDK(2)\fP.
.
.SH OPTIONS
.l
\fIvdk-config\fP accepts the following options:
.TP 8
.B  \-v \-\-version
Print the currently installed version of \fIVDK\fP on the standard output.
.TP 8
.B  \-h \-\-help
Print a short help on the standard output.
.TP 8
.B  \-l \-\-libs
Print the linker flags that are necessary to link a \fIVDK\fP program.
.TP 8
.B  \-\-libs\-only\-L
Print only the \-L/\-R part of the \-\-libs.
.TP 8
.B  \-\-libs\-only\-l
Print only the \-l part of the \-\-libs.
.TP 8
.B  \-c \-\-cflags
Print the compiler flags that are necessary to compile a \fIVDK(2)\fP program.
.TP 8
.B  \-d \-\-define
Add to the compiler flags a \fI-D_VDK_\fP.
.SH SEE ALSO
.BR gtk-config-2.0 (1),
.BR /usr/doc/vdk-@VERSION@/vdk-config-2.txt
.SH COPYRIGHT
Copyright \(co  2000 VDK Team
Copyright \(co  1998 Owen Taylor

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.
