.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CHDMAN 6 "December 11, 2008"

.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)

.SH "NAME"
chdman \- CHD compression frontend.

.SH "SYNOPSIS"
.B chdman
.RI "OPTION CHDFILE [OPTIONS]"

.SH "DESCRIPTION"
MAME Compressed Hunks of Data (CHD) manager.

.SH "OPTIONS"
.IP "-info input.chd"
.IP "-createraw inputhd.raw output.chd [inputoffs [hunksize]]"
.IP "-createhd inputhd.raw output.chd [inputoffs [cylinders heads sectors [sectorsize [hunksize]]]]"
.IP "-createblankhd output.chd cylinders heads sectors [sectorsize [hunksize]]"
.IP "-createcd input.toc output.chd"
.IP "-createav input.avi output.chd [firstframe [numframes]]"
.IP "-copydata input.chd output.chd"
.IP "-extract input.chd output.raw"
.IP "-extractcd input.chd output.toc output.bin"
.IP "-extractav input.chd output.avi [firstframe [numframes]]"
.IP "-verify input.chd"
.IP "-verifyfix input.chd"
.IP "-update input.chd output.chd"
.IP "-chomp inout.chd output.chd maxhunk"
.IP "-merge parent.chd diff.chd output.chd"
.IP "-diff parent.chd compare.chd diff.chd"
.IP "-setchs inout.chd cylinders heads sectors"
.IP "-fixavdata inout.chd"

.SH "COPYRIGHT"
Copyright (C) 1997-2008, Nicola Salmoria and the MAME(tm) team

.SH "AUTHOR"
Written by Nicola Salmoria and the MAME(tm) team.

.sp 3
This manual page was written by Ludovic Lechapt <ludomatic@gmail.com>,
for the Debian project but may be used by others.
