#!/bin/sh

# Slackware build script for ISO Master
# Written by Erik Hanson  erik@slackbuilds.org

PRGNAM=isomaster
VERSION=0.8.1
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP 
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2 || exit 1
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# No autotools, do manually.
patch -p0 < $CWD/Makefile.patch || exit 1
CFLAGS="$SLKCFLAGS" make || exit 1
make install DESTDIR=$PKG || exit 1
strip --strip-unneeded $PKG/usr/bin/*
gzip -9 $PKG/usr/man/man?/*

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -a CHANGELOG.TXT CREDITS.TXT LICENCE.TXT README.TXT TODO.TXT $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
