=pod

=head1 NAME

B<dos33fsprogs> - collection of tools for Apple II files and disk images

=head1 DESCRIPTION

B<dos33(1)> - tool for accessing files inside an Apple DOS 3.3 disk image

B<make_b(1)> - add an Apple II BLOAD header to a binary file

B<mkdos33fs(1)> - create Apple II DOS 3.3 filesystems in a .dsk image

B<tokenize_asoft(1)> - convert ASCII into tokenized Applesoft

B<asoft_detoken(1)> - convert tokenized Applesoft into ASCII

B<integer_detoken(1)> - convert tokenized Apple Integer BASIC to ASCII

B<dos33_text2ascii(1)> - convert Apple II text files to UNIX

See the man page for each individual program for details.

=head1 SEE ALSO

=over

=item a2tools(1)

=item kegs(1)

=back

=head1 WEBSITE

http://www.deater.net/weave/vmwprod/apple/

=head1 AUTHORS

B<dos33fstools> written by Vince Weaver <vince _at_ deater.net>.

This manual page written by B. Watson for the SlackBuilds.org project,
but it may be used by anyone.
