# pod source for zita-ajbridge man page
# pod2man -s1 -r0.4.0 --stderr -nZITA-AJBRIDGE -cSlackBuilds.org < zita-ajbridge.pod > zita-ajbridge.1

=pod

=head1 NAME

zita-a2j - use ALSA capture device as a JACK client, with resampling

zita-j2a - use ALSA playback device as a JACK client, with resampling

=head1 SYNOPSIS

zita-a2j I<options>

zita-j2a I<options>

=head1 DESCRIPTION

zita-ajbridge provides two applications, zita-a2j and zita-j2a.  They
allow using an ALSA device as a Jack client, to provide additional
capture (a2j) or playback (j2a) channels.  Functionally these are
equivalent to the alsa_in and alsa_out clients that come with JACK,
but they provide much better audio quality. The resampling ratio will
typically be stable within 1 PPM and change only very smoothly. Delay
will be stable as well even under worst case conditions, e.g. the JACK
client running near the end of the cycle.

=head1 OPTIONS

Options for both executables are the same, except the default JACK client name.

=over

=item -h

Display this text

=item -j <jackname>

Name as Jack client [zita-j2a or zita-a2j]

=item -d <device>

ALSA playback device [none]

=item -r <rate>

Sample rate [48000]

=item -p <period>

Period size [256]

=item -n <nfrags>

Number of fragments [2]

=item -c <nchannels>

Number of channels [2]

=item -Q <quality>

Resampling quality [48]

=item -O <latency>

Latency adjustment[0]

=item -L

Force 16-bit and 2 channels [off]

=item -v

Print tracing information [off]

=back

=head1 AUTHOR

B<zita-ajbridge> is (C) 2006-2011 Fons Adriaensen <fons@linuxaudio.org>
