'\" t
.\"     Title: openjazz
.\"    Author: Carsten Teibes
.\" Generator: Asciidoctor 2.0.15
.\"      Date: 2026-02-28
.\"    Manual: OpenJazz Manual
.\"    Source: OpenJazz "20260301"
.\"  Language: English
.\"
.TH "OPENJAZZ" "6" "2026-02-28" "OpenJazz 20260301" "OpenJazz Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
openjazz \- Jack Jazzrabbit 1 game engine reimplementation
.SH "SYNOPSIS"
.sp
\fBopenjazz\fP [\fIoptions\fP] <\fIgame directory 1\fP> <\fIgame directory 2\fP>
.SH "DESCRIPTION"
.sp
OpenJazz is a free, open\-source version of the classic Jazz Jackrabbit PC
platform games.
.br
To play, you will need original data files.
.SH "OPTIONS"
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display command line flags and general help.
.RE
.sp
\fB\-v\fP, \fB\-\-version\fP
.RS 4
Display engine version.
.RE
.sp
\fB\-f\fP, \fB\-\-fullscreen\fP
.RS 4
Start in fullscreen mode.
.RE
.sp
\fB\-\-window\fP
.RS 4
Start in window mode.
.RE
.sp
\fB\-m\fP
.RS 4
Start with muted audio.
.RE
.sp
\fB\-s\fP, \fB\-\-scale[=]\fP <\fIFactor\fP>
.RS 4
Scale window by factor. Can be between \fI1\fP and \fI4\fP.
.RE
.sp
\fB\-w\fP, \fB\-\-world[=]\fP <\fIWorld\fP> \fB\-l\fP, \fB\-\-level[=]\fP <\fILevel\fP>
.RS 4
Directly load specific world/level.
.RE
.sp
\fB\-q\fP, \fB\-\-[no\-]quiet\fP
.RS 4
Enable/Disable console logging.
.RE
.sp
\fB\-\-verbose[=]\fP <\fIDebug Level\fP>
.RS 4
Set logging verbosity. Can be one of \fImax\fP, \fItrace\fP, \fIdebug\fP, \fIinfo\fP, \fIwarn\fP,
\fIerror\fP, \fIfatal\fP.
.RE
.SH "FILES"
.sp
\fIopenjazz.cfg\fP
.RS 4
The configuration file.
.RE
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Note
.ps -1
.br
.sp
Command line parameters will take precedence over values in the
configuration file
.sp .5v
.RE
.sp
\fIopenjazz.log\fP
.RS 4
The generated logfile.
.RE
.sp
\fBGame Data\fP
.RS 4
OpenJazz should be compatible with all released versions of Jazz
Jackrabbit 1.
.br
This includes the Shareware Episodes, "Holiday Hare" and "Holiday Hare \(aq95",
the "Jazz Jackrabbit CD" with "The Lost Episodes" and the "Complete" edition.
.RE
.SH "INGAME CONTROLS"
.sp
\fBFixed Controls\fP
.RS 4
.TS
allbox tab(:);
lt lt.
T{
.sp
Key(s)
T}:T{
.sp
Purpose
T}
T{
.sp
\f(CREnter\fP
T}:T{
.sp
Choose a menu option
T}
T{
.sp
\f(CREscape\fP
T}:T{
.sp
Go back to the previous menu
T}
T{
.sp
\f(CRF9\fP
T}:T{
.sp
View in\-game statistics (e.g. FPS)
T}
T{
.sp
\f(CRP\fP
T}:T{
.sp
Pause the game
T}
T{
.sp
\f(CRAlt\0+\0Enter\fP
T}:T{
.sp
Switch between full\-screen and windowed mode
T}
T{
.sp
\f(CR1\-5\fP
T}:T{
.sp
Switch weapon to Blaster, Toaster, Missile, Bouncer or TNT
respectively. If the desired weapon is not available,
try next.
T}
.TE
.sp
.RE
.sp
\fBConfigurable Controls\fP
.RS 4
These are configurable via the "setup options" menu. Default settings:
.TS
allbox tab(:);
lt lt.
T{
.sp
Key(s)
T}:T{
.sp
Purpose
T}
T{
.sp
\f(CRLeft arrow\fP and \f(CRRight arrow\fP
T}:T{
.sp
Move left and right
T}
T{
.sp
\f(CRSpace bar\fP
T}:T{
.sp
Jump/Swim upwards
T}
T{
.sp
\f(CRleft Alt\fP
T}:T{
.sp
Shoot
T}
T{
.sp
\f(CRright Ctrl\fP
T}:T{
.sp
Change weapon
T}
.TE
.sp
.RE
.if n .sp
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Important
.ps -1
.br
.sp
Under Windows the Jump and Shoot keys are moved to the right to
avoid opening the window context menu. That means \f(CRSpace bar\fP \(rA Shoot and
\f(CRright Alt\fP \(rA Jump/Swim upwards. Other platforms may have other defaults.
.sp .5v
.RE
.sp
\fBGame Controllers\fP
.RS 4
Most game controllers and joysticks that SDL recognizes can be used.
.br
However, not all axes or buttons may be available. Needs manual settings.
.RE
.SH "REPORTING BUGS"
.sp
Bugs can be reported at the
.URL "https://github.com/AlisterT/OpenJazz/issues" "issue tracker" "."
.SH "SEE ALSO"
.sp
\fBJ1E\fP \- level editor by Newspaz,
\fBJJ1MOD\fP \- graphic editor by Doubble Dutch
.sp
.URL "http://alister.eu/jazz/oj/" "The OpenJazz Homepage" ""
.SH "AUTHORS"
.sp
AJ Thomson (AlisterT)
.RS 4
Engine, project lead
.RE
.sp
Alireza Nejati
.RS 4
Menu plasma effect
.RE
.sp
newspaz
.RS 4
Bug fixes, enemy improvements
.RE
.sp
Carsten Teibes (carstene1ns)
.RS 4
Maintenance, bug fixes, documentation
.br
Integrating the ports (Wii, 3DS, PSP, PSVita, SDL2, ...)
.br
Additional coding (logger, CLI, ...)
.br
Modernizing
.br
UI improvements
.RE
.sp
Lars Persson (anotherguest)
.RS 4
Movie playback fixes
.RE
.sp
CYBERDEViL
.RS 4
Savegame algorithm
.RE
.sp
Scott Smith (Pickle)
.RS 4
GP2X/WIZ, Canoo, Pandora ports
.RE
.sp
Przemysław Buczkowski (przemub)
.RS 4
Android, Haiku ports
.RE
.sp
Matthieu Milan (usineur)
.RS 4
PSVita port
.RE
.sp
deniska
.RS 4
PSP port
.RE
.sp
tehpola
.RS 4
Wii port
.RE
.sp
pocketinsanity
.RS 4
PocketPC port
.RE
.sp
Ricerind
.RS 4
Mac OS X port
.RE
.sp
Slaanesh
.RS 4
GP32 port
.RE
.sp
GPF
.RS 4
Dreamcast port
.RE
.sp
Cameron Cawley (ccawley2011)
.RS 4
RISC OS, SDL2 port
.RE
.sp
midzer
.RS 4
Web port
.RE
