# pod source for openjazz man page
# pod2man -s6 -r160214 --stderr -cSlackBuilds.org openjazz.pod > openjazz.6

=pod

=head1 NAME

B<openjazz> - free/open-source game engine for Jazz Jackrabbit

=head1 SYNOPSIS

B<openjazz> I<[-f]> I<[dir] ...>

=head1 DESCRIPTION

OpenJazz is a free, open-source version of the classic Jazz Jackrabbit(tm)
games. OpenJazz can be compiled on a wide range of operating systems,
including Windows 98/Me/XP and Linux. OpenJazz requires the files
from any of the following games:

=over

=item Jazz Jackrabbit

=item Jazz Jackrabbit CD

=item Jazz Jackrabbit Shareware Edition

=item Jazz Jackrabbit Christmas Edition

=item Jazz Jackrabbit: Holiday Hare 1995

=back

OpenJazz will not work with any of the Jazz Jackrabbit 2 games. Don't
get confused: there's a "Holiday Hare 1998", which isn't supported
(only the 1995 version is).

There is no support for saving/loading the game. Multiplayer
is supported, but not well tested.

=head1 OPTIONS

B<-f> starts the game fullscreen. Any other option beginning with - will
be ignored. Anything else is treated as a directory to be added to the
file search path.

=head1 FILES

Game data files must be named in uppercase (e.g. B<BLOCKS.000>).

The search path for game data files includes, in order:

=over

=item the current directory

=item $HOME/.openjazz/

=item all paths listed on the command line I<in reverse order>

=back

In addition, the file B<openjazz.000> (containing the OpenJazz logo,
note the lowercase name) will be searched for in B</usr/share/openjazz>
after all other directories (so each separate game doesn't need its
own copy, when you've got multiple games installed).

B<$HOME/.openjazz/> stores user preferences and any custom levels
downloaded from multiplayer servers. Will be created if it doesn't
exist.

=head1 SEE ALSO

B<http://www.alister.eu/jazz/oj/faq.php>

=head1 AUTHORS

B<openjazz> is copyright (c) 2005-2013 Alister Thomson.

This man page written by B. Watson for the SlackBuilds.org project, and may
be used by anyone.
