#!/bin/bash

# Slackware build script for openjazz

# Written by B. Watson (urchlay@slackware.uk)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20260928 bkw: update for v20260301.
# 20211026 bkw:
# - update for v20190106. Can't build old versions.
# - binary in /usr/games, share dir /usr/share/games/openjazz.
# - update man page.
# - install shareware docs as *.txt, convert to utf-8.
# - recreate paths.diff for this version.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=openjazz
VERSION=${VERSION:-20260301}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi
SLKCFLAGS+=" -DNDEBUG"

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz --no-same-owner
cd $PRGNAM-$VERSION
chown -R root:root .
find . ! -type l    -a \( \
  \(     -perm /111 -a ! -perm 755 -a -exec chmod -f 755 {} + \) -o \
  \(   ! -perm /111 -a ! -perm 644 -a -exec chmod -f 644 {} + \) \)

mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS_RELEASE="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS_RELEASE="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib$LIBDIRSUFFIX \
    -DCMAKE_INSTALL_MANDIR=man \
    -DCMAKE_INSTALL_BINDIR=games \
    -DCMAKE_INSTALL_DOCDIR=doc/$PRGNAM-$VERSION \
    -DCMAKE_BUILD_TYPE=Release ..
  make VERBOSE=1
  make install/strip DESTDIR=$PKG
cd ..

# grr.
rm -rf $PKG/usr/man/man6/*
mv $PKG/usr/games/OpenJazz $PKG/usr/games/$PRGNAM

# 20211026 bkw: upstream's .desktop is useless.
rm -f $PKG/usr/share/applications/*.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/shareware \
  $PKG/usr/share/games/$PRGNAM/shareware

# shareware data. the *.DOC files are renamed to .txt to avoid dumb
# desktop environments thinking they're ms-word docs. ORDER_DE and
# ORDER_UK are non-ASCII, convert to Unicode and UTF-8.
cd $PKG/usr/share/games/$PRGNAM/shareware
unzip $CWD/jjrabbit.zip
  for i in *.DOC; do
    j=$( basename $i .DOC )
    dest=$PKG/usr/doc/$PRGNAM-$VERSION/shareware/$j.txt
    sed 's,\r,,g' $i | iconv -f cp437 -t utf-8 > $dest
  done
  rm -f *.EXE *.DIZ *.DOC *.PIF
cd -

# shareware wrapper script
mkdir -p $PKG/usr/games
cat <<EOF >$PKG/usr/games/$PRGNAM-shareware
#!/bin/sh
exec $PRGNAM /usr/share/games/$PRGNAM/shareware "\$@"
EOF
chmod 755 $PKG/usr/games/$PRGNAM-shareware

# upstream's icon is horrid, I'll keep the one I've been using.
rm -f $PKG/usr/share/pixmaps/* $PKG/usr/share/icons/hicolor/*/apps/*

# shareware icon came from windows jazz jackrabbit CD, converted with icotool
cat $CWD/$PRGNAM.png > $PKG/usr/share/icons/hicolor/48x48/apps/$PRGNAM.png
ln -sf ../icons/hicolor/48x48/apps/$PRGNAM.png \
       $PKG/usr/share/pixmaps/$PRGNAM.png

# man page is a slightly modified version of upstream's
mkdir -p $PKG/usr/man/man6
gzip -9c < $CWD/$PRGNAM.6 > $PKG/usr/man/man6/$PRGNAM.6.gz
ln -s $PRGNAM.6.gz $PKG/usr/man/man6/$PRGNAM-shareware.6.gz

mkdir -p $PKG/usr/share/applications
cat $CWD/$PRGNAM-shareware.desktop \
  > $PKG/usr/share/applications/$PRGNAM-shareware.desktop

for i in *.txt; do
  sed 's,\r,,g' $i > $PKG/usr/doc/$PRGNAM-$VERSION/$i
done
cp -a README* $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
