perl-Try-Tiny
perl-Test-Harness
perl-Test-Fatal
perl-Meta-Requirements-Range
perl-ExtUtils-Config
perl-B-COW
perl-lwp-mediatypes
perl-http-date
perl-encode-locale
perl-Test-NoWarnings
perl-Test-Needs
perl-JSON
perl-IO-HTML
perl-ExtUtils-InstallPaths
perl-ExtUtils-Helpers
perl-Clone
perl-CPAN-Requirements-Dynamic
perl-http-message
perl-html-tagset
perl-extutils-pkgconfig
perl-extutils-depends
perl-Test-Requires
perl-Test-Deep
perl-Module-Build-Tiny
perl-www-robotrules
perl-net-http
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-html-parser
perl-glib
perl-file-listing
perl-common-sense
perl-cairo
perl-Test-RequiresInternet
perl-HTTP-CookieJar
perl-Types-Serialiser
perl-Mozilla-CA
perl-MIME-Charset
perl-Glib-Object-Introspection
perl-File-ShareDir-Install
perl-Class-Inspector
perl-Canary-Stability
perl-Cairo-GObject
libwww-perl
perl-lwp-useragent-cached
perl-data-dump
perl-Unicode-LineBreak
perl-Text-CharWidth
perl-Term-ReadLine-Gnu
perl-LWP-Protocol-https
perl-JSON-XS
perl-Gtk3
perl-File-ShareDir
pipe-viewer
