.\" Man page for aaphoto

.TH AAPHOTO "1" "October 7 2024" "aaphoto-0.45" "SlackBuilds.org"

.SH NAME
aaphoto - automatic color correction of photos

.SH SYNOPSIS
aaphoto [option[s]] [source file[s]]

.SH DESCRIPTION
Auto Adjust Photo is a tiny command-line image manipulation tool
for automatic color correction of photos. It tries to make the picture
look better. The program does this by analyzing the input image and then
sets the most optimal contrast, gamma, color balance and saturation for it.
.br

The following image types are supported:
.br
bmp, jpg, png
.br
.PP
Quality settings can be applied only to jpg format images.
.br

.SH OPTIONS
The following options are supported:
.TP
\fB\-h\fR   \fB\-\-help\fR
Print this help
.TP
\fB\-v\fR   \fB\-\-version\fR
Print version information
.TP
\fB\-a\fR   \fB\-\-autoadjust\fR
Auto adjust the colors of the image
.TP
\fB\-o\fR   \fB\-\-output\fR
Set output directory
.TP
	\fB\-\-overwrite\fR
Overwrite mode, the original source file is replaced
.TP
	\fB\-\-jpg\fR
JPG image output
.TP
	\fB\-\-png\fR
PNG image output with alpha channel support
.TP
	\fB\-\-bmp\fR
BMP image output
.TP
\fB\-r\fR   \fB\-\-resize\fR
Resize image taking the longer side in % or pixels
.TP
	\fB\-\-rotate90\fR
Rotate image with 90 degrees clockwise
.TP
	\fB\-\-rotate180\fR
Rotate image with 180 degrees
.TP
	\fB\-\-rotate270\fR
Rotate image with 90 degrees counter\-clockwise
.TP
	\fB\-\-flipx\fR
Mirror image horizontally
.TP
	\fB\-\-flipy\fR
Mirror image vertically
.TP
	\fB\-\-noexif\fR
Save image without EXIF info
.TP
\fB\-q\fR   \fB\-\-quality\fR
Set image quality from 1 to 100
.TP
\fB\-t\fR   \fB\-\-threads\fR
Set number of working threads (default: autodetect)
.TP
\fB\-s\fR   \fB\-\-silent\fR
Silent mode, no information printed during operation
.TP
	\fB\-\-quiet\fR
Same as \-s, \-\-silent
.TP
\fB\-V\fR   \fB\-\-verbose\fR
Print verbose information about processing
.TP
	\fB\-\-test\fR
Print detailed test information into image

.SH EXAMPLES
aaphoto folders
.br
aaphoto image.jpg
.br
aaphoto \fB\-a \-r600 \-q85\fR *.jpg
.br
aaphoto mydir
.br
aaphoto \fB\-V \-\-resize70%\fR image.png
.br
aaphoto \fB\-\-quality60\fR image.jpg
.br
aaphoto image.jpg

.SH EXIT STATUS
.br
\fB0\fR (success) if at least one file was processed, or \fB1\fR (error) if no files were processed (either due to an error in the arguments, or because none of the files exist, or because none of them are in supported formats).

.SH REMARKS
.br
\- file format is determined by the filename extension. Supported extensions:
\fB.bmp\fR, \fB.jpg\fR, \fB.jpeg\fR, \fB.jpe\fR, \fB.png\fR.
.br
\- filename extensions are case\-insensitive (\fB.jpg\fR and \fB.JPG\fR are treated
the same way).
.br
\- if a file is misnamed (has no extension, or has the wrong one),
it won't be processed. Example: if a PNG file gets renamed to
\fBfoo.jpg\fR, it will fail.
.br
\- auto adjust parameter is set by default without any other parameters
.br
\- a _new filename will be generated without \fB\-\-overwrite\fR parameter
.br
\- every file is processed on directory input but not recursively
.br
\- order of parameters does not matter
.br
\- resize value can be set in percentage too
.br
\- resize parameter should be less or equal than original
.br
\- resize uses the best (and slowest) resampling method
.br
\- default jpeg compression quality is 95%
.br
\- EXIF information is restored in jpeg images by default
.br
\- number of threads is set to the number of online processors by default

.SH AUTHORS
.br
Auto Adjust Photo
.br
Copyright (C) 2006\-2011 Andras Horvath
.br
E\-mail: mail@log69.com \- suggestions & feedbacks are welcome
.br
URL: http://log69.com \- the official site
.br
Man page originally made by rezso (rezso@rezso.net), and modified for
SlackBuilds.org by B. Watson (urchlay@slackware.uk).
.PP
The following libraries are used by this program:
.br
libgomp - OpenMP for parallel programming, http://gcc.gnu.org/onlinedocs/libgomp/
.br
libjpeg - IJG JPEG software, http://www.ijg.org/
.br
libpng - PNG software, http://www.libpng.org/
.br
libz - Compression library, http://www.zlib.net/

.SH LICENSE
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
.br
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.br
You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

.SH "SEE ALSO"
The full documentation for \fBaaphoto\fR is available on the website: \fBhttp://log69.com\fR
