.TH "CEFERINO" "6" "2014-03-30" "0.97.8+svn37" "SlackBuilds.org"
.SH "NAME"
ceferino \- action game similar to Super Pang
.SH "SYNOPSIS"
.B ceferino
.B ceferinosetup
.B ceferinoeditor
.SH "DESCRIPTION"
The game is similar to 'Super Pang'.

You are attacked by little green balls which are bouncing around and which you have to destroy with your knife. Your knife, however, is limited to being thrown upwards, so you have to get under the balls to destroy them.

Even worse, if you destroy a large ball, it doesn't just vanish, but breaks apart into two smaller balls. Levels consist of little platforms connected by ladders, so you can go up and down or find cover if needed.
.SH "USAGE"
.B ceferinosetup

With this program you can configure the game options: video mode, full screen or windowed mode, music and sounds. The configuration is stored in $HOME/.ceferino

You can move through the menu using the arrow keys, return and space.

.B ceferino

This command allows to run the game. It will get the game options from $HOME/.ceferino and, after a brief introduction, will present a menu in which you can select a new game and some other things.

During the game, you can use the following keys:
     Left Arrow \- Move Left
     Right Arrow \- Move Right
     x \- Throw a knife
     z and c \- Roll on the floor
     Up Arrow \- Climb Stairs
     Down Arrow \- Crouch

The purpose of the game is to destroy all the balls and go up levels without being killed.

The highest scores are stored in $HOME/.ceferinomarcas

.B ceferinoeditor

With this program you can edit the levels of the game. The data describing the new levels will be stored in $HOME/.ceferinoniveles.map

You can use the mouse to modify the map.
.SH "AUTHORS"
The game has been written by LosersJuegos ( see http://www.losersjuegos.com.ar/ ):
         \- Hugo Ruscitti <hugoruscitti@yahoo.com.ar>
           \- Walter Velazquez <wgv_tattoo@yahoo.com.ar>
             \- Gabriel Valentin <vcgdebian@yahoo.com.ar> 

This manual page was written for the Debian GNU/Linux system by Miriam Ruiz
<little_miry@yahoo.es> (but may be used by others, of course). It was modified
slightly by B. Watson for SlackBuilds.org.
