.TH "PINBALL-CONFIG" "6"
.SH "NAME"
pinball-config \- returns information about installed pinball libraries and
binaries
.SH SYNOPSIS
.B pinball-config
[OPTIONS]
.SH DESCRIPTION
The
.B pinball-config
shell script is designed to retrieve the configuration information about
the libraries and binaries of the
.B pinball
package.
.SH "OPTIONS"
.TP
\fB\-\-version\fR
displays the pinball version number
.TP
\fB\-\-libs\fR
lists libraries needed for building new levels
.TP
\fB\-\-cflags\fR
lists additional compilation flags needed
.TP
\fB\-\-datadir\fR
Display the installation datadir
.TP
\fB\-\-libdir\fR
Display the installation libdir
.TP
\fB\-\-prefix\fR
Display the installation prefix
.TP
\fB\-\-exec\-prefix\fR
Display the installation exec-prefix
.SH "SEE ALSO"
.PP
The program is documented fully by the 
.B README
file that can be found under
.B /usr/share/doc/pinball/README
on
.B Debian GNU/Linux.
.SH "AUTHOR"
.PP
This manual page was written by Jochen Friedrich <jochen@scram.de> for
the
.B Debian GNU/Linux
system (but may be used by others).
