#!/bin/sh

# Slackware build script for QtOctave

# Written by Mauro Giachero (mauro dot giachero at gmail dot com)

PRGNAM=qtoctave
VERSION=${VERSION:-0.7.1}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

JOBS=${JOBS:-3}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

set -e # Exit on most errors

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;
chmod a+x configure

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --qtdir=/usr/lib/qt4

make -j$JOBS
make install INSTALL_ROOT=$PKG

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
# The "doc" folder contains developer-oriented documentation, while (qt)octave-doc contain
# user-oriented docs.
cp -a $PRGNAM/doc LEEME.txt NEWS.txt LICENSE_GPL.txt README.txt \
  $PKG/usr/doc/$PRGNAM-$VERSION
ln -s /usr/share/$PRGNAM/qtoctave-doc $PKG/usr/doc/$PRGNAM-$VERSION/qtoctave-doc
ln -s /usr/share/$PRGNAM/octave-doc $PKG/usr/doc/$PRGNAM-$VERSION/octave-doc
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

# QtOctave doesn't have a nice icon for menus, so we use the Octave icon
cp $CWD/octave-sombrero.png $PKG/usr/share/qtoctave/images
mkdir -p $PKG/usr/share/applications
cp $CWD/qtoctave.desktop $PKG/usr/share/applications

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
