#!/bin/sh

# Slackware build script for Hugin
# Written by Erik Hanson  erik@slackbuilds.org

set -eu

PRGNAM=hugin
VERSION=0.7.0_rc2
SRCVER=0.7.0
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
fi

rm -rf $PKG
mkdir -p $TMP $PKG
cd $TMP
rm -rf $PRGNAM-$SRCVER
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$SRCVER
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

cmake \
  -DCMAKE_C_FLAGS="$SLKCFLAGS" \
  -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
  -DCMAKE_EXE_LINKER_FLAGS="-lpthread" \
  -DCMAKE_INSTALL_PREFIX=/usr .

make
make install DESTDIR=$PKG

find $PKG | xargs file | egrep "ELF.*executable" | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
find $PKG | xargs file | egrep "ELF.*shared object" | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null

mv $PKG/usr/share/man $PKG/usr/man
gzip -9 $PKG/usr/man/man?/*.?

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION $PKG/install
cp -a AUTHORS COPYING ChangeLog INSTALL_cmake LICENCE LICENCE_JHEAD \
      LICENCE_VIGRA README README_JP README_WINDOWS TODO \
      $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
