#!/bin/sh
#
# Slackware build script for openl2tp
#
# Written by Eugene P. <pieu@mail.ru>
#

PRGNAM=openl2tp
VERSION=${VERSION:-1.8}
BUILD=${BUILD:-2}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

patch -p1 < $CWD/Makefile.diff

make OPT_CFLAGS="$SLKCFLAGS -Wno-error=unused-but-set-variable" \
  SYS_LIBDIR=/usr/lib${LIBDIRSUFFIX}
make install DESTDIR=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Move and fix perms on manpages
mv $PKG/usr/share/man $PKG/usr ; rmdir $PKG/usr/share
find $PKG/usr/man -type f -exec chmod 0644 {} \;

mkdir -p $PKG/etc/rc.d
cat etc/rc.d/init.d/openl2tpd > $PKG/etc/rc.d/rc.openl2tpd.new
chmod 0755 $PKG/etc/rc.d/rc.openl2tpd.new

mkdir -p $PKG/etc/sysconfig
sed -e "s,^OPENL2TPD_CONFIG_FILE=.*$,OPENL2TPD_CONFIG_FILE=/etc/openl2tpd.conf," \
  etc/sysconfig/openl2tpd > $PKG/etc/sysconfig/openl2tpd.new

# Copy config files for the OpenL2TP daemon
cat $CWD/sample.conf > $PKG/etc/openl2tpd.conf.new

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a README CHANGES LICENSE COPYING INSTALL $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
