diff -Naur sslscan-1.11.7-rbsec.orig/Makefile sslscan-1.11.7-rbsec/Makefile
--- sslscan-1.11.7-rbsec.orig/Makefile	2016-06-14 00:42:11.000000000 +1200
+++ sslscan-1.11.7-rbsec/Makefile	2016-06-28 08:35:03.817568419 +1200
@@ -80,11 +80,6 @@
 .openssl.is.fresh: opensslpull
 	true
 opensslpull:
-	if [ -d openssl -a -d openssl/.git ]; then \
-		cd ./openssl && git checkout OpenSSL_1_0_2-stable && git pull | grep -q "Already up-to-date." && [ -e ../.openssl.is.fresh ] || touch ../.openssl.is.fresh ; \
-	else \
-		git clone --depth 1 -b OpenSSL_1_0_2-stable https://github.com/openssl/openssl ./openssl && cd ./openssl && touch ../.openssl.is.fresh ; \
-	fi
 	# Re-enable SSLv2 EXPORT ciphers
 	sed -i.bak 's/# if 0/# if 1/g' openssl/ssl/s2_lib.c
 	rm openssl/ssl/s2_lib.c.bak
