#!/bin/bash

# Slackware build script for profanity

# Copyright 2015-2018 Pedro R.M. Júnior, Campinas, SP, Brazil
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=profanity
VERSION=${VERSION:-0.18.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

LIBDIR=/usr/lib${LIBDIRSUFFIX}
[ -f ${LIBDIR}/libpython3.so        ] && python_stat=enabled || pgp_stat=disabled
[ -f ${LIBDIR}/libnotify.so         ] && notify_stat=enabled || notify_stat=disabled
[ -f ${LIBDIR}/libenchant-2.so      ] && spell_stat=enabled  || spell_stat=disabled
[ -f ${LIBDIR}/libXss.so            ] && xss_stat=enabled    || xss_stat=disabled
[ -f ${LIBDIR}/libgtk-3.so          ] && gtk_stat=enabled    || gtk_stat=disabled
[ -f ${LIBDIR}/libgdk_pixbuf-2.0.so ] && gdk_stat=enabled    || gdk_stat=disabled
[ -f ${LIBDIR}/libotr.so            ] && otr_stat=enabled    || otr_stat=disabled
[ -f ${LIBDIR}/libgpgme.so          ] && pgp_stat=enabled    || pgp_stat=disabled
[ -f ${LIBDIR}/libqrencode.so       ] && qr_stat=enabled     || qr_stat=disabled

omemo="-D omemo=disabled"
if [ -f ${LIBDIR}/libgcrypt.so ]
then
  if [ -f ${LIBDIR}/libomemo-c-c.so -o -f ${LIBDIR}/libomemo-c.a ]
  then
    omemo="-D omemo=enabled -D omemo-backend=libomemo-c"
  elif [ -f ${LIBDIR}/libsignal-protocol-c.so -o \
         -f ${LIBDIR}/libsignal-protocol-c.a ]
  then
    omemo_stat=enabled
    omemo_backend=libsignal
    omemo="-D omemo=enabled -D omemo-backend=libsignal"
  fi
fi

# qrencode is used for showing OMEMO fingerprints.
# If there's no OMEMO support, have it disabled.
echo "$omemo" | grep -q "disabled" && qr_stat=disabled || true

# Add "Spellcheck" status to the list of features summary.
if ! grep -q "  'Spellcheck'" meson.build
then
  sed -i "/  'QR Code'/s/$/\n  'Spellcheck': enchant_dep.found(),/" meson.build
fi

mkdir build
BLD=$(pwd)/build
export CFLAGS="$SLKCFLAGS"
meson setup \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --includedir=/usr/include \
  --datadir=/usr/share \
  --mandir=/usr/man \
  --sysconfdir=/etc \
  --localstatedir=/var \
  -D c-plugins=enabled \
  -D python-plugins=$python_stat \
  -D otr=$otr_stat \
  -D pgp=$pgp_stat \
  $omemo \
  -D omemo-qrcode=$qr_stat \
  -D notifications=$notify_stat \
  -D icons-and-clipboard=$gtk_stat \
  -D gdk-pixbuf=$gdk_stat \
  -D xscreensaver=$xss_stat \
  -D spellcheck=$spell_stat \
  $BLD

meson compile -v -C $BLD
DESTDIR=$PKG meson install -C $BLD

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# "profanity.1" is marked executable!!!
find $PKG/usr/man -type f -exec chmod -x '{}' \; -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mv $PKG/usr/share/doc $PKG/usr
mv $PKG/usr/doc/$PRGNAM $PKG/usr/doc/$PRGNAM-$VERSION
cp -a LICENSE.txt COPYING CHANGELOG $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/README > $PKG/usr/doc/$PRGNAM-$VERSION/README.sw
# Append to README.sw the features enabled during packaging.
cat << "__EOF__" >> $PKG/usr/doc/$PRGNAM-$VERSION/README.sw

The list of features enabled for your package:

__EOF__
# Print every line starting from "  Features" until the first empty line.
sed -n '/  Features/,/^$/p' $BLD/meson-logs/meson-log.txt | \
  sed '/^$/d' >> $PKG/usr/doc/$PRGNAM-$VERSION/README.sw

rm -f $PKG/usr/lib*/*.la

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
