PACKAGE_NAME="ddcci"
PACKAGE_VERSION="@VERSION@"
CLEAN=true
BUILT_MODULE_NAME[0]="ddcci"
BUILT_MODULE_NAME[1]="ddcci-backlight"
BUILT_MODULE_LOCATION[0]="ddcci/"
BUILT_MODULE_LOCATION[1]="ddcci-backlight/"
DEST_MODULE_LOCATION[0]="/extra"
DEST_MODULE_LOCATION[1]="/extra"
PRE_BUILD="./fix-strncpy.sh $kernelver"
MAKE[0]="make KVER=$kernelver -C ${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
AUTOINSTALL="yes"
