// 59617ba689a66a319ab98b543e8188cf474f7640
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "1.5.3"
#define GIT_HASH "59617ba689a66a319ab98b543e8188cf474f7640"
#define GIT_TIME "2025-12-01 19:37:17 +0100"
#define HG_REVISION_NUMBER 1764614237
#define HG_REVISION_HASH_STRING "59617ba689a6"
#define HG_TIME "251201-1837"
