# This xorg.conf.d configuration snippet for Slackware configures
# the X server to automatically load the nvidia X driver when it
# detects a device driven by the nvidia-drm kernel driver.
# Please note that this works on Linux kernels version 6.12 or higher
# with CONFIG_DRM enabled, and only if the nvidia-drm.ko kernel module
# for the versions 390 and later of the nvidia driver or the nvidia.ko
# kernel module for the version 340 is loaded before the X server is
# started.  (Glommed from the Debian file)

Section "OutputClass"
        Identifier "NVidia"
        MatchDriver "nvidia-drm"
        Driver "nvidia"
        Option "AllowEmptyInitialConfiguration"
        # Slackware specific directory
        ModulePath "/usr/lib@LIBDIRSUFFIX@/xorg/modules"
EndSection
