#!/bin/bash

# Slackware build script for openscad-mcad

# Copyright 2020 Fernando Lopez Jr. <fernando.lopezjr@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# 20220312 bkw: Modified by SlackBuilds.org: VERSION must be constant,
# and match VERSION in the .info file.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=openscad-mcad
COMVER=bd0a7ba3f042bfbced5ca1894b236cea08904e26
VERSION=${VERSION:-2021.10.25.bd0a7ba}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}
ARCH=noarch

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

SRCNAM=MCAD

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM-$COMVER
tar xvf $CWD/$SRCNAM-$COMVER.tar.gz
cd $SRCNAM-$COMVER

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \+ -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \+

mkdir -p $PKG/usr/share/openscad/libraries/MCAD/bitmap

install -m775 __init__.py $PKG/usr/share/openscad/libraries/MCAD/
install -m775 openscad_testing.py $PKG/usr/share/openscad/libraries/MCAD/
install -m775 openscad_utils.py $PKG/usr/share/openscad/libraries/MCAD/
install -m775 test_docs.py $PKG/usr/share/openscad/libraries/MCAD/
install -m775 test_mcad.py $PKG/usr/share/openscad/libraries/MCAD/

install -m775 2Dshapes.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 3d_triangle.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 array.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bearing.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/alphabet_block.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/bitmap.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/height_map.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/letter_necklace.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/name_tag.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 bitmap/test_name_tag.scad $PKG/usr/share/openscad/libraries/MCAD/bitmap
install -m775 boxes.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 constants.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 curves.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 fonts.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 gears.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 gridbeam.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 hardware.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 involute_gears.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 layouts.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 lego_compatibility.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 libtriangles.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 linear_bearing.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 materials.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 math.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 metric_fastners.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 motors.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 multiply.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 nuts_and_bolts.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 polyholes.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 profiles.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 regular_shapes.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 screw.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 servos.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 shapes.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 stepper.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 teardrop.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 transformations.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 triangles.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 trochoids.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 units.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 unregular_shapes.scad $PKG/usr/share/openscad/libraries/MCAD/
install -m775 utilities.scad $PKG/usr/share/openscad/libraries/MCAD/

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a bitmap/README TODO README.markdown lgpl-2.1.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
