#!/bin/bash

# Slackware build script for eawpats

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# If the main download URL goes away, try
# http://www.george.ca/interests/eawpats12_full.tar.gz
# This is the original author's site, but it's more polite to download
# from the gentoo mirror (see .info file)

# 20191201 bkw: symlink eawpats.cfg to timidity.cfg in doinst.sh,
# if there's no timidity.cfg already. This makes things Just Work(tm).

# 20140511 bkw: one patch was missing due to tar being silly.
# When extracting (with tar, which is really tar-1.26 on slack 14.1):
# tar: eawpats/charang.pat: implausibly old time stamp 1969-12-31 18:59:59
# The file gets extracted fine, it's just a warning. But the old tar-1.13
# used by makepkg just ignores the file, so it doesn't end up
# in the package! The fix is just to touch it after extraction.
# I only ever noticed this because allegro's pat2dat chokes on
# missing patches.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=eawpats
VERSION=${VERSION:-12}
SRCVER=${VERSION}_full
ARCH=noarch
BUILD=${BUILD:-3}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
tar xvf $CWD/$PRGNAM$SRCVER.tar.gz
cd $PRGNAM
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

# see above
touch charang.pat

# Un-DOSify text files
find . -type f -print0 | xargs -0 file | grep 'text.*CRLF' | \
	cut -d: -f1 | xargs perl -i -pe 's/\r//g'

mkdir -p $PKG/usr/share/sounds/$PRGNAM $PKG/etc/timidity
egrep -v '^($|#)' linuxconfig/timidity.cfg | \
	sed 's,/home/user,/usr/share/sounds,' > \
	$PKG/etc/timidity/$PRGNAM.cfg.new

rm -rf winconfig linuxconfig

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv *.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mv * $PKG/usr/share/sounds/$PRGNAM

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
