#!/bin/sh

# Slackware build script for eawpats

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# If the main download URL goes away, try
# http://www.george.ca/interests/eawpats12_full.tar.gz
# This is the original author's site, but it's more polite to download
# from the gentoo mirror (see .info file)

PRGNAM=eawpats
VERSION=${VERSION:-12}
SRCVER=${VERSION}_full
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
tar xvf $CWD/$PRGNAM$SRCVER.tar.gz
cd $PRGNAM
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Un-DOSify text files
find . -type f -print0 | xargs -0 file | grep 'text.*CRLF' | \
	cut -d: -f1 | xargs perl -i -pe 's/\r//g'

mkdir -p $PKG/usr/share/sounds/$PRGNAM $PKG/etc/timidity
egrep -v '^($|#)' linuxconfig/timidity.cfg | \
	sed 's,/home/user,/usr/share/sounds,' > \
	$PKG/etc/timidity/$PRGNAM.cfg.new

rm -rf winconfig linuxconfig

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
mv *.txt $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mv * $PKG/usr/share/sounds/$PRGNAM

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
