#!/bin/sh

# Slackware build script for Quantum GIS

# Copyright 2011 David Spencer, Baildon, West Yorkshire, U.K.
# Copyright 2013 Benjamin Trigona-Harany
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=qgis
VERSION=${VERSION:-2.8.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/${PRGNAM}-$VERSION.tar.bz2
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

WITHGRASS=""
if pkg-config --exists grass; then
  WITHGRASS="-DGRASS_PREFIX=$(pkg-config --variable=prefix grass)"
fi

WITHSERVER="-DWITH_MAPSERVER=FALSE"
CGIBINDIR="${CGIBINDIR:-/var/www/cgi-bin/qgis}"
if [ "${SERVER:-no}" = "yes" ]; then
  WITHSERVER="-DWITH_MAPSERVER=TRUE -DQGIS_CGIBIN_SUBDIR=$CGIBINDIR"
fi

cmake . \
  -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
  -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL="on" \
  -DQGIS_LIB_SUBDIR=lib${LIBDIRSUFFIX} \
  -DQGIS_LIBEXEC_SUBDIR=lib${LIBDIRSUFFIX}/qgis \
  -DQGIS_PLUGIN_SUBDIR=lib${LIBDIRSUFFIX}/qgis \
  $WITHSERVER \
  $WITHGRASS

make
make install DESTDIR=$PKG

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

find $PKG/usr/man -type f -exec gzip -9 {} \;

install -D -m 0644 debian/qgis.desktop \
  $PKG/usr/share/applications/qgis.desktop
install -D -m 0644 debian/qgis.xml \
  $PKG/usr/share/mime/packages/qgis.xml

mkdir -p $PKG/usr/share/pixmaps
ln -s /usr/share/qgis/images/icons/qgis-icon.png $PKG/usr/share/pixmaps/qgis.png
ln -s /usr/share/qgis/images/icons/qgis-mime-icon.png $PKG/usr/share/pixmaps/qgis-mime.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  doc/AUTHORS BUGS CODING doc/CONTRIBUTORS COPYING ChangeLog \
  doc/DONORS Exception_to_GPL_for_Qt.txt INSTALL NEWS \
  PROVENANCE README.md doc/SPONSORS TODO doc/TRANSLATORS \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
cat $CWD/README.server > $PKG/usr/doc/$PRGNAM-$VERSION/README.server

# Move a couple of optional server files to a more appropriate place -- they
# need to be properly customised (and the server works without them).
if [ -d $PKG/$CGIBINDIR ]; then
  mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/examples
  mv $PKG/$CGIBINDIR/wms_metadata.xml $PKG/$CGIBINDIR/admin.sld \
    $PKG/usr/doc/$PRGNAM-$VERSION/examples
fi

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh  > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
