.TH UNRAR "1" "December 2009" "unrar " "User Commands"
.SH NAME
unrar \- manual page for unrar 
.SH SYNOPSIS
.B unrar
\fI<command> -<switch 1> -<switch N> <archive> <files\fR...\fI>\fR
.SH DESCRIPTION
UNRAR 3.91 freeware      Copyright (c) 1993-2009 Alexander Roshal
.IP
<@listfiles...> <path_to_extract\e>
.PP
<Commands>
.TP
.BR e
Extract files to current directory
.TP
.BR l[t,b]
List archive [technical, bare]
.TP
.BR p
Print file to stdout
.TP
.BR t
Test archive files
.TP
.BR v[t,b]
Verbosely list archive [technical,bare]
.TP
.BR x
Extract files with full path
.PP
<Switches>
.TP
.BR -
Stop switches scanning
.TP
.BR ad
Append archive name to destination path
.TP
.BR ai
Ignore file attributes
.TP
.BR ap<path>
Set path inside archive
.TP
.BR c-
Disable comments show
.TP
.BR cfg-
Disable read configuration
.TP
.BR cl
Convert names to lower case
.TP
.BR cu
Convert names to upper case
.TP
.BR dh
Open shared files
.TP
.BR ep
Exclude paths from names
.TP
.BR ep3
Expand paths to full including the drive letter
.TP
.BR f
Freshen files
.TP
.BR id[c,d,p,q]
Disable messages
.TP
.BR ierr
Send all messages to stderr
.TP
.BR inul
Disable all messages
.TP
.BR kb
Keep broken extracted files
.TP
.BR n<file>
Include only specified file
.TP
.BR n@
Read file names to include from stdin
.TP
.BR n@<list>
Include files in specified list file
.TP
.BR o+
Overwrite existing files
.TP
.BR o-
Do not overwrite existing files
.TP
.BR or
Rename files automatically
.TP
.BR ow
Save or restore file owner and group
.TP
.BR p[password]
Set password
.TP
.BR p-
Do not query password
.TP
.BR r
Recurse subdirectories
.TP
.BR sl<size>
Process files with size less than specified
.TP
.BR sm<size>
Process files with size more than specified
.TP
.BR ta<date>
Process files modified after <date> in YYYYMMDDHHMMSS format
.TP
.BR tb<date>
Process files modified before <date> in YYYYMMDDHHMMSS format
.TP
.BR tn<time>
Process files newer than <time>
.TP
.BR to<time>
Process files older than <time>
.TP
.BR ts<m,c,a>[N]
Save or restore file time (modification, creation, access)
.TP
.BR u
Update files
.TP
.BR v
List all volumes
.TP
.BR ver[n]
File version control
.TP
.BR vp
Pause before each volume
.TP
.BR x<file>
Exclude specified file
.TP
.BR x@
Read file names to exclude from stdin
.TP
.BR x@<list>
Exclude files in specified list file
.TP
.BR y
Assume Yes on all queries
