#!/bin/sh

# Slackware build script for exomizer

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20210225 bkw: update for v3.1.0, try using upstream's download
# URL again. Handle bitbucket adding ?rev=<hash> to the filename, by
# using .zip* as the source filename. Not ideal, but workable.

# 20191201 bkw: update for v3.0.2
# 20180829 bkw: update for v3.0.1

# 20180619 bkw:
# - update for v3.0.0
# - host tarball on naptime instead of ponce.cc
# - handle old style or new style zip filename
# - only install exoraw if it exists (was removed in 3.0.0)
# - can still build with VERSION=2.0.9 or VERSION=2.0.10, if needed

PRGNAM=exomizer
VERSION=${VERSION:-3.1.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir -p $PRGNAM-$VERSION
cd $PRGNAM-$VERSION
unzip $CWD/${PRGNAM}${VERSION//./}.zip* -x dos/\* win32/\* || \
  unzip $CWD/$PRGNAM-$VERSION.zip* -x dos/\* win32/\*
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

make -C src CFLAGS="$SLKCFLAGS"
mkdir -p $PKG/usr/bin
install -s -m0755 src/$PRGNAM src/exobasic $PKG/usr/bin
[ -x src/exoraw ] && install -s -m0755 src/exoraw $PKG/usr/bin

# exodecrs and rawdecrs contain decompressors written in 6502, 6809,
# and z80 asm. Best place for them is the doc dir.
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/examples
cp -a *.txt $PKG/usr/doc/$PRGNAM-$VERSION
cp -a exodecrs rawdecrs $PKG/usr/doc/$PRGNAM-$VERSION/examples
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
