#!/bin/sh

## Written by hollywoodb (hollywoodb@fastmail.fm)
## Package Homepage: http://sam.zoy.org/monsterz/

# Verify script is being run by root user.
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root!"
    exit
fi

NAME=monsterz
VERSION=0.7.0
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$NAME
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
tar -zxvf $CWD/$NAME-$VERSION.tar.gz || exit 1
cd $NAME-$VERSION || exit 1
chown -R root:root .
chmod -R u+w,go+r-w,a-s .

# Fix installation prefix in Makefile
sed -i s#'prefix = /usr/local'#'prefix = /usr'# Makefile || exit 1

make clean
make || exit 1
make install DESTDIR=$PKG || exit 1

mkdir -p $PKG/usr/share/{applications,pixmaps}
install -m 0644 $CWD/monsterz.desktop $PKG/usr/share/applications/monsterz.desktop
install -m 0644 graphics/icon.png $PKG/usr/share/pixmaps/monsterz.png

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

mkdir -p $PKG/usr/doc/$NAME-$VERSION
cp -a AUTHORS COPYING INSTALL README TODO $PKG/usr/doc/$NAME-$VERSION
cat $CWD/$NAME.SlackBuild > $PKG/usr/doc/$NAME-$VERSION/$NAME.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n -p $OUTPUT/$NAME-$VERSION-$ARCH-$BUILD$TAG.tgz
