.TH GEMGET 1 "7 December 2024"

.SH NAME
gemget \- file downloader for gemini protocol

.SH SYNOPSIS
.B gemget
[\fI\,OPTION\/\fR]...
[\fI\,URL\/\fR]...

.SH DESCRIPTION
A command line downloader for the Gemini protocol. It works well with
streams and can print headers for debugging as well.

.SH OPTIONS
.TP 5
\fB\,-e\/\fR, \fB\,--add-extension\/\fR
Add .gmi extensions to gemini files that don't have it, like
directories.
.TP 5
\fB\,--cert\/\fR \fI\,string\/\fR
Path to a PEM encoded TLS client certificate to be sent with the
request.
.TP 5
\fB\,--connect-timeout\/\fR \fI\,uint\/\fR
Max time allowed to form a connection and get the header, in seconds.
Set to 0 for no timeout. (default 15)
.TP 5
\fB\,-d\/\fR, \fB\,--directory\/\fR \fI\,string\/\fR
The directory where downloads go (default ".")
.TP 5
\fB\,--header\/\fR
Print out (even with --quiet) the response header to stdout in the
format: Header: <status> <meta>
.TP 5
\fB\,-f\/\fR, \fB\,--input-file\/\fR \fI\,string\/\fR
Input file with a single URL on each line. Empty lines or lines starting
with # are ignored. URLs on the command line will be processed first.
.TP 5
\fB\,-i\/\fR, \fB\,--insecure\/\fR
Skip checking the cert.
.TP 5
\fB\,--key\/\fR \fI\,string\/\fR
Path to a PEM encoded TLS key for the provided client cert.
.TP 5
\fB\,-m\/\fR, \fB\,--max-size\/\fR \fI\,string\/\fR
Set the file size limit. Any download that exceeds this size will
cause an Info output and be deleted.
Leaving it blank or setting to zero bytes will result in no limit.
This flag is ignored when outputting to stdout.

Format: <num> <optional-byte-size>

Examples: 423, 3.2KiB, '2.5 MB', '22 MiB', '10gib', 3M
.TP 5
\fB\,-t\/\fR, \fB\,--max-time\/\fR \fI\,uint\/\fR
Set the downloading time limit, in seconds. Any download that
takes longer will cause an Info output and be deleted.
.TP 5
\fB\,--no-progress-bar\/\fR
Disable the progress bar output.
.TP 5
\fB\,-o\/\fR, \fB\,--output\/\fR \fI\,string\/\fR
Output path, for when there is only one URL.
'-' means stdout and implies --quiet.
It overrides --directory.
.TP 5
\fB\,-p\/\fR, \fB\,--proxy\/\fR \fI\,string\/\fR
A proxy that can requests are sent to instead.
Can be a domain or IP with port. Port 1965 is assumed otherwise.
.TP 5
\fB\,-q\/\fR, \fB\,--quiet\/\fR
Neither info strings or the progress bar will be printed.
Note that normally infos are printed to stderr, not stdout.
.TP 5
\fB\,-r\/\fR, \fB\,--redirect\/\fR \fI\,uint\/\fR
How many redirects to follow before erroring out. (default 5)
.TP 5
\fB\,-s\/\fR, \fB\,--skip\/\fR
Move to the next URL when one fails.
.TP 5
\fB\,--socks\/\fR \fI\,string\/\fR
Host/address for a SOCKS5 proxy.
.TP 5
\fB\,--socks-pass\/\fR \fI\,string\/\fR
Password for a SOCKS5 proxy (optional)
.TP 5
\fB\,--socks-user\/\fR \fI\,string\/\fR
Username for a SOCKS5 proxy (optional)
.TP 5
\fB\,-v\/\fR, \fB\,--version\/\fR
Find out what version of gemget you're running.

.SH AUTHOR
makeworld <makeworld@protonmail.com>
