.TH ROTTEXPR 6 "2023-12-03" "0.01" "Rise of the Triad"

.SH NAME
rottexpr \- Rise of the Triad source port

.SH SYNOPSIS
.B rottexpr
.RI [ options ]
.br
.B rott\-demo
.RI [ options ]
.br
.B rott\-reg
.RI [ options ]
.br
.B rott\-cdrom
.RI [ options ]

.SH DESCRIPTION
.B ROTTEXPR
is a port of Apogee's 3D action title Rise of the Triad, originally released in 1994.
.B ROTTEXPR
uses the SDL2 libraries to make the game playable on modern operating systems, including Linux, and adds features including higher
screen resolutions, adaptive HUD positioning, configurable gameplay options, and a number of bug fixes.

.SH OPTIONS
.TP
.BR aim
Show aim crosshair.
.TP
.BR fullscreen
Start in fullscreen mode.
.TP
.BR window
Start in windowed mode.
.TP
.BR resolution\  \fIwidth\fPx\fIheight\fP
Specify the screen resolution to use (next parameter is widthxheight).
Valid resolutions are 320x200, 640x480 and 800x600.
.TP
.BR filertl\  \fIfile.rtl\fP
Load external Userlevels (RTL files) (next parameter is RTL filename).
Not available in shareware/demo version.
.TP
.BR filertc\  \fIfile.rtc\fP
Load external Battlelevels (RTC files) (next parameter is RTC filename).
Not available in shareware/demo version.
.TP
.BR file\  \fIfile.wad\fP
Load external WAD file (next parameter is WAD filename).
Not available in shareware/demo version.
.TP
.BR nojoys
Disable check for joystick.
.TP
.BR nomouse
Disable check for mouse.
.TP
.BR nosound
Disable sound.
.TP
.BR noecho
Turn off sound reverb.
.TP
.BR ver
Version number.
.TP
.BR mapstats
Dump Map statistics to ERROR.
.TP
.BR tilestats
Dump Tile statistics to ERROR.
.TP
.BR mono
Enable mono-monitor support.
.TP
.BR screenshots
Clean screen capture for shots.
.TP
.BR pause
Pauses startup screen information.
.TP
.BR enablevr
Enable VR helmet input devices.
.TP
.BR demoexit
Exit program when demo is terminated.
.TP
.BR warp\  \fIlevel\fP
Warp to specific ROTT level (next parameter is level to start on).
.TP
.BR timelimit\  \fItime\fP
Play ROTT in time limit mode (next parameter is time in seconds).
.TP
.BR maxtimelimit\  \fItime\fP
Maximimum time to count down from (next parameter is time in seconds).
.TP
.BR dopefish
Activate an Easter-egg with references to the Dopefish from the Commander Keen games.

.SH FILES
Game data files are searched for in \fB/usr/share/games/rottexpr\fR. Each
game binary requires its own particular data files:
.PP
\fBrottexpr\-demo\fR (shareware/demo) \- HUNTBGIN.WAD HUNTBGIN.RTC HUNTBGIN.RTL REMOTE1.RTS
.PP
\fBrottexpr\-reg\fR (registered floppy/download) \- DARKWAR.WAD DARKWAR.RTC DARKWAR.RTL REMOTE1.RTS
.PP
\fBrottexpr\-cdrom\fR (retail CD) \- DARKWAR.WAD ROTTCD.RTC DARKWAR.RTL REMOTE1.RTS
.PP
All filenames must be UPPERCASE.
.PP
Simply run \fBrottexpr\fR to play the "best" version of the game that you
have the data files for (CD\-ROM, Registered, or Demo, in that order).
.PP
User config data is stored in \fB~/.rottexpr\fR for the shareware/demo version
and \fB~/.rottexpr/darkwar\fR for the registered and CD\-ROM versions.

.SH AUTHORS
ROTT was created and published as shareware by Apogee Software, Ltd. and was published commercially by FormGen, Inc.
.PP
The primary contributors to the icculus.org port were Steven Fuller, Ryan C. Gordon, John Hall and Dan Olson.
.PP
The rottexpr port was started by Steven LeVesque, with significant contributions by Emile Belanger.
See https://github.com/LTCHIPS/rottexpr for more information.
.PP
This manual page was originally written by Fabian Greffrath <fabian@debian-unofficial.org>
for the Debian project (but may be used by others), and was modified for
the SlackBuilds.org games/rott project by B. Watson, and for rottexpr by Brent Spillner.
