.TH DMG2IMG 1 "July 2026" "dmg2img 1.6.7" "User Commands"
.SH NAME
dmg2img \- convert compressed Apple DMG files to standard disk images
.SH SYNOPSIS
.B dmg2img
.RI [ options ] " input.dmg " [ output.img | \- ]
.PP
.B dmg2img
.RI [ options ] " \-i input.dmg \-o " "output.img | \-"
.SH DESCRIPTION
.B dmg2img
converts compressed Apple DMG archives to standard HFS+ disk image
files. It supports zlib and bzip2 compressed images.
.SH OPTIONS
.TP
.B \-i
Specify the input DMG file.
.TP
.B \-o
Specify the output image. Use
.B \-
to write the image to standard output.
.TP
.B \-l
List the partitions contained in the input image.
.TP
.BI \-p " N"
Extract only partition number
.IR N .
.TP
.B \-s
Operate silently.
.TP
.B \-v
Enable verbose output.
.TP
.B \-V
Enable extremely verbose output.
.TP
.B \-d
Enable debugging output.
.SH SEE ALSO
.BR vfdecrypt (1)
.SH AUTHORS
The original program was written by vu1tur and Jean-Pierre Demailly.
.PP
This manual page is based on the page written by Soeren Sonnenburg for
the Debian project and may be used by others.
