#!/bin/sh

# Slackware build script for The Haskell Platform
#
# Written by Jockey S. Kyd (jockey dot kyd at gmail dot com)
# Public domain
#
# From 20120712, Christoph Willing <c.willing@uq.edu.au>

PRGNAM=haskell-platform
VERSION=${VERSION:-2012.2.0.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
    case "$(uname -m)" in
        i?86) ARCH=i486 ;;
        arm*) ARCH=arm ;;
           *) ARCH=$(uname -m) ;;
    esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
    SLKCFLAGS="-O2 -march=i486 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
    SLKCFLAGS="-O2 -march=i686 -mtune=i686"
    LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
    SLKCFLAGS="-O2 -fPIC"
    LIBDIRSUFFIX="64"
else
    SLKCFLAGS="-O2"
    LIBDIRSUFFIX=""
fi

set -e
rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

# Ensure libdir is passed to each package
patch -p0 < $CWD/honour_libdir.diff

# get path and version of ghc
GHC_VERSION=$(ghc --numeric-version)

# Recommended ghc version for this haskell-platform is ghc-7.4.1 but
# to allow for other ghc versions (current SBo is ghc-7.4.2),
# configure needs the --enable-unsupported-ghc-version option.
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --enable-unsupported-ghc-version \
  --prefix=/usr \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --libdir=/usr/lib${LIBDIRSUFFIX}/ghc-${GHC_VERSION}

make

# unsupport DESTDIR, so work around a bit
patch -p1 < $CWD/not_update_pkg_db.diff
sed -i "s:\(\./Setup copy\):\1 --destdir=$PKG:" scripts/install.sh
make install
# collecting config files
PKGCONFDIR=$PKG/usr/lib${LIBDIRSUFFIX}/ghc-${GHC_VERSION}/package.conf.d
mkdir -p $PKGCONFDIR
for pkg in $(cat packages/platform.packages); do
    pkg_conf=packages/${pkg}/${pkg}.conf
    if [ -f $pkg_conf ]; then
        mv $pkg_conf $PKGCONFDIR
    fi
done

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc
if [ -d $PKG/usr/share/doc ]; then
    mv $PKG/usr/share/doc/* $PKG/usr/doc/
    rmdir $PKG/usr/share/doc
fi
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
echo "$GHC_PKG recache" > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

