#!/bin/sh

# Slackware build script for Jackhammer

# Copyright 2015 Gethyn ThomasQuail <gethyn@bloodbathsoftworks.com>
# All rights reserved.
#
# Based on:
# TeamSpeak3 SlackBuild by Willy Sudiarto Raharjo <willysr@slackbuilds.org>
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=jackhammer
VERSION=${VERSION:-11855}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
JDIR=opt/Jackhammer

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "x86_64" ]; then
  JARCH="x64"
else
  JARCH="x86"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
mkdir -p $PKG/opt
chmod +x $CWD/"$PRGNAM"_"$VERSION"_linux_"$JARCH".run
$CWD/"$PRGNAM"_"$VERSION"_linux_"$JARCH".run --noexec --target $PKG/$JDIR
cd $PKG/$JDIR
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Desktop and launcher related stuff
install -D -m 0644 $PRGNAM.xpm $PKG/usr/share/pixmaps/$PRGNAM.xpm
install -D -m 0644 $CWD/$PRGNAM.desktop $PKG/usr/share/applications/$PRGNAM.desktop
install -D -m 0755 $CWD/$PRGNAM $PKG/usr/bin/$PRGNAM

# This is so we don't overwrite configs
mv $PKG/$JDIR/VDKGameCfg.ini $PKG/$JDIR/VDKGameCfg.ini.new
mv $PKG/$JDIR/VDKRunCfg.ini $PKG/$JDIR/VDKRunCfg.ini.new
mv $PKG/$JDIR/VDKSettings.ini $PKG/$JDIR/VDKSettings.ini.new

# Cleanup
rm -f $PKG/$JDIR/$PRGNAM.desktop
rm -f $PKG/$JDIR/libQtCore.so.4
rm -f $PKG/$JDIR/libQtGui.so.4
rm -f $PKG/$JDIR/libQtNetwork.so.4
rm -f $PKG/$JDIR/libQtOpenGL.so.4

# Make it so we have write access to the folder
chgrp -R users $PKG/$JDIR
chmod -R 774 $PKG/$JDIR

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $PKG/$JDIR/readme_en.rtf $PKG/$JDIR/readme_ru.rtf $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
