.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TKDIFF 1 "May 28, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tkdiff \- view the differences between two files
.SH SYNOPSIS
.B tkdiff
.RI [OPTION]... [FILES...]
.SH DESCRIPTION
.B tkdiff 
is a graphical front-end for the standard Unix 'diff' utility.
.PP
Its features include highlighted difference regions (with a quick
overview/navigation bar) and linked scrolling of files. It provides
file-merge and change-summary facilities, line number toggling (for easier
cut & paste) and support for Subversion, RCS, CVS and SCCS.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
.TP
.B \-rREV
diff against revision REV
.TP
.B \-a ANCESTORFILE
.TP
.B \-o MERGEOUTPUTFILE
Output to MERGEOUTPUTFILE
.TP
.B \-L LEFT_FILE_LABEL [-L RIGHT_FILE_LABEL]
Label left and right file windows respectively.
.TP
.B \-h, \-\-help
Show summary of options.
.SH EXAMPLES
.PP
Interactive selection of files to compare:
.br
    tkdiff

Plain files:
.br
    tkdiff FILE1 FILE2
.PP
Plain file with conflict markers:
.br
    tkdiff \-conflict FILE
.PP
Source control (AccuRev, BitKeeper, CVS, Subversion, Perforce, PVCS,
RCS, SCCS, ClearCase)
.br
    tkdiff FILE
.br
    tkdiff \-rREV FILE
.br
    tkdiff \-rREV1 \-rREV2 FILE
.br
    tkdiff OLD-URL[@OLDREV] NEW-URL[@NEWREV] (Subversion)
.PP
.SH SEE ALSO
.BR diff (1)
.br
.SH AUTHOR
tkdiff was written by John M. Klassa.
.PP
This manual page was written by Barry deFreese <bdefreese@comcast.net>,
for the Debian project (but may be used by others).
