[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/cryoglyph.git?rev=53ba3e879539d19ed8162942126a977ec896cc3b"]
git = "https://github.com/iced-rs/cryoglyph.git"
rev = "53ba3e879539d19ed8162942126a977ec896cc3b"
replace-with = "vendored-sources"

[source."git+https://github.com/iced-rs/winit.git?rev=05b8ff17a06562f0a10bb46e6eaacbe2a95cb5ed"]
git = "https://github.com/iced-rs/winit.git"
rev = "05b8ff17a06562f0a10bb46e6eaacbe2a95cb5ed"
replace-with = "vendored-sources"

[source."git+https://github.com/squidowl/iced?rev=a6cd98b0debe317ba9ad0d8b364684939e086fa3"]
git = "https://github.com/squidowl/iced"
rev = "a6cd98b0debe317ba9ad0d8b364684939e086fa3"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
