#!/bin/sh

# Slackware build script for fontmatrix

# Written by Larry Hajali <larryhaja[at]gmail[dot]com>

PRGNAM=fontmatrix
VERSION=${VERSION:-0.4.2}
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION-Source
tar xvf $CWD/$PRGNAM-$VERSION-Source.tar.gz
cd $PRGNAM-$VERSION-Source
chown -R root:root .
find . \
 \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Fix the desktop menu item.
echo "" >> $PRGNAM.desktop
echo "StartupNotify=false" >> $PRGNAM.desktop

mkdir build && cd build
  cmake \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DOWN_SHAPER=1 \
    -DCMAKE_SKIP_RPATH:BOOL=1 \
    -DRPATH_STYLE:STRING=none \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" ..

  make
  make install DESTDIR=$PKG
cd ..

( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null || true
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | \
    xargs strip --strip-unneeded 2> /dev/null
)

rm -rf $PKG/usr/share/icons
for i in 16 22 32 48 64 128; do
  mkdir -p $PKG/usr/share/icons/hicolor/${i}x${i}/apps
  install -m 0644 src/icons/application-fontmatrix_${i}.png \
    $PKG/usr/share/icons/hicolor/${i}x${i}/apps/$PRGNAM.png
done

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  COPYING INSTALL TODO harfbuzz/{COPYING.*,README,AUTHORS} \
  $PKG/usr/doc/$PRGNAM-$VERSION
cat harfbuzz/COPYING > $PKG/usr/doc/$PRGNAM-$VERSION/COPYING.harfbuzz
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
chmod 0644 $PKG/usr/doc/$PRGNAM-$VERSION/*

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
