.TH ZCUT "1" "December 2012" "SlackBuilds.org" "ZTools"
.SH NAME
zcut \- extract Infocom story files from disk images
.SH SYNOPSIS
.B zcut
\fIinput-file-1 \fR[\fIinput-file-2\fR...] \fIoutput-file\fR
.br
.B zcut
\fI/dev/fd0\fR [\fIoutput\-file\fR]
.br
.B unmfm
[\fIinput\-file\fR] [\fIoutput\-file\fR]
.SH DESCRIPTION
ZCut extracts Infocom story files (aka Z\-code) from
.PP
\- Amstrad CPC disk images [.DSK]
.br
\- Apple ][ disk images [.DSK, .NIB]
.br
\- Atari 800/XL/XE disk images [.ATR]
.br
\- Commodore 64/128 disk images [.D64]
.br
\- Commodore Amiga ADF format (only Deadline so far) [.ADF]
.br
\- IBM PC bootable disks or disk images
.br
\- Oric disk images (after conversion through UnMFM) [.DSK]
.br
\- any file if the Z\-code is stored in one piece
.PP
unmfm preprocesses Oric disk images for use with zcut. It has no
purpose for any other type of disk image. unmfm's output files
are only useful with zcut (not for use with Oric emulators).
.SH SEE ALSO
.BR zdebugtool (1),
.BR zcheck (1),
.BR inforead (1),
.BR pix2gif (1),
.BR txd (1)
.PP
zcut.txt and unmfm.txt, in
/usr/doc/ztools-@VERSION@/
.SH AUTHORS
1.2 includes changes by the Webulator
.br
1.1 Written by Stefan Jokisch in 1998.
.PP
Based on work by Matthew T. Russotto,
Paul D. Doherty, Stephen Tjasink, Mark Howell and Michael Jenkin.
.PP
This man page created by B. Watson, for SlackBuilds.org
