.TH "ZDEBUGTOOL" 1 "December 2012" "SlackBuilds.org" "ZTools"
.SH NAME 
zdebugtool \- sneak into the depths of INFOCOM adventures 
.SH SYNOPSIS 
.B
zdebugtool
[ \-ghamotvdc ] [ \-0123 ] [ file ] 
.SH DESCRIPTION 
This little tool gives you an insight into the inner
workings and hidden secrets of the classic INFOCOM (tm) text
adventures. 
.PP
It works with every INFOCOM game, whether it is an old
standard one like Zork I or Deadline or one of the newer
graphics games like Shogun or Zork Zero. 
.PP
Additionally, it can be used to analyze the save files
of all such games. 
.SH OPTIONS
.TP
.B \-g
display name of game 
.TP
.B \-h
display game header structure 
.TP
.B \-a
display alphabet 
.TP
.B \-m
display macros 
.TP
.B \-o
display object list 
.TP
.B \-t
display object tree 
.TP
.B \-v
display (global) variables 
.TP
.B \-d
display dictionary 
.TP
.B \-c
check data file 
.TP
.B \-0
suppress enumeration 
.TP
.B \-1
suppress attributes 
.TP
.B \-2
decimal enumeration 
.TP
.B \-3
suppress property stuff 
.SH AUTHOR 
This program was written by me, Paul David Doherty, in
1992. 
.PP
Some ideas incorporated in this program came from other
people involved with INFOCOM interpreters and debuggers,
especially Mark Howell, Mike Threepoint, and Paul Smith.
Sascha Wildner sent me some bug reports. Thanks a lot. 
.PP
If you want to report any bugs or make any suggestions,
you can contact me via Email. My address:
h0142kdd@rz.hu\-berlin.de 
.br
[
.I note:
this email address is from 1993, it doesn't work any more. \-\- BW ]
.PP
This man page created from PDD's preformatted DebugTool.man by B. Watson,
for SlackBuilds.org.
.SH COPYRIGHTS 
This program is freely distributable. However, it is not in
the Public Domain, so please don't distribute modified
versions without notifying me. 
.SH BUGS 
There are no known bugs. 
.PP
However, if you use the \-t option, you should set the
stack to 10000 (because the recursions will eat some
stack). 
.PP
Also, as the \-t option performs quite a few jumps in
the file, it can take a long time if the file is on a disk.
It is advisable to put it on your hard disk or into RAM. 
.PP COMPATIBILITY 
The program is written without using any Amiga\-specific
functions. I have tried to make it work on little\-endian
machines as well as big\-endian ones. However, I had no
possibility to test whether it compiles (and works) on any
system apart from the Amiga. 
.SH "VERSION HISTORY "
1.00 (31.5.1992) 
.PP
First public release. 
.PP
1.01 (18.7.1992) 
.PP
Externalised global variables. Made minor changes
concerning the header flags. 
.PP
1.02 (25.7.1992) 
.PP
Added \-c option. 
.PP
1.03 (4.8.1992) 
.PP
Minor changes again. 
.PP
1.10 (1.11.1992) 
.PP
Changed \-v option to \-d. Added (new) \-v option. Added
property stuff (in \-o option) and \-3 option. Changed
attributes format (in \-o and \-t). Expanded \-t option to
seek for closed chains. Added debugging info. Minor
fixes. 
.PP
1.11 (6.5.1993) 
.PP
Updated header flags and offsets. 
