#!/bin/bash

# Slackware build script for ztools

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://sam.zoy.org/wtfpl/ for details.

PRGNAM=ztools
VERSION=${VERSION:-7.3.1}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

TARVER=${VERSION//./}
ZCUTVER=12
ZDEBUGVER=111

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir -p $PRGNAM-$VERSION
cd $PRGNAM-$VERSION

# extract 'em all first. None of these have a top-level dir in
# their archive. Also DebugTools was lha'ed on an Amiga, causing
# filename weirdness (Makefile => srcMakefile, etc).
mkdir -p $PRGNAM zcut zdebugtool
( cd $PRGNAM && tar xvf $CWD/$PRGNAM$TARVER.tar.gz )
( cd zcut && unzip $CWD/zcut$ZCUTVER.zip )
( cd zdebugtool && lha x $CWD/DebugTool_$ZDEBUGVER.lha && rename src '' src* )

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

BINDIR=$PKG/usr/bin
DOCDIR=$PKG/usr/doc/$PRGNAM-$VERSION
MANDIR=$PKG/usr/man/man1
PATCHDIR=$CWD/patches
mkdir -p $BINDIR $DOCDIR $MANDIR

cd $PRGNAM
  patch -p1 < $PATCHDIR/$PRGNAM-zcheck.diff
  make CFLAGS="$SLKCFLAGS"
  mv check.1 zcheck.1
  mv check zcheck
  for bin in zcheck infodump pix2gif txd; do
    grep -v inforead < $bin.1 | gzip -9c > $MANDIR/$bin.1.gz
	 install -m0755 -s $bin $BINDIR
  done
  cat readme.1st > $DOCDIR/$PRGNAM.txt
cd ..

cd zcut
  patch -p1 < $PATCHDIR/zcut-compilefix.diff
  patch -p1 < $PATCHDIR/zcut-floppy_usage.diff
  patch -p1 < $PATCHDIR/zcut-zversion.diff

  gcc $SLKCFLAGS -o zcut zcut$ZCUTVER.c
  gcc $SLKCFLAGS -o unmfm unmfm.cpp
  install -s -m0755 zcut unmfm $BINDIR

  sed 's,\r,,' < ZCUT.TXT > $DOCDIR/zcut.txt
  sed 's,\r,,' < unMFM.txt > $DOCDIR/unmfm.txt

  # man page created for this SlackBuild
  sed "s,@VERSION@,$VERSION,g" < $CWD/zcut.1 | gzip -9c > $MANDIR/zcut.1.gz
  ln -s zcut.1.gz $MANDIR/unmfm.1.gz
cd ..

cd zdebugtool
  patch -p1 < $PATCHDIR/zdebugtool-compilefix.diff
  make CFLAGS="$SLKCFLAGS"
  install -s -m0755 zdebugtool $BINDIR
  # man page reconstituted from preformatted DebugTools.man
  gzip -9c < $CWD/zdebugtool.1 > $MANDIR/zdebugtool.1.gz
cd ..

# Also include my own modest z-code utility. It replaces the zren.exe
# that ships with zcut.
install -m0755 $CWD/zrename $PKG/usr/bin/zrename
perl $CWD/zrename --man | gzip -9c > $MANDIR/zrename.1.gz

cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
