.TH MADBOMBER "6" "April 2009" "New Breed Software" "Games"
.SH NAME
madbomber \- clone of the Activision game "Kaboom!"
.SH SYNOPSIS
.B
madbomber
[\-\-fullscreen] [\-\-disable\-sound] [\-\-usage] [\-\-help]
.SH DESCRIPTION
Mad Bomber is a clone of the excellent 1981 Atari 2600 video game
"Kaboom!" by Larry Kaplan of Activision.
.P
The Mad Bomber is loose in the city and he's dropping bombs
everywhere! It's your job to catch them before they hit the ground
and explode. Luckily, you have a set of trusty buckets to extinguish
them with.
.SH OPTIONS
.TP
\fB\-\-disable\-sound\fR
Disable sound
.TP
\fB\-\-fullscreen\fR
(Try to) run in fullscreen
.TP
\fB\-?\fR, \fB\-\-help\fR
Show long help message
.TP
\fB\-\-usage\fR
Show brief usage message
.SH CONTROLS
.SS Title screen controls
.TP
\fBUp/Down\fR
Choose option
.TP
\fBSpace/Return\fR
Activate option
.TP
\fBMouse\-click\fR
Activate option under mouse pointer
.TP
\fBEscape\fR
Quit program
.P
.SS Option screen controls
.TP
\fBUp/Down\fR
Choose option
.TP
\fBSpace/Return\fR
Activate option
.TP
\fBMouse\-click\fR
Activate option under mouse pointer
.TP
\fBEscape\fR
Return to title screen
.P
.SS Game controls
.TP
\fBLeft/Right\fR
Move buckets
.TP
\fBMouse\-motion\fR
Move buckets
.TP
\fBSpace/Return\fR
Fire
.TP
\fBMouse\-click\fR
Fire
.TP
\fB1/2/3/4\fR
(in Vs. mode) Move Mad Bomber
                     (1 = left, fast
                      2 = left, slow
                      3 = right, slow
                      4 = right, fast)
.TP
\fBTab/P\fR
Pause
.TP
\fBEscape\fR
Quit game (return to title screen)
.SH FILES
.TP
\fB/usr/share/madbomber\fR
game data (images, music, sound)
.TP
\fB$HOME/.madbomber\fR
per\-user settings and high\-score records
.SH AUTHOR
Bill Kendrick (New Breed Software)
.P
New Breed Software's web site is located at
.br
.nh
\fBhttp://www.newbreedsoftware.com/\fR
.hy
.P
Man page created by B. Watson for SlackBuilds.org project (but others
are free to use it)

.SH COPYRIGHT
Mad Bomber is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any
later version.

