# pod source for xroar man page. convert with:
# pod2man --stderr -s6 -r0.32 -u -cSlackBuilds.org xroar.pod > xroar.6

=head1 NAME

xroar - Dragon and CoCo 1/2 emulator.

=head1 SYNOPSIS

xroar [-c CONFFILE] [OPTION]...

=head1 DESCRIPTION

XRoar is a Dragon emulator.  Due to hardware similarities, XRoar also emulates the Tandy Colour Computer
(CoCo) models 1 & 2.

This man page just documents the command-line options to xroar. For full documentation,  see the info page for
xroar, or the HTML documentation in /usr/doc/xroar-_VERSION_/xroar.html.

=head1 OPTIONS

=over 5

=item -c CONFFILE

specify a configuration file

=item Machines

=item -default-machine NAME

default machine on startup

=item -machine NAME

configure named machine (B<-machine help> for list)

=item -machine-desc TEXT

machine description

=item -machine-arch ARCH

machine architecture (B<-machine-arch help> for list)

=item -machine-keyboard LAYOUT

keyboard layout (B<-machine-keyboard> help for list)

=item -machine-cpu CPU

machine CPU (B<-machine-cpu help> for list)

=item -bas NAME

BASIC ROM to use (CoCo only)

=item -extbas NAME

Extended BASIC ROM to use

=item -altbas NAME

64K mode Extended BASIC ROM (Dragon 64)

=item -nobas

disable BASIC

=item -noextbas

disable Extended BASIC

=item -noaltbas

disable 64K mode Extended BASIC

=item -ext-charset NAME

external character generator ROM to use

=item -tv-type TYPE

TV type (B<-tv-type help> for list)

=item -vdg-type TYPE

VDG type (6847 or 6847t1)

=item -ram KBYTES

amount of RAM in K

=item -machine-cart NAME

default cartridge for selected machine

=item -nodos

don't automatically pick a DOS cartridge

=item Cartridges

=item -cart NAME

configure named cartridge (B<-cart help> for list)

=item -cart-desc TEXT

cartridge description

=item -cart-type TYPE

cartridge base type (B<-cart-type help> for list)

=item -cart-rom NAME

ROM image to load ($C000-)

=item -cart-rom2 NAME

second ROM image to load ($E000-)

=item -cart-autorun

autorun cartridge

=item -cart-becker

enable becker port where supported

=item Becker port

=item -becker

prefer becker-enabled DOS (when picked automatically)

=item -becker-ip ADDRESS

address or hostname of DriveWire server [127.0.0.1]

=item -becker-port PORT

port of DriveWire server [65504]

=item Files

=item -load FILENAME

load or attach FILENAME

=item -run FILENAME

load or attach FILENAME and attempt autorun

=item Cassettes

=item -tape-write FILENAME

open FILENAME for tape writing

=item -no-tape-fast

disable fast tape loading

=item -tape-pad

force tape leader padding

=item -no-tape-pad-auto

disable automatic leader padding

=item -tape-rewrite

enable tape rewriting

=item Disks

=item -disk-write-back

default to enabling write-back for disk images

=item -no-disk-auto-os9

don't try to detect headerless OS-9 JVC disk images

=item Firmware ROM images

=item -rompath PATH

ROM search path (colon-separated list)

=item -romlist NAME=LIST

define a ROM list

=item -romlist-print

print defined ROM lists

=item -crclist NAME=LIST

define a ROM CRC list

=item -crclist-print

print defined ROM CRC lists

=item -force-crc-match

force per-architecture CRC matches

=item User interface

=item -ui MODULE

user-interface module (B<-ui help> for list)

=item Video

=item -vo MODULE

video module (B<-vo help> for list)

=item -fs

start emulator full-screen if possible

=item -fskip FRAMES

frameskip (default: 0)

=item -ccr RENDERER

cross-colour renderer (B<-ccr help> for list)

=item -geometry WxH+X+Y

initial emulator geometry

=item -invert-text

start with text mode inverted

=item Audio

=item -ao MODULE

audio module (B<-ao help> for list)

=item -ao-device STRING

device to use for audio module

=item -ao-format FMT

set audio sample format (B<-ao-format help> for list)

=item -ao-rate HZ

set audio frame rate (if supported by module)

=item -ao-channels N

set number of audio channels, 1 or 2

=item -ao-fragments N

set number of audio fragments

=item -ao-fragment-ms MS

set audio fragment size in ms (if supported)

=item -ao-fragment-frames N

set audio fragment size in samples (if supported)

=item -ao-buffer-ms MS

set total audio buffer size in ms (if supported)

=item -ao-buffer-frames N

set total audio buffer size in samples (if supported)

=item -volume VOLUME

audio volume (0 - 100)

=item -fast-sound

faster but less accurate sound

=item Keyboard

=item -keymap CODE

host keyboard type (B<-keymap help> for list)

=item -kbd-translate

enable keyboard translation

=item -type STRING

intercept ROM calls to type STRING into BASIC

=item Joysticks

See JOYSTICK SPECS below for the description of the SPEC arguments.

=item -joy NAME

configure named joystick (B<-joy help> for list)

=item -joy-desc TEXT

joystick description

=item -joy-axis AXIS=SPEC

configure joystick axis

=item -joy-button BTN=SPEC

configure joystick button

=item -joy-right NAME

map right joystick

=item -joy-left NAME

map left joystick

=item -joy-virtual NAME

specify the `virtual' joystick to cycle [kjoy0]

=item Printing

=item -lp-file FILENAME

append Dragon printer output to FILENAME

=item -lp-pipe COMMAND

pipe Dragon printer output to COMMAND

=item Debugging

=item -gdb

disable GDB target

=item -gdb-ip

address of interface for GDB target [localhost]

=item -gdb-port

port for GDB target to listen on [65520]

=item -trace

start with trace mode on

=item -debug-ui FLAGS

UI debugging (see manual, or -1 for all)

=item -debug-file FLAGS

file debugging (see manual, or -1 for all)

=item -debug-fdc FLAGS

FDC debugging (see manual, or -1 for all)

=item -debug-gdb FLAGS

GDB target debugging (see manual, or -1 for all)

=item -v, verbose LEVEL

general debug verbosity (0-3) [1]

=item -q, --quiet

equivalent to --verbose 0

=item -timeout SECONDS

run for SECONDS then quit

=back

=head1 Other options

=over 5

=item -config-print

print full configuration to standard output

=item -h, --help

display this help and exit

=item -V, --version

output version information and exit

=back

=head1 JOYSTICK SPECS

Joystick SPECs are of the form [INTERFACE:][ARG[,ARG]...], from:

	INTERFACE       Axis ARGs                       Button ARGs

	physical        joystick-index,[-]axis-index    joystick-index,button-index
	keyboard        key-name0,key-name1             key-name
	mouse           screen-offset0,screen-offset1   button-number

For physical joysticks a `-' before the axis index inverts the axis.  AXIS 0 is the X-axis, and AXIS 1 the
Y-axis.  BTN 0 is the only one used so far, but in the future BTN 1 will be the second button on certain CoCo
joysticks.

=head1 COPYRIGHT

xroar is Copyright (c) 2009 Ciaran Anscomb

This man page written by B. Watson for the SlackBuilds.org project (but it may be used by anyone).

This is free software.  You may redistribute copies of it under the terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.  There is NO WARRANTY, to the extent permitted by law.

=head1 SEE ALSO

The info page for xroar (includes much information not found in this man page).

http://en.wikipedia.org/wiki/TRS-80_Color_Computer

http://archive.worldofdragon.org/index.php?title=Main_Page

http://archive.worldofdragon.org/archive/index.php
