diff -Naur Pd-0.42.5-extended-orig/packages/Makefile Pd-0.42.5-extended/packages/Makefile
--- Pd-0.42.5-extended-orig/packages/Makefile	2010-09-10 01:03:57.000000000 +0100
+++ Pd-0.42.5-extended/packages/Makefile	2010-11-03 19:06:37.095286845 +0000
@@ -404,7 +404,7 @@
 	echo '<p>Please consider trying to get rid of software patents in your country: <a href="http://www.nosoftwarepatents.com" target="nsp">http://www.nosoftwarepatents.com</a></p>' >> $(README_FILE)
 	echo "<h3>Pure Data CVS Developers</h3>" >> $(README_FILE)	
 # this may seem whack, but it generates the list of developers from the SourceForge site:
-	curl 'http://sourceforge.net/project/memberlist.php?group_id=55736' | grep -A2 -e '<td>' | sed 's|\(href="\)|target="w" \1http://sourceforge.net|' >> $(README_FILE)
+	cat $(DEVELOPERSLIST) >> $(README_FILE)
 	echo "</p>" >> $(README_FILE)
 	echo "<p>" >> $(README_FILE)
 	echo "Many others not listed have contributed their time and effort, this is just a list of the current developers in the SourceForge project.  But really, every Pd user is a developer and is encouraged to contribute to the CVS repository." >> $(README_FILE)
