#!/bin/sh

# Slackware build script for 2ping

# Written by B. Watson (yalhcru@gmail.com)

# Licensed under the WTFPL. See http://www.wtfpl.net/txt/copying/ for details.

# 20180821 bkw:
# - update for v4.2.
# - document optional deps in README.
# - include wireshark stuff in package.

PRGNAM=2ping
VERSION=${VERSION:-4.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

# This could be a noarch package, except python libs are installed
# to /usr/lib64 on x86_64 and /usr/lib elsewhere :(
# No C or C++ is compiled so no SLKCFLAGS here.
LIBDIRSUFFIX=""
if [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

python3 setup.py install --root=$PKG

# Include wireshark stuff, if we have a wireshark that can use it (built
# with lua52). The lua script is for decoding, the .pcap file is a sample
# packet capture (belongs in doc dir).
if [ -x /usr/bin/wireshark ] && ldd /usr/bin/wireshark | fgrep -q lua5.2; then
  mkdir -p $PKG/usr/lib$LIBDIRSUFFIX/wireshark/plugins
  cp -a wireshark/*.lua $PKG/usr/lib$LIBDIRSUFFIX/wireshark/plugins
fi

mkdir -p $PKG/usr/man/man1
gzip -9c < doc/$PRGNAM.1 > $PKG/usr/man/man1/$PRGNAM.1.gz
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/wireshark
cp -a README* COPYING ChangeLog doc/*.py doc/*.md $PKG/usr/doc/$PRGNAM-$VERSION
cp -a wireshark/*.pcap $PKG/usr/doc/$PRGNAM-$VERSION/wireshark

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
