#!/bin/sh

# Slackware build script for yakuake
# Written by Steffen Schwebel (steffen.schwebel at web.de)

# Modified by the SlackBuilds.org project

PRGNAM=yakuake
VERSION=2.7.5
ARCH=${ARCH:-i486}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=`pwd`
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ $ARCH = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
elif [ $ARCH = "s390" ]; then
  SLKCFLAGS="-O2"
elif [ $ARCH = "x86_64" ]; then
  SLKCFLAGS="-O2"
elif [ $ARCH = "ipent4" ]; then
  SLKCFLAGS="-O2 -march=pentium4 -mtune=i686 -msse -msse2"
elif [ $ARCH = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
else
  echo "Unrecognized architecture type! Check the script: $0"
  exit 1
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP || exit 1
rm -rf $PRGNAM-$VERSION
tar xjvf $CWD/$PRGNAM-$VERSION.tar.bz2 || exit 1
cd $PRGNAM-$VERSION || exit 1
chown -R root:root .
chmod -R a-s,u+w,go+r-w .

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/opt/kde \
  --program-prefix="" \
  --program-suffix="" \
  || exit 1

make || exit 1
make install-strip DESTDIR=$PKG || exit 1

# No man pages with yakuake

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
for i in \
  AUTHORS COPYING ChangeLog INSTALL README TODO ;
  do cat $i > $PKG/usr/doc/$PRGNAM-$VERSION/$i ;
done
cat yakuake/NEWS > $PKG/usr/doc/$PRGNAM-$VERSION/NEWS
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.tgz
