name: Create build check
on:
  push:
    tags:
      - '15.0**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  create-build-check-issue:
    name: Create build check issue
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for actions/checkout
      issues: write # for peter-evans/create-issue-from-file
    if: contains(fromJSON('["SlackBuildsOrg/slackbuilds"]'), github.repository)
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: false
          persist-credentials: false

      - name: Create build check issue
        id: create-issue
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6.0.0
        with:
          title: '${{ github.ref_name }}: Build check'
          content-filepath: .github/BUILD_CHECK_ISSUE.md


