#!/bin/bash
# $Id: lxde-common.SlackBuild,v 1.5 2009/09/11 20:36:29 root Exp root $
# Copyright (c) 2008-2009  Eric Hameleers, Eindhoven, NL
# Copyright 2010-2025 Matteo Bernardini <ponce@slackbuilds.org>, Pisa, Italy
# All rights reserved.
#
#   Permission to use, copy, modify, and distribute this software for
#   any purpose with or without fee is hereby granted, provided that
#   the above copyright notice and this permission notice appear in all
#   copies.
#
#   THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
#   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#   SUCH DAMAGE.
# -----------------------------------------------------------------------------
#
# Slackware SlackBuild script
# ===========================
# By:         Eric Hameleers <alien@slackware.com>
# For:        lxde-common
# Descr:      a set of default configurations for LXDE
# URL:        http://lxde.sourceforge.net/
# Needs:
# Changelog:
# 0.3.2.1-1:  04/jun/2008 by Eric Hameleers <alien@slackware.com>
#             * Initial build.
# 0.4.2-1:    11/sep/2009 by Eric Hameleers <alien@slackware.com>
#             * Update.
# 0.5.0-1:    13/sep/2010 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Adapted to slackbuilds.org's autotools template.
#             * Fixed lxpanel and xinitrc.
# 20110313_736ded3: 29/mar/2011 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Updated to git version.
# 0.5.5-1:    26/dec/2011 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
#             * su_cmd defaults to gksu-polkit.
# 0.5.5-2:    31/dec/2011 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Updated panel default config with battery indicator.
# 0.5.5-3:    07/jun/2013 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Switched from gksu-polkit to ktsuss.
#             * Small cleanups and fixes.
# 0.5.5-4:    14/nov/2013 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Removed the option to switch to root completely
#               (see http://bit.ly/no-more-su-pcmanfm)
# 0.5.6-1:    02/sep/2014 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
# 20141008_8877e46: 09/oct/2014 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
# 0.99.1:     10/jul/2016 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
# 0.99.2:     09/dec/2016 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
# 0.99.3:     11/apr/2025 by Matteo Bernardini <ponce@slackbuilds.org>
#             * Update.
#
# Run 'sh lxde-common.SlackBuild' to build a Slackware package.
# The package is created in /tmp .
# Install using 'installpkg'.
#
# -----------------------------------------------------------------------------

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=lxde-common
VERSION=${VERSION:-0.99.3}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

DOCS="AUTHORS COPYING INSTALL ChangeLog NEWS README"

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}


if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.?z
cd $PRGNAM-$VERSION
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

sh autogen.sh || true

CXXFLAGS="$SLKCFLAGS" \
CFLAGS="$SLKCFLAGS" \
./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --localstatedir=/var \
  --sysconfdir=/etc \
  --enable-man \
  --mandir=/usr/man \
  --docdir=/usr/doc/$PRGNAM-$VERSION \
  --program-prefix= \
  --program-suffix= \
  --build=$ARCH-slackware-linux
make
make DESTDIR=$PKG install

# this slips the make install
install -m 0644 -D lxde-logout.desktop \
  $PKG/usr/share/applications/lxde-logout.desktop

# add a xinitrc file for xwmconfig:
install -m 0755 -D $CWD/config/xinitrc.lxde \
  $PKG/etc/X11/xinit/xinitrc.lxde

# make sure that KDM picks up the LXDE session type as well:
mkdir -p $PKG/usr/share/apps/kdm/sessions
( cd $PKG/usr/share/apps/kdm/sessions
  for i in $(ls ../../../xsessions/*.desktop) ; do ln -sf $i ; done )

# patch desktop.conf to use the Tango icon theme
sed -i -e 's#nuoveXT2#Tango#' $PKG/etc/xdg/lxsession/LXDE/desktop.conf || exit 1

# preserve modified config files
mv $PKG/etc/xdg/lxsession/LXDE/desktop.conf \
  $PKG/etc/xdg/lxsession/LXDE/desktop.conf.new
mv $PKG/etc/xdg/lxsession/LXDE/autostart \
  $PKG/etc/xdg/lxsession/LXDE/autostart.new
mv $PKG/etc/xdg/pcmanfm/LXDE/pcmanfm.conf \
  $PKG/etc/xdg/pcmanfm/LXDE/pcmanfm.conf.new

# use some sane defaults for lxpanel
rm -f $PKG/etc/xdg/lxpanel/LXDE/config \
  $PKG/etc/xdg/lxpanel/LXDE/panels/panel
install -m 0644 $CWD/config/panel \
  $PKG/etc/xdg/lxpanel/LXDE/panels/panel.new
install -m 0644 $CWD/config/config \
  $PKG/etc/xdg/lxpanel/LXDE/config.new

# add documentation:
mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
find $PKG/usr/doc -type f -exec chmod 644 {} \;

find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
