#!/bin/sh

# Slackware build script for QMC2

# Copyright 2010-2020  Erik Hanson, Minneapolis, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=qmc2
VERSION=${VERSION:-0.195}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM
chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
 -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

patch -p1 < $CWD/qmc2-qt5.15.patch
patch --binary -p1 < $CWD/qmc2-types.patch

CXX_FLAGS="$SLKCFLAGS" LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
make EMU=MESS PREFIX=/usr PRETTY=0 MACHINE=$ARCH
make install EMU=MESS PREFIX=/usr DESTDIR=$PKG

make clean
CXX_FLAGS="$SLKCFLAGS" LDFLAGS="-L/usr/lib${LIBDIRSUFFIX}" \
make EMU=MAME PREFIX=/usr PRETTY=0 MACHINE=$ARCH
make install EMU=MAME PREFIX=/usr DESTDIR=$PKG

cd tools/qchdman
qmake qchdman.pro
make
install -D -m 0755 qchdman $PKG/usr/bin/qchdman
cd -

find $PKG | xargs file | egrep "ELF.*executable" | cut -f 1 -d : \
          | xargs strip --strip-unneeded 2> /dev/null

#install -D -m 0644 $CWD/qmc2.desktop $PKG/usr/share/applications/qmc2.desktop
#install -D -m 0644 $CWD/qmc2.png $PKG/usr/share/pixmaps/qmc2.png
install -D -m 0644 $CWD/qchdman.desktop $PKG/usr/share/applications/qchman.desktop
#install -D -m 0644 $CWD/qchdman.png $PKG/usr/share/pixmaps/qchdman.png

mv $PKG/etc/qmc2/qmc2.ini $PKG/etc/qmc2/qmc2.ini.new

mkdir -p $PKG/usr/doc
mv $PKG/usr/share/qmc2/doc/ $PKG/usr/doc/$PRGNAM-$VERSION/
ln -s ../../doc/$PRGNAM-$VERSION $PKG/usr/share/qmc2/doc
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
