#!/bin/sh

# Slackware build script for Netbeans IDE

# Copyright (c) 2008-2009, Antonio Hernández Blas <hba.nihilismus@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1.- Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# This script is just a binary repackaging.

# Updated by Andre Barboza <bmg.andre@gmail.com>

PRGNAM=netbeans
VERSION=${VERSION:-8.0.2}
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}

BUNDLE=${BUNDLE:+-$BUNDLE}
DATE="201411181905"

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-${PRGNAM}${BUNDLE}
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG/opt $OUTPUT
cd $PKG/opt
unzip -o $CWD/$PRGNAM-$VERSION-$DATE${BUNDLE}.zip
chown -R root:root .

find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

# Add netbeans to KDE/GNOME/XFCE menu
install -D -m 0644 $CWD/$PRGNAM.desktop \
  $PKG/usr/share/applications/$PRGNAM.desktop

# Add an icon for netbeans
install -D -m 0644 $CWD/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM.png

# Add an script to call netbeans from /usr/bin.
mkdir -p $PKG/usr/bin
cat <<- EOF > $PKG/usr/bin/$PRGNAM
#!/bin/sh
cd \$HOME
/opt/$PRGNAM/bin/netbeans \$@
EOF
chmod 0755 $PKG/usr/bin/$PRGNAM

find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

# Don't clobber any existing config file
mv $PKG/opt/$PRGNAM/etc/netbeans.conf \
   $PKG/opt/$PRGNAM/etc/netbeans.conf.new
mv $PKG/opt/$PRGNAM/etc/netbeans.clusters \
   $PKG/opt/$PRGNAM/etc/netbeans.clusters.new
mv $PKG/opt/$PRGNAM/etc/netbeans.import \
   $PKG/opt/$PRGNAM/etc/netbeans.import.new

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cd $PKG/opt/$PRGNAM
cp -a *.html *.txt *.css $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
